# 04 – Details

Esplorazione e data cleaning del dataset `details.csv`.

**Colonne:**
| Colonna | Descrizione |
|---|---|
| `mal_id` | ID univoco dell'anime su MyAnimeList |
| `title` | Titolo dell'anime |
| `title_japanese` | Titolo in giapponese |
| `url` | URL della pagina MAL dell'anime |
| `image_url` | URL dell'immagine di copertina |
| `type` | Tipo (TV, Movie, etc) |
| `status` | Stato di trasmissione |
| `score` | Punteggio medio |
| `scored_by` | Numero di utenti che hanno votato |
| `start_date` | Data di inizio trasmissione |
| `end_date` | Data di fine trasmissione |
| `synopsis` | Sinossi testuale |
| `rank` | Classifica globale |
| `popularity` | Popolarità |
| `members` | Numero di utenti che hanno l'anime nella loro lista |
| `favorites` | Numero di utenti che hanno messo l'anime tra i preferiti |
| `genres` | Lista di generi |
| `studios` | Lista di studi di produzione |
| `themes` | Lista di temi narrativi |
| `demographics` | Lista di target demografici |
| `source` | Materiale di origine (Manga, Novel, Original, etc) |
| `rating` | Classificazione per età |
| `episodes` | Numero di episodi |
| `season` | Stagione di uscita |
| `year` | Anno di uscita |
| `producers` | Lista di produttori |
| `explicit_genres` | Lista di generi espliciti |
| `licensors` | Lista di licenziatari |
| `streaming` | Lista di piattaforme di streaming |

## 1. Import e caricamento dati
Importiamo le librerie necessarie e carichiamo il file csv. Facciamo una esplorazione generica per capire la struttura e le caratteristiche del dataset.

In [50]:
import pandas as pd
import numpy as np
from dataset_analyzer import analyze

df_details = pd.read_csv('../datasets/details.csv')
print(f'Shape: {df_details.shape}')
df_details.info()
df_details.head()

Shape: (28955, 29)
<class 'pandas.DataFrame'>
RangeIndex: 28955 entries, 0 to 28954
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   mal_id           28955 non-null  int64
 1   title            28955 non-null  str
 2   title_japanese   28836 non-null  str
 3   url              28955 non-null  str
 4   image_url        28955 non-null  str
 5   type             28888 non-null  str
 6   status           28955 non-null  str
 7   score            18882 non-null  float64
 8   scored_by        18882 non-null  float64
 9   start_date       28104 non-null  str
 10  end_date         11267 non-null  str
 11  synopsis         23828 non-null  str
 12  rank             21997 non-null  float64
 13  popularity       28955 non-null  int64
 14  members          28955 non-null  int64
 15  favorites        28955 non-null  int64
 16  genres           28955 non-null  str
 17  studios          28955 non-null  str
 18  themes           28955 non-null  str
 19  demographics     28955 non-null  str
 20  source           28955 non-null  str
 21  rating           28355 non-null  str
 22  episodes         28275 non-null  float64
 23  season           6266 non-null   str
 24  year             6266 non-null   float64
 25  producers        28955 non-null  str
 26  explicit_genres  28955 non-null  str
 27  licensors        28955 non-null  str
 28  streaming        28955 non-null  str
dtypes: float64(5), int64(4), str(20)
memory usage: 6.4 MB

,mal_id,title,title_japanese,url,image_url,type,status,score,scored_by,start_date,...,demographics,source,rating,episodes,season,year,producers,explicit_genres,licensors,streaming
0,59356,-Socket-,-socket-,https://myanimelist.net/anime/59356/-Socket-,https://cdn.myanimelist.net/images/anime/1043/...,Movie,Finished Airing,NaN,NaN,2010-01-01T00:00:00+00:00,...,[],Original,G - All Ages,1.0,NaN,NaN,['Nagoya Zokei University'],[],[],[]
1,56036,......,......,https://myanimelist.net/anime/56036/-,https://cdn.myanimelist.net/images/anime/1057/...,Music,Finished Airing,6.53,503.0,2023-06-11T00:00:00+00:00,...,[],Original,PG-13 - Teens 13 or older,1.0,NaN,NaN,[],[],[],[]
2,2928,.hack//G.U. Returner,.HACK//G.U. RETURNER,https://myanimelist.net/anime/2928/hack__GU_Re...,https://cdn.myanimelist.net/images/anime/1798/...,OVA,Finished Airing,6.65,9745.0,2007-01-18T00:00:00+00:00,...,[],Game,PG-13 - Teens 13 or older,1.0,NaN,NaN,"['Bandai Visual', 'CyberConnect2']",[],[],[]
3,3269,.hack//G.U. Trilogy,.hack//G.U. Trilogy,https://myanimelist.net/anime/3269/hack__GU_Tr...,https://cdn.myanimelist.net/images/anime/1566/...,Movie,Finished Airing,7.06,15373.0,2007-12-22T00:00:00+00:00,...,[],Game,PG-13 - Teens 13 or older,1.0,NaN,NaN,['Bandai Visual'],[],"['Funimation', 'Bandai Entertainment']",[]
4,4469,.hack//G.U. Trilogy: Parody Mode,.hack//G.U. Trilogy,https://myanimelist.net/anime/4469/hack__GU_Tr...,https://cdn.myanimelist.net/images/anime/10/86...,Special,Finished Airing,6.35,4317.0,2008-03-25T00:00:00+00:00,...,[],Game,PG-13 - Teens 13 or older,1.0,NaN,NaN,['Bandai Visual'],[],[],[]

Il dataset contiene **28.955 righe** e **29 colonne**. Alcune colonne presentano valori nulli. Alcuni dtype richiedono conversione: le date sono in formato stringa, e alcune colonne intere (`scored_by`, `rank`, `episodes`, `year`) sono memorizzate come `float64`. Quiesti veranno gestiti singolarmente nella sezione 2.

## 1.1 Rimozione duplicati esatti

Prima dell'analisi per colonna, rimuoviamo le righe con valori identici in **tutte** le colonne, mantenendo solo la prima occorrenza.

In [ ]:
n_originale = len(df_details)

mask_dup = df_details.duplicated(keep=False)       # tutte le occorrenze coinvolte
n_righe_coinvolte = mask_dup.sum()                  # righe totali che hanno almeno un duplicato
n_gruppi = df_details[mask_dup].duplicated(keep='first').sum()  # occorrenze extra (da rimuovere)
n_tenute = n_righe_coinvolte - n_gruppi             # prime occorrenze mantenute

print(f'Righe totali coinvolte in duplicazioni : {n_righe_coinvolte:,}')
print(f'  → prime occorrenze mantenute         : {n_tenute:,}')
print(f'  → occorrenze extra rimosse           : {n_gruppi:,}')
print()

df_details.drop_duplicates(keep='first', inplace=True)
print(f'Righe prima della rimozione : {n_originale:,}')
print(f'Righe dopo la rimozione     : {len(df_details):,}')

Righe totali coinvolte in duplicazioni : 0
  → prime occorrenze mantenute         : 0
  → occorrenze extra rimosse           : 0

Righe prima della rimozione : 28,955
Righe dopo la rimozione     : 28,955

## 2. Analisi colonna per colonna

### 2.1 `mal_id`

È la **chiave primaria** del dataset. Deve essere intera, non nulla e univoca. Utilizziamo `analyze` per verificare queste proprietà.

In [51]:
analyze(df_details['mal_id'])

  Nome serie                     mal_id
  dtype                          int64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Zeri                           0  (0.00%)
  Positivi                       28,955   (100.00%)
  Negativi                       0   (0.00%)
  Valori unici                   28,955  (100.00%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            1
  Max                            62,590
  Range                          62,589
  Media                          33,977.52
  Mediana                        37,969.00
  Moda/e                         1, 5, 6
  Dev. standard                  19,616.86
  Varianza                       384,821,140
  Errore std (SEM)               115.2836
  IQR  (Q3 − Q1)                 34,980.50
  Q1  (25° pct)                  15,454.00
  Q3  (75° pct)                  50,434.50
  P5  ( 5° pct)                  1,591.70
  P95 (95° pct)                  60,286.20
  Coefficiente di variazione     57.73%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -37,016.75
  Soglia alta   (Q3 + 1.5×IQR)   102,905.25
  Outlier rilevati               0  (0.00%)

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  1 – 3,130                           2,830     9.8%
  3,130 – 6,259                       1,681     5.8%
  6,259 – 9,389                       1,217     4.2%
  9,389 – 12,518                      1,019     3.5%
  12,518 – 15,648                       519     1.8%
  15,648 – 18,777                       662     2.3%
  18,777 – 21,907                       587     2.0%
  21,907 – 25,036                       704     2.4%
  25,036 – 28,166                       466     1.6%
  28,166 – 31,295                     1,150     4.0%
  31,295 – 34,424                     1,494     5.2%
  34,424 – 37,554                     1,898     6.6%
  37,554 – 40,683                     1,907     6.6%
  40,683 – 43,813                     1,496     5.2%
  43,813 – 46,942                     2,135     7.4%
  46,942 – 50,072                     1,756     6.1%
  50,072 – 53,201                     1,639     5.7%
  53,201 – 56,331                     1,876     6.5%
  56,331 – 59,460                     1,974     6.8%
  59,460 – 62,590                     1,945     6.7%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   62,590  [indice 9478]
    #2   62,589  [indice 2564]
    #3   62,584  [indice 9044]
    #4   62,582  [indice 21137]
    #5   62,580  [indice 21965]
    #6   62,572  [indice 6616]
    #7   62,568  [indice 5505]
    #8   62,567  [indice 19928]
    #9   62,566  [indice 4673]
    #10  62,564  [indice 24102]

  I 10 più piccoli:
    #1   1  [indice 4253]
    #2   5  [indice 4255]
    #3   6  [indice 25296]
    #4   7  [indice 26630]
    #5   8  [indice 2818]
    #6   15  [indice 6081]
    #7   16  [indice 8001]
    #8   17  [indice 9666]
    #9   18  [indice 10147]
    #10  19  [indice 16162]

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                59,356            1     0.0%
                56,036            1     0.0%
                 2,928            1     0.0%
                 3,269            1     0.0%
                 4,469            1     0.0%
                   454            1     0.0%
                 1,143            1     0.0%
                   299            1     0.0%
                 9,332            1     0.0%
                10,390            1     0.0%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                56,606            1     0.0%
                34,895            1     0.0%
                36,305            1     0.0%
                31,245            1     0.0%
                59,421            1     0.0%
                58,303            1     0.0%
                52,512            1     0.0%
                45,069            1     0.0%
                45,187            1     0.0%
                46,436            1     0.0%

**Osservazioni:**
- **Nessun valore nullo**: tutti i 28.955 record hanno un ID univoco.
- **Nessun duplicato**: ogni riga corrisponde a un anime distinto.
- **Dtype corretto**: `int64`, nessuna conversione necessaria.

Nessuna pulizia necessaria.

### 2.2 `title`

Colonna testuale con il titolo dell'anime. Verifichiamo la presenza di valori nulli e duplicati.

In [52]:
analyze(df_details['title'])

  Nome serie                     title
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Stringhe vuote                 0
  Valori unici                   28,953  (99.99%)
  Valori duplicati               2

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  1  caratteri
  Lunghezza max                  186  caratteri
  Lunghezza media                24.70  caratteri
  Lunghezza mediana              21.0000  caratteri
  Dev. standard lunghezza        15.07
  IQR lunghezza                  18.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=186  Shinjiteita Nakama-tachi ni Dungeon Okuchi de Korosarekaketa ga Gift "Mugen Gacha" de Level 9999 no Nakama-tachi wo Te n…
    #2   len=141  99-kai Danzai sareta Loop Reijou desu ga Konse wa "Chouzetsu Aisare Mode" desu tte!? Shin no Chikara ni Mezamete Hajimar…
    #3   len=140  Shoukan Showcase: Isekai Teni shita Saki de Fennec ga Akuma no Shouchou!? Bouken kara Tsuihou sareta node, Uta to Dance …
    #4   len=132  Mukuwarenakatta Murabito A, Kizoku ni Hirowarete Dekiai sareru Ue ni, Jitsu wa Motteita Densetsu-kyuu no Kami Skill mo K…
    #5   len=130  Kanchigai no Atelier Meister: Eiyuu Party no Moto Zatsuyougakari ga, Jitsu wa Sentou Igai ga SSS Rank Datta to Iu Yoku A…
    #6   len=130  NEET Kunoichi to Nazeka Dousei Hajimemashita: Nazeka Beach de Dogimagi Shimashita/Nazeka Moto Koutou Youma to Nakayoku N…
    #7   len=126  Watashi no Naka no Gensou-teki Sekaikan Oyobi Sono Kengen wo Souki Saseta Aru Genjitsu de no Dekigoto ni Kansuru Ichi Ko…
    #8   len=124  Kochira Katsushikaku Kameari Kouenmae Hashutsujo: Seton Tankentai! Sumidagawa no Chikai - Omoide no Shiroi Kujira wo Sag…
    #9   len=120  Kochira Katsushikaku Kameari Kouenmae Hashutsujo: Ryou-san to Chuuken Lucky Monogatari - Kameari Dai Houimou wo Kawase!!
    #10  len=120  Tsuujou Kougeki ga Zentai Kougeki de Ni-kai Kougeki no Okaasan wa Suki desu ka? Namiuchigiwa no Okaasan wa Suki desu ka?

  Le 10 stringhe più corte:
    #1   len=1  2
    #2   len=1  9
    #3   len=1  ◯
    #4   len=1  F
    #5   len=1  K
    #6   len=1  M
    #7   len=1  Q
    #8   len=1  R
    #9   len=1  T
    #10  len=1  X

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  1 – 10                              3,742    12.9%
  10 – 19                             9,458    32.7%
  19 – 28                             6,669    23.0%
  28 – 38                             4,282    14.8%
  38 – 47                             2,418     8.4%
  47 – 56                             1,192     4.1%
  56 – 65                               639     2.2%
  65 – 75                               269     0.9%
  75 – 84                               154     0.5%
  84 – 93                                61     0.2%
  93 – 102                               30     0.1%
  102 – 112                              23     0.1%
  112 – 121                              10     0.0%
  121 – 130                               4     0.0%
  130 – 139                               1     0.0%
  139 – 149                               2     0.0%
  149 – 158                               0     0.0%
  158 – 167                               0     0.0%
  167 – 176                               0     0.0%
  176 – 186                               1     0.0%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                                                                     Conteggio        %
  ───────────────────────────────────────────────────────────────────────   ──────────   ──────
  Moonlight                                                                          2     0.0%
  Shen Lan Qi Yu Wushuang Zhu: Tianmo Pian                                           2     0.0%
  -Socket-                                                                           1     0.0%
  ......                                                                             1     0.0%
  .hack//G.U. Returner                                                               1     0.0%
  .hack//G.U. Trilogy                                                                1     0.0%
  .hack//G.U. Trilogy: Parody Mode                                                   1     0.0%
  .hack//Gift                                                                        1     0.0%
  .hack//Intermezzo                                                                  1     0.0%
  .hack//Liminality                                                                  1     0.0%

  I 10 meno frequenti (più rari):
  Valore                                                                     Conteggio        %
  ───────────────────────────────────────────────────────────────────────   ──────────   ──────
  Zutto Tomodachi                                                                    1     0.0%
  Zutto Suki Datta                                                                   1     0.0%
  Zutto Mae kara Suki deshita. Kokuhaku Jikkou Iinkai: Kinyoubi no Ohayou            1     0.0%
  Zutto Mae kara Suki deshita. Kokuhaku Jikkou Iinkai                                1     0.0%
  Zutaboro Reijou wa Ane no Moto Konyakusha ni Dekiai sareru                         1     0.0%
  Zurukute Sugoi                                                                     1     0.0%
  Zurui Maboroshi                                                                    1     0.0%
  Zuqiu Wangzhe                                                                      1     0.0%
  Zuqiu Jianghu                                                                      1     0.0%
  Zuoyou Nao Zhili Kaifa                                                             1     0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 3,715  (12.8%)
  Contiene maiuscole             28,915  (99.9%)
  Contiene minuscole             28,861  (99.7%)
  Contiene spazi                 26,023  (89.9%)
  Contiene caratteri speciali    12,572  (43.4%)
  Contiene URL                   1  (0.0%)
  Contiene @                     53  (0.2%)
  Solo numerico                  14
  Solo alfabetico                2,302
  Solo alfanumerico              2,332

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               715,147
  Caratteri unici                165
  Caratteri medi per valore      24.70

Analisi parole / token
────────────────────────────────────────────────────────────────────────────────

  Parole medie per valore        4.08
  Max parole                     30
  Min parole                     1

  Le 10 parole più comuni:
  Parola                  Conteggio
  ────────────────────   ──────────
  no                          6,572
  to                          1,207
  Season                      1,051
  ni                            817
  wa                            777
  -                             727
  The                           713
  Movie                         641
  wo                            567
  Xiao                          558

**Osservazioni:**
- **Nessun valore nullo**: tutti i 28.955 record hanno un titolo.
- **Quasi univoco**: 28.953 valori distinti su 28.955. Ci solo 2 titoli duplicati che verifichiamo successivamente. 
- **Lunghezze variabili**: da 1 carattere (titoli come `2`, `9`, singole lettere) a 186 caratteri (lunghi titoli isekai). Vacciamo delle verifiche per approfondire. 
- **14 titoli solo numerici** (es. `2`, `9`). Indaghiamo in seguito.
- **1 titolo contiene un URL** (~0.0%). Ingaghiamo in seguito.
- **43.4% contiene caratteri speciali**: normale, i titoli includono punteggiatura, simboli e trattini.

In [ ]:
# Titoli duplicati 
dup_mask = df_details.duplicated(subset=['title'], keep=False)
print(f'Titoli duplicati (righe coinvolte): {dup_mask.sum()}')
print()
print(df_details[dup_mask][['mal_id', 'title', 'type', 'status', 'year']].to_string(index=False))

# Titoli solo numerici 
print()
print('─' * 60)
num_mask = df_details['title'].str.fullmatch(r'\d+')
print(f'Titoli solo numerici: {num_mask.sum()}')
print()
print(df_details[num_mask][['mal_id', 'title', 'type', 'year']].to_string(index=False))

# Titolo che contiene un URL 
print()
print('─' * 60)
url_mask = df_details['title'].str.contains(r'https?://', regex=True, na=False)
print(f'Titoli con URL: {url_mask.sum()}')
print()
print(df_details[url_mask][['mal_id', 'title', 'type', 'year']].to_string(index=False))

# Lunghezze estreme 
print()
print('─' * 60)
print('Titoli più corti (len ≤ 2):')
short_mask = df_details['title'].str.len() <= 2
print(df_details[short_mask][['mal_id', 'title', 'type', 'year']].to_string(index=False))
print()
print('Titoli più lunghi (len ≥ 100):')
long_mask = df_details['title'].str.len() >= 100
print(df_details[long_mask][['mal_id', 'title', 'type', 'year']].to_string(index=False))

Titoli duplicati (righe coinvolte): 4

 mal_id                                    title  type          status  year
  59994                                Moonlight Music Finished Airing  <NA>
  60524                                Moonlight Music Finished Airing  <NA>
  53367 Shen Lan Qi Yu Wushuang Zhu: Tianmo Pian   ONA Finished Airing  <NA>
  55740 Shen Lan Qi Yu Wushuang Zhu: Tianmo Pian   ONA Finished Airing  <NA>

────────────────────────────────────────────────────────────
Titoli solo numerici: 14

 mal_id  title  type  year
  29978    001   ONA  <NA>
  60145   1135 Music  <NA>
  37065    123 Music  <NA>
  55204   1985 Music  <NA>
  30234   1989 Music  <NA>
  38756      2 Music  <NA>
  54066   2005 Music  <NA>
  32813   2010 Music  <NA>
  53789     32 Music  <NA>
  53771   3341 Music  <NA>
  60486    520 Movie  <NA>
  13971 663114 Movie  <NA>
  41457     86    TV  2021
  36089      9 Music  <NA>

────────────────────────────────────────────────────────────
Titoli con URL: 1

 mal_id                                                                     title  type  year
   8357 Himitsukessha Taka no Tsume The Movie 3: http://takanotsume.jp wa Eien ni Movie  <NA>

────────────────────────────────────────────────────────────
Titoli più corti (len ≤ 2):
 mal_id title  type  year
  38756     2 Music  <NA>
  53789    32 Music  <NA>
  41457    86    TV  2021
  36089     9 Music  <NA>
   6535    Ai Movie  <NA>
  45384    AU    TV  <NA>
  31687     ◯   ONA  <NA>
  10578    C³    TV  2011
  41185    CP Music  <NA>
   4357    El   OVA  <NA>
   6055     F    TV  1988
    386    H2    TV  1995
  62354    Io Music  <NA>
  14467     K    TV  2012
  54322    Ke Movie  <NA>
  50238     M Music  <NA>
  44645    OK Movie  <NA>
   2785    OZ   OVA  <NA>
  51427    Po Music  <NA>
  51608     Q Music  <NA>
  60502     R   ONA  <NA>
  52546     T   OVA  <NA>
   7279    TO   OVA  <NA>
  50533    We    PV  <NA>
    156     X    TV  2001
   1276    Ys   OVA  <NA>
  43637    Yu Movie  <NA>

Titoli più lunghi (len ≥ 100):
 mal_id                                                                                                                                                                                      title       type  year
  62002                                              99-kai Danzai sareta Loop Reijou desu ga Konse wa "Chouzetsu Aisare Mode" desu tte!? Shin no Chikara ni Mezamete Hajimaru 100-kaime no Jinsei        NaN  <NA>
  61224                                                                              A-Rank Party wo Ridatsu shita Ore wa, Moto Oshiego-tachi to Meikyuu Shinbu wo Mezasu.: Party Tokushuu! Clover TV Special  <NA>
  54171                                                                                   Bleach: Shuku! Rukia Dakkan! Kagayaku! Shinigami Juuban Shoubu! Mitai Shinigami Doon to Misemasu Special    Special  <NA>
  55717                                                                                       Dekisokonai to Yobareta Motoeiyuu wa Jikka kara Tsuihou sareta node Sukikatte ni Ikiru Koto ni Shita         TV  2024
  59002                                                                               Hazure Skill "Kinomi Master": Skill no Mi (Tabetara Shinu) wo Mugen ni Taberareru You ni Natta Ken ni Tsuite         TV  2025
  61534                                                                    Hazure Skill "Kinomi Master": Skill no Mi (Tabetara Shinu) wo Mugen ni Taberareru You ni Natta Ken ni Tsuite Mini Anime        ONA  <NA>
  52830                                                                                  Isekai de Cheat Skill wo Te ni Shita Ore wa, Genjitsu Sekai wo mo Musou Suru: Level Up wa Jinsei wo Kaeta         TV  2023
  56906                                                                     Isekai de Cheat Skill wo Te ni Shita Ore wa, Genjitsu Sekai wo mo Musou Suru: Level Up wa Jinsei wo Kaeta (TV Special) TV Special  <NA>
  58359                                                                          Isshun de Chiryou shiteita noni Yakutatazu to Tsuihou sareta Tensai Chiyushi, Yami Healer toshite Tanoshiku Ikiru         TV  2025
  62188                                                                              Kaketa Tsuki no Mercedes: Kyuuketsuki no Kizoku ni Tensei shita kedo Suteraresou nanode Dungeon wo Seiha suru        NaN  <NA>
  60140                                                         Kanchigai no Atelier Meister: Eiyuu Party no Moto Zatsuyougakari ga, Jitsu wa Sentou Igai ga SSS Rank Datta to Iu Yoku Aru Hanashi         TV  2025
  40762                                                                               Keishichou Tokumubu Tokushu Kyouakuhan Taisakushitsu Dainanaka: Tokunana - Ichinen Mae, Nijou Kujaku no Urei    Special  <NA>
  33882                                                                               Kochira Katsushikaku Kameari Kouenmae Hashutsujo: Mezase! Kameari Superstar!! Ryoutsu-shiki Idol e no Michi!    Special  <NA>
  33880                                                                                   Kochira Katsushikaku Kameari Kouenmae Hashutsujo: Ryou-san no Sushi Kui Nee! - Choujou Maguro Taiketsu!!    Special  <NA>
  33876                                                                   Kochira Katsushikaku Kameari Kouenmae Hashutsujo: Ryou-san to Chuuken Lucky Monogatari - Kameari Dai Houimou wo Kawase!!    Special  <NA>
  33878                                                                      Kochira Katsushikaku Kameari Kouenmae Hashutsujo: Ryoutsu no Asakusa Renewal Daisakusen!! - Aa, Omoide no Hanayashiki    Special  <NA>
  33875                                                                            Kochira Katsushikaku Kameari Kouenmae Hashutsujo: Ryoutsu vs. Nakimushi Idol!? Nihon 1-shuu Dai Sugoroku Game!!    Special  <NA>
  33879                                                               Kochira Katsushikaku Kameari Kouenmae Hashutsujo: Seton Tankentai! Sumidagawa no Chikai - Omoide no Shiroi Kujira wo Sagase!    Special  <NA>
  33881                                                                                    Kochira Katsushikaku Kameari Kouenmae Hashutsujo: Washi to Ore!? - Bokura wa Asakusa Shounen Tanteidan!    Special  <NA>
  56352                                                                                     Loop 7-kaime no Akuyaku Reijou wa, Moto Tekikoku de Jiyuu Kimama na Hanayome Seikatsu wo Mankitsu suru         TV  2024
  48417                                                                               Maou Gakuin no Futekigousha II: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou         TV  2023
  48418                                                                        Maou Gakuin no Futekigousha II: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou Part 2         TV  2024
  40496                                                                                  Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou         TV  2020
  37377                                                                                       Masamune-kun no Revenge: Uchi no Mama ni Kagitte/Tsunade Shima, Futatabi./12-Ji wo Sugita Cinderella        OVA  <NA>
  57315                                                                                    Meitou "Isekai no Yu" Kaitakuki: Around 40 Onsen Mania no Tensei Saki wa, Nonbiri Onsen Tengoku deshita         TV  2024
  60948                                                                                    Mezametara Saikyou Soubi to Uchuusenmochi Datta node, Ikkodate Mezashite Youhei toshite Jiyuu ni Ikitai        NaN  <NA>
  61276                                                                                     Mikata ga Yowasugite Hojo Mahou ni Tesshiteita Kyuutei Mahoushi, Tsuihou sarete Saikyou wo Mezashimasu         TV  2025
  57005                                                       Mukuwarenakatta Murabito A, Kizoku ni Hirowarete Dekiai sareru Ue ni, Jitsu wa Motteita Densetsu-kyuu no Kami Skill mo Kakusei shita         TV  <NA>
  61271                                                         NEET Kunoichi to Nazeka Dousei Hajimemashita: Nazeka Beach de Dogimagi Shimashita/Nazeka Moto Koutou Youma to Nakayoku Narimashita        ONA  <NA>
  61549                                                                              Okiraku Ryoushu no Tanoshii Ryouchi Bouei: Seisankei Majutsu de Na mo Naki Mura wo Saikyou no Jousai Toshi ni         TV  <NA>
  60023                                                                             Ore no Imouto ga Konnani Kawaii Wake ga Nai x Toaru Majutsu no Index Movie: Endymion no Kiseki - Kokuchi Eizou         CM  <NA>
  61154                                                                              Otome Game no Hametsu Flag shika Nai Akuyaku Reijou ni Tensei shiteshimatta... Movie Honpen Mae Special Eizou        ONA  <NA>
  56736                                                                     Saikyou Degarashi Ouji no Anyaku Teii Arasoi: Munou wo Enjiru SS Rank Ouji wa Koui Keishousen wo Kage kara Shihai suru        NaN  <NA>
  56845                                                                                   Saikyou Tank no Meikyuu Kouryaku: Tairyoku 9999 no Rare Skill-mochi Tank, Yuusha Party wo Tsuihou sareru         TV  2024
  57834                                                                                   Shangri-La Frontier: Kusoge Hunter, Kamige ni Idoman to su - Saishin Wa made Maruwakari! Chousoku Digest TV Special  <NA>
  44037                                                                                  Shin no Nakama ja Nai to Yuusha no Party wo Oidasareta node, Henkyou de Slow Life suru Koto ni Shimashita         TV  2021
  53488                                                                              Shin no Nakama ja Nai to Yuusha no Party wo Oidasareta node, Henkyou de Slow Life suru Koto ni Shimashita 2nd         TV  2024
  60303 Shinjiteita Nakama-tachi ni Dungeon Okuchi de Korosarekaketa ga Gift "Mugen Gacha" de Level 9999 no Nakama-tachi wo Te ni Irete Moto Party Member to Sekai ni Fukushuu & "Zamaa!" Shimasu!         TV  2025
  61127                                               Shoukan Showcase: Isekai Teni shita Saki de Fennec ga Akuma no Shouchou!? Bouken kara Tsuihou sareta node, Uta to Dance de Sekai wo Kaemasu!      Music  <NA>
  56735                                                                                  Tenkou-saki no Seiso Karen na Bishoujo ga, Mukashi Danshi to Omotte Issho ni Asonda Osananajimi Datta Ken         TV  <NA>
  60284                                                                                   Tousouchuu: Great Mission - Maika to Rabbi no Souryoku Shuzai - Tsuki Sekaiichi no Tousousha wa Dare da! TV Special  <NA>
  40102                                                                   Tsuujou Kougeki ga Zentai Kougeki de Ni-kai Kougeki no Okaasan wa Suki desu ka? Namiuchigiwa no Okaasan wa Suki desu ka?        OVA  <NA>
  36596                                                             Watashi no Naka no Gensou-teki Sekaikan Oyobi Sono Kengen wo Souki Saseta Aru Genjitsu de no Dekigoto ni Kansuru Ichi Kousatsu      Music  <NA>
  46431                                                                          Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan: Dakara, Shishunki wa Owarazu ni, Seishun wa Tsuzuiteiku.        OVA  <NA>
  59424                                                                       Yuusha Party wo Tsuihou sareta Shiromadoushi, S-Rank Boukensha ni Hirowareru: Kono Shiromadoushi ga Kikakugai Sugiru         TV  2025

**Risultati dell'indagine:**

- **Titoli duplicati (2 coppie, 4 righe):** `Moonlight` e `Shen Lan Qi Yu Wushuang Zhu: Tianmo Pian` compaiono ciascuno due volte, ma con `mal_id` distinti. Sono anime separati su MAL che condividono il titolo. **Nessuna rimozione necessaria.**

- **Titoli solo numerici (14 righe):** tutti legittimi. La maggior parte sono video musicali (`Music`) o cortometraggi in cui titoli brevi o numerici sono comuni. **Nessuna azione necessaria.**

- **Titolo contenente un URL (1 riga):** `Himitsukessha Taka no Tsume The Movie 3: http://takanotsume.jp wa Eien ni` (`mal_id` 8357). L'URL è parte integrante del titolo ufficiale del film, caratteristica della serie *Taka no Tsume* nota per titoli volutamente assurdi. **Nessuna azione necessaria.**

- **Lunghezze estreme:** i titoli molto corti (1–2 caratteri) sono anime reali con titoli brevi; i titoli molto lunghi (fino a 186 caratteri) sono tipici degli produzioni moderni. Nessun valore anomalo.

**Conclusione:** la colonna `title` non richiede alcuna pulizia. Tutti i casi apparentemente anomali sono valori legittimi.

### 2.3 `title_japanese`

Colonna testuale con il titolo in giapponese. I null sono ammessi: anime di produzione non giapponese o senza titolo kanji registrato su MAL non avranno questo campo.

In [9]:
analyze(df_details['title_japanese'])

  Nome serie                     title_japanese
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,836  (99.59%)
  Null / NaN                     119  (0.41%)
  Stringhe vuote                 0
  Valori unici                   27,772  (95.91%)
  Valori duplicati               1,064

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  1  caratteri
  Lunghezza max                  85  caratteri
  Lunghezza media                12.24  caratteri
  Lunghezza mediana              10.0000  caratteri
  Dev. standard lunghezza        8.69
  IQR lunghezza                  10.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=85  ラブライブ School idol project！μ's→NEXT LoveLive！2014～ENDLESS PARADE～アンコールアニメーション 0209Ver.
    #2   len=79  信じていた仲間達にダンジョン奥地で殺されかけたがギフト『無限ガチャ』でレベル9999の仲間達を手に入れて元パーティーメンバーと世界に復讐＆『ざまぁ！』します!
    #3   len=78  SUPA DUPA FLY feat. 湘南乃風, MOOMIN, KENTY GROSS, BES, APOLLO, NATURAL WEAPON, 導楽
    #4   len=74  DANCE EVOLUTION DANCE MASTERS SILENT HILL ROBBIE !!!!!!!!!!! - 着ぐるみ兎が踊ってみた
    #5   len=74  Vivy -Fluorite Eye's Song- 特別総集編「-To make everyone happy with my singing-」
    #6   len=73  ユーリ!!! on ICE Yuri Plisetsky GPF in Barcelona EX "Welcome to The Madness"
    #7   len=69  Candy boy -Nonchalant talk of the certain twin sisters in daily life-
    #8   len=69  ラブライブ School idol project！μ's→NEXT LoveLive！2014～ENDLESS PARADE～幕間ドラマ
    #9   len=67  バンドリ！ ガールズバンドパーティ！ 5th Anniversary Animation -CiRCLE THANKS PARTY！-
    #10  len=66  Inter College Animation Festival (2004) (インターカレッジ・アニメーション・フェスティバル)

  Le 10 stringhe più corte:
    #1   len=1  2
    #2   len=1  9
    #3   len=1  愛
    #4   len=1  愛
    #5   len=1  証
    #6   len=1  足
    #7   len=1  ◯
    #8   len=1  缠
    #9   len=1  창
    #10  len=1  笛

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  1 – 5                               5,933    20.6%
  5 – 9                               8,363    29.0%
  9 – 13                              5,417    18.8%
  13 – 17                             3,022    10.5%
  17 – 22                             2,183     7.6%
  22 – 26                             1,684     5.8%
  26 – 30                               925     3.2%
  30 – 34                               536     1.9%
  34 – 38                               307     1.1%
  38 – 43                               201     0.7%
  43 – 47                               132     0.5%
  47 – 51                                54     0.2%
  51 – 55                                31     0.1%
  55 – 59                                23     0.1%
  59 – 64                                11     0.0%
  64 – 68                                 6     0.0%
  68 – 72                                 2     0.0%
  72 – 76                                 3     0.0%
  76 – 80                                 2     0.0%
  80 – 85                                 1     0.0%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                              Conteggio        %
  ────────────────────────────────   ──────────   ──────
  おしりたんてい                                     9     0.0%
  僕のヒーローアカデミア                                 7     0.0%
  ゲゲゲの鬼太郎                                     5     0.0%
  ゴールデンカムイ                                    5     0.0%
  ああっ女神さまっ                                    4     0.0%
  아기공룡 둘리                                     4     0.0%
  ぼのぼの                                        4     0.0%
  文豪ストレイドッグス                                  4     0.0%
  キャットマン                                      4     0.0%
  地獄先生ぬ～べ～                                    4     0.0%

  I 10 meno frequenti (più rari):
  Valore                              Conteggio        %
  ────────────────────────────────   ──────────   ──────
  ずっと友達                                       1     0.0%
  ずっと好きだった                                    1     0.0%
  ずっと前から好きでした。～告白実行委員会～ 「金曜日のおはよう」            1     0.0%
  ずっと前から好きでした。～告白実行委員会～                       1     0.0%
  ずたぼろ令嬢は姉の元婚約者に溺愛される                         1     0.0%
  ズルくてすごい                                     1     0.0%
  ズルい幻                                        1     0.0%
  足球王者                                        1     0.0%
  足球江湖                                        1     0.0%
  左右脑智力开发                                     1     0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 2,618  (9.1%)
  Contiene maiuscole             6,097  (21.1%)
  Contiene minuscole             3,300  (11.4%)
  Contiene spazi                 10,743  (37.3%)
  Contiene caratteri speciali    27,304  (94.7%)
  Contiene URL                   0  (0.0%)
  Contiene @                     10  (0.0%)
  Solo numerico                  9
  Solo alfabetico                598
  Solo alfanumerico              621

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               352,903
  Caratteri unici                4,559
  Caratteri medi per valore      12.24

Analisi parole / token
────────────────────────────────────────────────────────────────────────────────

  Parole medie per valore        1.65
  Max parole                     14
  Min parole                     1

  Le 10 parole più comuni:
  Parola                  Conteggio
  ────────────────────   ──────────
  THE                           418
  ANIMATION                     237
  劇場版                           231
  The                           186
  第二季                           160
  of                            140
  the                           136
  2                             131
  映画                            120
  -                              92

**Osservazioni:**
- **119 valori nulli** (~0.4%): strutturali, anime di produzione non giapponese o senza titolo kanji registrato su MAL.

Nessuna pulizia necessaria.

In [10]:
# Nessuna operazione richiesta: i null sono strutturali
print(f'Null in title_japanese : {df_details["title_japanese"].isna().sum()} ({df_details["title_japanese"].isna().mean()*100:.1f}%)')

Null in title_japanese : 119 (0.4%)

### 2.4 `url`

URL della pagina MAL dell'anime. Essendo derivato direttamente dal `mal_id`, ci aspettiamo assenza di null e unicità.

In [11]:
analyze(df_details['url'])

  Nome serie                     url
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Stringhe vuote                 0
  Valori unici                   28,955  (100.00%)
  Valori duplicati               0

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  35  caratteri
  Lunghezza max                  216  caratteri
  Lunghezza media                60.19  caratteri
  Lunghezza mediana              57.0000  caratteri
  Dev. standard lunghezza        14.92
  IQR lunghezza                  17.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=216  https://myanimelist.net/anime/60303/Shinjiteita_Nakama-tachi_ni_Dungeon_Okuchi_de_Korosarekaketa_ga_Gift_Mugen_Gacha_de_…
    #2   len=173  https://myanimelist.net/anime/62002/99-kai_Danzai_sareta_Loop_Reijou_desu_ga_Konse_wa_Chouzetsu_Aisare_Mode_desu_tte_Shi…
    #3   len=172  https://myanimelist.net/anime/61127/Shoukan_Showcase__Isekai_Teni_shita_Saki_de_Fennec_ga_Akuma_no_Shouchou_Bouken_kara_…
    #4   len=166  https://myanimelist.net/anime/57005/Mukuwarenakatta_Murabito_A_Kizoku_ni_Hirowarete_Dekiai_sareru_Ue_ni_Jitsu_wa_Motteit…
    #5   len=166  https://myanimelist.net/anime/61271/NEET_Kunoichi_to_Nazeka_Dousei_Hajimemashita__Nazeka_Beach_de_Dogimagi_Shimashita_Na…
    #6   len=165  https://myanimelist.net/anime/60140/Kanchigai_no_Atelier_Meister__Eiyuu_Party_no_Moto_Zatsuyougakari_ga_Jitsu_wa_Sentou_…
    #7   len=162  https://myanimelist.net/anime/36596/Watashi_no_Naka_no_Gensou-teki_Sekaikan_Oyobi_Sono_Kengen_wo_Souki_Saseta_Aru_Genjit…
    #8   len=158  https://myanimelist.net/anime/33879/Kochira_Katsushikaku_Kameari_Kouenmae_Hashutsujo__Seton_Tankentai_Sumidagawa_no_Chik…
    #9   len=154  https://myanimelist.net/anime/33876/Kochira_Katsushikaku_Kameari_Kouenmae_Hashutsujo__Ryou-san_to_Chuuken_Lucky_Monogata…
    #10  len=154  https://myanimelist.net/anime/56736/Saikyou_Degarashi_Ouji_no_Anyaku_Teii_Arasoi__Munou_wo_Enjiru_SS_Rank_Ouji_wa_Koui_K…

  Le 10 stringhe più corte:
    #1   len=35  https://myanimelist.net/anime/156/X
    #2   len=36  https://myanimelist.net/anime/6055/F
    #3   len=36  https://myanimelist.net/anime/386/H2
    #4   len=37  https://myanimelist.net/anime/56036/-
    #5   len=37  https://myanimelist.net/anime/38756/2
    #6   len=37  https://myanimelist.net/anime/36089/9
    #7   len=37  https://myanimelist.net/anime/4934/AF
    #8   len=37  https://myanimelist.net/anime/6535/Ai
    #9   len=37  https://myanimelist.net/anime/101/Air
    #10  len=37  https://myanimelist.net/anime/31687/◯

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  35 – 44                             2,571     8.9%
  44 – 53                             9,088    31.4%
  53 – 62                             7,155    24.7%
  62 – 71                             4,774    16.5%
  71 – 80                             2,536     8.8%
  80 – 89                             1,392     4.8%
  89 – 98                               778     2.7%
  98 – 107                              329     1.1%
  107 – 116                             174     0.6%
  116 – 125                              77     0.3%
  125 – 134                              37     0.1%
  134 – 143                              22     0.1%
  143 – 152                              11     0.0%
  152 – 161                               4     0.0%
  161 – 170                               4     0.0%
  170 – 179                               2     0.0%
  179 – 188                               0     0.0%
  188 – 197                               0     0.0%
  197 – 206                               0     0.0%
  206 – 216                               1     0.0%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                                                                                                        Conteggio        %
  ──────────────────────────────────────────────────────────────────────────────────────────────────────────   ──────────   ──────
  https://myanimelist.net/anime/59356/-Socket-                                                                          1     0.0%
  https://myanimelist.net/anime/56036/-                                                                                 1     0.0%
  https://myanimelist.net/anime/2928/hack__GU_Returner                                                                  1     0.0%
  https://myanimelist.net/anime/3269/hack__GU_Trilogy                                                                   1     0.0%
  https://myanimelist.net/anime/4469/hack__GU_Trilogy__Parody_Mode                                                      1     0.0%
  https://myanimelist.net/anime/454/hack__Gift                                                                          1     0.0%
  https://myanimelist.net/anime/1143/hack__Intermezzo                                                                   1     0.0%
  https://myanimelist.net/anime/299/hack__Liminality                                                                    1     0.0%
  https://myanimelist.net/anime/9332/hack__Quantum                                                                      1     0.0%
  https://myanimelist.net/anime/10390/hack__Quantum__Sore_ike_Bokura_no_Chimuchimu-chan                                 1     0.0%

  I 10 meno frequenti (più rari):
  Valore                                                                                                        Conteggio        %
  ──────────────────────────────────────────────────────────────────────────────────────────────────────────   ──────────   ──────
  https://myanimelist.net/anime/56606/Zutto_Tomodachi                                                                   1     0.0%
  https://myanimelist.net/anime/34895/Zutto_Suki_Datta                                                                  1     0.0%
  https://myanimelist.net/anime/36305/Zutto_Mae_kara_Suki_deshita_Kokuhaku_Jikkou_Iinkai__Kinyoubi_no_Ohayou            1     0.0%
  https://myanimelist.net/anime/31245/Zutto_Mae_kara_Suki_deshita_Kokuhaku_Jikkou_Iinkai                                1     0.0%
  https://myanimelist.net/anime/59421/Zutaboro_Reijou_wa_Ane_no_Moto_Konyakusha_ni_Dekiai_sareru                        1     0.0%
  https://myanimelist.net/anime/58303/Zurukute_Sugoi                                                                    1     0.0%
  https://myanimelist.net/anime/52512/Zurui_Maboroshi                                                                   1     0.0%
  https://myanimelist.net/anime/45069/Zuqiu_Wangzhe                                                                     1     0.0%
  https://myanimelist.net/anime/45187/Zuqiu_Jianghu                                                                     1     0.0%
  https://myanimelist.net/anime/46436/Zuoyou_Nao_Zhili_Kaifa                                                            1     0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 28,955  (100.0%)
  Contiene maiuscole             28,915  (99.9%)
  Contiene minuscole             28,955  (100.0%)
  Contiene spazi                 0  (0.0%)
  Contiene caratteri speciali    28,955  (100.0%)
  Contiene URL                   28,955  (100.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               1,742,829
  Caratteri unici                145
  Caratteri medi per valore      60.19

**Osservazioni:**
- **Nessun valore nullo**: tutti i 28.955 record hanno un URL valido.
- **Nessun duplicato**: coerente con `mal_id` come chiave primaria.

Nessuna pulizia necessaria.

In [12]:
# Nessuna operazione richiesta
print(f'Null in url      : {df_details["url"].isna().sum()}')
print(f'Duplicati in url : {df_details["url"].duplicated().sum()}')

Null in url      : 0
Duplicati in url : 0

### 2.5 `image_url`

URL dell'immagine di copertina. MAL usa un'immagine placeholder per gli anime privi di copertina reale; la identifichiamo e aggiungiamo una colonna booleana `has_image` per distinguere i due casi.

In [13]:
DEFAULT_IMG = 'https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png'
placeholder = (df_details['image_url'] == DEFAULT_IMG).sum()
print(f'Immagini placeholder : {placeholder:,} ({placeholder/len(df_details)*100:.1f}%)')
print(f'Immagini reali       : {len(df_details)-placeholder:,} ({(len(df_details)-placeholder)/len(df_details)*100:.1f}%)')
print()
analyze(df_details['image_url'])

Immagini placeholder : 198 (0.7%)
Immagini reali       : 28,757 (99.3%)


  Nome serie                     image_url
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Stringhe vuote                 0
  Valori unici                   28,758  (99.32%)
  Valori duplicati               197

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  50  caratteri
  Lunghezza max                  64  caratteri
  Lunghezza media                54.69  caratteri
  Lunghezza mediana              56.0000  caratteri
  Dev. standard lunghezza        1.93
  IQR lunghezza                  3.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #2   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #3   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #4   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #5   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #6   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #7   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #8   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #9   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #10  len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png

  Le 10 stringhe più corte:
    #1   len=50  https://cdn.myanimelist.net/images/anime/1/303.jpg
    #2   len=50  https://cdn.myanimelist.net/images/anime/1/740.jpg
    #3   len=50  https://cdn.myanimelist.net/images/anime/1/834.jpg
    #4   len=50  https://cdn.myanimelist.net/images/anime/1/317.jpg
    #5   len=50  https://cdn.myanimelist.net/images/anime/1/139.jpg
    #6   len=50  https://cdn.myanimelist.net/images/anime/1/137.jpg
    #7   len=50  https://cdn.myanimelist.net/images/anime/1/359.jpg
    #8   len=50  https://cdn.myanimelist.net/images/anime/1/864.jpg
    #9   len=50  https://cdn.myanimelist.net/images/anime/1/766.jpg
    #10  len=50  https://cdn.myanimelist.net/images/anime/1/952.jpg

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  50 – 50                                19     0.1%
  50 – 51                               372     1.3%
  51 – 52                             6,498    22.4%
  52 – 53                             3,171    11.0%
  53 – 54                                 0     0.0%
  54 – 55                             2,069     7.1%
  55 – 56                            16,628    57.4%
  56 – 57                                 0     0.0%
  57 – 58                                 0     0.0%
  58 – 59                                 0     0.0%
  59 – 60                                 0     0.0%
  60 – 61                                 0     0.0%
  61 – 62                                 0     0.0%
  62 – 63                                 0     0.0%
  63 – 64                               198     0.7%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                                                              Conteggio        %
  ────────────────────────────────────────────────────────────────   ──────────   ──────
  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png          198     0.7%
  https://cdn.myanimelist.net/images/anime/1043/144360.jpg                    1     0.0%
  https://cdn.myanimelist.net/images/anime/1057/137264.jpg                    1     0.0%
  https://cdn.myanimelist.net/images/anime/1798/115989.jpg                    1     0.0%
  https://cdn.myanimelist.net/images/anime/1566/151023.jpg                    1     0.0%
  https://cdn.myanimelist.net/images/anime/10/8661.jpg                        1     0.0%
  https://cdn.myanimelist.net/images/anime/2/23085.jpg                        1     0.0%
  https://cdn.myanimelist.net/images/anime/1844/131542.jpg                    1     0.0%
  https://cdn.myanimelist.net/images/anime/7/23079.jpg                        1     0.0%
  https://cdn.myanimelist.net/images/anime/1894/148837.jpg                    1     0.0%

  I 10 meno frequenti (più rari):
  Valore                                                              Conteggio        %
  ────────────────────────────────────────────────────────────────   ──────────   ──────
  https://cdn.myanimelist.net/images/anime/1462/138377.jpg                    1     0.0%
  https://cdn.myanimelist.net/images/anime/1498/104331.jpg                    1     0.0%
  https://cdn.myanimelist.net/images/anime/6/88310.jpg                        1     0.0%
  https://cdn.myanimelist.net/images/anime/3/82121.jpg                        1     0.0%
  https://cdn.myanimelist.net/images/anime/1518/149900.jpg                    1     0.0%
  https://cdn.myanimelist.net/images/anime/1782/141913.jpg                    1     0.0%
  https://cdn.myanimelist.net/images/anime/1096/126324.jpg                    1     0.0%
  https://cdn.myanimelist.net/images/anime/1697/128146.jpg                    1     0.0%
  https://cdn.myanimelist.net/images/anime/1281/129044.jpg                    1     0.0%
  https://cdn.myanimelist.net/images/anime/1043/130263.jpg                    1     0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 28,955  (100.0%)
  Contiene maiuscole             0  (0.0%)
  Contiene minuscole             28,955  (100.0%)
  Contiene spazi                 0  (0.0%)
  Contiene caratteri speciali    28,955  (100.0%)
  Contiene URL                   28,955  (100.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               1,583,516
  Caratteri unici                31
  Caratteri medi per valore      54.69

**Osservazioni:**
- **198 URL placeholder** (~0.7%): corrispondono all'immagine generica di MAL, segnale di assenza di copertina reale.
- **Aggiunta colonna `has_image`**: booleano che distingue gli anime con copertina reale (`True`) da quelli con placeholder (`False`).

In [14]:
DEFAULT_IMG = 'https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png'
df_details['has_image'] = df_details['image_url'] != DEFAULT_IMG
print(f'has_image → True (reale): {df_details["has_image"].sum():,}  |  False (placeholder): {(~df_details["has_image"]).sum():,}')

has_image → True (reale): 28,757  |  False (placeholder): 198

### 2.6 `type`

Colonna categorica con il tipo di anime (TV, Movie, OVA, ONA, Special, Music, CM, PV, TV Special). I null sono attesi per gli anime `Not yet aired` il cui tipo non è ancora registrato su MAL.

In [15]:
analyze(df_details['type'])

  Nome serie                     type
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,888  (99.77%)
  Null / NaN                     67  (0.23%)
  Stringhe vuote                 0
  Valori unici                   9  (0.03%)
  Valori duplicati               28,879

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  2  caratteri
  Lunghezza max                  10  caratteri
  Lunghezza media                3.73  caratteri
  Lunghezza mediana              3.0000  caratteri
  Dev. standard lunghezza        1.81
  IQR lunghezza                  3.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=10  TV Special
    #2   len=10  TV Special
    #3   len=10  TV Special
    #4   len=10  TV Special
    #5   len=10  TV Special
    #6   len=10  TV Special
    #7   len=10  TV Special
    #8   len=10  TV Special
    #9   len=10  TV Special
    #10  len=10  TV Special

  Le 10 stringhe più corte:
    #1   len=2  TV
    #2   len=2  TV
    #3   len=2  TV
    #4   len=2  TV
    #5   len=2  TV
    #6   len=2  TV
    #7   len=2  CM
    #8   len=2  TV
    #9   len=2  TV
    #10  len=2  TV

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  2 – 2                               9,172    31.8%
  2 – 3                               8,280    28.7%
  3 – 4                                   0     0.0%
  4 – 5                               8,914    30.9%
  5 – 6                                   0     0.0%
  6 – 7                               1,755     6.1%
  7 – 8                                   0     0.0%
  8 – 9                                   0     0.0%
  9 – 10                                767     2.7%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore        Conteggio        %
  ──────────   ──────────   ──────
  TV                8,414    29.1%
  Movie             4,915    17.0%
  OVA               4,184    14.5%
  ONA               4,096    14.2%
  Music             3,999    13.8%
  Special           1,755     6.1%
  TV Special          767     2.7%
  CM                  483     1.7%
  PV                  275     1.0%

  I 10 meno frequenti (più rari):
  Valore        Conteggio        %
  ──────────   ──────────   ──────
  PV                  275     1.0%
  CM                  483     1.7%
  TV Special          767     2.7%
  Special           1,755     6.1%
  Music             3,999    13.8%
  ONA               4,096    14.2%
  OVA               4,184    14.5%
  Movie             4,915    17.0%
  TV                8,414    29.1%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 0  (0.0%)
  Contiene maiuscole             28,888  (100.0%)
  Contiene minuscole             11,436  (39.6%)
  Contiene spazi                 767  (2.7%)
  Contiene caratteri speciali    0  (0.0%)
  Contiene URL                   0  (0.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                28,121
  Solo alfanumerico              28,121

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               107,709
  Caratteri unici                20
  Caratteri medi per valore      3.73

**Osservazioni:**
- **67 valori nulli**: strutturali, anime con stato `Not yet aired` per cui il tipo non è ancora registrato su MAL.
- **9 valori distinti**: tutti coerenti con la tassonomia MAL (TV, Movie, OVA, ONA, Special, Music, CM, PV, TV Special).

Nessuna pulizia necessaria.

In [16]:
# Nessuna operazione richiesta: i null sono strutturali (Not yet aired)
print(f'Null in type  : {df_details["type"].isna().sum()}')
print(f'Valori unici  : {sorted(df_details["type"].dropna().unique().tolist())}')

Null in type  : 67
Valori unici  : ['CM', 'Movie', 'Music', 'ONA', 'OVA', 'PV', 'Special', 'TV', 'TV Special']

### 2.7 `status`

Colonna categorica con lo stato di trasmissione. I valori attesi sono `Finished Airing`, `Currently Airing` e `Not yet aired`.

In [17]:
analyze(df_details['status'])

  Nome serie                     status
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Stringhe vuote                 0
  Valori unici                   3  (0.01%)
  Valori duplicati               28,952

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  13  caratteri
  Lunghezza max                  16  caratteri
  Lunghezza media                14.97  caratteri
  Lunghezza mediana              15.0000  caratteri
  Dev. standard lunghezza        0.29
  IQR lunghezza                  0.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=16  Currently Airing
    #2   len=16  Currently Airing
    #3   len=16  Currently Airing
    #4   len=16  Currently Airing
    #5   len=16  Currently Airing
    #6   len=16  Currently Airing
    #7   len=16  Currently Airing
    #8   len=16  Currently Airing
    #9   len=16  Currently Airing
    #10  len=16  Currently Airing

  Le 10 stringhe più corte:
    #1   len=13  Not yet aired
    #2   len=13  Not yet aired
    #3   len=13  Not yet aired
    #4   len=13  Not yet aired
    #5   len=13  Not yet aired
    #6   len=13  Not yet aired
    #7   len=13  Not yet aired
    #8   len=13  Not yet aired
    #9   len=13  Not yet aired
    #10  len=13  Not yet aired

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  13 – 13                               544     1.9%
  13 – 14                                 0     0.0%
  14 – 15                            28,097    97.0%
  15 – 16                               314     1.1%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore              Conteggio        %
  ────────────────   ──────────   ──────
  Finished Airing        28,097    97.0%
  Not yet aired             544     1.9%
  Currently Airing          314     1.1%

  I 10 meno frequenti (più rari):
  Valore              Conteggio        %
  ────────────────   ──────────   ──────
  Currently Airing          314     1.1%
  Not yet aired             544     1.9%
  Finished Airing        28,097    97.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 0  (0.0%)
  Contiene maiuscole             28,955  (100.0%)
  Contiene minuscole             28,955  (100.0%)
  Contiene spazi                 28,955  (100.0%)
  Contiene caratteri speciali    0  (0.0%)
  Contiene URL                   0  (0.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               433,551
  Caratteri unici                19
  Caratteri medi per valore      14.97

Analisi parole / token
────────────────────────────────────────────────────────────────────────────────

  Parole medie per valore        2.02
  Max parole                     3
  Min parole                     2

  Le 10 parole più comuni:
  Parola                  Conteggio
  ────────────────────   ──────────
  Airing                     28,411
  Finished                   28,097
  Not                           544
  yet                           544
  aired                         544
  Currently                     314

**Osservazioni:**
- **Nessun valore nullo**: tutti i 28.955 record hanno uno stato definito.
- **3 valori distinti**: `Finished Airing`, `Currently Airing`, `Not yet aired`, coerenti con la tassonomia MAL.

Nessuna pulizia necessaria.

In [18]:
# Nessuna operazione richiesta
print(f'Null in status : {df_details["status"].isna().sum()}')
print(df_details['status'].value_counts())

Null in status : 0
status
Finished Airing     28097
Not yet aired         544
Currently Airing      314
Name: count, dtype: int64

### 2.8 `score` e `scored_by`

Le due colonne sono co-nulle: quando un anime non ha voti sufficienti su MAL, entrambe sono `NaN`.

In [19]:
analyze(df_details['score'])

  Nome serie                     score
  dtype                          float64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               18,882  (65.21%)
  Null / NaN                     10,073  (34.79%)
  Zeri                           0  (0.00%)
  Positivi                       18,882   (65.21%)
  Negativi                       0   (0.00%)
  Valori unici                   561  (1.94%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            1.8900
  Max                            9.2900
  Range                          7.4000
  Media                          6.3905
  Mediana                        6.3600
  Moda/e                         6.2900
  Dev. standard                  0.8920
  Varianza                       0.7957
  Errore std (SEM)               0.0065
  IQR  (Q3 − Q1)                 1.2600
  Q1  (25° pct)                  5.7700
  Q3  (75° pct)                  7.0300
  P5  ( 5° pct)                  4.9900
  P95 (95° pct)                  7.8700
  Coefficiente di variazione     13.96%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   3.8800
  Soglia alta   (Q3 + 1.5×IQR)   8.9200
  Outlier rilevati               102  (0.35%)

  Top 5 outlier estremi (per valore assoluto):
    [23116]  9.2900
    [6593]  9.1000
    [23288]  9.0700
    [7379]  9.0500
    [7383]  9.0500

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  1 – 2                                   3     0.0%
  2 – 2                                   4     0.0%
  2 – 3                                   8     0.0%
  3 – 3                                  20     0.1%
  3 – 3                                  26     0.1%
  3 – 4                                  50     0.3%
  4 – 4                                 123     0.7%
  4 – 4                                 451     2.4%
  4 – 5                                 886     4.7%
  5 – 5                               1,890    10.0%
  5 – 5                               2,647    14.0%
  5 – 6                               2,991    15.8%
  6 – 6                               3,010    15.9%
  6 – 7                               2,275    12.0%
  7 – 7                               2,133    11.3%
  7 – 7                               1,280     6.8%
  7 – 8                                 629     3.3%
  8 – 8                                 326     1.7%
  8 – 8                                 111     0.6%
  8 – 9                                  19     0.1%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   9.2900  [indice 23116]
    #2   9.1000  [indice 6593]
    #3   9.0700  [indice 23288]
    #4   9.0500  [indice 7379]
    #5   9.0500  [indice 7383]
    #6   9.0500  [indice 22020]
    #7   9.0300  [indice 9671]
    #8   9.0300  [indice 17926]
    #9   9.0200  [indice 7291]
    #10  9.0200  [indice 7367]

  I 10 più piccoli:
    #1   1.8900  [indice 24273]
    #2   2.0100  [indice 26063]
    #3   2.2300  [indice 8219]
    #4   2.3300  [indice 25364]
    #5   2.4100  [indice 12885]
    #6   2.4300  [indice 668]
    #7   2.5600  [indice 329]
    #8   2.6800  [indice 440]
    #9   2.6800  [indice 14102]
    #10  2.7500  [indice 17254]

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                6.2900          102     0.4%
                6.3300          100     0.3%
                6.5300           99     0.3%
                6.5100           98     0.3%
                6.2100           97     0.3%
                6.4600           95     0.3%
                6.0600           95     0.3%
                6.4100           95     0.3%
                5.9800           94     0.3%
                6.4400           93     0.3%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                3.5300            1     0.0%
                4.0000            1     0.0%
                3.4800            1     0.0%
                3.6400            1     0.0%
                8.8400            1     0.0%
                8.8200            1     0.0%
                3.3300            1     0.0%
                2.0100            1     0.0%
                2.3300            1     0.0%
                1.8900            1     0.0%

In [20]:
analyze(df_details['scored_by'])

  Nome serie                     scored_by
  dtype                          float64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               18,882  (65.21%)
  Null / NaN                     10,073  (34.79%)
  Zeri                           0  (0.00%)
  Positivi                       18,882   (65.21%)
  Negativi                       0   (0.00%)
  Valori unici                   9,245  (31.93%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            101.0000
  Max                            2,979,733
  Range                          2,979,632
  Media                          29,963.08
  Mediana                        1,528.00
  Moda/e                         120.0000
  Dev. standard                  121,966.56
  Varianza                       14,875,842,969
  Errore std (SEM)               887.5990
  IQR  (Q3 − Q1)                 9,813.50
  Q1  (25° pct)                  332.2500
  Q3  (75° pct)                  10,145.75
  P5  ( 5° pct)                  134.0000
  P95 (95° pct)                  138,467.35
  Coefficiente di variazione     407.06%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -14,388.00
  Soglia alta   (Q3 + 1.5×IQR)   24,866.00
  Outlier rilevati               3,150  (10.88%)

  Top 5 outlier estremi (per valore assoluto):
    [22010]  2,979,733
    [4788]  2,919,353
    [17990]  2,365,396
    [12300]  2,281,401
    [6593]  2,248,907

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  101 – 149,082                      18,019    95.4%
  149,082 – 298,064                     452     2.4%
  298,064 – 447,045                     160     0.8%
  447,045 – 596,027                      82     0.4%
  596,027 – 745,009                      52     0.3%
  745,009 – 893,990                      26     0.1%
  893,990 – 1,042,972                    28     0.1%
  1,042,972 – 1,191,953                  17     0.1%
  1,191,953 – 1,340,935                  11     0.1%
  1,340,935 – 1,489,917                  14     0.1%
  1,489,917 – 1,638,898                   3     0.0%
  1,638,898 – 1,787,880                   4     0.0%
  1,787,880 – 1,936,861                   3     0.0%
  1,936,861 – 2,085,843                   3     0.0%
  2,085,843 – 2,234,825                   2     0.0%
  2,234,825 – 2,383,806                   4     0.0%
  2,383,806 – 2,532,788                   0     0.0%
  2,532,788 – 2,681,769                   0     0.0%
  2,681,769 – 2,830,751                   0     0.0%
  2,830,751 – 2,979,733                   2     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   2,979,733  [indice 22010]
    #2   2,919,353  [indice 4788]
    #3   2,365,396  [indice 17990]
    #4   2,281,401  [indice 12300]
    #5   2,248,907  [indice 6593]
    #6   2,240,438  [indice 23654]
    #7   2,181,208  [indice 2633]
    #8   2,088,445  [indice 16821]
    #9   2,027,815  [indice 12360]
    #10  2,003,062  [indice 22017]

  I 10 più piccoli:
    #1   101.0000  [indice 9274]
    #2   101.0000  [indice 17221]
    #3   101.0000  [indice 25338]
    #4   102.0000  [indice 6562]
    #5   102.0000  [indice 7693]
    #6   102.0000  [indice 12256]
    #7   102.0000  [indice 13395]
    #8   102.0000  [indice 15143]
    #9   103.0000  [indice 1637]
    #10  103.0000  [indice 2744]

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
              120.0000           46     0.2%
              121.0000           44     0.2%
              117.0000           42     0.1%
              111.0000           41     0.1%
              127.0000           40     0.1%
              132.0000           40     0.1%
              143.0000           39     0.1%
              151.0000           39     0.1%
              135.0000           39     0.1%
              133.0000           38     0.1%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
              1,887.00            1     0.0%
             10,038.00            1     0.0%
            104,106.00            1     0.0%
             15,624.00            1     0.0%
              2,219.00            1     0.0%
             14,906.00            1     0.0%
              4,192.00            1     0.0%
             94,201.00            1     0.0%
            250,375.00            1     0.0%
             65,863.00            1     0.0%

**Osservazioni:**
- **10.073 valori nulli** (~34.8%) in entrambe le colonne: strutturali, anime senza voti sufficienti per avere uno score su MAL. Co-nullità confermata.
- **`score`**: dtype `float64` corretto (valori decimali). Nessuna conversione necessaria.
- **`scored_by`**: dtype `float64` → convertito a `Int64` (nullable integer), dato che i valori sono interi.

In [21]:
# Verifica co-nullità
print(f'Null in score     : {df_details["score"].isna().sum():,}')
print(f'Null in scored_by : {df_details["scored_by"].isna().sum():,}')
print(f'Co-nulli (entrambi NaN) : {(df_details["score"].isna() & df_details["scored_by"].isna()).sum():,}')
print()

df_details['scored_by'] = df_details['scored_by'].astype('Int64')
print(f'scored_by dtype : {df_details["scored_by"].dtype}')

Null in score     : 10,073
Null in scored_by : 10,073
Co-nulli (entrambi NaN) : 10,073

scored_by dtype : Int64

### 2.9 `start_date`

Data di inizio trasmissione, memorizzata come stringa ISO 8601 con timezone UTC. Va convertita in `datetime64[us, UTC]`. I null sono attesi per gli anime `Not yet aired` senza data confermata.

In [22]:
analyze(df_details['start_date'])

  Nome serie                     start_date
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,104  (97.06%)
  Null / NaN                     851  (2.94%)
  Stringhe vuote                 0
  Valori unici                   9,367  (32.35%)
  Valori duplicati               18,737

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  25  caratteri
  Lunghezza max                  25  caratteri
  Lunghezza media                25.00  caratteri
  Lunghezza mediana              25.0000  caratteri
  Dev. standard lunghezza        0.00
  IQR lunghezza                  0.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=25  2010-01-01T00:00:00+00:00
    #2   len=25  2023-06-11T00:00:00+00:00
    #3   len=25  2007-01-18T00:00:00+00:00
    #4   len=25  2007-12-22T00:00:00+00:00
    #5   len=25  2008-03-25T00:00:00+00:00
    #6   len=25  2003-11-16T00:00:00+00:00
    #7   len=25  2003-03-28T00:00:00+00:00
    #8   len=25  2002-06-20T00:00:00+00:00
    #9   len=25  2011-01-28T00:00:00+00:00
    #10  len=25  2011-01-28T00:00:00+00:00

  Le 10 stringhe più corte:
    #1   len=25  2010-01-01T00:00:00+00:00
    #2   len=25  2023-06-11T00:00:00+00:00
    #3   len=25  2007-01-18T00:00:00+00:00
    #4   len=25  2007-12-22T00:00:00+00:00
    #5   len=25  2008-03-25T00:00:00+00:00
    #6   len=25  2003-11-16T00:00:00+00:00
    #7   len=25  2003-03-28T00:00:00+00:00
    #8   len=25  2002-06-20T00:00:00+00:00
    #9   len=25  2011-01-28T00:00:00+00:00
    #10  len=25  2011-01-28T00:00:00+00:00

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Tutte le stringhe hanno la stessa lunghezza. (25 caratteri)

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                       Conteggio        %
  ─────────────────────────   ──────────   ──────
  2012-01-01T00:00:00+00:00          158     0.6%
  2011-01-01T00:00:00+00:00          153     0.5%
  2019-01-01T00:00:00+00:00          146     0.5%
  2010-01-01T00:00:00+00:00          145     0.5%
  2026-01-01T00:00:00+00:00          133     0.5%
  2015-01-01T00:00:00+00:00          125     0.4%
  2013-01-01T00:00:00+00:00          122     0.4%
  2008-01-01T00:00:00+00:00          114     0.4%
  2009-01-01T00:00:00+00:00          110     0.4%
  2014-01-01T00:00:00+00:00          109     0.4%

  I 10 meno frequenti (più rari):
  Valore                       Conteggio        %
  ─────────────────────────   ──────────   ──────
  2019-08-17T00:00:00+00:00            1     0.0%
  1995-11-11T00:00:00+00:00            1     0.0%
  1980-04-15T00:00:00+00:00            1     0.0%
  1992-07-04T00:00:00+00:00            1     0.0%
  2015-12-08T00:00:00+00:00            1     0.0%
  2011-05-18T00:00:00+00:00            1     0.0%
  2014-05-21T00:00:00+00:00            1     0.0%
  2009-02-27T00:00:00+00:00            1     0.0%
  2019-05-19T00:00:00+00:00            1     0.0%
  2020-10-17T00:00:00+00:00            1     0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 28,104  (100.0%)
  Contiene maiuscole             28,104  (100.0%)
  Contiene minuscole             0  (0.0%)
  Contiene spazi                 0  (0.0%)
  Contiene caratteri speciali    28,104  (100.0%)
  Contiene URL                   0  (0.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               702,600
  Caratteri unici                14
  Caratteri medi per valore      25.00

**Osservazioni:**
- **851 valori nulli** (~2.9%): strutturali, anime `Not yet aired` senza data confermata.
- **Conversione dtype**: da stringa ISO 8601 a `datetime64[us, UTC]`.

In [23]:
df_details['start_date'] = pd.to_datetime(df_details['start_date'], errors='coerce', utc=True)
print(f'start_date dtype : {df_details["start_date"].dtype}')
print(f'Null residui     : {df_details["start_date"].isna().sum()}')
print(f'Range            : {df_details["start_date"].min()} → {df_details["start_date"].max()}')

start_date dtype : datetime64[us, UTC]
Null residui     : 851
Range            : 1917-01-01 00:00:00+00:00 → 2027-01-01 00:00:00+00:00

### 2.10 `end_date`

Data di fine trasmissione, stessa struttura di `start_date`. I null sono strutturalmente più numerosi: gli anime `Currently Airing` e `Not yet aired` non hanno ancora una data di fine.

In [24]:
analyze(df_details['end_date'])

  Nome serie                     end_date
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               11,267  (38.91%)
  Null / NaN                     17,688  (61.09%)
  Stringhe vuote                 0
  Valori unici                   5,607  (19.36%)
  Valori duplicati               5,660

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  25  caratteri
  Lunghezza max                  25  caratteri
  Lunghezza media                25.00  caratteri
  Lunghezza mediana              25.0000  caratteri
  Dev. standard lunghezza        0.00
  IQR lunghezza                  0.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=25  2003-04-10T00:00:00+00:00
    #2   len=25  2011-04-07T00:00:00+00:00
    #3   len=25  2011-04-07T00:00:00+00:00
    #4   len=25  2006-09-28T00:00:00+00:00
    #5   len=25  2002-09-26T00:00:00+00:00
    #6   len=25  2003-03-27T00:00:00+00:00
    #7   len=25  2018-12-28T00:00:00+00:00
    #8   len=25  2024-09-22T00:00:00+00:00
    #9   len=25  2025-03-23T00:00:00+00:00
    #10  len=25  1964-10-27T00:00:00+00:00

  Le 10 stringhe più corte:
    #1   len=25  2003-04-10T00:00:00+00:00
    #2   len=25  2011-04-07T00:00:00+00:00
    #3   len=25  2011-04-07T00:00:00+00:00
    #4   len=25  2006-09-28T00:00:00+00:00
    #5   len=25  2002-09-26T00:00:00+00:00
    #6   len=25  2003-03-27T00:00:00+00:00
    #7   len=25  2018-12-28T00:00:00+00:00
    #8   len=25  2024-09-22T00:00:00+00:00
    #9   len=25  2025-03-23T00:00:00+00:00
    #10  len=25  1964-10-27T00:00:00+00:00

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Tutte le stringhe hanno la stessa lunghezza. (25 caratteri)

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                       Conteggio        %
  ─────────────────────────   ──────────   ──────
  2013-01-01T00:00:00+00:00           21     0.2%
  2019-01-01T00:00:00+00:00           18     0.2%
  2012-01-01T00:00:00+00:00           18     0.2%
  2014-01-01T00:00:00+00:00           17     0.2%
  2023-03-26T00:00:00+00:00           17     0.2%
  2008-01-01T00:00:00+00:00           15     0.1%
  2016-03-25T00:00:00+00:00           14     0.1%
  2011-01-01T00:00:00+00:00           14     0.1%
  2017-01-01T00:00:00+00:00           14     0.1%
  2016-03-26T00:00:00+00:00           14     0.1%

  I 10 meno frequenti (più rari):
  Valore                       Conteggio        %
  ─────────────────────────   ──────────   ──────
  2017-11-22T00:00:00+00:00            1     0.0%
  1980-09-23T00:00:00+00:00            1     0.0%
  2020-07-22T00:00:00+00:00            1     0.0%
  2025-07-05T00:00:00+00:00            1     0.0%
  2011-11-16T00:00:00+00:00            1     0.0%
  2007-09-12T00:00:00+00:00            1     0.0%
  2016-07-23T00:00:00+00:00            1     0.0%
  2021-11-19T00:00:00+00:00            1     0.0%
  2009-03-31T00:00:00+00:00            1     0.0%
  2001-04-25T00:00:00+00:00            1     0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 11,267  (100.0%)
  Contiene maiuscole             11,267  (100.0%)
  Contiene minuscole             0  (0.0%)
  Contiene spazi                 0  (0.0%)
  Contiene caratteri speciali    11,267  (100.0%)
  Contiene URL                   0  (0.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               281,675
  Caratteri unici                14
  Caratteri medi per valore      25.00

**Osservazioni:**
- **17.688 valori nulli** (~61.1%): strutturali, anime `Currently Airing` o `Not yet aired` non hanno ancora una data di fine.
- **Conversione dtype**: da stringa ISO 8601 a `datetime64[us, UTC]`.

In [25]:
df_details['end_date'] = pd.to_datetime(df_details['end_date'], errors='coerce', utc=True)
print(f'end_date dtype : {df_details["end_date"].dtype}')
print(f'Null residui   : {df_details["end_date"].isna().sum()}')
print(f'Range          : {df_details["end_date"].min()} → {df_details["end_date"].max()}')

end_date dtype : datetime64[us, UTC]
Null residui   : 17688
Range          : 1962-02-25 00:00:00+00:00 → 2026-04-10 00:00:00+00:00

### 2.11 `synopsis`

Testo della sinossi dell'anime. I null sono strutturali: cortometraggi, CM e PV spesso non hanno una sinossi registrata su MAL. Aggiungiamo una colonna booleana `has_synopsis` per distinguere i casi.

In [26]:
analyze(df_details['synopsis'])

  Nome serie                     synopsis
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               23,828  (82.29%)
  Null / NaN                     5,127  (17.71%)
  Stringhe vuote                 0
  Valori unici                   23,540  (81.30%)
  Valori duplicati               288

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  10  caratteri
  Lunghezza max                  3,750  caratteri
  Lunghezza media                377.40  caratteri
  Lunghezza mediana              251.0000  caratteri
  Dev. standard lunghezza        351.38
  IQR lunghezza                  499.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=3750  Li Xiaobai, who entered the immersive stand-alone game Faerie Continent, joined the Xianyu Sect of the Northern Territor…
    #2   len=3635  Tezuka × Atobe ÷ Koharu↵ Fudomine Middle School's tennis captain, Kippei Tachibana, asks rival school captains Kunimitsu…
    #3   len=3268  One hundred thousand years ago, the immortal world was in a melee, the gods fell, and a hidden mystery "Book of Life and…
    #4   len=2737  In In the year 2113 A.D., a team of scientists is dispatched to Antarctica to investigate the region's abnormal seismic …
    #5   len=2731  In the previous life, although Qin Yichen, the sage of alchemy, possessed the most alchemy technique in the mainland and…
    #6   len=2633  The plot consists of a chase of a hijacked MBT-99A tank, designed by the United States Air Force (which is odd, but will…
    #7   len=2615  This film consists of 6 animated shorts produced by the Human Rights Commission of Korea.  Like the previous movie, the …
    #8   len=2412  GOSHO collection reveals the origin of the smash hit "Detective Conan." "GO" into his world, and we will "SHO" you SEVEN…
    #9   len=2410  Shouhei Zenya (The Night Before The Invitation)↵ Prior to the U-17 training camp invitations, the middle schoolers spend…
    #10  len=2315  Based on a seinen manga by Kikuchi Naoe and Yokomi Hirohiko, serialised in IKKI. ↵ ↵ The "story" is that a manga artist …

  Le 10 stringhe più corte:
    #1   len=10  G9+1 film.
    #2   len=12  BD Specials.
    #3   len=12  BD specials.
    #4   len=12  DVD special.
    #5   len=13  DVD/BD extra.
    #6   len=13  Nurse hentai.
    #7   len=13  DVD specials.
    #8   len=13  DVD Specials.
    #9   len=14  Chinpui movie.
    #10  len=14  Second season.

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  10 – 197                           10,641    44.7%
  197 – 384                           4,010    16.8%
  384 – 571                           2,984    12.5%
  571 – 758                           2,166     9.1%
  758 – 945                           1,799     7.5%
  945 – 1,132                         1,395     5.9%
  1,132 – 1,319                         582     2.4%
  1,319 – 1,506                         154     0.6%
  1,506 – 1,693                          50     0.2%
  1,693 – 1,880                          20     0.1%
  1,880 – 2,067                          10     0.0%
  2,067 – 2,254                           7     0.0%
  2,254 – 2,441                           3     0.0%
  2,441 – 2,628                           1     0.0%
  2,628 – 2,815                           3     0.0%
  2,815 – 3,002                           0     0.0%
  3,002 – 3,189                           0     0.0%
  3,189 – 3,376                           1     0.0%
  3,376 – 3,563                           0     0.0%
  3,563 – 3,750                           2     0.0%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Conteggio        %
  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────   ──────────   ──────
  No synopsis has been added for this series yet.↵ ↵ Click here to update this information.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              23     0.1%
  Furukawa Taku film.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    12     0.1%
  Film by Takashi Ito.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   12     0.1%
  A short animation by Taku Furukawa.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    10     0.0%
  A short film by Okamoto Tadanari.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       7     0.0%
  Short animation by Rapparu.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             6     0.0%
  Short film by Hirano Ryou.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              6     0.0%
  A short puppet animation movie by Tadahito Mochinaga.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   6     0.0%
  Short film by Kurosaka Keita.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           6     0.0%
  A short film by Haruka Suzuki.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          5     0.0%

  I 10 meno frequenti (più rari):
  Valore                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Conteggio        %
  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────   ──────────   ──────
  Music video for the song Zutto Tomodachi by Keiko Utsumi that was featured on NHK's Minna no Uta program.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1     0.0%
  Setsuna Shiraha has loved her childhood friend Ginta Akaishi for a very long time. Her feelings for him are immensely strong, having grown to the point where she masturbates while smelling his used shirts. One unfortunate night, however, when Shiraha is touching herself in the locker room, her teacher Kuroki catches her red-handed, blackmails her, and proceeds to force himself on her. Being helpless, Shiraha cannot do anything but endure the pain and suffering—lest both her and Akaishi's reputations be forever tarnished.↵ ↵ [Written by MAL Rewrite]                                                                                                                                                                                                                                                                                                                                                                                                              1     0.0%

**Osservazioni:**
- **5.127 valori nulli** (~17.7%): strutturali, anime privi di sinossi su MAL (spesso cortometraggi, CM, PV).
- **Aggiunta colonna `has_synopsis`**: booleano che indica la presenza di una sinossi.

In [27]:
df_details['has_synopsis'] = df_details['synopsis'].notna()
print(f'has_synopsis → True (con sinossi): {df_details["has_synopsis"].sum():,}  |  False: {(~df_details["has_synopsis"]).sum():,}')

has_synopsis → True (con sinossi): 23,828  |  False: 5,127

### 2.12 `rank`

Classifica globale MAL basata sullo score. I null sono strutturali: anime senza score sufficiente non ricevono un rank. Il dtype `float64` va convertito a `Int64` (nullable integer).

In [28]:
analyze(df_details['rank'])

  Nome serie                     rank
  dtype                          float64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               21,997  (75.97%)
  Null / NaN                     6,958  (24.03%)
  Zeri                           0  (0.00%)
  Positivi                       21,997   (75.97%)
  Negativi                       0   (0.00%)
  Valori unici                   17,765  (61.35%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            1.0000
  Max                            22,020.00
  Range                          22,019.00
  Media                          11,033.16
  Mediana                        11,008.00
  Moda/e                         2,651.00, 2,819.00, 9,326.00
  Dev. standard                  6,388.28
  Varianza                       40,810,115
  Errore std (SEM)               43.0727
  IQR  (Q3 − Q1)                 11,010.00
  Q1  (25° pct)                  5,505.00
  Q3  (75° pct)                  16,515.00
  P5  ( 5° pct)                  1,102.80
  P95 (95° pct)                  21,027.40
  Coefficiente di variazione     57.90%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -11,010.00
  Soglia alta   (Q3 + 1.5×IQR)   33,030.00
  Outlier rilevati               0  (0.00%)

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  1 – 1,101                           1,099     5.0%
  1,101 – 2,202                       1,100     5.0%
  2,202 – 3,303                       1,100     5.0%
  3,303 – 4,404                       1,101     5.0%
  4,404 – 5,505                       1,100     5.0%
  5,505 – 6,606                       1,098     5.0%
  6,606 – 7,707                       1,104     5.0%
  7,707 – 8,808                       1,100     5.0%
  8,808 – 9,909                       1,100     5.0%
  9,909 – 11,010                      1,099     5.0%
  11,010 – 12,111                     1,097     5.0%
  12,111 – 13,212                     1,100     5.0%
  13,212 – 14,313                     1,097     5.0%
  14,313 – 15,414                     1,101     5.0%
  15,414 – 16,515                     1,102     5.0%
  16,515 – 17,616                     1,053     4.8%
  17,616 – 18,717                     1,029     4.7%
  18,717 – 19,818                     1,005     4.6%
  19,818 – 20,919                     1,194     5.4%
  20,919 – 22,020                     1,218     5.5%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   22,020.00  [indice 10035]
    #2   22,019.00  [indice 20107]
    #3   22,018.00  [indice 20122]
    #4   22,017.00  [indice 20103]
    #5   22,016.00  [indice 20102]
    #6   22,016.00  [indice 20120]
    #7   22,015.00  [indice 20109]
    #8   22,014.00  [indice 20108]
    #9   22,013.00  [indice 9992]
    #10  22,013.00  [indice 20099]

  I 10 più piccoli:
    #1   1.0000  [indice 23116]
    #2   2.0000  [indice 6593]
    #3   3.0000  [indice 23288]
    #4   4.0000  [indice 22020]
    #5   5.0000  [indice 7379]
    #6   6.0000  [indice 7383]
    #7   7.0000  [indice 9671]
    #8   8.0000  [indice 17926]
    #9   9.0000  [indice 7291]
    #10  10.0000  [indice 7367]

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
              2,651.00            4     0.0%
             17,918.00            4     0.0%
             11,370.00            4     0.0%
              2,819.00            4     0.0%
             21,304.00            4     0.0%
             19,113.00            4     0.0%
              9,326.00            4     0.0%
             12,891.00            4     0.0%
             10,183.00            3     0.0%
              6,715.00            3     0.0%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
              3,494.00            1     0.0%
             17,085.00            1     0.0%
             17,084.00            1     0.0%
              3,516.00            1     0.0%
             10,390.00            1     0.0%
             17,082.00            1     0.0%
             17,080.00            1     0.0%
             17,079.00            1     0.0%
             17,077.00            1     0.0%
             11,688.00            1     0.0%

**Osservazioni:**
- **6.958 valori nulli** (~24.0%): strutturali, anime non classificati da MAL (score assente o insufficiente).
- **Conversione dtype**: da `float64` a `Int64` (nullable integer), dato che i valori sono interi.

In [29]:
df_details['rank'] = df_details['rank'].astype('Int64')
print(f'rank dtype   : {df_details["rank"].dtype}')
print(f'Null residui : {df_details["rank"].isna().sum():,}')

rank dtype   : Int64
Null residui : 6,958

### 2.13 `popularity`, `members`, `favorites`

Tre colonne numeriche che misurano l'interesse degli utenti MAL verso l'anime. Sono sempre valorizzate (anche gli anime senza voti hanno qualche utente nella lista). Il dtype `int64` è già corretto.

In [30]:
for col in ['popularity', 'members', 'favorites']:
    analyze(df_details[col])

  Nome serie                     popularity
  dtype                          int64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Zeri                           0  (0.00%)
  Positivi                       28,955   (100.00%)
  Negativi                       0   (0.00%)
  Valori unici                   21,954  (75.82%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            1
  Max                            28,999
  Range                          28,998
  Media                          14,500.36
  Mediana                        14,497.00
  Moda/e                         10,785, 15,862, 21,379
  Dev. standard                  8,373.66
  Varianza                       70,118,240
  Errore std (SEM)               49.2100
  IQR  (Q3 − Q1)                 14,507.00
  Q1  (25° pct)                  7,247.50
  Q3  (75° pct)                  21,754.50
  P5  ( 5° pct)                  1,450.70
  P95 (95° pct)                  27,549.00
  Coefficiente di variazione     57.75%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -14,513.00
  Soglia alta   (Q3 + 1.5×IQR)   43,515.00
  Outlier rilevati               0  (0.00%)

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  1 – 1,450                           1,448     5.0%
  1,450 – 2,900                       1,448     5.0%
  2,900 – 4,350                       1,450     5.0%
  4,350 – 5,800                       1,450     5.0%
  5,800 – 7,250                       1,447     5.0%
  7,250 – 8,700                       1,449     5.0%
  8,700 – 10,150                      1,444     5.0%
  10,150 – 11,600                     1,452     5.0%
  11,600 – 13,050                     1,445     5.0%
  13,050 – 14,500                     1,448     5.0%
  14,500 – 15,949                     1,440     5.0%
  15,949 – 17,399                     1,447     5.0%
  17,399 – 18,849                     1,450     5.0%
  18,849 – 20,299                     1,446     5.0%
  20,299 – 21,749                     1,447     5.0%
  21,749 – 23,199                     1,445     5.0%
  23,199 – 24,649                     1,449     5.0%
  24,649 – 26,099                     1,450     5.0%
  26,099 – 27,549                     1,454     5.0%
  27,549 – 28,999                     1,446     5.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   28,999  [indice 27903]
    #2   28,997  [indice 22580]
    #3   28,995  [indice 1676]
    #4   28,995  [indice 13829]
    #5   28,993  [indice 15901]
    #6   28,993  [indice 27904]
    #7   28,992  [indice 651]
    #8   28,991  [indice 14014]
    #9   28,989  [indice 1353]
    #10  28,989  [indice 26780]

  I 10 più piccoli:
    #1   1  [indice 22010]
    #2   2  [indice 4788]
    #3   3  [indice 6593]
    #4   4  [indice 17990]
    #5   5  [indice 12300]
    #6   6  [indice 23654]
    #7   7  [indice 2633]
    #8   8  [indice 9671]
    #9   9  [indice 16821]
    #10  10  [indice 24921]

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                24,020            5     0.0%
                10,785            5     0.0%
                15,862            5     0.0%
                21,379            5     0.0%
                26,019            5     0.0%
                20,862            4     0.0%
                 6,847            4     0.0%
                14,372            4     0.0%
                14,977            4     0.0%
                18,513            4     0.0%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                24,773            1     0.0%
                 8,916            1     0.0%
                 4,680            1     0.0%
                 1,077            1     0.0%
                21,427            1     0.0%
                24,834            1     0.0%
                27,775            1     0.0%
                11,703            1     0.0%
                13,183            1     0.0%
                11,466            1     0.0%


  Nome serie                     members
  dtype                          int64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Zeri                           0  (0.00%)
  Positivi                       28,955   (100.00%)
  Negativi                       0   (0.00%)
  Valori unici                   12,276  (42.40%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            23
  Max                            4,230,312
  Range                          4,230,289
  Media                          38,753.37
  Mediana                        1,077.00
  Moda/e                         80
  Dev. standard                  167,376.33
  Varianza                       28,014,834,772
  Errore std (SEM)               983.6311
  IQR  (Q3 − Q1)                 8,960.50
  Q1  (25° pct)                  233.0000
  Q3  (75° pct)                  9,193.50
  P5  ( 5° pct)                  82.7000
  P95 (95° pct)                  182,254.70
  Coefficiente di variazione     431.90%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -13,207.75
  Soglia alta   (Q3 + 1.5×IQR)   22,634.25
  Outlier rilevati               5,042  (17.41%)

  Top 5 outlier estremi (per valore assoluto):
    [22010]  4,230,312
    [4788]  4,170,767
    [6593]  3,576,199
    [17990]  3,430,848
    [12300]  3,323,322

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  23 – 211,537                       27,690    95.6%
  211,537 – 423,051                     663     2.3%
  423,051 – 634,566                     227     0.8%
  634,566 – 846,080                     131     0.5%
  846,080 – 1,057,595                    78     0.3%
  1,057,595 – 1,269,109                  48     0.2%
  1,269,109 – 1,480,624                  24     0.1%
  1,480,624 – 1,692,138                  23     0.1%
  1,692,138 – 1,903,653                  25     0.1%
  1,903,653 – 2,115,167                  10     0.0%
  2,115,167 – 2,326,681                  12     0.0%
  2,326,681 – 2,538,196                   6     0.0%
  2,538,196 – 2,749,710                   5     0.0%
  2,749,710 – 2,961,225                   3     0.0%
  2,961,225 – 3,172,739                   3     0.0%
  3,172,739 – 3,384,254                   3     0.0%
  3,384,254 – 3,595,768                   2     0.0%
  3,595,768 – 3,807,283                   0     0.0%
  3,807,283 – 4,018,797                   0     0.0%
  4,018,797 – 4,230,312                   2     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   4,230,312  [indice 22010]
    #2   4,170,767  [indice 4788]
    #3   3,576,199  [indice 6593]
    #4   3,430,848  [indice 17990]
    #5   3,323,322  [indice 12300]
    #6   3,232,300  [indice 23654]
    #7   3,212,739  [indice 2633]
    #8   3,080,867  [indice 9671]
    #9   3,035,328  [indice 16821]
    #10  2,984,661  [indice 24921]

  I 10 più piccoli:
    #1   23  [indice 27903]
    #2   24  [indice 13829]
    #3   24  [indice 22580]
    #4   25  [indice 1676]
    #5   25  [indice 27904]
    #6   26  [indice 15901]
    #7   27  [indice 651]
    #8   27  [indice 14014]
    #9   27  [indice 22160]
    #10  27  [indice 26780]

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                    80          127     0.4%
                    83          122     0.4%
                    82          117     0.4%
                    79          117     0.4%
                    78          112     0.4%
                    84          110     0.4%
                    81          109     0.4%
                    86          104     0.4%
                    77           99     0.3%
                    75           93     0.3%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                 5,525            1     0.0%
                27,334            1     0.0%
               249,631            1     0.0%
                46,157            1     0.0%
                11,529            1     0.0%
                75,080            1     0.0%
                 2,588            1     0.0%
                13,757            1     0.0%
                10,893            1     0.0%
               232,624            1     0.0%


  Nome serie                     favorites
  dtype                          int64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Zeri                           12,923  (44.63%)
  Positivi                       16,032   (55.37%)
  Negativi                       0   (0.00%)
  Valori unici                   1,984  (6.85%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            0
  Max                            243,358
  Range                          243,358
  Media                          430.8490
  Mediana                        1.0000
  Moda/e                         0
  Dev. standard                  4,520.61
  Varianza                       20,435,916
  Errore std (SEM)               26.5666
  IQR  (Q3 − Q1)                 17.0000
  Q1  (25° pct)                  0.0000
  Q3  (75° pct)                  17.0000
  P5  ( 5° pct)                  0.0000
  P95 (95° pct)                  806.9000
  Coefficiente di variazione     1049.23%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -25.5000
  Soglia alta   (Q3 + 1.5×IQR)   42.5000
  Outlier rilevati               5,336  (18.43%)

  Top 5 outlier estremi (per valore assoluto):
    [17919]  243,358
    [6593]  236,754
    [9671]  223,927
    [23288]  198,245
    [22010]  183,305

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  0 – 12,167                         28,742    99.3%
  12,167 – 24,335                       106     0.4%
  24,335 – 36,503                        51     0.2%
  36,503 – 48,671                        14     0.0%
  48,671 – 60,839                        14     0.0%
  60,839 – 73,007                         6     0.0%
  73,007 – 85,175                         7     0.0%
  85,175 – 97,343                         6     0.0%
  97,343 – 109,511                        0     0.0%
  109,511 – 121,679                       3     0.0%
  121,679 – 133,846                       0     0.0%
  133,846 – 146,014                       0     0.0%
  146,014 – 158,182                       0     0.0%
  158,182 – 170,350                       0     0.0%
  170,350 – 182,518                       1     0.0%
  182,518 – 194,686                       1     0.0%
  194,686 – 206,854                       1     0.0%
  206,854 – 219,022                       0     0.0%
  219,022 – 231,190                       1     0.0%
  231,190 – 243,358                       2     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   243,358  [indice 17919]
    #2   236,754  [indice 6593]
    #3   223,927  [indice 9671]
    #4   198,245  [indice 23288]
    #5   183,305  [indice 22010]
    #6   181,989  [indice 4788]
    #7   118,013  [indice 16833]
    #8   114,139  [indice 4091]
    #9   114,076  [indice 22129]
    #10  94,186  [indice 12360]

  I 10 più piccoli:
    #1   0  [indice 0]
    #2   0  [indice 17]
    #3   0  [indice 18]
    #4   0  [indice 22]
    #5   0  [indice 30]
    #6   0  [indice 32]
    #7   0  [indice 34]
    #8   0  [indice 38]
    #9   0  [indice 39]
    #10  0  [indice 40]

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                     0       12,923    44.6%
                     1        2,657     9.2%
                     2        1,344     4.6%
                     3          859     3.0%
                     4          639     2.2%
                     5          513     1.8%
                     6          424     1.5%
                     7          354     1.2%
                     8          310     1.1%
                     9          267     0.9%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                 1,621            1     0.0%
                 3,323            1     0.0%
                 4,204            1     0.0%
                 1,042            1     0.0%
                 1,494            1     0.0%
                 6,566            1     0.0%
                 8,120            1     0.0%
                23,052            1     0.0%
                 1,742            1     0.0%
                 1,129            1     0.0%

**Osservazioni:**
- **Nessun valore nullo** in nessuna delle tre colonne.
- **Dtype corretto**: `int64` per tutte e tre.
- **Distribuzioni asimmetriche**: code lunghe verso destra, da tenere in considerazione nelle analisi.

Nessuna pulizia necessaria.

In [31]:
# Nessuna operazione richiesta
for col in ['popularity', 'members', 'favorites']:
    print(f'Null in {col:<12}: {df_details[col].isna().sum()}')

Null in popularity  : 0
Null in members     : 0
Null in favorites   : 0

### 2.14 `genres`, `studios`, `themes`, `demographics`, `producers`, `licensors`, `streaming`

Colonne contenenti liste serializzate come stringhe Python (es. `"['Comedy', 'Drama']"`).

In [32]:
list_cols = ['genres', 'studios', 'themes', 'demographics', 'producers', 'licensors', 'streaming']
for col in list_cols:
    analyze(df_details[col])

  Nome serie                     genres
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Stringhe vuote                 0
  Valori unici                   931  (3.22%)
  Valori duplicati               28,024

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  2  caratteri
  Lunghezza max                  90  caratteri
  Lunghezza media                16.96  caratteri
  Lunghezza mediana              13.0000  caratteri
  Dev. standard lunghezza        12.71
  IQR lunghezza                  14.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=90  ['Avant Garde', 'Award Winning', 'Drama', 'Mystery', 'Sci-Fi', 'Supernatural', 'Suspense']
    #2   len=81  ['Adventure', 'Drama', 'Horror', 'Mystery', 'Sci-Fi', 'Supernatural', 'Suspense']
    #3   len=80  ['Action', 'Adventure', 'Drama', 'Horror', 'Mystery', 'Romance', 'Supernatural']
    #4   len=80  ['Action', 'Adventure', 'Drama', 'Horror', 'Mystery', 'Romance', 'Supernatural']
    #5   len=80  ['Avant Garde', 'Award Winning', 'Drama', 'Mystery', 'Supernatural', 'Suspense']
    #6   len=80  ['Action', 'Award Winning', 'Drama', 'Mystery', 'Romance', 'Sci-Fi', 'Suspense']
    #7   len=79  ['Action', 'Adventure', 'Comedy', 'Drama', 'Mystery', 'Sci-Fi', 'Supernatural']
    #8   len=77  ['Adventure', 'Avant Garde', 'Award Winning', 'Mystery', 'Romance', 'Sci-Fi']
    #9   len=75  ['Award Winning', 'Drama', 'Mystery', 'Sci-Fi', 'Supernatural', 'Suspense']
    #10  len=74  ['Action', 'Adventure', 'Boys Love', 'Fantasy', 'Mystery', 'Supernatural']

  Le 10 stringhe più corte:
    #1   len=2  []
    #2   len=2  []
    #3   len=2  []
    #4   len=2  []
    #5   len=2  []
    #6   len=2  []
    #7   len=2  []
    #8   len=2  []
    #9   len=2  []
    #10  len=2  []

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  2 – 6                               5,983    20.7%
  6 – 10                              6,417    22.2%
  10 – 15                             3,242    11.2%
  15 – 19                             1,509     5.2%
  19 – 24                             4,249    14.7%
  24 – 28                             1,900     6.6%
  28 – 32                             1,524     5.3%
  32 – 37                             2,104     7.3%
  37 – 41                               453     1.6%
  41 – 46                               896     3.1%
  46 – 50                               271     0.9%
  50 – 54                               178     0.6%
  54 – 59                               104     0.4%
  59 – 63                                76     0.3%
  63 – 68                                20     0.1%
  68 – 72                                16     0.1%
  72 – 76                                 5     0.0%
  76 – 81                                 7     0.0%
  81 – 85                                 0     0.0%
  85 – 90                                 1     0.0%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                                                                 Conteggio        %
  ───────────────────────────────────────────────────────────────────   ──────────   ──────
  []                                                                         5,983    20.7%
  ['Comedy']                                                                 2,705     9.3%
  ['Fantasy']                                                                1,487     5.1%
  ['Hentai']                                                                 1,305     4.5%
  ['Slice of Life']                                                            854     2.9%
  ['Avant Garde']                                                              795     2.7%
  ['Drama']                                                                    778     2.7%
  ['Action']                                                                   657     2.3%
  ['Action', 'Adventure', 'Fantasy']                                           639     2.2%
  ['Adventure', 'Fantasy']                                                     596     2.1%

  I 10 meno frequenti (più rari):
  Valore                                                                 Conteggio        %
  ───────────────────────────────────────────────────────────────────   ──────────   ──────
  ['Horror', 'Erotica']                                                          1     0.0%
  ['Action', 'Comedy', 'Horror', 'Suspense']                                     1     0.0%
  ['Comedy', 'Supernatural', 'Suspense']                                         1     0.0%
  ['Action', 'Fantasy', 'Suspense']                                              1     0.0%
  ['Action', 'Comedy', 'Fantasy', 'Horror', 'Supernatural', 'Hentai']            1     0.0%
  ['Action', 'Drama', 'Mystery', 'Suspense']                                     1     0.0%
  ['Award Winning', 'Comedy', 'Girls Love']                                      1     0.0%
  ['Avant Garde', 'Drama', 'Fantasy', 'Girls Love', 'Ecchi']                     1     0.0%
  ['Action', 'Drama', 'Horror', 'Supernatural', 'Suspense']                      1     0.0%
  ['Action', 'Adventure', 'Drama', 'Horror', 'Supernatural']                     1     0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 0  (0.0%)
  Contiene maiuscole             22,972  (79.3%)
  Contiene minuscole             22,972  (79.3%)
  Contiene spazi                 13,998  (48.3%)
  Contiene caratteri speciali    28,955  (100.0%)
  Contiene URL                   0  (0.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               491,089
  Caratteri unici                39
  Caratteri medi per valore      16.96

Analisi parole / token
────────────────────────────────────────────────────────────────────────────────

  Parole medie per valore        1.86
  Max parole                     9
  Min parole                     1

  Le 10 parole più comuni:
  Parola                  Conteggio
  ────────────────────   ──────────
  []                          5,983
  ['Action',                  5,008
  'Fantasy']                  3,019
  ['Comedy',                  2,912
  ['Comedy']                  2,705
  'Sci-Fi']                   2,603
  ['Adventure',               1,993
  'Adventure',                1,814
  of                          1,596
  'Comedy',                   1,559


  Nome serie                     studios
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Stringhe vuote                 0
  Valori unici                   1,910  (6.60%)
  Valori duplicati               27,045

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  2  caratteri
  Lunghezza max                  157  caratteri
  Lunghezza media                10.84  caratteri
  Lunghezza mediana              10.0000  caratteri
  Dev. standard lunghezza        9.52
  IQR lunghezza                  16.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=157  ['Sunrise', 'Khara', 'Studio Rikka', 'Bridge', 'Kamikaze Douga', 'Trigger', 'Graphinica', 'Studio Colorido', 'dwarf', 'S…
    #2   len=152  ['ufotable', 'Shaft', 'A-1 Pictures', 'SILVER LINK.', 'Lerche', 'Wit Studio', 'Lay-duce', 'CloverWorks', 'Drive', 'Ijige…
    #3   len=147  ['Production I.G', 'David Production', 'Kinema Citrus', 'Anima', 'Kamikaze Douga', 'Trigger', 'Wit Studio', 'Polygon Pic…
    #4   len=121  ['Magic Bus', 'Studio Colorido', 'DandeLion Animation Studio', 'Studio GOONEYS', 'Pancake', 'Mimoid', 'team Yamahitsuji'…
    #5   len=114  ['Production I.G', 'Kinema Citrus', 'Kamikaze Douga', 'Trigger', 'Studio Colorido', 'Geno Studio', 'Science SARU']
    #6   len=101  ['Studio Hibari', 'Shirogumi', 'Larx Entertainment', 'TriF Studio', 'Scooter Films', 'Reirs', 'LinQ']
    #7   len=96  ['Nippon Animation', 'Gallop', 'TMS Entertainment', 'SynergySP', 'DLE', 'Bandai Namco Pictures']
    #8   len=96  ['Gonzo', 'Gainax', 'Production I.G', 'Madhouse', 'Studio 4°C', 'Satelight', 'CoMix Wave Films']
    #9   len=94  ['Zexcs', 'Studio Colorido', 'Studio Nanahoshi', 'team Yamahitsuji', 'Studio Lemon', 'Nagomi']
    #10  len=85  ['P.A. Works', 'Zexcs', 'Lapin Track', 'Studio Kafka', '100studio', 'Studio Graph77']

  Le 10 stringhe più corte:
    #1   len=2  []
    #2   len=2  []
    #3   len=2  []
    #4   len=2  []
    #5   len=2  []
    #6   len=2  []
    #7   len=2  []
    #8   len=2  []
    #9   len=2  []
    #10  len=2  []

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  2 – 9                              14,432    49.8%
  9 – 17                              7,121    24.6%
  17 – 25                             5,651    19.5%
  25 – 33                               803     2.8%
  33 – 40                               725     2.5%
  40 – 48                               141     0.5%
  48 – 56                                44     0.2%
  56 – 64                                20     0.1%
  64 – 71                                 4     0.0%
  71 – 79                                 2     0.0%
  79 – 87                                 3     0.0%
  87 – 95                                 1     0.0%
  95 – 102                                3     0.0%
  102 – 110                               0     0.0%
  110 – 118                               1     0.0%
  118 – 126                               1     0.0%
  126 – 133                               0     0.0%
  133 – 141                               0     0.0%
  141 – 149                               1     0.0%
  149 – 157                               2     0.0%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                                              Conteggio        %
  ────────────────────────────────────────────────   ──────────   ──────
  []                                                     11,703    40.4%
  ['Toei Animation']                                        882     3.0%
  ['Sunrise']                                               560     1.9%
  ['J.C.Staff']                                             411     1.4%
  ['TMS Entertainment']                                     365     1.3%
  ['Madhouse']                                              345     1.2%
  ['Shanghai Animation Film Studio']                        343     1.2%
  ['Studio Deen']                                           303     1.0%
  ['Studio Pierrot']                                        273     0.9%
  ['Production I.G']                                        272     0.9%

  I 10 meno frequenti (più rari):
  Valore                                              Conteggio        %
  ────────────────────────────────────────────────   ──────────   ──────
  ['Niceboat Animation', 'Guton Animation Studio']            1     0.0%
  ['WAO World', 'Studio Live']                                1     0.0%
  ['Flying Fish Studio', 'Bu Keneng de Shijie']               1     0.0%
  ['Niceboat Animation', 'Taiko Studios']                     1     0.0%
  ['Foch Film', 'Ai Si Animation Studio']                     1     0.0%
  ['Production GoodBook']                                     1     0.0%
  ['Studio March']                                            1     0.0%
  ['TMS Entertainment', 'Echoes']                             1     0.0%
  ['Artland', 'G&G Direction']                                1     0.0%
  ['indigo line']                                             1     0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 819  (2.8%)
  Contiene maiuscole             16,907  (58.4%)
  Contiene minuscole             15,356  (53.0%)
  Contiene spazi                 10,954  (37.8%)
  Contiene caratteri speciali    28,955  (100.0%)
  Contiene URL                   0  (0.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               314,000
  Caratteri unici                79
  Caratteri medi per valore      10.84

Analisi parole / token
────────────────────────────────────────────────────────────────────────────────

  Parole medie per valore        1.53
  Max parole                     18
  Min parole                     1

  Le 10 parole più comuni:
  Parola                  Conteggio
  ────────────────────   ──────────
  []                         11,703
  Animation']                 1,778
  ['Studio                    1,700
  Studio']                      959
  ['Toei                        914
  Animation                     722
  Entertainment']               579
  ['Sunrise']                   560
  Pictures']                    489
  Production']                  429


  Nome serie                     themes
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Stringhe vuote                 0
  Valori unici                   1,044  (3.61%)
  Valori duplicati               27,911

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  2  caratteri
  Lunghezza max                  87  caratteri
  Lunghezza media                11.14  caratteri
  Lunghezza mediana              9.0000  caratteri
  Dev. standard lunghezza        10.78
  IQR lunghezza                  14.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=87  ['Adult Cast', 'High Stakes Game', 'Organized Crime', 'Psychological', 'Strategy Game']
    #2   len=80  ['Adult Cast', 'Gore', 'Historical', 'Martial Arts', 'Psychological', 'Samurai']
    #3   len=73  ['Love Polygon', 'School', 'Time Travel', 'Urban Fantasy', 'Visual Arts']
    #4   len=73  ['Adult Cast', 'Gore', 'Organized Crime', 'Psychological', 'Super Power']
    #5   len=72  ['Adult Cast', 'Detective', 'Organized Crime', 'Super Power', 'Vampire']
    #6   len=70  ['Anthropomorphic', 'Love Polygon', 'Mahou Shoujo', 'Performing Arts']
    #7   len=70  ['Anthropomorphic', 'Love Polygon', 'Mahou Shoujo', 'Performing Arts']
    #8   len=69  ['Adult Cast', 'Gore', 'Historical', 'Isekai', 'Military', 'Samurai']
    #9   len=69  ['Adult Cast', 'Gore', 'Historical', 'Isekai', 'Military', 'Samurai']
    #10  len=69  ['Adult Cast', 'Gore', 'Historical', 'Isekai', 'Military', 'Samurai']

  Le 10 stringhe più corte:
    #1   len=2  []
    #2   len=2  []
    #3   len=2  []
    #4   len=2  []
    #5   len=2  []
    #6   len=2  []
    #7   len=2  []
    #8   len=2  []
    #9   len=2  []
    #10  len=2  []

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  2 – 6                              11,818    40.8%
  6 – 10                              6,748    23.3%
  10 – 14                             2,017     7.0%
  14 – 19                             2,098     7.2%
  19 – 23                             2,096     7.2%
  23 – 27                             1,675     5.8%
  27 – 31                               956     3.3%
  31 – 36                               467     1.6%
  36 – 40                               461     1.6%
  40 – 44                               257     0.9%
  44 – 48                               146     0.5%
  48 – 53                                75     0.3%
  53 – 57                                81     0.3%
  57 – 61                                23     0.1%
  61 – 65                                18     0.1%
  65 – 70                                12     0.0%
  70 – 74                                 5     0.0%
  74 – 78                                 0     0.0%
  78 – 82                                 1     0.0%
  82 – 87                                 1     0.0%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                                                     Conteggio        %
  ───────────────────────────────────────────────────────   ──────────   ──────
  []                                                            11,818    40.8%
  ['Music']                                                      4,015    13.9%
  ['Anthropomorphic']                                              923     3.2%
  ['School']                                                       912     3.1%
  ['Historical']                                                   858     3.0%
  ['Mecha']                                                        615     2.1%
  ['Parody']                                                       321     1.1%
  ['Mythology']                                                    276     1.0%
  ['Super Power']                                                  272     0.9%
  ['Martial Arts']                                                 258     0.9%

  I 10 meno frequenti (più rari):
  Valore                                                     Conteggio        %
  ───────────────────────────────────────────────────────   ──────────   ──────
  ['Adult Cast', 'Gore', 'Survival']                                 1     0.0%
  ['Adult Cast', 'Survival']                                         1     0.0%
  ['Adult Cast', 'Historical', 'Military', 'Time Travel']            1     0.0%
  ['Racing', 'Space', 'Super Power']                                 1     0.0%
  ['Harem', 'Mahou Shoujo']                                          1     0.0%
  ['Psychological', 'Urban Fantasy']                                 1     0.0%
  ['Martial Arts', 'Mecha', 'School', 'Super Power']                 1     0.0%

**Osservazioni:**
- **Nessun valore nullo** in nessuna delle 7 colonne.
- **Liste vuote `[]` legittime**: anime senza studio, senza genere, senza streaming, ecc.
- **Formato stringa mantenuto**: sufficiente per le analisi testuali; deserializzabile con `ast.literal_eval` quando necessario.

Nessuna pulizia necessaria.

In [33]:
# Nessuna operazione richiesta
list_cols = ['genres', 'studios', 'themes', 'demographics', 'producers', 'licensors', 'streaming']
for col in list_cols:
    print(f'Null in {col:<14}: {df_details[col].isna().sum()}')

Null in genres        : 0
Null in studios       : 0
Null in themes        : 0
Null in demographics  : 0
Null in producers     : 0
Null in licensors     : 0
Null in streaming     : 0

### 2.15 `source`

Colonna categorica con il materiale di origine dell'anime (Manga, Novel, Original, …). I valori sono coerenti con la tassonomia MAL; non ci aspettiamo null.

In [34]:
analyze(df_details['source'])

  Nome serie                     source
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Stringhe vuote                 0
  Valori unici                   17  (0.06%)
  Valori duplicati               28,938

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  4  caratteri
  Lunghezza max                  12  caratteri
  Lunghezza media                7.28  caratteri
  Lunghezza mediana              8.0000  caratteri
  Dev. standard lunghezza        2.11
  IQR lunghezza                  3.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=12  Picture book
    #2   len=12  Picture book
    #3   len=12  Picture book
    #4   len=12  Picture book
    #5   len=12  Visual novel
    #6   len=12  Visual novel
    #7   len=12  Visual novel
    #8   len=12  4-koma manga
    #9   len=12  Visual novel
    #10  len=12  Visual novel

  Le 10 stringhe più corte:
    #1   len=4  Game
    #2   len=4  Game
    #3   len=4  Game
    #4   len=4  Game
    #5   len=4  Game
    #6   len=4  Book
    #7   len=4  Game
    #8   len=4  Book
    #9   len=4  Book
    #10  len=4  Book

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  4 – 4                               1,697     5.9%
  4 – 5                               7,931    27.4%
  5 – 6                                   0     0.0%
  6 – 7                               2,794     9.6%
  7 – 8                              12,359    42.7%
  8 – 9                                 955     3.3%
  9 – 10                                  0     0.0%
  10 – 11                             1,436     5.0%
  11 – 12                             1,783     6.2%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore          Conteggio        %
  ────────────   ──────────   ──────
  Original           12,359    42.7%
  Manga               5,508    19.0%
  Unknown             2,794     9.6%
  Game                1,473     5.1%
  Other               1,326     4.6%
  Light novel         1,199     4.1%
  Visual novel        1,160     4.0%
  Novel                 820     2.8%
  Web manga             654     2.3%
  4-koma manga          339     1.2%

  I 10 meno frequenti (più rari):
  Valore          Conteggio        %
  ────────────   ──────────   ──────
  Radio                  14     0.0%
  Card game              79     0.3%
  Web novel             222     0.8%
  Book                  224     0.8%
  Mixed media           237     0.8%
  Music                 263     0.9%
  Picture book          284     1.0%
  4-koma manga          339     1.2%
  Web manga             654     2.3%
  Novel                 820     2.8%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 339  (1.2%)
  Contiene maiuscole             28,616  (98.8%)
  Contiene minuscole             28,955  (100.0%)
  Contiene spazi                 4,174  (14.4%)
  Contiene caratteri speciali    339  (1.2%)
  Contiene URL                   0  (0.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                24,781
  Solo alfanumerico              24,781

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               210,660
  Caratteri unici                35
  Caratteri medi per valore      7.28

**Osservazioni:**
- **Nessun valore nullo**: tutti i 28.955 record hanno un valore di source.
- **17 valori distinti**: tutti coerenti con la tassonomia MAL, incluso `Unknown` (2.794 casi) che è un valore esplicito per anime con origine non documentata.

Nessuna pulizia necessaria.

In [35]:
# Nessuna operazione richiesta
print(f'Null in source : {df_details["source"].isna().sum()}')
print(df_details['source'].value_counts())

Null in source : 0
source
Original        12359
Manga            5508
Unknown          2794
Game             1473
Other            1326
Light novel      1199
Visual novel     1160
Novel             820
Web manga         654
4-koma manga      339
Picture book      284
Music             263
Mixed media       237
Book              224
Web novel         222
Card game          79
Radio              14
Name: count, dtype: int64

### 2.16 `rating`

Classificazione per età secondo la tassonomia MAL (G, PG, PG-13, R-17+, R+, Rx). I null sono strutturali: alcuni anime non hanno ancora una classificazione registrata.

In [36]:
analyze(df_details['rating'])

  Nome serie                     rating
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,355  (97.93%)
  Null / NaN                     600  (2.07%)
  Stringhe vuote                 0
  Valori unici                   6  (0.02%)
  Valori duplicati               28,349

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  11  caratteri
  Lunghezza max                  30  caratteri
  Lunghezza media                18.08  caratteri
  Lunghezza mediana              13.0000  caratteri
  Dev. standard lunghezza        6.67
  IQR lunghezza                  13.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=30  R - 17+ (violence & profanity)
    #2   len=30  R - 17+ (violence & profanity)
    #3   len=30  R - 17+ (violence & profanity)
    #4   len=30  R - 17+ (violence & profanity)
    #5   len=30  R - 17+ (violence & profanity)
    #6   len=30  R - 17+ (violence & profanity)
    #7   len=30  R - 17+ (violence & profanity)
    #8   len=30  R - 17+ (violence & profanity)
    #9   len=30  R - 17+ (violence & profanity)
    #10  len=30  R - 17+ (violence & profanity)

  Le 10 stringhe più corte:
    #1   len=11  Rx - Hentai
    #2   len=11  Rx - Hentai
    #3   len=11  Rx - Hentai
    #4   len=11  Rx - Hentai
    #5   len=11  Rx - Hentai
    #6   len=11  Rx - Hentai
    #7   len=11  Rx - Hentai
    #8   len=11  Rx - Hentai
    #9   len=11  Rx - Hentai
    #10  len=11  Rx - Hentai

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  11 – 11                             1,583     5.6%
  11 – 12                             9,066    32.0%
  12 – 13                             4,421    15.6%
  13 – 14                                 0     0.0%
  14 – 15                                 0     0.0%
  15 – 16                             1,229     4.3%
  16 – 17                                 0     0.0%
  17 – 18                                 0     0.0%
  18 – 19                                 0     0.0%
  19 – 20                                 0     0.0%
  20 – 21                                 0     0.0%
  21 – 22                                 0     0.0%
  22 – 23                                 0     0.0%
  23 – 24                                 0     0.0%
  24 – 25                            10,463    36.9%
  25 – 26                                 0     0.0%
  26 – 27                                 0     0.0%
  27 – 28                                 0     0.0%
  28 – 29                                 0     0.0%
  29 – 30                             1,593     5.6%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                            Conteggio        %
  ──────────────────────────────   ──────────   ──────
  PG-13 - Teens 13 or older            10,463    36.9%
  G - All Ages                          9,066    32.0%
  PG - Children                         4,421    15.6%
  R - 17+ (violence & profanity)        1,593     5.6%
  Rx - Hentai                           1,583     5.6%
  R+ - Mild Nudity                      1,229     4.3%

  I 10 meno frequenti (più rari):
  Valore                            Conteggio        %
  ──────────────────────────────   ──────────   ──────
  R+ - Mild Nudity                      1,229     4.3%
  Rx - Hentai                           1,583     5.6%
  R - 17+ (violence & profanity)        1,593     5.6%
  PG - Children                         4,421    15.6%
  G - All Ages                          9,066    32.0%
  PG-13 - Teens 13 or older            10,463    36.9%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 12,056  (42.5%)
  Contiene maiuscole             28,355  (100.0%)
  Contiene minuscole             28,355  (100.0%)
  Contiene spazi                 28,355  (100.0%)
  Contiene caratteri speciali    28,355  (100.0%)
  Contiene URL                   0  (0.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               512,707
  Caratteri unici                37
  Caratteri medi per valore      18.08

Analisi parole / token
────────────────────────────────────────────────────────────────────────────────

  Parole medie per valore        4.64
  Max parole                     6
  Min parole                     3

  Le 10 parole più comuni:
  Parola                  Conteggio
  ────────────────────   ──────────
  -                          28,355
  PG-13                      10,463
  Teens                      10,463
  13                         10,463
  or                         10,463
  older                      10,463
  G                           9,066
  All                         9,066
  Ages                        9,066
  PG                          4,421

**Osservazioni:**
- **600 valori nulli** (~2.1%): strutturali, anime senza classificazione per età registrata su MAL.
- **6 valori distinti**: G, PG, PG-13, R-17+, R+, Rx, tutti coerenti con la classificazione MAL.

Nessuna pulizia necessaria.

In [37]:
# Nessuna operazione richiesta: i null sono strutturali
print(f'Null in rating : {df_details["rating"].isna().sum()}')
print(df_details['rating'].value_counts())

Null in rating : 600
rating
PG-13 - Teens 13 or older         10463
G - All Ages                       9066
PG - Children                      4421
R - 17+ (violence & profanity)     1593
Rx - Hentai                        1583
R+ - Mild Nudity                   1229
Name: count, dtype: int64

### 2.17 `episodes`

Numero di episodi dell'anime. I null sono strutturali: anime in corso o non ancora in onda possono non avere ancora un numero definitivo. Il dtype `float64` va convertito a `Int64` (nullable integer).

In [38]:
analyze(df_details['episodes'])

  Nome serie                     episodes
  dtype                          float64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,275  (97.65%)
  Null / NaN                     680  (2.35%)
  Zeri                           0  (0.00%)
  Positivi                       28,275   (97.65%)
  Negativi                       0   (0.00%)
  Valori unici                   261  (0.90%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            1.0000
  Max                            3,000.00
  Range                          2,999.00
  Media                          14.1301
  Mediana                        2.0000
  Moda/e                         1.0000
  Dev. standard                  47.1614
  Varianza                       2,224.20
  Errore std (SEM)               0.2805
  IQR  (Q3 − Q1)                 12.0000
  Q1  (25° pct)                  1.0000
  Q3  (75° pct)                  13.0000
  P5  ( 5° pct)                  1.0000
  P95 (95° pct)                  52.0000
  Coefficiente di variazione     333.77%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -17.0000
  Soglia alta   (Q3 + 1.5×IQR)   31.0000
  Outlier rilevati               3,035  (10.48%)

  Top 5 outlier estremi (per valore assoluto):
    [13697]  3,000.00
    [18525]  1,818.00
    [5259]  1,787.00
    [7808]  1,717.00
    [4660]  1,664.00

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  1 – 150                            28,035    99.2%
  150 – 300                             155     0.5%
  300 – 450                              50     0.2%
  450 – 600                              15     0.1%
  600 – 750                               6     0.0%
  750 – 900                               2     0.0%
  900 – 1,050                             2     0.0%
  1,050 – 1,200                           0     0.0%
  1,200 – 1,350                           2     0.0%
  1,350 – 1,500                           2     0.0%
  1,500 – 1,650                           1     0.0%
  1,650 – 1,800                           3     0.0%
  1,800 – 1,950                           1     0.0%
  1,950 – 2,100                           0     0.0%
  2,100 – 2,250                           0     0.0%
  2,250 – 2,400                           0     0.0%
  2,400 – 2,550                           0     0.0%
  2,550 – 2,700                           0     0.0%
  2,700 – 2,850                           0     0.0%
  2,850 – 3,000                           1     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   3,000.00  [indice 13697]
    #2   1,818.00  [indice 18525]
    #3   1,787.00  [indice 5259]
    #4   1,717.00  [indice 7808]
    #5   1,664.00  [indice 4660]
    #6   1,565.00  [indice 12550]
    #7   1,471.00  [indice 14913]
    #8   1,428.00  [indice 9245]
    #9   1,306.00  [indice 12547]
    #10  1,274.00  [indice 16157]

  I 10 più piccoli:
    #1   1.0000  [indice 0]
    #2   1.0000  [indice 1]
    #3   1.0000  [indice 2]
    #4   1.0000  [indice 3]
    #5   1.0000  [indice 4]
    #6   1.0000  [indice 5]
    #7   1.0000  [indice 6]
    #8   1.0000  [indice 13]
    #9   1.0000  [indice 14]
    #10  1.0000  [indice 15]

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                1.0000       13,871    47.9%
               12.0000        2,335     8.1%
                2.0000        1,651     5.7%
               26.0000        1,344     4.6%
               13.0000        1,145     4.0%
               52.0000          850     2.9%
                3.0000          759     2.6%
                4.0000          628     2.2%
                6.0000          471     1.6%
               24.0000          392     1.4%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
              196.0000            1     0.0%
              215.0000            1     0.0%
              214.0000            1     0.0%
              138.0000            1     0.0%
              418.0000            1     0.0%
              620.0000            1     0.0%
              126.0000            1     0.0%
              530.0000            1     0.0%
              720.0000            1     0.0%
              520.0000            1     0.0%

**Osservazioni:**
- **680 valori nulli** (~2.3%): strutturali, anime in corso o non ancora in onda senza numero definitivo di episodi.
- **Conversione dtype**: da `float64` a `Int64` (nullable integer), dato che i valori sono interi.

In [39]:
df_details['episodes'] = df_details['episodes'].astype('Int64')
print(f'episodes dtype   : {df_details["episodes"].dtype}')
print(f'Null residui     : {df_details["episodes"].isna().sum()}')
print(f'Range            : {df_details["episodes"].min()} – {df_details["episodes"].max()}')

episodes dtype   : Int64
Null residui     : 680
Range            : 1 – 3000

### 2.18 `season`

Stagione di uscita dell'anime (spring, summer, fall, winter). I null sono strutturali: Movies, OVA, ONA, Music, CM e PV non appartengono a una stagione MAL.

In [40]:
analyze(df_details['season'])

  Nome serie                     season
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               6,266  (21.64%)
  Null / NaN                     22,689  (78.36%)
  Stringhe vuote                 0
  Valori unici                   4  (0.01%)
  Valori duplicati               6,262

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  4  caratteri
  Lunghezza max                  6  caratteri
  Lunghezza media                5.42  caratteri
  Lunghezza mediana              6.0000  caratteri
  Dev. standard lunghezza        0.91
  IQR lunghezza                  2.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=6  spring
    #2   len=6  spring
    #3   len=6  winter
    #4   len=6  summer
    #5   len=6  winter
    #6   len=6  winter
    #7   len=6  spring
    #8   len=6  spring
    #9   len=6  summer
    #10  len=6  spring

  Le 10 stringhe più corte:
    #1   len=4  fall
    #2   len=4  fall
    #3   len=4  fall
    #4   len=4  fall
    #5   len=4  fall
    #6   len=4  fall
    #7   len=4  fall
    #8   len=4  fall
    #9   len=4  fall
    #10  len=4  fall

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  4 – 4                               1,825    29.1%
  4 – 5                                   0     0.0%
  5 – 6                               4,441    70.9%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore    Conteggio        %
  ──────   ──────────   ──────
  spring        1,972    31.5%
  fall          1,825    29.1%
  winter        1,302    20.8%
  summer        1,167    18.6%

  I 10 meno frequenti (più rari):
  Valore    Conteggio        %
  ──────   ──────────   ──────
  summer        1,167    18.6%
  winter        1,302    20.8%
  fall          1,825    29.1%
  spring        1,972    31.5%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 0  (0.0%)
  Contiene maiuscole             0  (0.0%)
  Contiene minuscole             6,266  (100.0%)
  Contiene spazi                 0  (0.0%)
  Contiene caratteri speciali    0  (0.0%)
  Contiene URL                   0  (0.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                6,266
  Solo alfanumerico              6,266

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               33,946
  Caratteri unici                14
  Caratteri medi per valore      5.42

**Osservazioni:**
- **22.689 valori nulli** (~78.4%): strutturali, Movies, OVA, ONA, Music, CM e PV non appartengono a una stagione MAL.
- **4 valori distinti**: `spring`, `summer`, `fall`, `winter`, tutti coerenti.

Nessuna pulizia necessaria.

In [41]:
# Nessuna operazione richiesta: i null sono strutturali
print(f'Null in season : {df_details["season"].isna().sum():,} ({df_details["season"].isna().mean()*100:.1f}%)')
print(df_details['season'].value_counts())

Null in season : 22,689 (78.4%)
season
spring    1972
fall      1825
winter    1302
summer    1167
Name: count, dtype: int64

### 2.19 `year`

Anno di uscita dell'anime. I null corrispondono esattamente a quelli di `season` (stessa logica strutturale). Il dtype `float64` va convertito a `Int64` (nullable integer).

In [42]:
analyze(df_details['year'])

  Nome serie                     year
  dtype                          float64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               6,266  (21.64%)
  Null / NaN                     22,689  (78.36%)
  Zeri                           0  (0.00%)
  Positivi                       6,266   (21.64%)
  Negativi                       0   (0.00%)
  Valori unici                   66  (0.23%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            1,961.00
  Max                            2,026.00
  Range                          65.0000
  Media                          2,010.03
  Mediana                        2,014.00
  Moda/e                         2,023.00
  Dev. standard                  13.2007
  Varianza                       174.2587
  Errore std (SEM)               0.1668
  IQR  (Q3 − Q1)                 15.0000
  Q1  (25° pct)                  2,005.00
  Q3  (75° pct)                  2,020.00
  P5  ( 5° pct)                  1,980.00
  P95 (95° pct)                  2,025.00
  Coefficiente di variazione     0.66%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   1,982.50
  Soglia alta   (Q3 + 1.5×IQR)   2,042.50
  Outlier rilevati               374  (1.29%)

  Top 5 outlier estremi (per valore assoluto):
    [460]  1,982.00
    [1026]  1,982.00
    [1415]  1,982.00
    [4393]  1,982.00
    [6566]  1,982.00

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  1,961 – 1,964                          11     0.2%
  1,964 – 1,967                          38     0.6%
  1,967 – 1,970                          47     0.8%
  1,970 – 1,974                          49     0.8%
  1,974 – 1,977                          95     1.5%
  1,977 – 1,980                          75     1.2%
  1,980 – 1,983                          96     1.5%
  1,983 – 1,987                          84     1.3%
  1,987 – 1,990                         135     2.2%
  1,990 – 1,993                         106     1.7%
  1,993 – 1,996                         118     1.9%
  1,996 – 2,000                         219     3.5%
  2,000 – 2,003                         359     5.7%
  2,003 – 2,006                         446     7.1%
  2,006 – 2,009                         486     7.8%
  2,009 – 2,013                         516     8.2%
  2,013 – 2,016                         992    15.8%
  2,016 – 2,019                         791    12.6%
  2,019 – 2,022                         701    11.2%
  2,022 – 2,026                         902    14.4%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   2,026.00  [indice 134]
    #2   2,026.00  [indice 733]
    #3   2,026.00  [indice 1152]
    #4   2,026.00  [indice 1355]
    #5   2,026.00  [indice 3361]
    #6   2,026.00  [indice 4687]
    #7   2,026.00  [indice 4700]
    #8   2,026.00  [indice 4762]
    #9   2,026.00  [indice 5459]
    #10  2,026.00  [indice 5929]

  I 10 più piccoli:
    #1   1,961.00  [indice 10205]
    #2   1,962.00  [indice 18377]
    #3   1,963.00  [indice 5835]
    #4   1,963.00  [indice 18135]
    #5   1,963.00  [indice 21308]
    #6   1,963.00  [indice 24408]
    #7   1,963.00  [indice 24416]
    #8   1,964.00  [indice 21]
    #9   1,964.00  [indice 2324]
    #10  1,964.00  [indice 22234]

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
              2,023.00          284     1.0%
              2,025.00          283     1.0%
              2,016.00          283     1.0%
              2,024.00          282     1.0%
              2,017.00          281     1.0%
              2,018.00          281     1.0%
              2,021.00          245     0.8%
              2,015.00          245     0.8%
              2,014.00          241     0.8%
              2,022.00          236     0.8%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
              1,962.00            1     0.0%
              1,961.00            1     0.0%
              1,964.00            4     0.0%
              1,963.00            5     0.0%
              1,966.00           11     0.0%
              1,965.00           12     0.0%
              1,968.00           14     0.0%
              1,967.00           15     0.1%
              1,972.00           15     0.1%
              1,969.00           16     0.1%

**Osservazioni:**
- **22.689 valori nulli**: identici a quelli di `season` (stessa logica strutturale).
- **Conversione dtype**: da `float64` a `Int64` (nullable integer).

In [43]:
df_details['year'] = df_details['year'].astype('Int64')
print(f'year dtype   : {df_details["year"].dtype}')
print(f'Null residui : {df_details["year"].isna().sum():,}')
print(f'Range        : {df_details["year"].min()} – {df_details["year"].max()}')

year dtype   : Int64
Null residui : 22,689
Range        : 1961 – 2026

### 2.20 `explicit_genres`

Colonna destinata ai generi espliciti (es. Hentai). Verifichiamo se contiene informazione utile o se è interamente vuota.

In [44]:
analyze(df_details['explicit_genres'])

  Nome serie                     explicit_genres
  dtype                          str
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Stringhe vuote                 0
  Valori unici                   1  (0.00%)
  Valori duplicati               28,954

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  2  caratteri
  Lunghezza max                  2  caratteri
  Lunghezza media                2.00  caratteri
  Lunghezza mediana              2.0000  caratteri
  Dev. standard lunghezza        0.00
  IQR lunghezza                  0.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #1   len=2  []
    #2   len=2  []
    #3   len=2  []
    #4   len=2  []
    #5   len=2  []
    #6   len=2  []
    #7   len=2  []
    #8   len=2  []
    #9   len=2  []
    #10  len=2  []

  Le 10 stringhe più corte:
    #1   len=2  []
    #2   len=2  []
    #3   len=2  []
    #4   len=2  []
    #5   len=2  []
    #6   len=2  []
    #7   len=2  []
    #8   len=2  []
    #9   len=2  []
    #10  len=2  []

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Tutte le stringhe hanno la stessa lunghezza. (2 caratteri)

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore    Conteggio        %
  ──────   ──────────   ──────
  []           28,955   100.0%

  I 10 meno frequenti (più rari):
  Valore    Conteggio        %
  ──────   ──────────   ──────
  []           28,955   100.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 0  (0.0%)
  Contiene maiuscole             0  (0.0%)
  Contiene minuscole             0  (0.0%)
  Contiene spazi                 0  (0.0%)
  Contiene caratteri speciali    28,955  (100.0%)
  Contiene URL                   0  (0.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

Statistiche a livello di carattere
────────────────────────────────────────────────────────────────────────────────

  Caratteri totali               57,910
  Caratteri unici                2
  Caratteri medi per valore      2.00

**Osservazioni:**
- La colonna contiene esclusivamente il valore `[]` (lista vuota) per tutte le 28.955 righe: **nessuna informazione utile**.
- **Rimozione della colonna**.

In [45]:
print(f'Valori unici in explicit_genres: {df_details["explicit_genres"].unique()}')
df_details.drop(columns=['explicit_genres'], inplace=True)
print('Colonna explicit_genres rimossa.')

Valori unici in explicit_genres: <StringArray>
['[]']
Length: 1, dtype: str
Colonna explicit_genres rimossa.

### 2.21 Chiave primaria `mal_id`

Verifichiamo che `mal_id` sia ancora univoco dopo tutte le operazioni di pulizia.

In [46]:
n_pk_dup = df_details.duplicated(subset=['mal_id'], keep=False).sum()
print(f'Duplicati su mal_id: {n_pk_dup}')

if n_pk_dup > 0:
    print('→ Rimozione duplicati sulla chiave primaria...')
    df_details.drop_duplicates(subset=['mal_id'], keep='first', inplace=True)
    print(f'Righe dopo la rimozione: {len(df_details):,}')
else:
    print('→ Chiave primaria già univoca, nessuna operazione richiesta.')

Duplicati su mal_id: 0
→ Chiave primaria già univoca, nessuna operazione richiesta.

## 3. Riepilogo e Salvataggio

Le operazioni di pulizia sono state effettuate colonna per colonna nella sezione 2. In questa sezione riepiloghiamo il risultato ed effettuiamo il salvataggio del dataset finale.

In [47]:
print('=== Riepilogo Dataset Pulito ===')
print(f'Righe originali      : {n_originale:>10,}')
print(f'Righe dopo cleaning  : {len(df_details):>10,}')
print(f'Righe rimosse totali : {n_originale - len(df_details):>10,}')
print()
print('Dtypes finali:')
print(df_details.dtypes)
print()
print('Valori mancanti residui:')
print(df_details.isnull().sum())

=== Riepilogo Dataset Pulito ===
Righe originali      :     28,955
Righe dopo cleaning  :     28,955
Righe rimosse totali :          0

Dtypes finali:
mal_id                          int64
title                             str
title_japanese                    str
url                               str
image_url                         str
type                              str
status                            str
score                         float64
scored_by                       Int64
start_date        datetime64[us, UTC]
end_date          datetime64[us, UTC]
synopsis                          str
rank                            Int64
popularity                      int64
members                         int64
favorites                       int64
genres                            str
studios                           str
themes                            str
demographics                      str
source                            str
rating                            str
episodes                        Int64
season                            str
year                            Int64
producers                         str
licensors                         str
streaming                         str
has_image                        bool
has_synopsis                     bool
dtype: object

Valori mancanti residui:
mal_id                0
title                 0
title_japanese      119
url                   0
image_url             0
type                 67
status                0
score             10073
scored_by         10073
start_date          851
end_date          17688
synopsis           5127
rank               6958
popularity            0
members               0
favorites             0
genres                0
studios               0
themes                0
demographics          0
source                0
rating              600
episodes            680
season            22689
year              22689
producers             0
licensors             0
streaming             0
has_image             0
has_synopsis          0
dtype: int64

In [48]:
df_details.head()

,mal_id,title,title_japanese,url,image_url,type,status,score,scored_by,start_date,...,source,rating,episodes,season,year,producers,licensors,streaming,has_image,has_synopsis
0,59356,-Socket-,-socket-,https://myanimelist.net/anime/59356/-Socket-,https://cdn.myanimelist.net/images/anime/1043/...,Movie,Finished Airing,NaN,<NA>,2010-01-01 00:00:00+00:00,...,Original,G - All Ages,1,NaN,<NA>,['Nagoya Zokei University'],[],[],True,True
1,56036,......,......,https://myanimelist.net/anime/56036/-,https://cdn.myanimelist.net/images/anime/1057/...,Music,Finished Airing,6.53,503,2023-06-11 00:00:00+00:00,...,Original,PG-13 - Teens 13 or older,1,NaN,<NA>,[],[],[],True,True
2,2928,.hack//G.U. Returner,.HACK//G.U. RETURNER,https://myanimelist.net/anime/2928/hack__GU_Re...,https://cdn.myanimelist.net/images/anime/1798/...,OVA,Finished Airing,6.65,9745,2007-01-18 00:00:00+00:00,...,Game,PG-13 - Teens 13 or older,1,NaN,<NA>,"['Bandai Visual', 'CyberConnect2']",[],[],True,True
3,3269,.hack//G.U. Trilogy,.hack//G.U. Trilogy,https://myanimelist.net/anime/3269/hack__GU_Tr...,https://cdn.myanimelist.net/images/anime/1566/...,Movie,Finished Airing,7.06,15373,2007-12-22 00:00:00+00:00,...,Game,PG-13 - Teens 13 or older,1,NaN,<NA>,['Bandai Visual'],"['Funimation', 'Bandai Entertainment']",[],True,True
4,4469,.hack//G.U. Trilogy: Parody Mode,.hack//G.U. Trilogy,https://myanimelist.net/anime/4469/hack__GU_Tr...,https://cdn.myanimelist.net/images/anime/10/86...,Special,Finished Airing,6.35,4317,2008-03-25 00:00:00+00:00,...,Game,PG-13 - Teens 13 or older,1,NaN,<NA>,['Bandai Visual'],[],[],True,True

In [49]:
df_details.to_csv('../datasets_cleaned/details_clean.csv', index=False)
print('Salvato: datasets_cleaned/details_clean.csv')

Salvato: datasets_cleaned/details_clean.csv