# 04 – Details

Esplorazione e data cleaning del dataset `details.csv`.

**Colonne:**
| Colonna | Descrizione |
|---|---|
| `mal_id` | ID univoco dell'anime su MyAnimeList |
| `title` | Titolo dell'anime (romaji/inglese) |
| `title_japanese` | Titolo in giapponese |
| `url` | URL della pagina MAL dell'anime |
| `image_url` | URL dell'immagine di copertina |
| `type` | Tipo (TV, Movie, OVA, ONA, Special, Music, CM, PV, TV Special) |
| `status` | Stato di trasmissione |
| `score` | Punteggio medio (1–10, float) |
| `scored_by` | Numero di utenti che hanno votato |
| `start_date` | Data di inizio trasmissione (ISO 8601) |
| `end_date` | Data di fine trasmissione (ISO 8601) |
| `synopsis` | Sinossi testuale |
| `rank` | Classifica globale MAL |
| `popularity` | Posizione nella classifica di popolarità |
| `members` | Numero di utenti che hanno l'anime nella loro lista |
| `favorites` | Numero di utenti che hanno messo l'anime tra i preferiti |
| `genres` | Lista di generi (stringa con lista Python) |
| `studios` | Lista di studi di produzione |
| `themes` | Lista di temi narrativi |
| `demographics` | Lista di target demografici |
| `source` | Materiale di origine (Manga, Novel, Original, …) |
| `rating` | Classificazione per età |
| `episodes` | Numero di episodi |
| `season` | Stagione di uscita (spring/summer/fall/winter) |
| `year` | Anno di uscita |
| `producers` | Lista di produttori |
| `explicit_genres` | Lista di generi espliciti |
| `licensors` | Lista di licenziatari |
| `streaming` | Lista di piattaforme di streaming |

## 1. Import e caricamento dati

In [1]:
import pandas as pd
import numpy as np
from dataset_analyzer import analyze

In [2]:
df_details = pd.read_csv('../datasets/details.csv')
print(f'Shape: {df_details.shape}')
df_details.info()
df_details.head()

Shape: (28955, 29)
<class 'pandas.DataFrame'>
RangeIndex: 28955 entries, 0 to 28954
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   mal_id           28955 non-null  int64
 1   title            28955 non-null  str
 2   title_japanese   28836 non-null  str
 3   url              28955 non-null  str
 4   image_url        28955 non-null  str
 5   type             28888 non-null  str
 6   status           28955 non-null  str
 7   score            18882 non-null  float64
 8   scored_by        18882 non-null  float64
 9   start_date       28104 non-null  str
 10  end_date         11267 non-null  str
 11  synopsis         23828 non-null  str
 12  rank             21997 non-null  float64
 13  popularity       28955 non-null  int64
 14  members          28955 non-null  int64
 15  favorites        28955 non-null  int64
 16  genres           28955 non-null  str
 17  studios          28955 non-null  str
 18  themes           28955 non-null  str
 19  demographics     28955 non-null  str
 20  source           28955 non-null  str
 21  rating           28355 non-null  str
 22  episodes         28275 non-null  float64
 23  season           6266 non-null   str
 24  year             6266 non-null   float64
 25  producers        28955 non-null  str
 26  explicit_genres  28955 non-null  str
 27  licensors        28955 non-null  str
 28  streaming        28955 non-null  str
dtypes: float64(5), int64(4), str(20)
memory usage: 6.4 MB

,mal_id,title,title_japanese,url,image_url,type,status,score,scored_by,start_date,...,demographics,source,rating,episodes,season,year,producers,explicit_genres,licensors,streaming
0,59356,-Socket-,-socket-,https://myanimelist.net/anime/59356/-Socket-,https://cdn.myanimelist.net/images/anime/1043/...,Movie,Finished Airing,NaN,NaN,2010-01-01T00:00:00+00:00,...,[],Original,G - All Ages,1.0,NaN,NaN,['Nagoya Zokei University'],[],[],[]
1,56036,......,......,https://myanimelist.net/anime/56036/-,https://cdn.myanimelist.net/images/anime/1057/...,Music,Finished Airing,6.53,503.0,2023-06-11T00:00:00+00:00,...,[],Original,PG-13 - Teens 13 or older,1.0,NaN,NaN,[],[],[],[]
2,2928,.hack//G.U. Returner,.HACK//G.U. RETURNER,https://myanimelist.net/anime/2928/hack__GU_Re...,https://cdn.myanimelist.net/images/anime/1798/...,OVA,Finished Airing,6.65,9745.0,2007-01-18T00:00:00+00:00,...,[],Game,PG-13 - Teens 13 or older,1.0,NaN,NaN,"['Bandai Visual', 'CyberConnect2']",[],[],[]
3,3269,.hack//G.U. Trilogy,.hack//G.U. Trilogy,https://myanimelist.net/anime/3269/hack__GU_Tr...,https://cdn.myanimelist.net/images/anime/1566/...,Movie,Finished Airing,7.06,15373.0,2007-12-22T00:00:00+00:00,...,[],Game,PG-13 - Teens 13 or older,1.0,NaN,NaN,['Bandai Visual'],[],"['Funimation', 'Bandai Entertainment']",[]
4,4469,.hack//G.U. Trilogy: Parody Mode,.hack//G.U. Trilogy,https://myanimelist.net/anime/4469/hack__GU_Tr...,https://cdn.myanimelist.net/images/anime/10/86...,Special,Finished Airing,6.35,4317.0,2008-03-25T00:00:00+00:00,...,[],Game,PG-13 - Teens 13 or older,1.0,NaN,NaN,['Bandai Visual'],[],[],[]

In [3]:
n_originale = len(df_details)

## 1.1 Rimozione duplicati esatti

Prima dell'analisi per colonna, rimuoviamo le righe con valori identici in **tutte** le colonne, mantenendo solo la prima occorrenza.

In [4]:
mask_dup = df_details.duplicated(keep=False)       # tutte le occorrenze coinvolte
n_righe_coinvolte = mask_dup.sum()                  # righe totali che hanno almeno un duplicato
n_gruppi = df_details[mask_dup].duplicated(keep='first').sum()  # occorrenze extra (da rimuovere)
n_tenute = n_righe_coinvolte - n_gruppi             # prime occorrenze mantenute

print(f'Righe totali coinvolte in duplicazioni : {n_righe_coinvolte:,}')
print(f'  → prime occorrenze mantenute         : {n_tenute:,}')
print(f'  → occorrenze extra rimosse           : {n_gruppi:,}')
print()

df_details.drop_duplicates(keep='first', inplace=True)
print(f'Righe prima della rimozione : {n_originale:,}')
print(f'Righe dopo la rimozione     : {len(df_details):,}')

Righe totali coinvolte in duplicazioni : 0
  → prime occorrenze mantenute         : 0
  → occorrenze extra rimosse           : 0

Righe prima della rimozione : 28,955
Righe dopo la rimozione     : 28,955

## 2. Analisi colonna per colonna

### 2.1 `mal_id`

In [5]:
analyze(df_details['mal_id'])

════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'mal_id'  ═══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    mal_id
  dtype                          int64
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           NUMERIC

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Zeros                          0  (0.00%)
  Positives                      28,955   (100.00%)
  Negatives                      0   (0.00%)
  Unique values                  28,955  (100.00%)

 📐 Descriptive Statistics
────────────────────────────────────────────────────────────────────────────────
  Min                            1
  Max                            62,590
  Range                          62,589
  Mean                           33,977.52
  Median                         37,969.00
  Mode(s)                        1, 5, 6
  Std Dev                        19,616.86
  Variance                       384,821,140
  Std Error (SEM)                115.2836
  IQR  (Q3 − Q1)                 34,980.50
  Q1  (25th pct)                 15,454.00
  Q3  (75th pct)                 50,434.50
  P5  ( 5th pct)                 1,591.70
  P95 (95th pct)                 60,286.20
  Coefficient of Variation       57.73%

 📈 Distribution Shape
────────────────────────────────────────────────────────────────────────────────
  Skewness                       -0.3802  → Approximately symmetric

  Mean position within [min, max]:
  1  │────────────────────────◆───────────────────│  62,590

 ✨ Value Distribution (sorted sparkline)
────────────────────────────────────────────────────────────────────────────────
  ▁▁▁▁▁▁▁▁▂▂▂▂▂▂▂▃▃▃▄▄▄▄▄▅▅▅▅▅▅▅▅▅▅▆▆▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇█████
  Each char ≈ 482 value(s) | min=1 → max=62,590

 📉 Histogram
────────────────────────────────────────────────────────────────────────────────
        1.00 – 3130.45    │█████████████████████████████████████████████ 2830
     3130.45 – 6259.90    │███████████████████████████ 1681
     6259.90 – 9389.35    │███████████████████ 1217
     9389.35 – 12518.80   │████████████████ 1019
    12518.80 – 15648.25   │████████ 519
    15648.25 – 18777.70   │███████████ 662
    18777.70 – 21907.15   │█████████ 587
    21907.15 – 25036.60   │███████████ 704
    25036.60 – 28166.05   │███████ 466
    28166.05 – 31295.50   │██████████████████ 1150
    31295.50 – 34424.95   │████████████████████████ 1494
    34424.95 – 37554.40   │██████████████████████████████ 1898
    37554.40 – 40683.85   │██████████████████████████████ 1907
    40683.85 – 43813.30   │████████████████████████ 1496
    43813.30 – 46942.75   │██████████████████████████████████ 2135
    46942.75 – 50072.20   │████████████████████████████ 1756
    50072.20 – 53201.65   │██████████████████████████ 1639
    53201.65 – 56331.10   │██████████████████████████████ 1876
    56331.10 – 59460.55   │███████████████████████████████ 1974
    59460.55 – 62590.00   │███████████████████████████████ 1945

 🔍 Outlier Analysis
────────────────────────────────────────────────────────────────────────────────
  IQR  method  [lo, hi]          [-37,016.75,  102,905.25]
    → Outliers (IQR)             0 values  (0.00%)

 🏆 Extreme Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 largest:
    #1   62,590  [index 9478]
    #2   62,589  [index 2564]
    #3   62,584  [index 9044]
    #4   62,582  [index 21137]
    #5   62,580  [index 21965]
    #6   62,572  [index 6616]
    #7   62,568  [index 5505]
    #8   62,567  [index 19928]
    #9   62,566  [index 4673]
    #10  62,564  [index 24102]

  Top 10 smallest:
    #1   1  [index 4253]
    #2   5  [index 4255]
    #3   6  [index 25296]
    #4   7  [index 26630]
    #5   8  [index 2818]
    #6   15  [index 6081]
    #7   16  [index 8001]
    #8   17  [index 9666]
    #9   18  [index 10147]
    #10  19  [index 16162]

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
         59,356  [█████████████████████████] 100.0%  1
         56,036  [█████████████████████████] 100.0%  1
          2,928  [█████████████████████████] 100.0%  1
          3,269  [█████████████████████████] 100.0%  1
          4,469  [█████████████████████████] 100.0%  1
            454  [█████████████████████████] 100.0%  1
          1,143  [█████████████████████████] 100.0%  1
            299  [█████████████████████████] 100.0%  1
          9,332  [█████████████████████████] 100.0%  1
         10,390  [█████████████████████████] 100.0%  1

  Top 10 least frequent:
         56,606  [█████████████████████████] 100.0%  1
         34,895  [█████████████████████████] 100.0%  1
         36,305  [█████████████████████████] 100.0%  1
         31,245  [█████████████████████████] 100.0%  1
         59,421  [█████████████████████████] 100.0%  1
         58,303  [█████████████████████████] 100.0%  1
         52,512  [█████████████████████████] 100.0%  1
         45,069  [█████████████████████████] 100.0%  1
         45,187  [█████████████████████████] 100.0%  1
         46,436  [█████████████████████████] 100.0%  1

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
Nessun null, nessun duplicato, dtype già `int64`. È la chiave primaria del dataset.

In [6]:
# Nessuna operazione richiesta
print(f'Null in mal_id      : {df_details["mal_id"].isna().sum()}')
print(f'Duplicati in mal_id : {df_details["mal_id"].duplicated().sum()}')

Null in mal_id      : 0
Duplicati in mal_id : 0

### 2.2 `title`

In [7]:
analyze(df_details['title'])

════════════════════════════════════════════════════════════════════════════════
═══════════════════════  🔬  SERIES ANALYSIS  —  'title'  ═══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    title
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  28,953  (99.99%)
  Duplicate values               2

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     1  chars
  Max length                     186  chars
  Mean length                    24.70  chars
  Median length                  21.0000  chars
  Std Dev length                 15.07
  IQR length                     18.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=186  Shinjiteita Nakama-tachi ni Dungeon Okuchi de Korosarekaketa ga Gift "…
    #2   len=141  99-kai Danzai sareta Loop Reijou desu ga Konse wa "Chouzetsu Aisare Mo…
    #3   len=140  Shoukan Showcase: Isekai Teni shita Saki de Fennec ga Akuma no Shoucho…
    #4   len=132  Mukuwarenakatta Murabito A, Kizoku ni Hirowarete Dekiai sareru Ue ni, …
    #5   len=130  Kanchigai no Atelier Meister: Eiyuu Party no Moto Zatsuyougakari ga, J…
    #6   len=130  NEET Kunoichi to Nazeka Dousei Hajimemashita: Nazeka Beach de Dogimagi…
    #7   len=126  Watashi no Naka no Gensou-teki Sekaikan Oyobi Sono Kengen wo Souki Sas…
    #8   len=124  Kochira Katsushikaku Kameari Kouenmae Hashutsujo: Seton Tankentai! Sum…
    #9   len=120  Kochira Katsushikaku Kameari Kouenmae Hashutsujo: Ryou-san to Chuuken …
    #10  len=120  Tsuujou Kougeki ga Zentai Kougeki de Ni-kai Kougeki no Okaasan wa Suki…

  10 Shortest strings:
    #1   len=1  2
    #2   len=1  9
    #3   len=1  ◯
    #4   len=1  F
    #5   len=1  K
    #6   len=1  M
    #7   len=1  Q
    #8   len=1  R
    #9   len=1  T
    #10  len=1  X

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────

        1.00 – 10.25      │██████████████████ 3742
       10.25 – 19.50      │█████████████████████████████████████████████ 9458
       19.50 – 28.75      │████████████████████████████████ 6669
       28.75 – 38.00      │████████████████████ 4282
       38.00 – 47.25      │████████████ 2418
       47.25 – 56.50      │██████ 1192
       56.50 – 65.75      │███ 639
       65.75 – 75.00      │█ 269
       75.00 – 84.25      │█ 154
       84.25 – 93.50      │ 61
       93.50 – 102.75     │ 30
      102.75 – 112.00     │ 23
      112.00 – 121.25     │ 10
      121.25 – 130.50     │ 4
      130.50 – 139.75     │ 1
      139.75 – 149.00     │ 2
      149.00 – 158.25     │ 0
      158.25 – 167.50     │ 0
      167.50 – 176.75     │ 0
      176.75 – 186.00     │ 1

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    Moonlight                   [█████████████████████████] 100.0%  2
    Shen Lan Qi Yu Wushuang Z…  [█████████████████████████] 100.0%  2
    -Socket-                    [████████████░░░░░░░░░░░░░]  50.0%  1
    ......                      [████████████░░░░░░░░░░░░░]  50.0%  1
    .hack//G.U. Returner        [████████████░░░░░░░░░░░░░]  50.0%  1
    .hack//G.U. Trilogy         [████████████░░░░░░░░░░░░░]  50.0%  1
    .hack//G.U. Trilogy: Paro…  [████████████░░░░░░░░░░░░░]  50.0%  1
    .hack//Gift                 [████████████░░░░░░░░░░░░░]  50.0%  1
    .hack//Intermezzo           [████████████░░░░░░░░░░░░░]  50.0%  1
    .hack//Liminality           [████████████░░░░░░░░░░░░░]  50.0%  1

  Top 10 least frequent (rarest):
    Zutto Tomodachi             [████████████░░░░░░░░░░░░░]  50.0%  1
    Zutto Suki Datta            [████████████░░░░░░░░░░░░░]  50.0%  1
    Zutto Mae kara Suki deshi…  [████████████░░░░░░░░░░░░░]  50.0%  1
    Zutto Mae kara Suki deshi…  [████████████░░░░░░░░░░░░░]  50.0%  1
    Zutaboro Reijou wa Ane no…  [████████████░░░░░░░░░░░░░]  50.0%  1
    Zurukute Sugoi              [████████████░░░░░░░░░░░░░]  50.0%  1
    Zurui Maboroshi             [████████████░░░░░░░░░░░░░]  50.0%  1
    Zuqiu Wangzhe               [████████████░░░░░░░░░░░░░]  50.0%  1
    Zuqiu Jianghu               [████████████░░░░░░░░░░░░░]  50.0%  1
    Zuoyou Nao Zhili Kaifa      [████████████░░░░░░░░░░░░░]  50.0%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                3,715  (12.8%)
  Contains uppercase             28,915  (99.9%)
  Contains lowercase             28,861  (99.7%)
  Contains whitespace            26,023  (89.9%)
  Contains special chars         12,572  (43.4%)
  Contains URL                   1  (0.0%)
  Contains @                     53  (0.2%)
  Fully numeric                  14
  Fully alpha                    2,302
  Fully alphanumeric             2,332

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               715,147
  Unique characters              165
  Avg chars per value            24.70

 💬 Word / Token Analysis
────────────────────────────────────────────────────────────────────────────────
  Avg words per value            4.08
  Max words                      30
  Min words                      1

  Top 10 most common words:
    no                    [█████████████████████████] 100.0%  6,572
    to                    [█████░░░░░░░░░░░░░░░░░░░░]  18.4%  1,207
    Season                [████░░░░░░░░░░░░░░░░░░░░░]  16.0%  1,051
    ni                    [███░░░░░░░░░░░░░░░░░░░░░░]  12.4%  817
    wa                    [███░░░░░░░░░░░░░░░░░░░░░░]  11.8%  777
    -                     [███░░░░░░░░░░░░░░░░░░░░░░]  11.1%  727
    The                   [███░░░░░░░░░░░░░░░░░░░░░░]  10.8%  713
    Movie                 [██░░░░░░░░░░░░░░░░░░░░░░░]   9.8%  641
    wo                    [██░░░░░░░░░░░░░░░░░░░░░░░]   8.6%  567
    Xiao                  [██░░░░░░░░░░░░░░░░░░░░░░░]   8.5%  558

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
Nessun null. I titoli duplicati sono attesi: adattamenti e remake diversi possono condividere lo stesso titolo.

In [8]:
# Nessuna operazione richiesta
print(f'Null in title : {df_details["title"].isna().sum()}')

Null in title : 0

### 2.3 `title_japanese`

In [9]:
analyze(df_details['title_japanese'])

════════════════════════════════════════════════════════════════════════════════
══════════════════  🔬  SERIES ANALYSIS  —  'title_japanese'  ═══════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    title_japanese
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,836  [██████████████████████████████]  99.6%
  Null / NaN                     119  (0.41%)
  Empty strings                  0
  Unique values                  27,772  (95.91%)
  Duplicate values               1,064

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     1  chars
  Max length                     85  chars
  Mean length                    12.24  chars
  Median length                  10.0000  chars
  Std Dev length                 8.69
  IQR length                     10.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=85  ラブライブ School idol project！μ's→NEXT LoveLive！2014～ENDLESS PARADE～アンコールア…
    #2   len=79  信じていた仲間達にダンジョン奥地で殺されかけたがギフト『無限ガチャ』でレベル9999の仲間達を手に入れて元パーティーメンバーと世界に復讐＆『…
    #3   len=78  SUPA DUPA FLY feat. 湘南乃風, MOOMIN, KENTY GROSS, BES, APOLLO, NATURAL WE…
    #4   len=74  DANCE EVOLUTION DANCE MASTERS SILENT HILL ROBBIE !!!!!!!!!!! - 着ぐるみ兎が踊…
    #5   len=74  Vivy -Fluorite Eye's Song- 特別総集編「-To make everyone happy with my singi…
    #6   len=73  ユーリ!!! on ICE Yuri Plisetsky GPF in Barcelona EX "Welcome to The Madne…
    #7   len=69  Candy boy -Nonchalant talk of the certain twin sisters in daily life-
    #8   len=69  ラブライブ School idol project！μ's→NEXT LoveLive！2014～ENDLESS PARADE～幕間ドラマ
    #9   len=67  バンドリ！ ガールズバンドパーティ！ 5th Anniversary Animation -CiRCLE THANKS PARTY！-
    #10  len=66  Inter College Animation Festival (2004) (インターカレッジ・アニメーション・フェスティバル)

  10 Shortest strings:
    #1   len=1  2
    #2   len=1  9
    #3   len=1  愛
    #4   len=1  愛
    #5   len=1  証
    #6   len=1  足
    #7   len=1  ◯
    #8   len=1  缠
    #9   len=1  창
    #10  len=1  笛

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        1.00 – 5.20       │████████████████████████████████ 5933
        5.20 – 9.40       │█████████████████████████████████████████████ 8363
        9.40 – 13.60      │█████████████████████████████ 5417
       13.60 – 17.80      │████████████████ 3022
       17.80 – 22.00      │████████████ 2183
       22.00 – 26.20      │█████████ 1684
       26.20 – 30.40      │█████ 925
       30.40 – 34.60      │███ 536
       34.60 – 38.80      │██ 307
       38.80 – 43.00      │█ 201
       43.00 – 47.20      │█ 132
       47.20 – 51.40      │ 54
       51.40 – 55.60      │ 31
       55.60 – 59.80      │ 23
       59.80 – 64.00      │ 11
       64.00 – 68.20      │ 6
       68.20 – 72.40      │ 2
       72.40 – 76.60      │ 3
       76.60 – 80.80      │ 2
       80.80 – 85.00      │ 1

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    おしりたんてい                     [█████████████████████████] 100.0%  9
    僕のヒーローアカデミア                 [███████████████████░░░░░░]  77.8%  7
    ゲゲゲの鬼太郎                     [██████████████░░░░░░░░░░░]  55.6%  5
    ゴールデンカムイ                    [██████████████░░░░░░░░░░░]  55.6%  5
    ああっ女神さまっ                    [███████████░░░░░░░░░░░░░░]  44.4%  4
    아기공룡 둘리                     [███████████░░░░░░░░░░░░░░]  44.4%  4
    ぼのぼの                        [███████████░░░░░░░░░░░░░░]  44.4%  4
    文豪ストレイドッグス                  [███████████░░░░░░░░░░░░░░]  44.4%  4
    キャットマン                      [███████████░░░░░░░░░░░░░░]  44.4%  4
    地獄先生ぬ～べ～                    [███████████░░░░░░░░░░░░░░]  44.4%  4

  Top 10 least frequent (rarest):
    ずっと友達                       [███░░░░░░░░░░░░░░░░░░░░░░]  11.1%  1
    ずっと好きだった                    [███░░░░░░░░░░░░░░░░░░░░░░]  11.1%  1
    ずっと前から好きでした。～告白実行委員会～ 「金曜…  [███░░░░░░░░░░░░░░░░░░░░░░]  11.1%  1
    ずっと前から好きでした。～告白実行委員会～       [███░░░░░░░░░░░░░░░░░░░░░░]  11.1%  1
    ずたぼろ令嬢は姉の元婚約者に溺愛される         [███░░░░░░░░░░░░░░░░░░░░░░]  11.1%  1
    ズルくてすごい                     [███░░░░░░░░░░░░░░░░░░░░░░]  11.1%  1
    ズルい幻                        [███░░░░░░░░░░░░░░░░░░░░░░]  11.1%  1
    足球王者                        [███░░░░░░░░░░░░░░░░░░░░░░]  11.1%  1
    足球江湖                        [███░░░░░░░░░░░░░░░░░░░░░░]  11.1%  1
    左右脑智力开发                     [███░░░░░░░░░░░░░░░░░░░░░░]  11.1%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                2,618  (9.1%)
  Contains uppercase             6,097  (21.1%)
  Contains lowercase             3,300  (11.4%)
  Contains whitespace            10,743  (37.3%)
  Contains special chars         27,304  (94.7%)
  Contains URL                   0  (0.0%)
  Contains @                     10  (0.0%)
  Fully numeric                  9
  Fully alpha                    598
  Fully alphanumeric             621

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               352,903
  Unique characters              4,559
  Avg chars per value            12.24

 💬 Word / Token Analysis
────────────────────────────────────────────────────────────────────────────────
  Avg words per value            1.65
  Max words                      14
  Min words                      1

  Top 10 most common words:
    THE                   [█████████████████████████] 100.0%  418
    ANIMATION             [██████████████░░░░░░░░░░░]  56.7%  237
    劇場版                   [██████████████░░░░░░░░░░░]  55.3%  231
    The                   [███████████░░░░░░░░░░░░░░]  44.5%  186
    第二季                   [██████████░░░░░░░░░░░░░░░]  38.3%  160
    of                    [████████░░░░░░░░░░░░░░░░░]  33.5%  140
    the                   [████████░░░░░░░░░░░░░░░░░]  32.5%  136
    2                     [████████░░░░░░░░░░░░░░░░░]  31.3%  131
    映画                    [███████░░░░░░░░░░░░░░░░░░]  28.7%  120
    -                     [██████░░░░░░░░░░░░░░░░░░░]  22.0%  92

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
I ~119 null sono strutturali: anime di produzione non giapponese o senza titolo kanji registrato su MAL.

In [10]:
# Nessuna operazione richiesta: i null sono strutturali
print(f'Null in title_japanese : {df_details["title_japanese"].isna().sum()} ({df_details["title_japanese"].isna().mean()*100:.1f}%)')

Null in title_japanese : 119 (0.4%)

### 2.4 `url`

In [11]:
analyze(df_details['url'])

════════════════════════════════════════════════════════════════════════════════
════════════════════════  🔬  SERIES ANALYSIS  —  'url'  ════════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    url
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  28,955  (100.00%)
  Duplicate values               0

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     35  chars
  Max length                     216  chars
  Mean length                    60.19  chars
  Median length                  57.0000  chars
  Std Dev length                 14.92
  IQR length                     17.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=216  https://myanimelist.net/anime/60303/Shinjiteita_Nakama-tachi_ni_Dungeo…
    #2   len=173  https://myanimelist.net/anime/62002/99-kai_Danzai_sareta_Loop_Reijou_d…
    #3   len=172  https://myanimelist.net/anime/61127/Shoukan_Showcase__Isekai_Teni_shit…
    #4   len=166  https://myanimelist.net/anime/57005/Mukuwarenakatta_Murabito_A_Kizoku_…
    #5   len=166  https://myanimelist.net/anime/61271/NEET_Kunoichi_to_Nazeka_Dousei_Haj…
    #6   len=165  https://myanimelist.net/anime/60140/Kanchigai_no_Atelier_Meister__Eiyu…
    #7   len=162  https://myanimelist.net/anime/36596/Watashi_no_Naka_no_Gensou-teki_Sek…
    #8   len=158  https://myanimelist.net/anime/33879/Kochira_Katsushikaku_Kameari_Kouen…
    #9   len=154  https://myanimelist.net/anime/33876/Kochira_Katsushikaku_Kameari_Kouen…
    #10  len=154  https://myanimelist.net/anime/56736/Saikyou_Degarashi_Ouji_no_Anyaku_T…

  10 Shortest strings:
    #1   len=35  https://myanimelist.net/anime/156/X
    #2   len=36  https://myanimelist.net/anime/6055/F
    #3   len=36  https://myanimelist.net/anime/386/H2
    #4   len=37  https://myanimelist.net/anime/56036/-
    #5   len=37  https://myanimelist.net/anime/38756/2
    #6   len=37  https://myanimelist.net/anime/36089/9
    #7   len=37  https://myanimelist.net/anime/4934/AF
    #8   len=37  https://myanimelist.net/anime/6535/Ai
    #9   len=37  https://myanimelist.net/anime/101/Air
    #10  len=37  https://myanimelist.net/anime/31687/◯

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
       35.00 – 44.05      │█████████████ 2571
       44.05 – 53.10      │█████████████████████████████████████████████ 9088
       53.10 – 62.15      │███████████████████████████████████ 7155
       62.15 – 71.20      │████████████████████████ 4774
       71.20 – 80.25      │█████████████ 2536
       80.25 – 89.30      │███████ 1392
       89.30 – 98.35      │████ 778
       98.35 – 107.40     │██ 329
      107.40 – 116.45     │█ 174
      116.45 – 125.50     │ 77
      125.50 – 134.55     │ 37
      134.55 – 143.60     │ 22
      143.60 – 152.65     │ 11
      152.65 – 161.70     │ 4
      161.70 – 170.75     │ 4
      170.75 – 179.80     │ 2
      179.80 – 188.85     │ 0
      188.85 – 197.90     │ 0
      197.90 – 206.95     │ 0
      206.95 – 216.00     │ 1

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1

  Top 10 least frequent (rarest):
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1
    https://myanimelist.net/a…  [█████████████████████████] 100.0%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                28,955  (100.0%)
  Contains uppercase             28,915  (99.9%)
  Contains lowercase             28,955  (100.0%)
  Contains whitespace            0  (0.0%)
  Contains special chars         28,955  (100.0%)
  Contains URL                   28,955  (100.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    0
  Fully alphanumeric             0

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               1,742,829
  Unique characters              145
  Avg chars per value            60.19

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
Nessun null, tutti gli URL sono unici (coerente con `mal_id` come chiave primaria).

In [12]:
# Nessuna operazione richiesta
print(f'Null in url      : {df_details["url"].isna().sum()}')
print(f'Duplicati in url : {df_details["url"].duplicated().sum()}')

Null in url      : 0
Duplicati in url : 0

### 2.5 `image_url`

In [13]:
DEFAULT_IMG = 'https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png'
placeholder = (df_details['image_url'] == DEFAULT_IMG).sum()
print(f'Immagini placeholder : {placeholder:,} ({placeholder/len(df_details)*100:.1f}%)')
print(f'Immagini reali       : {len(df_details)-placeholder:,} ({(len(df_details)-placeholder)/len(df_details)*100:.1f}%)')
print()
analyze(df_details['image_url'])

Immagini placeholder : 198 (0.7%)
Immagini reali       : 28,757 (99.3%)


════════════════════════════════════════════════════════════════════════════════
═════════════════════  🔬  SERIES ANALYSIS  —  'image_url'  ═════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    image_url
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  28,758  (99.32%)
  Duplicate values               197

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     50  chars
  Max length                     64  chars
  Mean length                    54.69  chars
  Median length                  56.0000  chars
  Std Dev length                 1.93
  IQR length                     3.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #2   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #3   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #4   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #5   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #6   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #7   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #8   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #9   len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png
    #10  len=64  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png

  10 Shortest strings:
    #1   len=50  https://cdn.myanimelist.net/images/anime/1/303.jpg
    #2   len=50  https://cdn.myanimelist.net/images/anime/1/740.jpg
    #3   len=50  https://cdn.myanimelist.net/images/anime/1/834.jpg
    #4   len=50  https://cdn.myanimelist.net/images/anime/1/317.jpg
    #5   len=50  https://cdn.myanimelist.net/images/anime/1/139.jpg
    #6   len=50  https://cdn.myanimelist.net/images/anime/1/137.jpg
    #7   len=50  https://cdn.myanimelist.net/images/anime/1/359.jpg
    #8   len=50  https://cdn.myanimelist.net/images/anime/1/864.jpg
    #9   len=50  https://cdn.myanimelist.net/images/anime/1/766.jpg
    #10  len=50  https://cdn.myanimelist.net/images/anime/1/952.jpg

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
       50.00 – 50.93      │ 19
       50.93 – 51.87      │█ 372
       51.87 – 52.80      │██████████████████ 6498
       52.80 – 53.73      │█████████ 3171
       53.73 – 54.67      │ 0
       54.67 – 55.60      │██████ 2069
       55.60 – 56.53      │█████████████████████████████████████████████ 16628
       56.53 – 57.47      │ 0
       57.47 – 58.40      │ 0
       58.40 – 59.33      │ 0
       59.33 – 60.27      │ 0
       60.27 – 61.20      │ 0
       61.20 – 62.13      │ 0
       62.13 – 63.07      │ 0
       63.07 – 64.00      │█ 198

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    https://cdn.myanimelist.n…  [█████████████████████████] 100.0%  198
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1

  Top 10 least frequent (rarest):
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1
    https://cdn.myanimelist.n…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.5%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                28,955  (100.0%)
  Contains uppercase             0  (0.0%)
  Contains lowercase             28,955  (100.0%)
  Contains whitespace            0  (0.0%)
  Contains special chars         28,955  (100.0%)
  Contains URL                   28,955  (100.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    0
  Fully alphanumeric             0

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               1,583,516
  Unique characters              31
  Avg chars per value            54.69

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Pulizia necessaria:**  
~198 URL corrispondono all'immagine placeholder di MAL → aggiungere colonna booleana `has_image` per distinguere gli anime con copertina reale.

In [14]:
DEFAULT_IMG = 'https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png'
df_details['has_image'] = df_details['image_url'] != DEFAULT_IMG
print(f'has_image → True (reale): {df_details["has_image"].sum():,}  |  False (placeholder): {(~df_details["has_image"]).sum():,}')

has_image → True (reale): 28,757  |  False (placeholder): 198

### 2.6 `type`

In [15]:
analyze(df_details['type'])

════════════════════════════════════════════════════════════════════════════════
═══════════════════════  🔬  SERIES ANALYSIS  —  'type'  ════════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    type
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,888  [██████████████████████████████]  99.8%
  Null / NaN                     67  (0.23%)
  Empty strings                  0
  Unique values                  9  (0.03%)
  Duplicate values               28,879

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     2  chars
  Max length                     10  chars
  Mean length                    3.73  chars
  Median length                  3.0000  chars
  Std Dev length                 1.81
  IQR length                     3.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=10  TV Special
    #2   len=10  TV Special
    #3   len=10  TV Special
    #4   len=10  TV Special
    #5   len=10  TV Special
    #6   len=10  TV Special
    #7   len=10  TV Special
    #8   len=10  TV Special
    #9   len=10  TV Special
    #10  len=10  TV Special

  10 Shortest strings:
    #1   len=2  TV
    #2   len=2  TV
    #3   len=2  TV
    #4   len=2  TV
    #5   len=2  TV
    #6   len=2  TV
    #7   len=2  CM
    #8   len=2  TV
    #9   len=2  TV
    #10  len=2  TV

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        2.00 – 2.89       │█████████████████████████████████████████████ 9172
        2.89 – 3.78       │█████████████████████████████████████████ 8280
        3.78 – 4.67       │ 0
        4.67 – 5.56       │████████████████████████████████████████████ 8914
        5.56 – 6.44       │ 0
        6.44 – 7.33       │█████████ 1755
        7.33 – 8.22       │ 0
        8.22 – 9.11       │ 0
        9.11 – 10.00      │████ 767

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    TV                          [█████████████████████████] 100.0%  8,414
    Movie                       [███████████████░░░░░░░░░░]  58.4%  4,915
    OVA                         [████████████░░░░░░░░░░░░░]  49.7%  4,184
    ONA                         [████████████░░░░░░░░░░░░░]  48.7%  4,096
    Music                       [████████████░░░░░░░░░░░░░]  47.5%  3,999
    Special                     [█████░░░░░░░░░░░░░░░░░░░░]  20.9%  1,755
    TV Special                  [██░░░░░░░░░░░░░░░░░░░░░░░]   9.1%  767
    CM                          [█░░░░░░░░░░░░░░░░░░░░░░░░]   5.7%  483
    PV                          [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.3%  275

  Top 10 least frequent (rarest):
    PV                          [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.3%  275
    CM                          [█░░░░░░░░░░░░░░░░░░░░░░░░]   5.7%  483
    TV Special                  [██░░░░░░░░░░░░░░░░░░░░░░░]   9.1%  767
    Special                     [█████░░░░░░░░░░░░░░░░░░░░]  20.9%  1,755
    Music                       [████████████░░░░░░░░░░░░░]  47.5%  3,999
    ONA                         [████████████░░░░░░░░░░░░░]  48.7%  4,096
    OVA                         [████████████░░░░░░░░░░░░░]  49.7%  4,184
    Movie                       [███████████████░░░░░░░░░░]  58.4%  4,915
    TV                          [█████████████████████████] 100.0%  8,414

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                0  (0.0%)
  Contains uppercase             28,888  (100.0%)
  Contains lowercase             11,436  (39.6%)
  Contains whitespace            767  (2.7%)
  Contains special chars         0  (0.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    28,121
  Fully alphanumeric             28,121

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               107,709
  Unique characters              20
  Avg chars per value            3.73

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
I ~67 null sono strutturali: anime con stato `Not yet aired` per cui il tipo non è ancora stato registrato su MAL. I valori presenti sono coerenti con la tassonomia MAL (TV, Movie, OVA, ONA, Special, Music, CM, PV, TV Special).

In [16]:
# Nessuna operazione richiesta: i null sono strutturali (Not yet aired)
print(f'Null in type  : {df_details["type"].isna().sum()}')
print(f'Valori unici  : {sorted(df_details["type"].dropna().unique().tolist())}')

Null in type  : 67
Valori unici  : ['CM', 'Movie', 'Music', 'ONA', 'OVA', 'PV', 'Special', 'TV', 'TV Special']

### 2.7 `status`

In [17]:
analyze(df_details['status'])

════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'status'  ═══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    status
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  3  (0.01%)
  Duplicate values               28,952

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     13  chars
  Max length                     16  chars
  Mean length                    14.97  chars
  Median length                  15.0000  chars
  Std Dev length                 0.29
  IQR length                     0.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=16  Currently Airing
    #2   len=16  Currently Airing
    #3   len=16  Currently Airing
    #4   len=16  Currently Airing
    #5   len=16  Currently Airing
    #6   len=16  Currently Airing
    #7   len=16  Currently Airing
    #8   len=16  Currently Airing
    #9   len=16  Currently Airing
    #10  len=16  Currently Airing

  10 Shortest strings:
    #1   len=13  Not yet aired
    #2   len=13  Not yet aired
    #3   len=13  Not yet aired
    #4   len=13  Not yet aired
    #5   len=13  Not yet aired
    #6   len=13  Not yet aired
    #7   len=13  Not yet aired
    #8   len=13  Not yet aired
    #9   len=13  Not yet aired
    #10  len=13  Not yet aired

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
       13.00 – 13.75      │█ 544
       13.75 – 14.50      │ 0
       14.50 – 15.25      │█████████████████████████████████████████████ 28097
       15.25 – 16.00      │█ 314

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    Finished Airing             [█████████████████████████] 100.0%  28,097
    Not yet aired               [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.9%  544
    Currently Airing            [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.1%  314

  Top 10 least frequent (rarest):
    Currently Airing            [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.1%  314
    Not yet aired               [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.9%  544
    Finished Airing             [█████████████████████████] 100.0%  28,097

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                0  (0.0%)
  Contains uppercase             28,955  (100.0%)
  Contains lowercase             28,955  (100.0%)
  Contains whitespace            28,955  (100.0%)
  Contains special chars         0  (0.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    0
  Fully alphanumeric             0

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               433,551
  Unique characters              19
  Avg chars per value            14.97

 💬 Word / Token Analysis
────────────────────────────────────────────────────────────────────────────────
  Avg words per value            2.02
  Max words                      3
  Min words                      2

  Top 10 most common words:
    Airing                [█████████████████████████] 100.0%  28,411
    Finished              [█████████████████████████]  98.9%  28,097
    Not                   [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.9%  544
    yet                   [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.9%  544
    aired                 [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.9%  544
    Currently             [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.1%  314

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
Nessun null. Tre valori coerenti: `Finished Airing`, `Currently Airing`, `Not yet aired`.

In [18]:
# Nessuna operazione richiesta
print(f'Null in status : {df_details["status"].isna().sum()}')
print(df_details['status'].value_counts())

Null in status : 0
status
Finished Airing     28097
Not yet aired         544
Currently Airing      314
Name: count, dtype: int64

### 2.8 `score` e `scored_by`

Le due colonne sono co-nulle: quando un anime non ha voti sufficienti su MAL, entrambe sono `NaN`.

In [19]:
analyze(df_details['score'])

════════════════════════════════════════════════════════════════════════════════
═══════════════════════  🔬  SERIES ANALYSIS  —  'score'  ═══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    score
  dtype                          float64
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           NUMERIC

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                18,882  [████████████████████░░░░░░░░░░]  65.2%
  Null / NaN                     10,073  (34.79%)
  Zeros                          0  (0.00%)
  Positives                      18,882   (65.21%)
  Negatives                      0   (0.00%)
  Unique values                  561  (1.94%)

 📐 Descriptive Statistics
────────────────────────────────────────────────────────────────────────────────
  Min                            1.8900
  Max                            9.2900
  Range                          7.4000
  Mean                           6.3905
  Median                         6.3600
  Mode(s)                        6.2900
  Std Dev                        0.8920
  Variance                       0.7957
  Std Error (SEM)                0.0065
  IQR  (Q3 − Q1)                 1.2600
  Q1  (25th pct)                 5.7700
  Q3  (75th pct)                 7.0300
  P5  ( 5th pct)                 4.9900
  P95 (95th pct)                 7.8700
  Coefficient of Variation       13.96%

 📈 Distribution Shape
────────────────────────────────────────────────────────────────────────────────
  Skewness                       -0.0269  → Approximately symmetric

  Mean position within [min, max]:
  1.8900  │───────────────────────────◆────────────────│  9.2900

 ✨ Value Distribution (sorted sparkline)
────────────────────────────────────────────────────────────────────────────────
  ▁▄▄▄▄▄▄▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇
  Each char ≈ 314 value(s) | min=1.8900 → max=9.2900

 📉 Histogram
────────────────────────────────────────────────────────────────────────────────
        1.89 – 2.26       │ 3
        2.26 – 2.63       │ 4
        2.63 – 3.00       │ 8
        3.00 – 3.37       │ 20
        3.37 – 3.74       │ 26
        3.74 – 4.11       │█ 50
        4.11 – 4.48       │██ 123
        4.48 – 4.85       │███████ 451
        4.85 – 5.22       │█████████████ 886
        5.22 – 5.59       │████████████████████████████ 1890
        5.59 – 5.96       │████████████████████████████████████████ 2647
        5.96 – 6.33       │█████████████████████████████████████████████ 2991
        6.33 – 6.70       │█████████████████████████████████████████████ 3010
        6.70 – 7.07       │██████████████████████████████████ 2275
        7.07 – 7.44       │████████████████████████████████ 2133
        7.44 – 7.81       │███████████████████ 1280
        7.81 – 8.18       │█████████ 629
        8.18 – 8.55       │█████ 326
        8.55 – 8.92       │██ 111
        8.92 – 9.29       │ 19

 🔍 Outlier Analysis
────────────────────────────────────────────────────────────────────────────────
  IQR  method  [lo, hi]          [3.8800,  8.9200]
    → Outliers (IQR)             102 values  (0.35%)

  Top 5 extreme IQR outliers (by abs value):
    [23116]  9.2900
    [6593]  9.1000
    [23288]  9.0700
    [7379]  9.0500
    [7383]  9.0500

 🏆 Extreme Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 largest:
    #1   9.2900  [index 23116]
    #2   9.1000  [index 6593]
    #3   9.0700  [index 23288]
    #4   9.0500  [index 7379]
    #5   9.0500  [index 7383]
    #6   9.0500  [index 22020]
    #7   9.0300  [index 9671]
    #8   9.0300  [index 17926]
    #9   9.0200  [index 7291]
    #10  9.0200  [index 7367]

  Top 10 smallest:
    #1   1.8900  [index 24273]
    #2   2.0100  [index 26063]
    #3   2.2300  [index 8219]
    #4   2.3300  [index 25364]
    #5   2.4100  [index 12885]
    #6   2.4300  [index 668]
    #7   2.5600  [index 329]
    #8   2.6800  [index 440]
    #9   2.6800  [index 14102]
    #10  2.7500  [index 17254]

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
         6.2900  [█████████████████████████] 100.0%  102
         6.3300  [█████████████████████████]  98.0%  100
         6.5300  [████████████████████████░]  97.1%  99
         6.5100  [████████████████████████░]  96.1%  98
         6.2100  [████████████████████████░]  95.1%  97
         6.4600  [███████████████████████░░]  93.1%  95
         6.0600  [███████████████████████░░]  93.1%  95
         6.4100  [███████████████████████░░]  93.1%  95
         5.9800  [███████████████████████░░]  92.2%  94
         6.4400  [███████████████████████░░]  91.2%  93

  Top 10 least frequent:
         3.5300  [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.0%  1
         4.0000  [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.0%  1
         3.4800  [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.0%  1
         3.6400  [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.0%  1
         8.8400  [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.0%  1
         8.8200  [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.0%  1
         3.3300  [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.0%  1
         2.0100  [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.0%  1
         2.3300  [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.0%  1
         1.8900  [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.0%  1

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

In [20]:
analyze(df_details['scored_by'])

════════════════════════════════════════════════════════════════════════════════
═════════════════════  🔬  SERIES ANALYSIS  —  'scored_by'  ═════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    scored_by
  dtype                          float64
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           NUMERIC

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                18,882  [████████████████████░░░░░░░░░░]  65.2%
  Null / NaN                     10,073  (34.79%)
  Zeros                          0  (0.00%)
  Positives                      18,882   (65.21%)
  Negatives                      0   (0.00%)
  Unique values                  9,245  (31.93%)

 📐 Descriptive Statistics
────────────────────────────────────────────────────────────────────────────────
  Min                            101.0000
  Max                            2,979,733
  Range                          2,979,632
  Mean                           29,963.08
  Median                         1,528.00
  Mode(s)                        120.0000
  Std Dev                        121,966.56
  Variance                       14,875,842,969
  Std Error (SEM)                887.5990
  IQR  (Q3 − Q1)                 9,813.50
  Q1  (25th pct)                 332.2500
  Q3  (75th pct)                 10,145.75
  P5  ( 5th pct)                 134.0000
  P95 (95th pct)                 138,467.35
  Coefficient of Variation       407.06%

 📈 Distribution Shape
────────────────────────────────────────────────────────────────────────────────
  Skewness                       9.7447  → Strongly right-skewed (long right tail)

  Mean position within [min, max]:
  101.0000  │◆───────────────────────────────────────────│  2,979,733

 ✨ Value Distribution (sorted sparkline)
────────────────────────────────────────────────────────────────────────────────
  ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂▂▃
  Each char ≈ 314 value(s) | min=101.0000 → max=2,979,733

 📉 Histogram
────────────────────────────────────────────────────────────────────────────────
      101.00 – 149082.60  │█████████████████████████████████████████████ 18019
   149082.60 – 298064.20  │█ 452
   298064.20 – 447045.80  │ 160
   447045.80 – 596027.40  │ 82
   596027.40 – 745009.00  │ 52
   745009.00 – 893990.60  │ 26
   893990.60 – 1042972.20 │ 28
  1042972.20 – 1191953.80 │ 17
  1191953.80 – 1340935.40 │ 11
  1340935.40 – 1489917.00 │ 14
  1489917.00 – 1638898.60 │ 3
  1638898.60 – 1787880.20 │ 4
  1787880.20 – 1936861.80 │ 3
  1936861.80 – 2085843.40 │ 3
  2085843.40 – 2234825.00 │ 2
  2234825.00 – 2383806.60 │ 4
  2383806.60 – 2532788.20 │ 0
  2532788.20 – 2681769.80 │ 0
  2681769.80 – 2830751.40 │ 0
  2830751.40 – 2979733.00 │ 2

 🔍 Outlier Analysis
────────────────────────────────────────────────────────────────────────────────
  IQR  method  [lo, hi]          [-14,388.00,  24,866.00]
    → Outliers (IQR)             3,150 values  (10.88%)

  Top 5 extreme IQR outliers (by abs value):
    [22010]  2,979,733
    [4788]  2,919,353
    [17990]  2,365,396
    [12300]  2,281,401
    [6593]  2,248,907

 🏆 Extreme Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 largest:
    #1   2,979,733  [index 22010]
    #2   2,919,353  [index 4788]
    #3   2,365,396  [index 17990]
    #4   2,281,401  [index 12300]
    #5   2,248,907  [index 6593]
    #6   2,240,438  [index 23654]
    #7   2,181,208  [index 2633]
    #8   2,088,445  [index 16821]
    #9   2,027,815  [index 12360]
    #10  2,003,062  [index 22017]

  Top 10 smallest:
    #1   101.0000  [index 9274]
    #2   101.0000  [index 17221]
    #3   101.0000  [index 25338]
    #4   102.0000  [index 6562]
    #5   102.0000  [index 7693]
    #6   102.0000  [index 12256]
    #7   102.0000  [index 13395]
    #8   102.0000  [index 15143]
    #9   103.0000  [index 1637]
    #10  103.0000  [index 2744]

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
       120.0000  [█████████████████████████] 100.0%  46
       121.0000  [████████████████████████░]  95.7%  44
       117.0000  [███████████████████████░░]  91.3%  42
       111.0000  [██████████████████████░░░]  89.1%  41
       127.0000  [██████████████████████░░░]  87.0%  40
       132.0000  [██████████████████████░░░]  87.0%  40
       143.0000  [█████████████████████░░░░]  84.8%  39
       151.0000  [█████████████████████░░░░]  84.8%  39
       135.0000  [█████████████████████░░░░]  84.8%  39
       133.0000  [█████████████████████░░░░]  82.6%  38

  Top 10 least frequent:
       1,887.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.2%  1
      10,038.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.2%  1
     104,106.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.2%  1
      15,624.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.2%  1
       2,219.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.2%  1
      14,906.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.2%  1
       4,192.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.2%  1
      94,201.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.2%  1
     250,375.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.2%  1
      65,863.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.2%  1

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Pulizie necessarie:**
- I null (~10.073) sono strutturali: anime senza voti sufficienti per avere uno score su MAL → nessuna rimozione
- `scored_by`: dtype `float64` → convertire a `Int64` (nullable integer), dato che i valori sono interi

In [21]:
# Verifica co-nullità
print(f'Null in score     : {df_details["score"].isna().sum():,}')
print(f'Null in scored_by : {df_details["scored_by"].isna().sum():,}')
print(f'Co-nulli (entrambi NaN) : {(df_details["score"].isna() & df_details["scored_by"].isna()).sum():,}')
print()

df_details['scored_by'] = df_details['scored_by'].astype('Int64')
print(f'scored_by dtype : {df_details["scored_by"].dtype}')

Null in score     : 10,073
Null in scored_by : 10,073
Co-nulli (entrambi NaN) : 10,073

scored_by dtype : Int64

### 2.9 `start_date`

In [22]:
analyze(df_details['start_date'])

════════════════════════════════════════════════════════════════════════════════
════════════════════  🔬  SERIES ANALYSIS  —  'start_date'  ═════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    start_date
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,104  [█████████████████████████████░]  97.1%
  Null / NaN                     851  (2.94%)
  Empty strings                  0
  Unique values                  9,367  (32.35%)
  Duplicate values               18,737

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     25  chars
  Max length                     25  chars
  Mean length                    25.00  chars
  Median length                  25.0000  chars
  Std Dev length                 0.00
  IQR length                     0.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=25  2010-01-01T00:00:00+00:00
    #2   len=25  2023-06-11T00:00:00+00:00
    #3   len=25  2007-01-18T00:00:00+00:00
    #4   len=25  2007-12-22T00:00:00+00:00
    #5   len=25  2008-03-25T00:00:00+00:00
    #6   len=25  2003-11-16T00:00:00+00:00
    #7   len=25  2003-03-28T00:00:00+00:00
    #8   len=25  2002-06-20T00:00:00+00:00
    #9   len=25  2011-01-28T00:00:00+00:00
    #10  len=25  2011-01-28T00:00:00+00:00

  10 Shortest strings:
    #1   len=25  2010-01-01T00:00:00+00:00
    #2   len=25  2023-06-11T00:00:00+00:00
    #3   len=25  2007-01-18T00:00:00+00:00
    #4   len=25  2007-12-22T00:00:00+00:00
    #5   len=25  2008-03-25T00:00:00+00:00
    #6   len=25  2003-11-16T00:00:00+00:00
    #7   len=25  2003-03-28T00:00:00+00:00
    #8   len=25  2002-06-20T00:00:00+00:00
    #9   len=25  2011-01-28T00:00:00+00:00
    #10  len=25  2011-01-28T00:00:00+00:00

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
  All strings have the same length. (25 chars)

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    2012-01-01T00:00:00+00:00   [█████████████████████████] 100.0%  158
    2011-01-01T00:00:00+00:00   [████████████████████████░]  96.8%  153
    2019-01-01T00:00:00+00:00   [███████████████████████░░]  92.4%  146
    2010-01-01T00:00:00+00:00   [███████████████████████░░]  91.8%  145
    2026-01-01T00:00:00+00:00   [█████████████████████░░░░]  84.2%  133
    2015-01-01T00:00:00+00:00   [████████████████████░░░░░]  79.1%  125
    2013-01-01T00:00:00+00:00   [███████████████████░░░░░░]  77.2%  122
    2008-01-01T00:00:00+00:00   [██████████████████░░░░░░░]  72.2%  114
    2009-01-01T00:00:00+00:00   [█████████████████░░░░░░░░]  69.6%  110
    2014-01-01T00:00:00+00:00   [█████████████████░░░░░░░░]  69.0%  109

  Top 10 least frequent (rarest):
    2019-08-17T00:00:00+00:00   [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.6%  1
    1995-11-11T00:00:00+00:00   [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.6%  1
    1980-04-15T00:00:00+00:00   [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.6%  1
    1992-07-04T00:00:00+00:00   [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.6%  1
    2015-12-08T00:00:00+00:00   [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.6%  1
    2011-05-18T00:00:00+00:00   [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.6%  1
    2014-05-21T00:00:00+00:00   [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.6%  1
    2009-02-27T00:00:00+00:00   [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.6%  1
    2019-05-19T00:00:00+00:00   [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.6%  1
    2020-10-17T00:00:00+00:00   [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.6%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                28,104  (100.0%)
  Contains uppercase             28,104  (100.0%)
  Contains lowercase             0  (0.0%)
  Contains whitespace            0  (0.0%)
  Contains special chars         28,104  (100.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    0
  Fully alphanumeric             0

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               702,600
  Unique characters              14
  Avg chars per value            25.00

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Pulizia necessaria:**
- I valori sono stringhe ISO 8601 con timezone UTC → convertire a `datetime64[us, UTC]`
- Gli ~851 null sono strutturali: anime `Not yet aired` senza data confermata

In [23]:
df_details['start_date'] = pd.to_datetime(df_details['start_date'], errors='coerce', utc=True)
print(f'start_date dtype : {df_details["start_date"].dtype}')
print(f'Null residui     : {df_details["start_date"].isna().sum()}')
print(f'Range            : {df_details["start_date"].min()} → {df_details["start_date"].max()}')

start_date dtype : datetime64[us, UTC]
Null residui     : 851
Range            : 1917-01-01 00:00:00+00:00 → 2027-01-01 00:00:00+00:00

### 2.10 `end_date`

In [24]:
analyze(df_details['end_date'])

════════════════════════════════════════════════════════════════════════════════
═════════════════════  🔬  SERIES ANALYSIS  —  'end_date'  ══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    end_date
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                11,267  [████████████░░░░░░░░░░░░░░░░░░]  38.9%
  Null / NaN                     17,688  (61.09%)
  Empty strings                  0
  Unique values                  5,607  (19.36%)
  Duplicate values               5,660

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     25  chars
  Max length                     25  chars
  Mean length                    25.00  chars
  Median length                  25.0000  chars
  Std Dev length                 0.00
  IQR length                     0.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=25  2003-04-10T00:00:00+00:00
    #2   len=25  2011-04-07T00:00:00+00:00
    #3   len=25  2011-04-07T00:00:00+00:00
    #4   len=25  2006-09-28T00:00:00+00:00
    #5   len=25  2002-09-26T00:00:00+00:00
    #6   len=25  2003-03-27T00:00:00+00:00
    #7   len=25  2018-12-28T00:00:00+00:00
    #8   len=25  2024-09-22T00:00:00+00:00
    #9   len=25  2025-03-23T00:00:00+00:00
    #10  len=25  1964-10-27T00:00:00+00:00

  10 Shortest strings:
    #1   len=25  2003-04-10T00:00:00+00:00
    #2   len=25  2011-04-07T00:00:00+00:00
    #3   len=25  2011-04-07T00:00:00+00:00
    #4   len=25  2006-09-28T00:00:00+00:00
    #5   len=25  2002-09-26T00:00:00+00:00
    #6   len=25  2003-03-27T00:00:00+00:00
    #7   len=25  2018-12-28T00:00:00+00:00
    #8   len=25  2024-09-22T00:00:00+00:00
    #9   len=25  2025-03-23T00:00:00+00:00
    #10  len=25  1964-10-27T00:00:00+00:00

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
  All strings have the same length. (25 chars)

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    2013-01-01T00:00:00+00:00   [█████████████████████████] 100.0%  21
    2019-01-01T00:00:00+00:00   [█████████████████████░░░░]  85.7%  18
    2012-01-01T00:00:00+00:00   [█████████████████████░░░░]  85.7%  18
    2014-01-01T00:00:00+00:00   [████████████████████░░░░░]  81.0%  17
    2023-03-26T00:00:00+00:00   [████████████████████░░░░░]  81.0%  17
    2008-01-01T00:00:00+00:00   [██████████████████░░░░░░░]  71.4%  15
    2016-03-25T00:00:00+00:00   [█████████████████░░░░░░░░]  66.7%  14
    2011-01-01T00:00:00+00:00   [█████████████████░░░░░░░░]  66.7%  14
    2017-01-01T00:00:00+00:00   [█████████████████░░░░░░░░]  66.7%  14
    2016-03-26T00:00:00+00:00   [█████████████████░░░░░░░░]  66.7%  14

  Top 10 least frequent (rarest):
    2017-11-22T00:00:00+00:00   [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.8%  1
    1980-09-23T00:00:00+00:00   [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.8%  1
    2020-07-22T00:00:00+00:00   [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.8%  1
    2025-07-05T00:00:00+00:00   [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.8%  1
    2011-11-16T00:00:00+00:00   [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.8%  1
    2007-09-12T00:00:00+00:00   [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.8%  1
    2016-07-23T00:00:00+00:00   [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.8%  1
    2021-11-19T00:00:00+00:00   [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.8%  1
    2009-03-31T00:00:00+00:00   [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.8%  1
    2001-04-25T00:00:00+00:00   [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.8%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                11,267  (100.0%)
  Contains uppercase             11,267  (100.0%)
  Contains lowercase             0  (0.0%)
  Contains whitespace            0  (0.0%)
  Contains special chars         11,267  (100.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    0
  Fully alphanumeric             0

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               281,675
  Unique characters              14
  Avg chars per value            25.00

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Pulizia necessaria:**
- Stessa conversione a `datetime64[us, UTC]` di `start_date`
- I ~17.688 null sono strutturali: anime `Currently Airing` o `Not yet aired` non hanno ancora una data di fine

In [25]:
df_details['end_date'] = pd.to_datetime(df_details['end_date'], errors='coerce', utc=True)
print(f'end_date dtype : {df_details["end_date"].dtype}')
print(f'Null residui   : {df_details["end_date"].isna().sum()}')
print(f'Range          : {df_details["end_date"].min()} → {df_details["end_date"].max()}')

end_date dtype : datetime64[us, UTC]
Null residui   : 17688
Range          : 1962-02-25 00:00:00+00:00 → 2026-04-10 00:00:00+00:00

### 2.11 `synopsis`

In [26]:
analyze(df_details['synopsis'])

════════════════════════════════════════════════════════════════════════════════
═════════════════════  🔬  SERIES ANALYSIS  —  'synopsis'  ══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    synopsis
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                23,828  [█████████████████████████░░░░░]  82.3%
  Null / NaN                     5,127  (17.71%)
  Empty strings                  0
  Unique values                  23,540  (81.30%)
  Duplicate values               288

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     10  chars
  Max length                     3,750  chars
  Mean length                    377.40  chars
  Median length                  251.0000  chars
  Std Dev length                 351.38
  IQR length                     499.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=3750  Li Xiaobai, who entered the immersive stand-alone game Faerie Continen…
    #2   len=3635  Tezuka × Atobe ÷ Koharu↵ Fudomine Middle School's tennis captain, Kipp…
    #3   len=3268  One hundred thousand years ago, the immortal world was in a melee, the…
    #4   len=2737  In In the year 2113 A.D., a team of scientists is dispatched to Antarc…
    #5   len=2731  In the previous life, although Qin Yichen, the sage of alchemy, posses…
    #6   len=2633  The plot consists of a chase of a hijacked MBT-99A tank, designed by t…
    #7   len=2615  This film consists of 6 animated shorts produced by the Human Rights C…
    #8   len=2412  GOSHO collection reveals the origin of the smash hit "Detective Conan.…
    #9   len=2410  Shouhei Zenya (The Night Before The Invitation)↵ Prior to the U-17 tra…
    #10  len=2315  Based on a seinen manga by Kikuchi Naoe and Yokomi Hirohiko, serialise…

  10 Shortest strings:
    #1   len=10  G9+1 film.
    #2   len=12  BD Specials.
    #3   len=12  BD specials.
    #4   len=12  DVD special.
    #5   len=13  DVD/BD extra.
    #6   len=13  Nurse hentai.
    #7   len=13  DVD specials.
    #8   len=13  DVD Specials.
    #9   len=14  Chinpui movie.
    #10  len=14  Second season.

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
       10.00 – 197.00     │█████████████████████████████████████████████ 10641
      197.00 – 384.00     │█████████████████ 4010
      384.00 – 571.00     │█████████████ 2984
      571.00 – 758.00     │█████████ 2166
      758.00 – 945.00     │████████ 1799
      945.00 – 1132.00    │██████ 1395
     1132.00 – 1319.00    │██ 582
     1319.00 – 1506.00    │█ 154
     1506.00 – 1693.00    │ 50
     1693.00 – 1880.00    │ 20
     1880.00 – 2067.00    │ 10
     2067.00 – 2254.00    │ 7
     2254.00 – 2441.00    │ 3
     2441.00 – 2628.00    │ 1
     2628.00 – 2815.00    │ 3
     2815.00 – 3002.00    │ 0
     3002.00 – 3189.00    │ 0
     3189.00 – 3376.00    │ 1
     3376.00 – 3563.00    │ 0
     3563.00 – 3750.00    │ 2

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    No synopsis has been adde…  [█████████████████████████] 100.0%  23
    Furukawa Taku film.         [█████████████░░░░░░░░░░░░]  52.2%  12
    Film by Takashi Ito.        [█████████████░░░░░░░░░░░░]  52.2%  12
    A short animation by Taku…  [███████████░░░░░░░░░░░░░░]  43.5%  10
    A short film by Okamoto T…  [████████░░░░░░░░░░░░░░░░░]  30.4%  7
    Short animation by Rappar…  [███████░░░░░░░░░░░░░░░░░░]  26.1%  6
    Short film by Hirano Ryou…  [███████░░░░░░░░░░░░░░░░░░]  26.1%  6
    A short puppet animation …  [███████░░░░░░░░░░░░░░░░░░]  26.1%  6
    Short film by Kurosaka Ke…  [███████░░░░░░░░░░░░░░░░░░]  26.1%  6
    A short film by Haruka Su…  [█████░░░░░░░░░░░░░░░░░░░░]  21.7%  5

  Top 10 least frequent (rarest):
    Music video for the song …  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.3%  1
    Setsuna Shiraha has loved…  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.3%  1
    A picture drama special b…  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.3%  1
    Love is blooming at Sakur…  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.3%  1
    The Shaderan family has f…  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.3%  1
    Music video for the song …  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.3%  1
    Music video for the song …  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.3%  1
    The second season of Zuos…  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.3%  1
    The story follows teenage…  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.3%  1
    Zunko Tohoku can make any…  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.3%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                5,520  (23.2%)
  Contains uppercase             23,826  (100.0%)
  Contains lowercase             23,828  (100.0%)
  Contains whitespace            23,828  (100.0%)
  Contains special chars         23,807  (99.9%)
  Contains URL                   3  (0.0%)
  Contains @                     38  (0.2%)
  Fully numeric                  0
  Fully alpha                    0
  Fully alphanumeric             0

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               8,992,584
  Unique characters              617
  Avg chars per value            377.40

 💬 Word / Token Analysis
────────────────────────────────────────────────────────────────────────────────
  Avg words per value            63.48
  Max words                      638
  Min words                      2

  Top 10 most common words:
    the                   [█████████████████████████] 100.0%  86,835
    to                    [█████████████░░░░░░░░░░░░]  50.5%  43,834
    of                    [████████████░░░░░░░░░░░░░]  47.1%  40,908
    a                     [████████████░░░░░░░░░░░░░]  46.5%  40,351
    and                   [███████████░░░░░░░░░░░░░░]  45.2%  39,283
    in                    [██████░░░░░░░░░░░░░░░░░░░]  23.1%  20,100
    is                    [██████░░░░░░░░░░░░░░░░░░░]  22.9%  19,911
    by                    [█████░░░░░░░░░░░░░░░░░░░░]  18.8%  16,286
    his                   [████░░░░░░░░░░░░░░░░░░░░░]  17.9%  15,580
    for                   [████░░░░░░░░░░░░░░░░░░░░░]  15.1%  13,106

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Pulizia necessaria:**
- I ~5.127 null sono strutturali: anime senza sinossi su MAL (spesso cortometraggi, CM, PV) → aggiungere colonna booleana `has_synopsis`

In [27]:
df_details['has_synopsis'] = df_details['synopsis'].notna()
print(f'has_synopsis → True (con sinossi): {df_details["has_synopsis"].sum():,}  |  False: {(~df_details["has_synopsis"]).sum():,}')

has_synopsis → True (con sinossi): 23,828  |  False: 5,127

### 2.12 `rank`

In [28]:
analyze(df_details['rank'])

════════════════════════════════════════════════════════════════════════════════
═══════════════════════  🔬  SERIES ANALYSIS  —  'rank'  ════════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    rank
  dtype                          float64
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           NUMERIC

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                21,997  [███████████████████████░░░░░░░]  76.0%
  Null / NaN                     6,958  (24.03%)
  Zeros                          0  (0.00%)
  Positives                      21,997   (75.97%)
  Negatives                      0   (0.00%)
  Unique values                  17,765  (61.35%)

 📐 Descriptive Statistics
────────────────────────────────────────────────────────────────────────────────
  Min                            1.0000
  Max                            22,020.00
  Range                          22,019.00
  Mean                           11,033.16
  Median                         11,008.00
  Mode(s)                        2,651.00, 2,819.00, 9,326.00
  Std Dev                        6,388.28
  Variance                       40,810,115
  Std Error (SEM)                43.0727
  IQR  (Q3 − Q1)                 11,010.00
  Q1  (25th pct)                 5,505.00
  Q3  (75th pct)                 16,515.00
  P5  ( 5th pct)                 1,102.80
  P95 (95th pct)                 21,027.40
  Coefficient of Variation       57.90%

 📈 Distribution Shape
────────────────────────────────────────────────────────────────────────────────
  Skewness                       0.0094  → Approximately symmetric

  Mean position within [min, max]:
  1.0000  │──────────────────────◆─────────────────────│  22,020.00

 ✨ Value Distribution (sorted sparkline)
────────────────────────────────────────────────────────────────────────────────
  ▁▁▁▁▁▂▂▂▂▂▂▂▂▃▃▃▃▃▃▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▅▅▅▅▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇████
  Each char ≈ 366 value(s) | min=1.0000 → max=22,020.00

 📉 Histogram
────────────────────────────────────────────────────────────────────────────────
        1.00 – 1101.95    │█████████████████████████████████████████ 1099
     1101.95 – 2202.90    │█████████████████████████████████████████ 1100
     2202.90 – 3303.85    │█████████████████████████████████████████ 1100
     3303.85 – 4404.80    │█████████████████████████████████████████ 1101
     4404.80 – 5505.75    │█████████████████████████████████████████ 1100
     5505.75 – 6606.70    │█████████████████████████████████████████ 1098
     6606.70 – 7707.65    │█████████████████████████████████████████ 1104
     7707.65 – 8808.60    │█████████████████████████████████████████ 1100
     8808.60 – 9909.55    │█████████████████████████████████████████ 1100
     9909.55 – 11010.50   │█████████████████████████████████████████ 1099
    11010.50 – 12111.45   │█████████████████████████████████████████ 1097
    12111.45 – 13212.40   │█████████████████████████████████████████ 1100
    13212.40 – 14313.35   │█████████████████████████████████████████ 1097
    14313.35 – 15414.30   │█████████████████████████████████████████ 1101
    15414.30 – 16515.25   │█████████████████████████████████████████ 1102
    16515.25 – 17616.20   │███████████████████████████████████████ 1053
    17616.20 – 18717.15   │██████████████████████████████████████ 1029
    18717.15 – 19818.10   │█████████████████████████████████████ 1005
    19818.10 – 20919.05   │████████████████████████████████████████████ 1194
    20919.05 – 22020.00   │█████████████████████████████████████████████ 1218

 🔍 Outlier Analysis
────────────────────────────────────────────────────────────────────────────────
  IQR  method  [lo, hi]          [-11,010.00,  33,030.00]
    → Outliers (IQR)             0 values  (0.00%)

 🏆 Extreme Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 largest:
    #1   22,020.00  [index 10035]
    #2   22,019.00  [index 20107]
    #3   22,018.00  [index 20122]
    #4   22,017.00  [index 20103]
    #5   22,016.00  [index 20102]
    #6   22,016.00  [index 20120]
    #7   22,015.00  [index 20109]
    #8   22,014.00  [index 20108]
    #9   22,013.00  [index 9992]
    #10  22,013.00  [index 20099]

  Top 10 smallest:
    #1   1.0000  [index 23116]
    #2   2.0000  [index 6593]
    #3   3.0000  [index 23288]
    #4   4.0000  [index 22020]
    #5   5.0000  [index 7379]
    #6   6.0000  [index 7383]
    #7   7.0000  [index 9671]
    #8   8.0000  [index 17926]
    #9   9.0000  [index 7291]
    #10  10.0000  [index 7367]

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
       2,651.00  [█████████████████████████] 100.0%  4
      17,918.00  [█████████████████████████] 100.0%  4
      11,370.00  [█████████████████████████] 100.0%  4
       2,819.00  [█████████████████████████] 100.0%  4
      21,304.00  [█████████████████████████] 100.0%  4
      19,113.00  [█████████████████████████] 100.0%  4
       9,326.00  [█████████████████████████] 100.0%  4
      12,891.00  [█████████████████████████] 100.0%  4
      10,183.00  [███████████████████░░░░░░]  75.0%  3
       6,715.00  [███████████████████░░░░░░]  75.0%  3

  Top 10 least frequent:
       3,494.00  [██████░░░░░░░░░░░░░░░░░░░]  25.0%  1
      17,085.00  [██████░░░░░░░░░░░░░░░░░░░]  25.0%  1
      17,084.00  [██████░░░░░░░░░░░░░░░░░░░]  25.0%  1
       3,516.00  [██████░░░░░░░░░░░░░░░░░░░]  25.0%  1
      10,390.00  [██████░░░░░░░░░░░░░░░░░░░]  25.0%  1
      17,082.00  [██████░░░░░░░░░░░░░░░░░░░]  25.0%  1
      17,080.00  [██████░░░░░░░░░░░░░░░░░░░]  25.0%  1
      17,079.00  [██████░░░░░░░░░░░░░░░░░░░]  25.0%  1
      17,077.00  [██████░░░░░░░░░░░░░░░░░░░]  25.0%  1
      11,688.00  [██████░░░░░░░░░░░░░░░░░░░]  25.0%  1

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Pulizia necessaria:**
- I ~6.958 null sono strutturali: anime non classificati da MAL (score assente o insufficiente)
- `dtype` float64 → convertire a `Int64` (nullable integer), dato che i valori sono interi

In [29]:
df_details['rank'] = df_details['rank'].astype('Int64')
print(f'rank dtype   : {df_details["rank"].dtype}')
print(f'Null residui : {df_details["rank"].isna().sum():,}')

rank dtype   : Int64
Null residui : 6,958

### 2.13 `popularity`, `members`, `favorites`

In [30]:
for col in ['popularity', 'members', 'favorites']:
    analyze(df_details[col])

════════════════════════════════════════════════════════════════════════════════
════════════════════  🔬  SERIES ANALYSIS  —  'popularity'  ═════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    popularity
  dtype                          int64
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           NUMERIC

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Zeros                          0  (0.00%)
  Positives                      28,955   (100.00%)
  Negatives                      0   (0.00%)
  Unique values                  21,954  (75.82%)

 📐 Descriptive Statistics
────────────────────────────────────────────────────────────────────────────────
  Min                            1
  Max                            28,999
  Range                          28,998
  Mean                           14,500.36
  Median                         14,497.00
  Mode(s)                        10,785, 15,862, 21,379
  Std Dev                        8,373.66
  Variance                       70,118,240
  Std Error (SEM)                49.2100
  IQR  (Q3 − Q1)                 14,507.00
  Q1  (25th pct)                 7,247.50
  Q3  (75th pct)                 21,754.50
  P5  ( 5th pct)                 1,450.70
  P95 (95th pct)                 27,549.00
  Coefficient of Variation       57.75%

 📈 Distribution Shape
────────────────────────────────────────────────────────────────────────────────
  Skewness                       0.0001  → Approximately symmetric

  Mean position within [min, max]:
  1  │──────────────────────◆─────────────────────│  28,999

 ✨ Value Distribution (sorted sparkline)
────────────────────────────────────────────────────────────────────────────────
  ▁▁▁▁▁▂▂▂▂▂▂▂▂▃▃▃▃▃▃▃▃▃▄▄▄▄▄▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇████
  Each char ≈ 482 value(s) | min=1 → max=28,999

 📉 Histogram
────────────────────────────────────────────────────────────────────────────────
        1.00 – 1450.90    │█████████████████████████████████████████████ 1448
     1450.90 – 2900.80    │█████████████████████████████████████████████ 1448
     2900.80 – 4350.70    │█████████████████████████████████████████████ 1450
     4350.70 – 5800.60    │█████████████████████████████████████████████ 1450
     5800.60 – 7250.50    │█████████████████████████████████████████████ 1447
     7250.50 – 8700.40    │█████████████████████████████████████████████ 1449
     8700.40 – 10150.30   │█████████████████████████████████████████████ 1444
    10150.30 – 11600.20   │█████████████████████████████████████████████ 1452
    11600.20 – 13050.10   │█████████████████████████████████████████████ 1445
    13050.10 – 14500.00   │█████████████████████████████████████████████ 1448
    14500.00 – 15949.90   │█████████████████████████████████████████████ 1440
    15949.90 – 17399.80   │█████████████████████████████████████████████ 1447
    17399.80 – 18849.70   │█████████████████████████████████████████████ 1450
    18849.70 – 20299.60   │█████████████████████████████████████████████ 1446
    20299.60 – 21749.50   │█████████████████████████████████████████████ 1447
    21749.50 – 23199.40   │█████████████████████████████████████████████ 1445
    23199.40 – 24649.30   │█████████████████████████████████████████████ 1449
    24649.30 – 26099.20   │█████████████████████████████████████████████ 1450
    26099.20 – 27549.10   │█████████████████████████████████████████████ 1454
    27549.10 – 28999.00   │█████████████████████████████████████████████ 1446

 🔍 Outlier Analysis
────────────────────────────────────────────────────────────────────────────────
  IQR  method  [lo, hi]          [-14,513.00,  43,515.00]
    → Outliers (IQR)             0 values  (0.00%)

 🏆 Extreme Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 largest:
    #1   28,999  [index 27903]
    #2   28,997  [index 22580]
    #3   28,995  [index 1676]
    #4   28,995  [index 13829]
    #5   28,993  [index 15901]
    #6   28,993  [index 27904]
    #7   28,992  [index 651]
    #8   28,991  [index 14014]
    #9   28,989  [index 1353]
    #10  28,989  [index 26780]

  Top 10 smallest:
    #1   1  [index 22010]
    #2   2  [index 4788]
    #3   3  [index 6593]
    #4   4  [index 17990]
    #5   5  [index 12300]
    #6   6  [index 23654]
    #7   7  [index 2633]
    #8   8  [index 9671]
    #9   9  [index 16821]
    #10  10  [index 24921]

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
         24,020  [█████████████████████████] 100.0%  5
         10,785  [█████████████████████████] 100.0%  5
         15,862  [█████████████████████████] 100.0%  5
         21,379  [█████████████████████████] 100.0%  5
         26,019  [█████████████████████████] 100.0%  5
         20,862  [████████████████████░░░░░]  80.0%  4
          6,847  [████████████████████░░░░░]  80.0%  4
         14,372  [████████████████████░░░░░]  80.0%  4
         14,977  [████████████████████░░░░░]  80.0%  4
         18,513  [████████████████████░░░░░]  80.0%  4

  Top 10 least frequent:
         24,773  [█████░░░░░░░░░░░░░░░░░░░░]  20.0%  1
          8,916  [█████░░░░░░░░░░░░░░░░░░░░]  20.0%  1
          4,680  [█████░░░░░░░░░░░░░░░░░░░░]  20.0%  1
          1,077  [█████░░░░░░░░░░░░░░░░░░░░]  20.0%  1
         21,427  [█████░░░░░░░░░░░░░░░░░░░░]  20.0%  1
         24,834  [█████░░░░░░░░░░░░░░░░░░░░]  20.0%  1
         27,775  [█████░░░░░░░░░░░░░░░░░░░░]  20.0%  1
         11,703  [█████░░░░░░░░░░░░░░░░░░░░]  20.0%  1
         13,183  [█████░░░░░░░░░░░░░░░░░░░░]  20.0%  1
         11,466  [█████░░░░░░░░░░░░░░░░░░░░]  20.0%  1

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════


════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'members'  ══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    members
  dtype                          int64
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           NUMERIC

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Zeros                          0  (0.00%)
  Positives                      28,955   (100.00%)
  Negatives                      0   (0.00%)
  Unique values                  12,276  (42.40%)

 📐 Descriptive Statistics
────────────────────────────────────────────────────────────────────────────────
  Min                            23
  Max                            4,230,312
  Range                          4,230,289
  Mean                           38,753.37
  Median                         1,077.00
  Mode(s)                        80
  Std Dev                        167,376.33
  Variance                       28,014,834,772
  Std Error (SEM)                983.6311
  IQR  (Q3 − Q1)                 8,960.50
  Q1  (25th pct)                 233.0000
  Q3  (75th pct)                 9,193.50
  P5  ( 5th pct)                 82.7000
  P95 (95th pct)                 182,254.70
  Coefficient of Variation       431.90%

 📈 Distribution Shape
────────────────────────────────────────────────────────────────────────────────
  Skewness                       9.8490  → Strongly right-skewed (long right tail)

  Mean position within [min, max]:
  23  │◆───────────────────────────────────────────│  4,230,312

 ✨ Value Distribution (sorted sparkline)
────────────────────────────────────────────────────────────────────────────────
  ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂▃
  Each char ≈ 482 value(s) | min=23 → max=4,230,312

 📉 Histogram
────────────────────────────────────────────────────────────────────────────────
       23.00 – 211537.45  │█████████████████████████████████████████████ 27690
   211537.45 – 423051.90  │█ 663
   423051.90 – 634566.35  │ 227
   634566.35 – 846080.80  │ 131
   846080.80 – 1057595.25 │ 78
  1057595.25 – 1269109.70 │ 48
  1269109.70 – 1480624.15 │ 24
  1480624.15 – 1692138.60 │ 23
  1692138.60 – 1903653.05 │ 25
  1903653.05 – 2115167.50 │ 10
  2115167.50 – 2326681.95 │ 12
  2326681.95 – 2538196.40 │ 6
  2538196.40 – 2749710.85 │ 5
  2749710.85 – 2961225.30 │ 3
  2961225.30 – 3172739.75 │ 3
  3172739.75 – 3384254.20 │ 3
  3384254.20 – 3595768.65 │ 2
  3595768.65 – 3807283.10 │ 0
  3807283.10 – 4018797.55 │ 0
  4018797.55 – 4230312.00 │ 2

 🔍 Outlier Analysis
────────────────────────────────────────────────────────────────────────────────
  IQR  method  [lo, hi]          [-13,207.75,  22,634.25]
    → Outliers (IQR)             5,042 values  (17.41%)

  Top 5 extreme IQR outliers (by abs value):
    [22010]  4,230,312
    [4788]  4,170,767
    [6593]  3,576,199
    [17990]  3,430,848
    [12300]  3,323,322

 🏆 Extreme Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 largest:
    #1   4,230,312  [index 22010]
    #2   4,170,767  [index 4788]
    #3   3,576,199  [index 6593]
    #4   3,430,848  [index 17990]
    #5   3,323,322  [index 12300]
    #6   3,232,300  [index 23654]
    #7   3,212,739  [index 2633]
    #8   3,080,867  [index 9671]
    #9   3,035,328  [index 16821]
    #10  2,984,661  [index 24921]

  Top 10 smallest:
    #1   23  [index 27903]
    #2   24  [index 13829]
    #3   24  [index 22580]
    #4   25  [index 1676]
    #5   25  [index 27904]
    #6   26  [index 15901]
    #7   27  [index 651]
    #8   27  [index 14014]
    #9   27  [index 22160]
    #10  27  [index 26780]

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
             80  [█████████████████████████] 100.0%  127
             83  [████████████████████████░]  96.1%  122
             82  [███████████████████████░░]  92.1%  117
             79  [███████████████████████░░]  92.1%  117
             78  [██████████████████████░░░]  88.2%  112
             84  [██████████████████████░░░]  86.6%  110
             81  [█████████████████████░░░░]  85.8%  109
             86  [████████████████████░░░░░]  81.9%  104
             77  [███████████████████░░░░░░]  78.0%  99
             75  [██████████████████░░░░░░░]  73.2%  93

  Top 10 least frequent:
          5,525  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.8%  1
         27,334  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.8%  1
        249,631  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.8%  1
         46,157  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.8%  1
         11,529  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.8%  1
         75,080  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.8%  1
          2,588  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.8%  1
         13,757  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.8%  1
         10,893  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.8%  1
        232,624  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.8%  1

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════


════════════════════════════════════════════════════════════════════════════════
═════════════════════  🔬  SERIES ANALYSIS  —  'favorites'  ═════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    favorites
  dtype                          int64
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           NUMERIC

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Zeros                          12,923  (44.63%)
  Positives                      16,032   (55.37%)
  Negatives                      0   (0.00%)
  Unique values                  1,984  (6.85%)

 📐 Descriptive Statistics
────────────────────────────────────────────────────────────────────────────────
  Min                            0
  Max                            243,358
  Range                          243,358
  Mean                           430.8490
  Median                         1.0000
  Mode(s)                        0
  Std Dev                        4,520.61
  Variance                       20,435,916
  Std Error (SEM)                26.5666
  IQR  (Q3 − Q1)                 17.0000
  Q1  (25th pct)                 0.0000
  Q3  (75th pct)                 17.0000
  P5  ( 5th pct)                 0.0000
  P95 (95th pct)                 806.9000
  Coefficient of Variation       1049.23%

 📈 Distribution Shape
────────────────────────────────────────────────────────────────────────────────
  Skewness                       29.2051  → Strongly right-skewed (long right tail)

  Mean position within [min, max]:
  0  │◆───────────────────────────────────────────│  243,358

 ✨ Value Distribution (sorted sparkline)
────────────────────────────────────────────────────────────────────────────────
  ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂
  Each char ≈ 482 value(s) | min=0 → max=243,358

 📉 Histogram
────────────────────────────────────────────────────────────────────────────────
        0.00 – 12167.90   │█████████████████████████████████████████████ 28742
    12167.90 – 24335.80   │ 106
    24335.80 – 36503.70   │ 51
    36503.70 – 48671.60   │ 14
    48671.60 – 60839.50   │ 14
    60839.50 – 73007.40   │ 6
    73007.40 – 85175.30   │ 7
    85175.30 – 97343.20   │ 6
    97343.20 – 109511.10  │ 0
   109511.10 – 121679.00  │ 3
   121679.00 – 133846.90  │ 0
   133846.90 – 146014.80  │ 0
   146014.80 – 158182.70  │ 0
   158182.70 – 170350.60  │ 0
   170350.60 – 182518.50  │ 1
   182518.50 – 194686.40  │ 1
   194686.40 – 206854.30  │ 1
   206854.30 – 219022.20  │ 0
   219022.20 – 231190.10  │ 1
   231190.10 – 243358.00  │ 2

 🔍 Outlier Analysis
────────────────────────────────────────────────────────────────────────────────
  IQR  method  [lo, hi]          [-25.5000,  42.5000]
    → Outliers (IQR)             5,336 values  (18.43%)

  Top 5 extreme IQR outliers (by abs value):
    [17919]  243,358
    [6593]  236,754
    [9671]  223,927
    [23288]  198,245
    [22010]  183,305

 🏆 Extreme Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 largest:
    #1   243,358  [index 17919]
    #2   236,754  [index 6593]
    #3   223,927  [index 9671]
    #4   198,245  [index 23288]
    #5   183,305  [index 22010]
    #6   181,989  [index 4788]
    #7   118,013  [index 16833]
    #8   114,139  [index 4091]
    #9   114,076  [index 22129]
    #10  94,186  [index 12360]

  Top 10 smallest:
    #1   0  [index 0]
    #2   0  [index 17]
    #3   0  [index 18]
    #4   0  [index 22]
    #5   0  [index 30]
    #6   0  [index 32]
    #7   0  [index 34]
    #8   0  [index 38]
    #9   0  [index 39]
    #10  0  [index 40]

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
              0  [█████████████████████████] 100.0%  12,923
              1  [█████░░░░░░░░░░░░░░░░░░░░]  20.6%  2,657
              2  [███░░░░░░░░░░░░░░░░░░░░░░]  10.4%  1,344
              3  [██░░░░░░░░░░░░░░░░░░░░░░░]   6.6%  859
              4  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.9%  639
              5  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.0%  513
              6  [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.3%  424
              7  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.7%  354
              8  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.4%  310
              9  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.1%  267

  Top 10 least frequent:
          1,621  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
          3,323  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
          4,204  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
          1,042  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
          1,494  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
          6,566  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
          8,120  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
         23,052  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
          1,742  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
          1,129  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
Nessun null, dtype già `int64`. Le distribuzioni sono fortemente asimmetriche (code lunghe verso destra), da tenere in considerazione nelle analisi.

In [31]:
# Nessuna operazione richiesta
for col in ['popularity', 'members', 'favorites']:
    print(f'Null in {col:<12}: {df_details[col].isna().sum()}')

Null in popularity  : 0
Null in members     : 0
Null in favorites   : 0

### 2.14 `genres`, `studios`, `themes`, `demographics`, `producers`, `licensors`, `streaming`

Colonne contenenti liste serializzate come stringhe Python (es. `"['Comedy', 'Drama']"`).

In [32]:
list_cols = ['genres', 'studios', 'themes', 'demographics', 'producers', 'licensors', 'streaming']
for col in list_cols:
    analyze(df_details[col])

════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'genres'  ═══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    genres
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  931  (3.22%)
  Duplicate values               28,024

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     2  chars
  Max length                     90  chars
  Mean length                    16.96  chars
  Median length                  13.0000  chars
  Std Dev length                 12.71
  IQR length                     14.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=90  ['Avant Garde', 'Award Winning', 'Drama', 'Mystery', 'Sci-Fi', 'Supern…
    #2   len=81  ['Adventure', 'Drama', 'Horror', 'Mystery', 'Sci-Fi', 'Supernatural', …
    #3   len=80  ['Action', 'Adventure', 'Drama', 'Horror', 'Mystery', 'Romance', 'Supe…
    #4   len=80  ['Action', 'Adventure', 'Drama', 'Horror', 'Mystery', 'Romance', 'Supe…
    #5   len=80  ['Avant Garde', 'Award Winning', 'Drama', 'Mystery', 'Supernatural', '…
    #6   len=80  ['Action', 'Award Winning', 'Drama', 'Mystery', 'Romance', 'Sci-Fi', '…
    #7   len=79  ['Action', 'Adventure', 'Comedy', 'Drama', 'Mystery', 'Sci-Fi', 'Super…
    #8   len=77  ['Adventure', 'Avant Garde', 'Award Winning', 'Mystery', 'Romance', 'S…
    #9   len=75  ['Award Winning', 'Drama', 'Mystery', 'Sci-Fi', 'Supernatural', 'Suspe…
    #10  len=74  ['Action', 'Adventure', 'Boys Love', 'Fantasy', 'Mystery', 'Supernatur…

  10 Shortest strings:
    #1   len=2  []
    #2   len=2  []
    #3   len=2  []
    #4   len=2  []
    #5   len=2  []
    #6   len=2  []
    #7   len=2  []
    #8   len=2  []
    #9   len=2  []
    #10  len=2  []

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        2.00 – 6.40       │██████████████████████████████████████████ 5983
        6.40 – 10.80      │█████████████████████████████████████████████ 6417
       10.80 – 15.20      │███████████████████████ 3242
       15.20 – 19.60      │███████████ 1509
       19.60 – 24.00      │██████████████████████████████ 4249
       24.00 – 28.40      │█████████████ 1900
       28.40 – 32.80      │███████████ 1524
       32.80 – 37.20      │███████████████ 2104
       37.20 – 41.60      │███ 453
       41.60 – 46.00      │██████ 896
       46.00 – 50.40      │██ 271
       50.40 – 54.80      │█ 178
       54.80 – 59.20      │█ 104
       59.20 – 63.60      │█ 76
       63.60 – 68.00      │ 20
       68.00 – 72.40      │ 16
       72.40 – 76.80      │ 5
       76.80 – 81.20      │ 7
       81.20 – 85.60      │ 0
       85.60 – 90.00      │ 1

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    []                          [█████████████████████████] 100.0%  5,983
    ['Comedy']                  [███████████░░░░░░░░░░░░░░]  45.2%  2,705
    ['Fantasy']                 [██████░░░░░░░░░░░░░░░░░░░]  24.9%  1,487
    ['Hentai']                  [█████░░░░░░░░░░░░░░░░░░░░]  21.8%  1,305
    ['Slice of Life']           [████░░░░░░░░░░░░░░░░░░░░░]  14.3%  854
    ['Avant Garde']             [███░░░░░░░░░░░░░░░░░░░░░░]  13.3%  795
    ['Drama']                   [███░░░░░░░░░░░░░░░░░░░░░░]  13.0%  778
    ['Action']                  [███░░░░░░░░░░░░░░░░░░░░░░]  11.0%  657
    ['Action', 'Adventure', '…  [███░░░░░░░░░░░░░░░░░░░░░░]  10.7%  639
    ['Adventure', 'Fantasy']    [██░░░░░░░░░░░░░░░░░░░░░░░]  10.0%  596

  Top 10 least frequent (rarest):
    ['Horror', 'Erotica']       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Action', 'Comedy', 'Hor…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Comedy', 'Supernatural'…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Action', 'Fantasy', 'Su…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Action', 'Comedy', 'Fan…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Action', 'Drama', 'Myst…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Award Winning', 'Comedy…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Avant Garde', 'Drama', …  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Action', 'Drama', 'Horr…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Action', 'Adventure', '…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                0  (0.0%)
  Contains uppercase             22,972  (79.3%)
  Contains lowercase             22,972  (79.3%)
  Contains whitespace            13,998  (48.3%)
  Contains special chars         28,955  (100.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    0
  Fully alphanumeric             0

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               491,089
  Unique characters              39
  Avg chars per value            16.96

 💬 Word / Token Analysis
────────────────────────────────────────────────────────────────────────────────
  Avg words per value            1.86
  Max words                      9
  Min words                      1

  Top 10 most common words:
    []                    [█████████████████████████] 100.0%  5,983
    ['Action',            [█████████████████████░░░░]  83.7%  5,008
    'Fantasy']            [█████████████░░░░░░░░░░░░]  50.5%  3,019
    ['Comedy',            [████████████░░░░░░░░░░░░░]  48.7%  2,912
    ['Comedy']            [███████████░░░░░░░░░░░░░░]  45.2%  2,705
    'Sci-Fi']             [███████████░░░░░░░░░░░░░░]  43.5%  2,603
    ['Adventure',         [████████░░░░░░░░░░░░░░░░░]  33.3%  1,993
    'Adventure',          [████████░░░░░░░░░░░░░░░░░]  30.3%  1,814
    of                    [███████░░░░░░░░░░░░░░░░░░]  26.7%  1,596
    'Comedy',             [███████░░░░░░░░░░░░░░░░░░]  26.1%  1,559

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════


════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'studios'  ══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    studios
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  1,910  (6.60%)
  Duplicate values               27,045

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     2  chars
  Max length                     157  chars
  Mean length                    10.84  chars
  Median length                  10.0000  chars
  Std Dev length                 9.52
  IQR length                     16.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=157  ['Sunrise', 'Khara', 'Studio Rikka', 'Bridge', 'Kamikaze Douga', 'Trig…
    #2   len=152  ['ufotable', 'Shaft', 'A-1 Pictures', 'SILVER LINK.', 'Lerche', 'Wit S…
    #3   len=147  ['Production I.G', 'David Production', 'Kinema Citrus', 'Anima', 'Kami…
    #4   len=121  ['Magic Bus', 'Studio Colorido', 'DandeLion Animation Studio', 'Studio…
    #5   len=114  ['Production I.G', 'Kinema Citrus', 'Kamikaze Douga', 'Trigger', 'Stud…
    #6   len=101  ['Studio Hibari', 'Shirogumi', 'Larx Entertainment', 'TriF Studio', 'S…
    #7   len=96  ['Nippon Animation', 'Gallop', 'TMS Entertainment', 'SynergySP', 'DLE'…
    #8   len=96  ['Gonzo', 'Gainax', 'Production I.G', 'Madhouse', 'Studio 4°C', 'Satel…
    #9   len=94  ['Zexcs', 'Studio Colorido', 'Studio Nanahoshi', 'team Yamahitsuji', '…
    #10  len=85  ['P.A. Works', 'Zexcs', 'Lapin Track', 'Studio Kafka', '100studio', 'S…

  10 Shortest strings:
    #1   len=2  []
    #2   len=2  []
    #3   len=2  []
    #4   len=2  []
    #5   len=2  []
    #6   len=2  []
    #7   len=2  []
    #8   len=2  []
    #9   len=2  []
    #10  len=2  []

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        2.00 – 9.75       │█████████████████████████████████████████████ 14432
        9.75 – 17.50      │██████████████████████ 7121
       17.50 – 25.25      │██████████████████ 5651
       25.25 – 33.00      │███ 803
       33.00 – 40.75      │██ 725
       40.75 – 48.50      │ 141
       48.50 – 56.25      │ 44
       56.25 – 64.00      │ 20
       64.00 – 71.75      │ 4
       71.75 – 79.50      │ 2
       79.50 – 87.25      │ 3
       87.25 – 95.00      │ 1
       95.00 – 102.75     │ 3
      102.75 – 110.50     │ 0
      110.50 – 118.25     │ 1
      118.25 – 126.00     │ 1
      126.00 – 133.75     │ 0
      133.75 – 141.50     │ 0
      141.50 – 149.25     │ 1
      149.25 – 157.00     │ 2

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    []                          [█████████████████████████] 100.0%  11,703
    ['Toei Animation']          [██░░░░░░░░░░░░░░░░░░░░░░░]   7.5%  882
    ['Sunrise']                 [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.8%  560
    ['J.C.Staff']               [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.5%  411
    ['TMS Entertainment']       [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.1%  365
    ['Madhouse']                [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.9%  345
    ['Shanghai Animation Film…  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.9%  343
    ['Studio Deen']             [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.6%  303
    ['Studio Pierrot']          [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.3%  273
    ['Production I.G']          [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.3%  272

  Top 10 least frequent (rarest):
    ['Niceboat Animation', 'G…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['WAO World', 'Studio Liv…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Flying Fish Studio', 'B…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Niceboat Animation', 'T…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Foch Film', 'Ai Si Anim…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Production GoodBook']     [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Studio March']            [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['TMS Entertainment', 'Ec…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Artland', 'G&G Directio…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['indigo line']             [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                819  (2.8%)
  Contains uppercase             16,907  (58.4%)
  Contains lowercase             15,356  (53.0%)
  Contains whitespace            10,954  (37.8%)
  Contains special chars         28,955  (100.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    0
  Fully alphanumeric             0

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               314,000
  Unique characters              79
  Avg chars per value            10.84

 💬 Word / Token Analysis
────────────────────────────────────────────────────────────────────────────────
  Avg words per value            1.53
  Max words                      18
  Min words                      1

  Top 10 most common words:
    []                    [█████████████████████████] 100.0%  11,703
    Animation']           [████░░░░░░░░░░░░░░░░░░░░░]  15.2%  1,778
    ['Studio              [████░░░░░░░░░░░░░░░░░░░░░]  14.5%  1,700
    Studio']              [██░░░░░░░░░░░░░░░░░░░░░░░]   8.2%  959
    ['Toei                [██░░░░░░░░░░░░░░░░░░░░░░░]   7.8%  914
    Animation             [██░░░░░░░░░░░░░░░░░░░░░░░]   6.2%  722
    Entertainment']       [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.9%  579
    ['Sunrise']           [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.8%  560
    Pictures']            [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.2%  489
    Production']          [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.7%  429

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════


════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'themes'  ═══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    themes
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  1,044  (3.61%)
  Duplicate values               27,911

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     2  chars
  Max length                     87  chars
  Mean length                    11.14  chars
  Median length                  9.0000  chars
  Std Dev length                 10.78
  IQR length                     14.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=87  ['Adult Cast', 'High Stakes Game', 'Organized Crime', 'Psychological',…
    #2   len=80  ['Adult Cast', 'Gore', 'Historical', 'Martial Arts', 'Psychological', …
    #3   len=73  ['Love Polygon', 'School', 'Time Travel', 'Urban Fantasy', 'Visual Art…
    #4   len=73  ['Adult Cast', 'Gore', 'Organized Crime', 'Psychological', 'Super Powe…
    #5   len=72  ['Adult Cast', 'Detective', 'Organized Crime', 'Super Power', 'Vampire…
    #6   len=70  ['Anthropomorphic', 'Love Polygon', 'Mahou Shoujo', 'Performing Arts']
    #7   len=70  ['Anthropomorphic', 'Love Polygon', 'Mahou Shoujo', 'Performing Arts']
    #8   len=69  ['Adult Cast', 'Gore', 'Historical', 'Isekai', 'Military', 'Samurai']
    #9   len=69  ['Adult Cast', 'Gore', 'Historical', 'Isekai', 'Military', 'Samurai']
    #10  len=69  ['Adult Cast', 'Gore', 'Historical', 'Isekai', 'Military', 'Samurai']

  10 Shortest strings:
    #1   len=2  []
    #2   len=2  []
    #3   len=2  []
    #4   len=2  []
    #5   len=2  []
    #6   len=2  []
    #7   len=2  []
    #8   len=2  []
    #9   len=2  []
    #10  len=2  []

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        2.00 – 6.25       │█████████████████████████████████████████████ 11818
        6.25 – 10.50      │██████████████████████████ 6748
       10.50 – 14.75      │████████ 2017
       14.75 – 19.00      │████████ 2098
       19.00 – 23.25      │████████ 2096
       23.25 – 27.50      │██████ 1675
       27.50 – 31.75      │████ 956
       31.75 – 36.00      │██ 467
       36.00 – 40.25      │██ 461
       40.25 – 44.50      │█ 257
       44.50 – 48.75      │█ 146
       48.75 – 53.00      │ 75
       53.00 – 57.25      │ 81
       57.25 – 61.50      │ 23
       61.50 – 65.75      │ 18
       65.75 – 70.00      │ 12
       70.00 – 74.25      │ 5
       74.25 – 78.50      │ 0
       78.50 – 82.75      │ 1
       82.75 – 87.00      │ 1

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    []                          [█████████████████████████] 100.0%  11,818
    ['Music']                   [████████░░░░░░░░░░░░░░░░░]  34.0%  4,015
    ['Anthropomorphic']         [██░░░░░░░░░░░░░░░░░░░░░░░]   7.8%  923
    ['School']                  [██░░░░░░░░░░░░░░░░░░░░░░░]   7.7%  912
    ['Historical']              [██░░░░░░░░░░░░░░░░░░░░░░░]   7.3%  858
    ['Mecha']                   [█░░░░░░░░░░░░░░░░░░░░░░░░]   5.2%  615
    ['Parody']                  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.7%  321
    ['Mythology']               [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.3%  276
    ['Super Power']             [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.3%  272
    ['Martial Arts']            [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.2%  258

  Top 10 least frequent (rarest):
    ['Adult Cast', 'Gore', 'S…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Adult Cast', 'Survival'…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Adult Cast', 'Historica…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Racing', 'Space', 'Supe…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Harem', 'Mahou Shoujo']   [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Psychological', 'Urban …  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Martial Arts', 'Mecha',…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Adult Cast', 'Historica…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Adult Cast', 'Mecha', '…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    ['Adult Cast', 'CGDCT', '…  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                0  (0.0%)
  Contains uppercase             17,137  (59.2%)
  Contains lowercase             17,104  (59.1%)
  Contains whitespace            7,361  (25.4%)
  Contains special chars         28,955  (100.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    0
  Fully alphanumeric             0

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               322,455
  Unique characters              52
  Avg chars per value            11.14

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════


════════════════════════════════════════════════════════════════════════════════
═══════════════════  🔬  SERIES ANALYSIS  —  'demographics'  ════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    demographics
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954

**Nessuna pulizia necessaria.**  
Nessun null in nessuna di queste colonne. Le liste vuote `[]` sono legittime (anime senza studio, senza streaming, ecc.). Il formato stringa viene mantenuto così com'è: è sufficiente per le analisi testuali e può essere deserializzato con `ast.literal_eval` quando serve.

In [33]:
# Nessuna operazione richiesta
list_cols = ['genres', 'studios', 'themes', 'demographics', 'producers', 'licensors', 'streaming']
for col in list_cols:
    print(f'Null in {col:<14}: {df_details[col].isna().sum()}')

Null in genres        : 0
Null in studios       : 0
Null in themes        : 0
Null in demographics  : 0
Null in producers     : 0
Null in licensors     : 0
Null in streaming     : 0

### 2.15 `source`

In [34]:
analyze(df_details['source'])

════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'source'  ═══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    source
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  17  (0.06%)
  Duplicate values               28,938

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     4  chars
  Max length                     12  chars
  Mean length                    7.28  chars
  Median length                  8.0000  chars
  Std Dev length                 2.11
  IQR length                     3.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=12  Picture book
    #2   len=12  Picture book
    #3   len=12  Picture book
    #4   len=12  Picture book
    #5   len=12  Visual novel
    #6   len=12  Visual novel
    #7   len=12  Visual novel
    #8   len=12  4-koma manga
    #9   len=12  Visual novel
    #10  len=12  Visual novel

  10 Shortest strings:
    #1   len=4  Game
    #2   len=4  Game
    #3   len=4  Game
    #4   len=4  Game
    #5   len=4  Game
    #6   len=4  Book
    #7   len=4  Game
    #8   len=4  Book
    #9   len=4  Book
    #10  len=4  Book

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        4.00 – 4.89       │██████ 1697
        4.89 – 5.78       │█████████████████████████████ 7931
        5.78 – 6.67       │ 0
        6.67 – 7.56       │██████████ 2794
        7.56 – 8.44       │█████████████████████████████████████████████ 12359
        8.44 – 9.33       │███ 955
        9.33 – 10.22      │ 0
       10.22 – 11.11      │█████ 1436
       11.11 – 12.00      │██████ 1783

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    Original                    [█████████████████████████] 100.0%  12,359
    Manga                       [███████████░░░░░░░░░░░░░░]  44.6%  5,508
    Unknown                     [██████░░░░░░░░░░░░░░░░░░░]  22.6%  2,794
    Game                        [███░░░░░░░░░░░░░░░░░░░░░░]  11.9%  1,473
    Other                       [███░░░░░░░░░░░░░░░░░░░░░░]  10.7%  1,326
    Light novel                 [██░░░░░░░░░░░░░░░░░░░░░░░]   9.7%  1,199
    Visual novel                [██░░░░░░░░░░░░░░░░░░░░░░░]   9.4%  1,160
    Novel                       [██░░░░░░░░░░░░░░░░░░░░░░░]   6.6%  820
    Web manga                   [█░░░░░░░░░░░░░░░░░░░░░░░░]   5.3%  654
    4-koma manga                [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.7%  339

  Top 10 least frequent (rarest):
    Radio                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.1%  14
    Card game                   [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.6%  79
    Web novel                   [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.8%  222
    Book                        [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.8%  224
    Mixed media                 [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.9%  237
    Music                       [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.1%  263
    Picture book                [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.3%  284
    4-koma manga                [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.7%  339
    Web manga                   [█░░░░░░░░░░░░░░░░░░░░░░░░]   5.3%  654
    Novel                       [██░░░░░░░░░░░░░░░░░░░░░░░]   6.6%  820

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                339  (1.2%)
  Contains uppercase             28,616  (98.8%)
  Contains lowercase             28,955  (100.0%)
  Contains whitespace            4,174  (14.4%)
  Contains special chars         339  (1.2%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    24,781
  Fully alphanumeric             24,781

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               210,660
  Unique characters              35
  Avg chars per value            7.28

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
Nessun null. I valori sono coerenti con la tassonomia MAL.

In [35]:
# Nessuna operazione richiesta
print(f'Null in source : {df_details["source"].isna().sum()}')
print(df_details['source'].value_counts())

Null in source : 0
source
Original        12359
Manga            5508
Unknown          2794
Game             1473
Other            1326
Light novel      1199
Visual novel     1160
Novel             820
Web manga         654
4-koma manga      339
Picture book      284
Music             263
Mixed media       237
Book              224
Web novel         222
Card game          79
Radio              14
Name: count, dtype: int64

### 2.16 `rating`

In [36]:
analyze(df_details['rating'])

════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'rating'  ═══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    rating
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,355  [█████████████████████████████░]  97.9%
  Null / NaN                     600  (2.07%)
  Empty strings                  0
  Unique values                  6  (0.02%)
  Duplicate values               28,349

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     11  chars
  Max length                     30  chars
  Mean length                    18.08  chars
  Median length                  13.0000  chars
  Std Dev length                 6.67
  IQR length                     13.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=30  R - 17+ (violence & profanity)
    #2   len=30  R - 17+ (violence & profanity)
    #3   len=30  R - 17+ (violence & profanity)
    #4   len=30  R - 17+ (violence & profanity)
    #5   len=30  R - 17+ (violence & profanity)
    #6   len=30  R - 17+ (violence & profanity)
    #7   len=30  R - 17+ (violence & profanity)
    #8   len=30  R - 17+ (violence & profanity)
    #9   len=30  R - 17+ (violence & profanity)
    #10  len=30  R - 17+ (violence & profanity)

  10 Shortest strings:
    #1   len=11  Rx - Hentai
    #2   len=11  Rx - Hentai
    #3   len=11  Rx - Hentai
    #4   len=11  Rx - Hentai
    #5   len=11  Rx - Hentai
    #6   len=11  Rx - Hentai
    #7   len=11  Rx - Hentai
    #8   len=11  Rx - Hentai
    #9   len=11  Rx - Hentai
    #10  len=11  Rx - Hentai

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
       11.00 – 11.95      │███████ 1583
       11.95 – 12.90      │███████████████████████████████████████ 9066
       12.90 – 13.85      │███████████████████ 4421
       13.85 – 14.80      │ 0
       14.80 – 15.75      │ 0
       15.75 – 16.70      │█████ 1229
       16.70 – 17.65      │ 0
       17.65 – 18.60      │ 0
       18.60 – 19.55      │ 0
       19.55 – 20.50      │ 0
       20.50 – 21.45      │ 0
       21.45 – 22.40      │ 0
       22.40 – 23.35      │ 0
       23.35 – 24.30      │ 0
       24.30 – 25.25      │█████████████████████████████████████████████ 10463
       25.25 – 26.20      │ 0
       26.20 – 27.15      │ 0
       27.15 – 28.10      │ 0
       28.10 – 29.05      │ 0
       29.05 – 30.00      │███████ 1593

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    PG-13 - Teens 13 or older   [█████████████████████████] 100.0%  10,463
    G - All Ages                [██████████████████████░░░]  86.6%  9,066
    PG - Children               [███████████░░░░░░░░░░░░░░]  42.3%  4,421
    R - 17+ (violence & profa…  [████░░░░░░░░░░░░░░░░░░░░░]  15.2%  1,593
    Rx - Hentai                 [████░░░░░░░░░░░░░░░░░░░░░]  15.1%  1,583
    R+ - Mild Nudity            [███░░░░░░░░░░░░░░░░░░░░░░]  11.7%  1,229

  Top 10 least frequent (rarest):
    R+ - Mild Nudity            [███░░░░░░░░░░░░░░░░░░░░░░]  11.7%  1,229
    Rx - Hentai                 [████░░░░░░░░░░░░░░░░░░░░░]  15.1%  1,583
    R - 17+ (violence & profa…  [████░░░░░░░░░░░░░░░░░░░░░]  15.2%  1,593
    PG - Children               [███████████░░░░░░░░░░░░░░]  42.3%  4,421
    G - All Ages                [██████████████████████░░░]  86.6%  9,066
    PG-13 - Teens 13 or older   [█████████████████████████] 100.0%  10,463

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                12,056  (42.5%)
  Contains uppercase             28,355  (100.0%)
  Contains lowercase             28,355  (100.0%)
  Contains whitespace            28,355  (100.0%)
  Contains special chars         28,355  (100.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    0
  Fully alphanumeric             0

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               512,707
  Unique characters              37
  Avg chars per value            18.08

 💬 Word / Token Analysis
────────────────────────────────────────────────────────────────────────────────
  Avg words per value            4.64
  Max words                      6
  Min words                      3

  Top 10 most common words:
    -                     [█████████████████████████] 100.0%  28,355
    PG-13                 [█████████░░░░░░░░░░░░░░░░]  36.9%  10,463
    Teens                 [█████████░░░░░░░░░░░░░░░░]  36.9%  10,463
    13                    [█████████░░░░░░░░░░░░░░░░]  36.9%  10,463
    or                    [█████████░░░░░░░░░░░░░░░░]  36.9%  10,463
    older                 [█████████░░░░░░░░░░░░░░░░]  36.9%  10,463
    G                     [████████░░░░░░░░░░░░░░░░░]  32.0%  9,066
    All                   [████████░░░░░░░░░░░░░░░░░]  32.0%  9,066
    Ages                  [████████░░░░░░░░░░░░░░░░░]  32.0%  9,066
    PG                    [████░░░░░░░░░░░░░░░░░░░░░]  15.6%  4,421

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
I ~600 null sono strutturali: anime senza classificazione per età registrata su MAL. I valori presenti (G, PG, PG-13, R-17+, R+, Rx) sono coerenti con la classificazione MAL.

In [37]:
# Nessuna operazione richiesta: i null sono strutturali
print(f'Null in rating : {df_details["rating"].isna().sum()}')
print(df_details['rating'].value_counts())

Null in rating : 600
rating
PG-13 - Teens 13 or older         10463
G - All Ages                       9066
PG - Children                      4421
R - 17+ (violence & profanity)     1593
Rx - Hentai                        1583
R+ - Mild Nudity                   1229
Name: count, dtype: int64

### 2.17 `episodes`

In [38]:
analyze(df_details['episodes'])

════════════════════════════════════════════════════════════════════════════════
═════════════════════  🔬  SERIES ANALYSIS  —  'episodes'  ══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    episodes
  dtype                          float64
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           NUMERIC

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,275  [█████████████████████████████░]  97.7%
  Null / NaN                     680  (2.35%)
  Zeros                          0  (0.00%)
  Positives                      28,275   (97.65%)
  Negatives                      0   (0.00%)
  Unique values                  261  (0.90%)

 📐 Descriptive Statistics
────────────────────────────────────────────────────────────────────────────────
  Min                            1.0000
  Max                            3,000.00
  Range                          2,999.00
  Mean                           14.1301
  Median                         2.0000
  Mode(s)                        1.0000
  Std Dev                        47.1614
  Variance                       2,224.20
  Std Error (SEM)                0.2805
  IQR  (Q3 − Q1)                 12.0000
  Q1  (25th pct)                 1.0000
  Q3  (75th pct)                 13.0000
  P5  ( 5th pct)                 1.0000
  P95 (95th pct)                 52.0000
  Coefficient of Variation       333.77%

 📈 Distribution Shape
────────────────────────────────────────────────────────────────────────────────
  Skewness                       24.2051  → Strongly right-skewed (long right tail)

  Mean position within [min, max]:
  1.0000  │◆───────────────────────────────────────────│  3,000.00

 ✨ Value Distribution (sorted sparkline)
────────────────────────────────────────────────────────────────────────────────
  ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂
  Each char ≈ 471 value(s) | min=1.0000 → max=3,000.00

 📉 Histogram
────────────────────────────────────────────────────────────────────────────────
        1.00 – 150.95     │█████████████████████████████████████████████ 28035
      150.95 – 300.90     │ 155
      300.90 – 450.85     │ 50
      450.85 – 600.80     │ 15
      600.80 – 750.75     │ 6
      750.75 – 900.70     │ 2
      900.70 – 1050.65    │ 2
     1050.65 – 1200.60    │ 0
     1200.60 – 1350.55    │ 2
     1350.55 – 1500.50    │ 2
     1500.50 – 1650.45    │ 1
     1650.45 – 1800.40    │ 3
     1800.40 – 1950.35    │ 1
     1950.35 – 2100.30    │ 0
     2100.30 – 2250.25    │ 0
     2250.25 – 2400.20    │ 0
     2400.20 – 2550.15    │ 0
     2550.15 – 2700.10    │ 0
     2700.10 – 2850.05    │ 0
     2850.05 – 3000.00    │ 1

 🔍 Outlier Analysis
────────────────────────────────────────────────────────────────────────────────
  IQR  method  [lo, hi]          [-17.0000,  31.0000]
    → Outliers (IQR)             3,035 values  (10.48%)

  Top 5 extreme IQR outliers (by abs value):
    [13697]  3,000.00
    [18525]  1,818.00
    [5259]  1,787.00
    [7808]  1,717.00
    [4660]  1,664.00

 🏆 Extreme Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 largest:
    #1   3,000.00  [index 13697]
    #2   1,818.00  [index 18525]
    #3   1,787.00  [index 5259]
    #4   1,717.00  [index 7808]
    #5   1,664.00  [index 4660]
    #6   1,565.00  [index 12550]
    #7   1,471.00  [index 14913]
    #8   1,428.00  [index 9245]
    #9   1,306.00  [index 12547]
    #10  1,274.00  [index 16157]

  Top 10 smallest:
    #1   1.0000  [index 0]
    #2   1.0000  [index 1]
    #3   1.0000  [index 2]
    #4   1.0000  [index 3]
    #5   1.0000  [index 4]
    #6   1.0000  [index 5]
    #7   1.0000  [index 6]
    #8   1.0000  [index 13]
    #9   1.0000  [index 14]
    #10  1.0000  [index 15]

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
         1.0000  [█████████████████████████] 100.0%  13,871
        12.0000  [████░░░░░░░░░░░░░░░░░░░░░]  16.8%  2,335
         2.0000  [███░░░░░░░░░░░░░░░░░░░░░░]  11.9%  1,651
        26.0000  [██░░░░░░░░░░░░░░░░░░░░░░░]   9.7%  1,344
        13.0000  [██░░░░░░░░░░░░░░░░░░░░░░░]   8.3%  1,145
        52.0000  [██░░░░░░░░░░░░░░░░░░░░░░░]   6.1%  850
         3.0000  [█░░░░░░░░░░░░░░░░░░░░░░░░]   5.5%  759
         4.0000  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.5%  628
         6.0000  [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.4%  471
        24.0000  [█░░░░░░░░░░░░░░░░░░░░░░░░]   2.8%  392

  Top 10 least frequent:
       196.0000  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
       215.0000  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
       214.0000  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
       138.0000  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
       418.0000  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
       620.0000  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
       126.0000  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
       530.0000  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
       720.0000  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
       520.0000  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Pulizia necessaria:**
- I ~680 null sono strutturali: anime in corso o con numero di episodi non ancora definito
- `dtype` float64 → convertire a `Int64` (nullable integer), dato che i valori sono interi

In [39]:
df_details['episodes'] = df_details['episodes'].astype('Int64')
print(f'episodes dtype   : {df_details["episodes"].dtype}')
print(f'Null residui     : {df_details["episodes"].isna().sum()}')
print(f'Range            : {df_details["episodes"].min()} – {df_details["episodes"].max()}')

episodes dtype   : Int64
Null residui     : 680
Range            : 1 – 3000

### 2.18 `season`

In [40]:
analyze(df_details['season'])

════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'season'  ═══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    season
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                6,266  [██████░░░░░░░░░░░░░░░░░░░░░░░░]  21.6%
  Null / NaN                     22,689  (78.36%)
  Empty strings                  0
  Unique values                  4  (0.01%)
  Duplicate values               6,262

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     4  chars
  Max length                     6  chars
  Mean length                    5.42  chars
  Median length                  6.0000  chars
  Std Dev length                 0.91
  IQR length                     2.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=6  spring
    #2   len=6  spring
    #3   len=6  winter
    #4   len=6  summer
    #5   len=6  winter
    #6   len=6  winter
    #7   len=6  spring
    #8   len=6  spring
    #9   len=6  summer
    #10  len=6  spring

  10 Shortest strings:
    #1   len=4  fall
    #2   len=4  fall
    #3   len=4  fall
    #4   len=4  fall
    #5   len=4  fall
    #6   len=4  fall
    #7   len=4  fall
    #8   len=4  fall
    #9   len=4  fall
    #10  len=4  fall

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        4.00 – 4.67       │██████████████████ 1825
        4.67 – 5.33       │ 0
        5.33 – 6.00       │█████████████████████████████████████████████ 4441

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    spring                      [█████████████████████████] 100.0%  1,972
    fall                        [███████████████████████░░]  92.5%  1,825
    winter                      [█████████████████░░░░░░░░]  66.0%  1,302
    summer                      [███████████████░░░░░░░░░░]  59.2%  1,167

  Top 10 least frequent (rarest):
    summer                      [███████████████░░░░░░░░░░]  59.2%  1,167
    winter                      [█████████████████░░░░░░░░]  66.0%  1,302
    fall                        [███████████████████████░░]  92.5%  1,825
    spring                      [█████████████████████████] 100.0%  1,972

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                0  (0.0%)
  Contains uppercase             0  (0.0%)
  Contains lowercase             6,266  (100.0%)
  Contains whitespace            0  (0.0%)
  Contains special chars         0  (0.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    6,266
  Fully alphanumeric             6,266

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               33,946
  Unique characters              14
  Avg chars per value            5.42

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
I ~22.689 null (~78%) sono strutturali: Movies, OVA, ONA, Music, CM e PV non appartengono a una stagione MAL. I quattro valori (`spring`, `summer`, `fall`, `winter`) sono coerenti.

In [41]:
# Nessuna operazione richiesta: i null sono strutturali
print(f'Null in season : {df_details["season"].isna().sum():,} ({df_details["season"].isna().mean()*100:.1f}%)')
print(df_details['season'].value_counts())

Null in season : 22,689 (78.4%)
season
spring    1972
fall      1825
winter    1302
summer    1167
Name: count, dtype: int64

### 2.19 `year`

In [42]:
analyze(df_details['year'])

════════════════════════════════════════════════════════════════════════════════
═══════════════════════  🔬  SERIES ANALYSIS  —  'year'  ════════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    year
  dtype                          float64
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           NUMERIC

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                6,266  [██████░░░░░░░░░░░░░░░░░░░░░░░░]  21.6%
  Null / NaN                     22,689  (78.36%)
  Zeros                          0  (0.00%)
  Positives                      6,266   (21.64%)
  Negatives                      0   (0.00%)
  Unique values                  66  (0.23%)

 📐 Descriptive Statistics
────────────────────────────────────────────────────────────────────────────────
  Min                            1,961.00
  Max                            2,026.00
  Range                          65.0000
  Mean                           2,010.03
  Median                         2,014.00
  Mode(s)                        2,023.00
  Std Dev                        13.2007
  Variance                       174.2587
  Std Error (SEM)                0.1668
  IQR  (Q3 − Q1)                 15.0000
  Q1  (25th pct)                 2,005.00
  Q3  (75th pct)                 2,020.00
  P5  ( 5th pct)                 1,980.00
  P95 (95th pct)                 2,025.00
  Coefficient of Variation       0.66%

 📈 Distribution Shape
────────────────────────────────────────────────────────────────────────────────
  Skewness                       -1.3120  → Strongly left-skewed (long left tail)

  Mean position within [min, max]:
  1,961.00  │─────────────────────────────────◆──────────│  2,026.00

 ✨ Value Distribution (sorted sparkline)
────────────────────────────────────────────────────────────────────────────────
  ▁▂▃▃▃▄▄▄▅▅▅▅▅▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇██████████
  Each char ≈ 104 value(s) | min=1,961.00 → max=2,026.00

 📉 Histogram
────────────────────────────────────────────────────────────────────────────────
     1961.00 – 1964.25    │ 11
     1964.25 – 1967.50    │██ 38
     1967.50 – 1970.75    │██ 47
     1970.75 – 1974.00    │██ 49
     1974.00 – 1977.25    │████ 95
     1977.25 – 1980.50    │███ 75
     1980.50 – 1983.75    │████ 96
     1983.75 – 1987.00    │████ 84
     1987.00 – 1990.25    │██████ 135
     1990.25 – 1993.50    │█████ 106
     1993.50 – 1996.75    │█████ 118
     1996.75 – 2000.00    │██████████ 219
     2000.00 – 2003.25    │████████████████ 359
     2003.25 – 2006.50    │████████████████████ 446
     2006.50 – 2009.75    │██████████████████████ 486
     2009.75 – 2013.00    │███████████████████████ 516
     2013.00 – 2016.25    │█████████████████████████████████████████████ 992
     2016.25 – 2019.50    │████████████████████████████████████ 791
     2019.50 – 2022.75    │████████████████████████████████ 701
     2022.75 – 2026.00    │█████████████████████████████████████████ 902

 🔍 Outlier Analysis
────────────────────────────────────────────────────────────────────────────────
  IQR  method  [lo, hi]          [1,982.50,  2,042.50]
    → Outliers (IQR)             374 values  (1.29%)

  Top 5 extreme IQR outliers (by abs value):
    [460]  1,982.00
    [1026]  1,982.00
    [1415]  1,982.00
    [4393]  1,982.00
    [6566]  1,982.00

 🏆 Extreme Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 largest:
    #1   2,026.00  [index 134]
    #2   2,026.00  [index 733]
    #3   2,026.00  [index 1152]
    #4   2,026.00  [index 1355]
    #5   2,026.00  [index 3361]
    #6   2,026.00  [index 4687]
    #7   2,026.00  [index 4700]
    #8   2,026.00  [index 4762]
    #9   2,026.00  [index 5459]
    #10  2,026.00  [index 5929]

  Top 10 smallest:
    #1   1,961.00  [index 10205]
    #2   1,962.00  [index 18377]
    #3   1,963.00  [index 5835]
    #4   1,963.00  [index 18135]
    #5   1,963.00  [index 21308]
    #6   1,963.00  [index 24408]
    #7   1,963.00  [index 24416]
    #8   1,964.00  [index 21]
    #9   1,964.00  [index 2324]
    #10  1,964.00  [index 22234]

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
       2,023.00  [█████████████████████████] 100.0%  284
       2,025.00  [█████████████████████████]  99.6%  283
       2,016.00  [█████████████████████████]  99.6%  283
       2,024.00  [█████████████████████████]  99.3%  282
       2,017.00  [█████████████████████████]  98.9%  281
       2,018.00  [█████████████████████████]  98.9%  281
       2,021.00  [██████████████████████░░░]  86.3%  245
       2,015.00  [██████████████████████░░░]  86.3%  245
       2,014.00  [█████████████████████░░░░]  84.9%  241
       2,022.00  [█████████████████████░░░░]  83.1%  236

  Top 10 least frequent:
       1,962.00  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.4%  1
       1,961.00  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.4%  1
       1,964.00  [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.4%  4
       1,963.00  [░░░░░░░░░░░░░░░░░░░░░░░░░]   1.8%  5
       1,966.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.9%  11
       1,965.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.2%  12
       1,968.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   4.9%  14
       1,967.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   5.3%  15
       1,972.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   5.3%  15
       1,969.00  [█░░░░░░░░░░░░░░░░░░░░░░░░]   5.6%  16

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Pulizia necessaria:**
- I null sono coerenti con quelli di `season` (stessa logica strutturale)
- `dtype` float64 → convertire a `Int64` (nullable integer)

In [43]:
df_details['year'] = df_details['year'].astype('Int64')
print(f'year dtype   : {df_details["year"].dtype}')
print(f'Null residui : {df_details["year"].isna().sum():,}')
print(f'Range        : {df_details["year"].min()} – {df_details["year"].max()}')

year dtype   : Int64
Null residui : 22,689
Range        : 1961 – 2026

### 2.20 `explicit_genres`

In [44]:
analyze(df_details['explicit_genres'])

════════════════════════════════════════════════════════════════════════════════
══════════════════  🔬  SERIES ANALYSIS  —  'explicit_genres'  ══════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    explicit_genres
  dtype                          str
  Shape                          28,955
  Index range                    0 … 28954
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     28,955
  Non-null values                28,955  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  1  (0.00%)
  Duplicate values               28,954

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     2  chars
  Max length                     2  chars
  Mean length                    2.00  chars
  Median length                  2.0000  chars
  Std Dev length                 0.00
  IQR length                     0.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=2  []
    #2   len=2  []
    #3   len=2  []
    #4   len=2  []
    #5   len=2  []
    #6   len=2  []
    #7   len=2  []
    #8   len=2  []
    #9   len=2  []
    #10  len=2  []

  10 Shortest strings:
    #1   len=2  []
    #2   len=2  []
    #3   len=2  []
    #4   len=2  []
    #5   len=2  []
    #6   len=2  []
    #7   len=2  []
    #8   len=2  []
    #9   len=2  []
    #10  len=2  []

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
  All strings have the same length. (2 chars)

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    []                          [█████████████████████████] 100.0%  28,955

  Top 10 least frequent (rarest):
    []                          [█████████████████████████] 100.0%  28,955

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                0  (0.0%)
  Contains uppercase             0  (0.0%)
  Contains lowercase             0  (0.0%)
  Contains whitespace            0  (0.0%)
  Contains special chars         28,955  (100.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    0
  Fully alphanumeric             0

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               57,910
  Unique characters              2
  Avg chars per value            2.00

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Pulizia necessaria:**
- La colonna contiene esclusivamente il valore `[]` (lista vuota) per tutte le righe → nessuna informazione utile
- Rimozione della colonna

In [45]:
print(f'Valori unici in explicit_genres: {df_details["explicit_genres"].unique()}')
df_details.drop(columns=['explicit_genres'], inplace=True)
print('Colonna explicit_genres rimossa.')

Valori unici in explicit_genres: <StringArray>
['[]']
Length: 1, dtype: str
Colonna explicit_genres rimossa.

### 2.21 Chiave primaria `mal_id`

Verifichiamo che `mal_id` sia ancora univoco dopo tutte le operazioni di pulizia.

In [46]:
n_pk_dup = df_details.duplicated(subset=['mal_id'], keep=False).sum()
print(f'Duplicati su mal_id: {n_pk_dup}')

if n_pk_dup > 0:
    print('→ Rimozione duplicati sulla chiave primaria...')
    df_details.drop_duplicates(subset=['mal_id'], keep='first', inplace=True)
    print(f'Righe dopo la rimozione: {len(df_details):,}')
else:
    print('→ Chiave primaria già univoca, nessuna operazione richiesta.')

Duplicati su mal_id: 0
→ Chiave primaria già univoca, nessuna operazione richiesta.

## 3. Data Cleaning

In [47]:
print('=== Riepilogo Dataset Pulito ===')
print(f'Righe originali      : {n_originale:>10,}')
print(f'Righe dopo cleaning  : {len(df_details):>10,}')
print(f'Righe rimosse totali : {n_originale - len(df_details):>10,}')
print()
print('Dtypes finali:')
print(df_details.dtypes)
print()
print('Valori mancanti residui:')
print(df_details.isnull().sum())

=== Riepilogo Dataset Pulito ===
Righe originali      :     28,955
Righe dopo cleaning  :     28,955
Righe rimosse totali :          0

Dtypes finali:
mal_id                          int64
title                             str
title_japanese                    str
url                               str
image_url                         str
type                              str
status                            str
score                         float64
scored_by                       Int64
start_date        datetime64[us, UTC]
end_date          datetime64[us, UTC]
synopsis                          str
rank                            Int64
popularity                      int64
members                         int64
favorites                       int64
genres                            str
studios                           str
themes                            str
demographics                      str
source                            str
rating                            str
episodes                        Int64
season                            str
year                            Int64
producers                         str
licensors                         str
streaming                         str
has_image                        bool
has_synopsis                     bool
dtype: object

Valori mancanti residui:
mal_id                0
title                 0
title_japanese      119
url                   0
image_url             0
type                 67
status                0
score             10073
scored_by         10073
start_date          851
end_date          17688
synopsis           5127
rank               6958
popularity            0
members               0
favorites             0
genres                0
studios               0
themes                0
demographics          0
source                0
rating              600
episodes            680
season            22689
year              22689
producers             0
licensors             0
streaming             0
has_image             0
has_synopsis          0
dtype: int64

In [48]:
df_details.head()

,mal_id,title,title_japanese,url,image_url,type,status,score,scored_by,start_date,...,source,rating,episodes,season,year,producers,licensors,streaming,has_image,has_synopsis
0,59356,-Socket-,-socket-,https://myanimelist.net/anime/59356/-Socket-,https://cdn.myanimelist.net/images/anime/1043/...,Movie,Finished Airing,NaN,<NA>,2010-01-01 00:00:00+00:00,...,Original,G - All Ages,1,NaN,<NA>,['Nagoya Zokei University'],[],[],True,True
1,56036,......,......,https://myanimelist.net/anime/56036/-,https://cdn.myanimelist.net/images/anime/1057/...,Music,Finished Airing,6.53,503,2023-06-11 00:00:00+00:00,...,Original,PG-13 - Teens 13 or older,1,NaN,<NA>,[],[],[],True,True
2,2928,.hack//G.U. Returner,.HACK//G.U. RETURNER,https://myanimelist.net/anime/2928/hack__GU_Re...,https://cdn.myanimelist.net/images/anime/1798/...,OVA,Finished Airing,6.65,9745,2007-01-18 00:00:00+00:00,...,Game,PG-13 - Teens 13 or older,1,NaN,<NA>,"['Bandai Visual', 'CyberConnect2']",[],[],True,True
3,3269,.hack//G.U. Trilogy,.hack//G.U. Trilogy,https://myanimelist.net/anime/3269/hack__GU_Tr...,https://cdn.myanimelist.net/images/anime/1566/...,Movie,Finished Airing,7.06,15373,2007-12-22 00:00:00+00:00,...,Game,PG-13 - Teens 13 or older,1,NaN,<NA>,['Bandai Visual'],"['Funimation', 'Bandai Entertainment']",[],True,True
4,4469,.hack//G.U. Trilogy: Parody Mode,.hack//G.U. Trilogy,https://myanimelist.net/anime/4469/hack__GU_Tr...,https://cdn.myanimelist.net/images/anime/10/86...,Special,Finished Airing,6.35,4317,2008-03-25 00:00:00+00:00,...,Game,PG-13 - Teens 13 or older,1,NaN,<NA>,['Bandai Visual'],[],[],True,True

## 4. Salvataggio dataset pulito

In [49]:
df_details.to_csv('../datasets_cleaned/details_clean.csv', index=False)
print('Salvato: datasets_cleaned/details_clean.csv')

Salvato: datasets_cleaned/details_clean.csv