# 08 – Person Details

Esplorazione e data cleaning del dataset `person_details.csv`.

**Colonne:**
| Colonna | Descrizione |
|---|---|
| `person_mal_id` | ID univoco della persona su MyAnimeList |
| `url` | URL della pagina MAL della persona |
| `website_url` | Sito web personale |
| `image_url` | URL dell'immagine del profilo |
| `name` | Nome completo |
| `given_name` | Nome proprio |
| `family_name` | Cognome |
| `birthday` | Data di nascita |
| `favorites` | Numero di utenti che l'hanno tra i preferiti |
| `relevant_location` | Posizione |

## 1. Import e caricamento dati
Importiamo le librerie necessarie e carichiamo il file csv. Facciamo una esplorazione generica per capire la struttura e le caratteristiche del dataset.

In [554]:
import pandas as pd
import numpy as np
from dataset_analyzer import analyze
df_pd = pd.read_csv('../datasets/person_details.csv')
print(f'Shape: {df_pd.shape}')
print()
df_pd.info()
df_pd.head()

Shape: (76699, 10)

<class 'pandas.DataFrame'>
RangeIndex: 76699 entries, 0 to 76698
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   person_mal_id      76699 non-null  int64
 1   url                76699 non-null  str
 2   website_url        17435 non-null  str
 3   image_url          76699 non-null  str
 4   name               76697 non-null  str
 5   given_name         46446 non-null  str
 6   family_name        58058 non-null  str
 7   birthday           17238 non-null  str
 8   favorites          76699 non-null  int64
 9   relevant_location  76699 non-null  str
dtypes: int64(2), str(8)
memory usage: 5.9 MB

,person_mal_id,url,website_url,image_url,name,given_name,family_name,birthday,favorites,relevant_location
0,1,https://myanimelist.net/people/1/Tomokazu_Seki,NaN,https://cdn.myanimelist.net/images/voiceactors...,Tomokazu Seki,智一,関,1972-09-08T00:00:00+00:00,6219,"Berlin, Germany"
1,2,https://myanimelist.net/people/2/Tomokazu_Sugita,https://agrs.co.jp/,https://cdn.myanimelist.net/images/voiceactors...,Tomokazu Sugita,智和,杉田,1980-10-11T00:00:00+00:00,47666,"Los Angeles, USA"
2,3,https://myanimelist.net/people/3/Satsuki_Yukino,NaN,https://cdn.myanimelist.net/images/voiceactors...,Satsuki Yukino,さつき,ゆきの,1970-05-25T00:00:00+00:00,1777,"Madrid, Spain"
3,4,https://myanimelist.net/people/4/Aya_Hirano,http://ayahirano.jp/,https://cdn.myanimelist.net/images/voiceactors...,Aya Hirano,綾,平野,1987-10-08T00:00:00+00:00,18374,"Paris, France"
4,5,https://myanimelist.net/people/5/Kenichi_Suzumura,https://intention-k.com,https://cdn.myanimelist.net/images/voiceactors...,Kenichi Suzumura,健一,鈴村,1974-09-12T00:00:00+00:00,5176,"Osaka, Japan"

## 1.2 Rimozione duplicati esatti

Con `relevant_location` rimossa, le righe che prima differivano solo per quella colonna diventano duplicati esatti. Rimuoviamo mantenendo solo la prima occorrenza.

In [555]:
n_originale = len(df_pd)

mask_dup = df_pd.duplicated(keep=False)
n_righe_coinvolte = mask_dup.sum()
n_gruppi = df_pd[mask_dup].duplicated(keep='first').sum()
n_tenute = n_righe_coinvolte - n_gruppi

print(f'Righe totali coinvolte in duplicazioni : {n_righe_coinvolte:,}')
print(f'  → prime occorrenze mantenute         : {n_tenute:,}')
print(f'  → occorrenze extra rimosse           : {n_gruppi:,}')
print()

df_pd.drop_duplicates(keep='first', inplace=True)
print(f'Righe prima della rimozione : {n_originale:,}')
print(f'Righe dopo la rimozione     : {len(df_pd):,}')

Righe totali coinvolte in duplicazioni : 6
  → prime occorrenze mantenute         : 3
  → occorrenze extra rimosse           : 3

Righe prima della rimozione : 76,699
Righe dopo la rimozione     : 76,696

## 2. Analisi colonna per colonna

### 2.1 `person_mal_id`

ID univoco della persona su MAL. È la **chiave primaria** del dataset. I valori duplicati **non sono attesi**.

In [556]:
analyze(df_pd['person_mal_id'])

  Nome serie                     person_mal_id
  dtype                          int64
  Dimensione                     76,696
  Range indice                   0 … 76698
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   76,696
  Valori non nulli               76,696  (100.00%)
  Null / NaN                     0  (0.00%)
  Zeri                           0  (0.00%)
  Positivi                       76,696   (100.00%)
  Negativi                       0   (0.00%)
  Valori unici                   76,594  (99.87%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            1
  Max                            90,015
  Range                          90,014
  Media                          48,631.73
  Mediana                        51,493.50
  Moda/e                         4,564, 6,638, 7,025
  Dev. standard                  26,142.85
  Varianza                       683,448,486
  Errore std (SEM)               94.3988
  IQR  (Q3 − Q1)                 42,959.75
  Q1  (25° pct)                  27,770.50
  Q3  (75° pct)                  70,730.25
  P5  ( 5° pct)                  4,179.75
  P95 (95° pct)                  86,049.25
  Coefficiente di variazione     53.76%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -36,669.12
  Soglia alta   (Q3 + 1.5×IQR)   135,169.88
  Outlier rilevati               0  (0.00%)

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  1 – 4,501                           4,121     5.4%
  4,501 – 9,002                       4,096     5.3%
  9,002 – 13,503                      3,920     5.1%
  13,503 – 18,003                     2,189     2.9%
  18,003 – 22,504                     2,221     2.9%
  22,504 – 27,005                     2,248     2.9%
  27,005 – 31,505                     2,250     2.9%
  31,505 – 36,006                     2,245     2.9%
  36,006 – 40,507                     4,151     5.4%
  40,507 – 45,008                     4,461     5.8%
  45,008 – 49,508                     4,460     5.8%
  49,508 – 54,009                     4,495     5.9%
  54,009 – 58,510                     4,485     5.8%
  58,510 – 63,010                     4,474     5.8%
  63,010 – 67,511                     4,496     5.9%
  67,511 – 72,012                     4,491     5.9%
  72,012 – 76,512                     4,501     5.9%
  76,512 – 81,013                     4,530     5.9%
  81,013 – 85,514                     4,494     5.9%
  85,514 – 90,015                     4,368     5.7%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   90,015
    #2   90,014
    #3   90,013
    #4   90,012
    #5   90,011
    #6   90,001
    #7   90,000
    #8   89,999
    #9   89,998
    #10  89,997

  I 10 più piccoli:
    #1   1
    #2   2
    #3   3
    #4   4
    #5   5
    #6   6
    #7   7
    #8   8
    #9   9
    #10  10

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                 4,564            3     0.0%
                 6,638            3     0.0%
                 7,025            3     0.0%
                 7,194            3     0.0%
                 8,074            3     0.0%
                 8,946            3     0.0%
                10,073            3     0.0%
                20,016            3     0.0%
                24,923            3     0.0%
                25,163            3     0.0%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                90,015            1     0.0%
                90,014            1     0.0%
                90,013            1     0.0%
                90,012            1     0.0%
                90,011            1     0.0%
                90,001            1     0.0%
                90,000            1     0.0%
                89,999            1     0.0%
                89,998            1     0.0%
                89,997            1     0.0%

**Osservazioni:**
- Nessun null
- Il dtype è già `int64` quindi nessuna conversione necessaria. 
- Si nota che 99.87% dei valori sono univoci. Stampiamo un campione per verificare i duplicati.

In [557]:
print(f'Null in person_mal_id      : {df_pd["person_mal_id"].isna().sum()}')
print(f'Duplicati in person_mal_id : {df_pd["person_mal_id"].duplicated().sum()}')

# Campione righe duplicate
mask_pk_dup = df_pd.duplicated(subset=['person_mal_id'], keep=False)
df_dup = df_pd[mask_pk_dup].sort_values('person_mal_id')
print(f'\nRighe coinvolte: {len(df_dup)} | person_mal_id unici duplicati: {df_dup["person_mal_id"].nunique()}')
df_dup.head(20)

Null in person_mal_id      : 0
Duplicati in person_mal_id : 102

Righe coinvolte: 183 | person_mal_id unici duplicati: 81

,person_mal_id,url,website_url,image_url,name,given_name,family_name,birthday,favorites,relevant_location
4170,4564,https://myanimelist.net/people/4564/Natsuko_Ta...,NaN,https://cdn.myanimelist.net/images/voiceactors...,Natsuko Takahashi,ナツコ,高橋,NaN,19,"Mumbai, India"
4171,4564,https://myanimelist.net/people/4564/Natsuko_Ta...,NaN,https://cdn.myanimelist.net/images/voiceactors...,Natsuko Takahashi,ナツコ,高橋,NaN,19,"Paris, France"
4172,4564,https://myanimelist.net/people/4564/Natsuko_Ta...,NaN,https://cdn.myanimelist.net/images/voiceactors...,Natsuko Takahashi,ナツコ,高橋,NaN,19,"Cape Town, South Africa"
6017,6638,https://myanimelist.net/people/6638/Toshio_Suzuki,NaN,https://cdn.myanimelist.net/images/voiceactors...,Toshio Suzuki,敏夫,鈴木,1948-08-19T00:00:00+00:00,354,"Madrid, Spain"
6018,6638,https://myanimelist.net/people/6638/Toshio_Suzuki,NaN,https://cdn.myanimelist.net/images/voiceactors...,Toshio Suzuki,敏夫,鈴木,1948-08-19T00:00:00+00:00,354,"Paris, France"
6019,6638,https://myanimelist.net/people/6638/Toshio_Suzuki,NaN,https://cdn.myanimelist.net/images/voiceactors...,Toshio Suzuki,敏夫,鈴木,1948-08-19T00:00:00+00:00,354,"Mumbai, India"
6379,7025,https://myanimelist.net/people/7025/Yoshiji_Ki...,NaN,https://cdn.myanimelist.net/images/voiceactors...,Yoshiji Kigami,益治,木上,1957-12-28T00:00:00+00:00,49,"Los Angeles, USA"
6380,7025,https://myanimelist.net/people/7025/Yoshiji_Ki...,NaN,https://cdn.myanimelist.net/images/voiceactors...,Yoshiji Kigami,益治,木上,1957-12-28T00:00:00+00:00,49,"Paris, France"
6381,7025,https://myanimelist.net/people/7025/Yoshiji_Ki...,NaN,https://cdn.myanimelist.net/images/voiceactors...,Yoshiji Kigami,益治,木上,1957-12-28T00:00:00+00:00,49,"Madrid, Spain"
6538,7194,https://myanimelist.net/people/7194/Youta_Tsur...,NaN,https://cdn.myanimelist.net/images/voiceactors...,Youta Tsuruoka,陽太,鶴岡,1959-04-28T00:00:00+00:00,448,"Chicago, USA"
6539,7194,https://myanimelist.net/people/7194/Youta_Tsur...,NaN,https://cdn.myanimelist.net/images/voiceactors...,Youta Tsuruoka,陽太,鶴岡,1959-04-28T00:00:00+00:00,448,"Paris, France"
6540,7194,https://myanimelist.net/people/7194/Youta_Tsur...,NaN,https://cdn.myanimelist.net/images/voiceactors...,Youta Tsuruoka,陽太,鶴岡,1959-04-28T00:00:00+00:00,448,"Rome, Italy"
7360,8074,https://myanimelist.net/people/8074/Jin_Aketagawa,NaN,https://cdn.myanimelist.net/images/voiceactors...,Jin Aketagawa,仁,明田川,1972-08-07T00:00:00+00:00,1326,"Chicago, USA"
7361,8074,https://myanimelist.net/people/8074/Jin_Aketagawa,NaN,https://cdn.myanimelist.net/images/voiceactors...,Jin Aketagawa,仁,明田川,1972-08-07T00:00:00+00:00,1326,"Berlin, Germany"
7362,8074,https://myanimelist.net/people/8074/Jin_Aketagawa,NaN,https://cdn.myanimelist.net/images/voiceactors...,Jin Aketagawa,仁,明田川,1972-08-07T00:00:00+00:00,1326,"Rome, Italy"
8166,8946,https://myanimelist.net/people/8946/Ayane,http://5pb.jp/ayane/,https://cdn.myanimelist.net/images/voiceactors...,Ayane,NaN,彩音,NaN,156,"London, UK"
8167,8946,https://myanimelist.net/people/8946/Ayane,http://5pb.jp/ayane/,https://cdn.myanimelist.net/images/voiceactors...,Ayane,NaN,彩音,NaN,156,"Sydney, Australia"
8168,8946,https://myanimelist.net/people/8946/Ayane,http://5pb.jp/ayane/,https://cdn.myanimelist.net/images/voiceactors...,Ayane,NaN,彩音,NaN,156,"Yokohama, Japan"
9225,10073,https://myanimelist.net/people/10073/Emily_Neves,https://www.linkedin.com/pub/emily-neves/20/3a...,https://cdn.myanimelist.net/images/voiceactors...,Emily Neves,NaN,NaN,1982-07-29T00:00:00+00:00,413,"Madrid, Spain"
9226,10073,https://myanimelist.net/people/10073/Emily_Neves,https://www.linkedin.com/pub/emily-neves/20/3a...,https://cdn.myanimelist.net/images/voiceactors...,Emily Neves,NaN,NaN,1982-07-29T00:00:00+00:00,413,"Cape Town, South Africa"

I duplicati consistono in righe in cui l'unico valore che cambia è `relevant_location`. Non possiamo rimuovere le righe in quanto non è possibile sapere quale location è quella corretta. In più, la presenza di questa colonna rompe la struttura della tabella dove ogni persona dovrebbe comparire in una sola riga dove la chiave primaria è   `person_mal_id`. Abbiamo deciso di rimuovere la colonna `relevant_location` e infine rimuovere le righe duplicate mantenendo solo la prima occorrenza.

In [558]:
# Rimozione colonna 
df_pd.drop(columns=['relevant_location'], inplace=True)

# Rimozione duplicati indotti (ora sono duplicati esatti)
n_prima = len(df_pd)
df_pd.drop_duplicates(subset=['person_mal_id'], keep='first', inplace=True)
df_pd.reset_index(drop=True, inplace=True)
print(f'Righe prima : {n_prima:,}')
print(f'Righe dopo  : {len(df_pd):,}')
print(f'Rimosse     : {n_prima - len(df_pd):,}')

Righe prima : 76,696
Righe dopo  : 76,594
Rimosse     : 102

### 2.2 `url`

URL della pagina MAL della persona. Ci aspettiamo unicità e nessun null. Utilizziamo `strip()` per rimuovere eventuali spazzi vuoti all inizio e fine del URL. Effetuiamo poi l'analisi usando la nostra libreria `dataset_analyzer` e facciamo un controllo sul format del URL. Controlliamo anche la consistenza `person_mal_id` ↔ `url`. L'URL contiene l'ID del personaggio nel percorso (`/people/{id}/`). Verifichiamo che l'ID estratto dall'URL corrisponda al valore di `person_mal_id` per ogni riga.

In [559]:
df_pd['url'] = df_pd['url'].str.strip()
analyze(df_pd['url'])

pattern = r'^https://myanimelist\.net/people/\d+/\S+$'
non_conformi = df_pd[~df_pd['url'].str.match(pattern)]
print(f'URL non conformi al formato atteso: {len(non_conformi)}')
if len(non_conformi) > 0:
    print(non_conformi[['person_mal_id', 'url', 'name']].to_string(index=True))

id_from_url = df_pd['url'].str.extract(r'/people/(\d+)/')[0].astype(int)
mismatch = (id_from_url != df_pd['person_mal_id'])
print(f'\nRighe con ID non coerente tra url e person_mal_id: {mismatch.sum()}')

  Nome serie                     url
  dtype                          str
  Dimensione                     76,594
  Range indice                   0 … 76593
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   76,594
  Valori non nulli               76,594  (100.00%)
  Null / NaN                     0  (0.00%)
    di cui stringhe vuote        0  (convertite a NULL)
  Valori unici                   76,594  (100.00%)
  Valori duplicati               0  (0.00%)

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  37  caratteri
  Lunghezza max                  84  caratteri
  Lunghezza media                48.91  caratteri
  Lunghezza mediana              49.0000  caratteri
  Dev. standard lunghezza        3.65
  IQR lunghezza                  4.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #   Lunghezza   Valore
  ───   ─────────   ───────────────────────────────────────────────────
   #1          84   https://myanimelist.net/people/58483/ichigo_from_K…
   #2          78   https://myanimelist.net/people/40094/Osaka_Sumiyos…
   #3          72   https://myanimelist.net/people/17181/Kisida_Kyodan…
   #4          71   https://myanimelist.net/people/85773/Shintenchi_Ka…
   #5          70   https://myanimelist.net/people/36549/Shounen_Shouj…
   #6          70   https://myanimelist.net/people/47495/Kamisama_Boku…
   #7          69   https://myanimelist.net/people/23501/Claudia_Patri…
   #8          69   https://myanimelist.net/people/63076/Bookcube_Netw…
   #9          68   https://myanimelist.net/people/9179/Domenico_Gaeta…
  #10          68   https://myanimelist.net/people/49563/Dai-616_Tokub…

  Le 10 stringhe più corte:
    #   Lunghezza   Valore
  ───   ─────────   ──────────────────────────────────────
   #1          37   https://myanimelist.net/people/4184/Q
   #2          38   https://myanimelist.net/people/898/Cho
   #3          38   https://myanimelist.net/people/6210/A9
   #4          38   https://myanimelist.net/people/7048/Bz
   #5          38   https://myanimelist.net/people/8223/De
   #6          38   https://myanimelist.net/people/8547/ED
   #7          38   https://myanimelist.net/people/12598/7
   #8          38   https://myanimelist.net/people/22689/3
   #9          38   https://myanimelist.net/people/23281/K
  #10          38   https://myanimelist.net/people/36692/M

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  37 – 39                               268     0.3%
  39 – 41                             2,550     3.3%
  41 – 44                             7,438     9.7%
  44 – 46                             6,630     8.7%
  46 – 48                            13,723    17.9%
  48 – 51                            28,220    36.8%
  51 – 53                            12,079    15.8%
  53 – 55                             4,122     5.4%
  55 – 58                             1,199     1.6%
  58 – 60                               196     0.3%
  60 – 62                                97     0.1%
  62 – 65                                43     0.1%
  65 – 67                                15     0.0%
  67 – 69                                 8     0.0%
  69 – 72                                 4     0.0%
  72 – 74                                 0     0.0%
  74 – 76                                 0     0.0%
  76 – 79                                 1     0.0%
  79 – 81                                 0     0.0%
  81 – 84                                 1     0.0%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                                                Conteggio      %
  ───────────────────────────────────────────────────   ─────────   ────
  https://myanimelist.net/people/1/Tomokazu_Seki                1   0.0%
  https://myanimelist.net/people/2/Tomokazu_Sugita              1   0.0%
  https://myanimelist.net/people/3/Satsuki_Yukino               1   0.0%
  https://myanimelist.net/people/4/Aya_Hirano                   1   0.0%
  https://myanimelist.net/people/5/Kenichi_Suzumura             1   0.0%
  https://myanimelist.net/people/6/Toshiyuki_Morikaw…           1   0.0%
  https://myanimelist.net/people/7/Eiji_Yanagisawa              1   0.0%
  https://myanimelist.net/people/8/Rie_Kugimiya                 1   0.0%
  https://myanimelist.net/people/9/Kotono_Mitsuishi             1   0.0%
  https://myanimelist.net/people/10/Johnny_Yong_Bosc…           1   0.0%

  I 10 meno frequenti (più rari):
  Valore                                                Conteggio      %
  ───────────────────────────────────────────────────   ─────────   ────
  https://myanimelist.net/people/90015/Daisuke_Tanig…           1   0.0%
  https://myanimelist.net/people/90014/Hirari                   1   0.0%
  https://myanimelist.net/people/90013/Tomoru_Emoto             1   0.0%
  https://myanimelist.net/people/90012/Pamon                    1   0.0%
  https://myanimelist.net/people/90011/Nanako_Kishim…           1   0.0%
  https://myanimelist.net/people/90001/Mizuha_Akatsu            1   0.0%
  https://myanimelist.net/people/90000/Akakage                  1   0.0%
  https://myanimelist.net/people/89999/Oneuldoyo                1   0.0%
  https://myanimelist.net/people/89998/Bamhaneul                1   0.0%
  https://myanimelist.net/people/89997/Bokja                    1   0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 76,594  (100.0%)
  Contiene maiuscole             75,579  (98.7%)
  Contiene minuscole             76,594  (100.0%)
  Contiene spazi                 0  (0.0%)
  Contiene caratteri speciali    76,594  (100.0%)
  Contiene URL                   76,594  (100.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

URL non conformi al formato atteso: 0

Righe con ID non coerente tra url e person_mal_id: 0

**Nessuna pulizia necessaria.**  
Nessun null, tutti gli URL sono unici e rispettano il pattern atteso (coerente con `person_mal_id` come chiave primaria).

### 2.3 `website_url`

Sito web personale della persona, campo **opzionale** su MAL. I null sono attesi in quanto alcune persone potrebbero non aver inserito il proprio sito. I duplicati sono possibili ma rari come per esempio più persone potrebbero condividere un sito.

In [560]:
df_pd['website_url'] = df_pd['website_url'].str.strip()
analyze(df_pd['website_url'])

# 1. Pattern: i valori non-null devono iniziare con http:// o https://
mask_invalid = df_pd['website_url'].notna() & ~df_pd['website_url'].str.match(r'^https?://')
print(f'URL senza protocollo http/https : {mask_invalid.sum()}')
if mask_invalid.sum() > 0:
    print(df_pd.loc[mask_invalid, ['person_mal_id', 'name', 'website_url']].to_string(index=True))

# 2. Valori anomali: presenza di spazi o assenza di punto (probabile non-URL)
mask_anomali = (df_pd['website_url'].notna()
                & (df_pd['website_url'].str.contains(r' ') | ~df_pd['website_url'].str.contains(r'\.')))
print(f'Valori anomali (spazi o senza punto) : {mask_anomali.sum()}')
if mask_anomali.sum() > 0:
    print(df_pd.loc[mask_anomali, ['person_mal_id', 'name', 'website_url']].to_string(index=True))

  Nome serie                     website_url
  dtype                          str
  Dimensione                     76,594
  Range indice                   0 … 76593
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   76,594
  Valori non nulli               17,408  (22.73%)
  Null / NaN                     59,186  (77.27%)
    di cui stringhe vuote        0  (convertite a NULL)
  Valori unici                   17,332  (22.63%)
  Valori duplicati               76  (0.10%)

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  9  caratteri
  Lunghezza max                  249  caratteri
  Lunghezza media                32.84  caratteri
  Lunghezza mediana              30.0000  caratteri
  Dev. standard lunghezza        11.44
  IQR lunghezza                  11.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #   Lunghezza   Valore
  ───   ─────────   ───────────────────────────────────────────────────
   #1         249   https://www.81produce.co.jp/actor_search/index.php…
   #2         233   https://www.google.com/url?sa=t&source=web&rct=j&u…
   #3         209   https://www.81produce.co.jp/actor_search/index.php…
   #4         209   https://www.81produce.co.jp/actor_search/index.php…
   #5         199   https://www.81produce.co.jp/dcms_plusdb/index.php/…
   #6         198   https://alyssamarek25.wixsite.com/website?fbclid=I…
   #7         192   https://www.81produce.co.jp/dcms_plusdb/index.php/…
   #8         191   https://www.81produce.co.jp/dcms_plusdb/index.php/…
   #9         166   https://hannahagglund.wixsite.com/hanna-h?fbclid=I…
  #10         154   https://www.haiyuza.net/%E4%BF%B3%E5%84%AA%E5%BA%A…

  Le 10 stringhe più corte:
    #   Lunghezza   Valore
  ───   ─────────   ──────────────
   #1           9   http://水鼠
   #2          10   http://N/A
   #3          10   http://CMJ
   #4          13   http://iku.vc
   #5          13   http://jo1.jp
   #6          14   http://muse.mu
   #7          14   http://syz.jp/
   #8          14   http://0m2.jp/
   #9          14   http://9mm.jp/
  #10          14   http://uki.jp/

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  9 – 21                              1,001     5.8%
  21 – 33                             9,749    56.0%
  33 – 45                             4,251    24.4%
  45 – 57                             1,825    10.5%
  57 – 69                               445     2.6%
  69 – 81                                85     0.5%
  81 – 93                                24     0.1%
  93 – 105                               10     0.1%
  105 – 117                               4     0.0%
  117 – 129                               0     0.0%
  129 – 141                               2     0.0%
  141 – 153                               1     0.0%
  153 – 165                               2     0.0%
  165 – 177                               1     0.0%
  177 – 189                               0     0.0%
  189 – 201                               4     0.0%
  201 – 213                               2     0.0%
  213 – 225                               0     0.0%
  225 – 237                               1     0.0%
  237 – 249                               1     0.0%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                                         Conteggio      %
  ────────────────────────────────────────────   ─────────   ────
  https://straykids.jype.com/                            9   0.1%
  http://www.nanabunnonijyuuni.com/artist/               8   0.0%
  https://mwamjapan.info/                                5   0.0%
  http://www.helloproject.com/c-ute/index.html           3   0.0%
  http://www.eonet.ne.jp/~fwkh4588/pairan.htm            3   0.0%
  http://fandc.co.jp/                                    3   0.0%
  http://www.ngy1.1st.ne.jp/~k2office/                   2   0.0%
  http://bnlyz.com/                                      2   0.0%
  http://sadistic-mode.or.tv/                            2   0.0%
  http://yutori.main.jp/                                 2   0.0%

  I 10 meno frequenti (più rari):
  Valore                                       Conteggio      %
  ──────────────────────────────────────────   ─────────   ────
  https://hirari.2-d.jp/                               1   0.0%
  http://www.redsight.net/                             1   0.0%
  https://manamikakudo.com/                            1   0.0%
  https://yukixrock0.amebaownd.com/                    1   0.0%
  https://gyunyuuu0123.wixsite.com/website             1   0.0%
  https://blog.naver.com/limeunsung1216                1   0.0%
  http://www.namazudou.com/                            1   0.0%
  https://blog.naver.com/kain_y552                     1   0.0%
  https://blog.naver.com/dnlclzmfovmxmdnjrtm           1   0.0%
  https://blog.naver.com/yoyo4117                      1   0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 4,849  (27.9%)
  Contiene maiuscole             644  (3.7%)
  Contiene minuscole             17,408  (100.0%)
  Contiene spazi                 14  (0.1%)
  Contiene caratteri speciali    17,408  (100.0%)
  Contiene URL                   17,406  (100.0%)
  Contiene @                     26  (0.1%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

URL senza protocollo http/https : 1
      person_mal_id         name                       website_url
3371           3655  Nana Shiiba  Http://nanakoro418.blog9.fc2.com
Valori anomali (spazi o senza punto) : 22
       person_mal_id                   name                                                                              website_url
1684            1756      Takayuki Sakazume                                             http://Takayuki Sakazume @ Production baobab
6666            7339       Hirohisa Tsuruta                                                                               http://N/A
8943            9791        Akiko Takeguchi                                               http://Akiko Takeguchi @ Production baobab
9217           10078             Ayaka Wada          http://twitter.com/ayakawada, http://ameblo.jp/wada-ayaka, http://s-mileage.jp/
9218           10079           Kanon Fukuda  http://www.twitter.com/kanonfukuda, http://ameblo.jp/kanon-fukuda, http://s-mileage.jp/
12394          14069         Toworu Kishiri                                                                          http://09280000
13933          17237           Scott Cargle                 http://www.imdb.com/name/nm0137099/, http://www.facebook.com/scottcargle
21362          32201             Mizunezumi                                                                                http://水鼠
24572          37661  Rodney Alan Greenblat                                        http://whimsyload.com/; http://www.rodneyfun.com/
29194          42301         Akihito Takara                                                              http://Sanzoku no Uta; 山賊の唄
32899          46053          Manuel Gimeno                                                               http://Instagram: @mg_dubb
37229          50421    Melissa Sternenberg                               http://fayettevillecomicshow.com › melissa-sternenberg-bio
37770          50962         Kulou Jingling                               http://Skeleton Wizard; Skeleton Fairy; 王 小磊; Xiaolei Wang
42483          55687            Maitê Cunha                                                            http://Instagram: @maitecunha
43384          56589           Effy Estrada                                                                      http://@EstradaEffy
44264          57479      Cassandra Valtier                                                                http://Ig: keiitygonzalez
45545          58765                MJ Choi                                                                               http://CMJ
46310          59534  Brandon Ortiz Santini                                                                   http://@SantiniBrandon
47659          60891    Fabián Rétiz García                                                                        http://@FabsRetiz
54718          67981         Botan Shishiro                                                                    http://@shishirobotan
54832          68095             Harusaruhi                                        http:// https://kamitsubaki.jp/artist/harusaruhi/
61601          74878               Ajigozen                                                               http://Iwashizukushi; 鰯づくし

- I null (59.186, ~77%) sono strutturali: la maggior parte delle persone non ha un sito web registrato su MAL.
- Risultano 22 righe con valori anomali che abbiamo deciso di tenere perchè non sono rilevanti per la nostra analisi statistica e per non perdere le informazioni delle altre colonne. 

**Nessuna pulizia necessaria.**

### 2.4 `image_url`

URL dell'immagine del profilo della persona su MAL. Effetuiamo l'analisi usando la nostra libreria `dataset_analyzer` dopo aver usato `strip()` per rimuovere spazi vuoti e facciamo poi un controllo sul format del URL.

In [561]:
df_pd['image_url'] = df_pd['image_url'].str.strip()
analyze(df_pd['image_url'])

pattern_img = r'^https://cdn\.myanimelist\.net/(images/voiceactors/\d+/\d+\.jpg|img/sp/icon/apple-touch-icon-256\.png)$'
non_conformi_img = df_pd[~df_pd['image_url'].str.match(pattern_img)]
print(f'Immagini non conformi al formato atteso: {len(non_conformi_img)}')
if len(non_conformi_img) > 0:
    print(non_conformi_img[['person_mal_id', 'name', 'image_url']].to_string(index=True))

  Nome serie                     image_url
  dtype                          str
  Dimensione                     76,594
  Range indice                   0 … 76593
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   76,594
  Valori non nulli               76,594  (100.00%)
  Null / NaN                     0  (0.00%)
    di cui stringhe vuote        0  (convertite a NULL)
  Valori unici                   28,429  (37.12%)
  Valori duplicati               48,165  (62.88%)

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  55  caratteri
  Lunghezza max                  64  caratteri
  Lunghezza media                61.75  caratteri
  Lunghezza mediana              64.0000  caratteri
  Dev. standard lunghezza        2.94
  IQR lunghezza                  6.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #   Lunghezza   Valore
  ───   ─────────   ───────────────────────────────────────────────────
   #1          64   https://cdn.myanimelist.net/img/sp/icon/apple-touc…
   #2          64   https://cdn.myanimelist.net/img/sp/icon/apple-touc…
   #3          64   https://cdn.myanimelist.net/img/sp/icon/apple-touc…
   #4          64   https://cdn.myanimelist.net/img/sp/icon/apple-touc…
   #5          64   https://cdn.myanimelist.net/img/sp/icon/apple-touc…
   #6          64   https://cdn.myanimelist.net/img/sp/icon/apple-touc…
   #7          64   https://cdn.myanimelist.net/img/sp/icon/apple-touc…
   #8          64   https://cdn.myanimelist.net/img/sp/icon/apple-touc…
   #9          64   https://cdn.myanimelist.net/img/sp/icon/apple-touc…
  #10          64   https://cdn.myanimelist.net/img/sp/icon/apple-touc…

  Le 10 stringhe più corte:
    #   Lunghezza   Valore
  ───   ─────────   ───────────────────────────────────────────────────
   #1          55   https://cdn.myanimelist.net/images/voiceactors/1/5…
   #2          55   https://cdn.myanimelist.net/images/voiceactors/3/6…
   #3          56   https://cdn.myanimelist.net/images/voiceactors/1/2…
   #4          56   https://cdn.myanimelist.net/images/voiceactors/1/1…
   #5          56   https://cdn.myanimelist.net/images/voiceactors/2/1…
   #6          56   https://cdn.myanimelist.net/images/voiceactors/3/3…
   #7          56   https://cdn.myanimelist.net/images/voiceactors/1/1…
   #8          56   https://cdn.myanimelist.net/images/voiceactors/1/2…
   #9          56   https://cdn.myanimelist.net/images/voiceactors/1/2…
  #10          56   https://cdn.myanimelist.net/images/voiceactors/1/2…

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  55 – 55                                 2     0.0%
  55 – 56                                59     0.1%
  56 – 57                             1,813     2.4%
  57 – 58                            26,556    34.7%
  58 – 59                                 0     0.0%
  59 – 60                                 0     0.0%
  60 – 61                                 0     0.0%
  61 – 62                                 0     0.0%
  62 – 63                                 0     0.0%
  63 – 64                            48,164    62.9%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                                                Conteggio       %
  ───────────────────────────────────────────────────   ─────────   ─────
  https://cdn.myanimelist.net/img/sp/icon/apple-touc…      48,164   62.9%
  https://cdn.myanimelist.net/images/voiceactors/3/1…           2    0.0%
  https://cdn.myanimelist.net/images/voiceactors/3/8…           2    0.0%
  https://cdn.myanimelist.net/images/voiceactors/1/8…           1    0.0%
  https://cdn.myanimelist.net/images/voiceactors/1/8…           1    0.0%
  https://cdn.myanimelist.net/images/voiceactors/1/7…           1    0.0%
  https://cdn.myanimelist.net/images/voiceactors/3/7…           1    0.0%
  https://cdn.myanimelist.net/images/voiceactors/1/7…           1    0.0%
  https://cdn.myanimelist.net/images/voiceactors/3/6…           1    0.0%
  https://cdn.myanimelist.net/images/voiceactors/2/1…           1    0.0%

  I 10 meno frequenti (più rari):
  Valore                                                Conteggio      %
  ───────────────────────────────────────────────────   ─────────   ────
  https://cdn.myanimelist.net/images/voiceactors/2/8…           1   0.0%
  https://cdn.myanimelist.net/images/voiceactors/3/8…           1   0.0%
  https://cdn.myanimelist.net/images/voiceactors/3/8…           1   0.0%
  https://cdn.myanimelist.net/images/voiceactors/2/8…           1   0.0%
  https://cdn.myanimelist.net/images/voiceactors/1/8…           1   0.0%
  https://cdn.myanimelist.net/images/voiceactors/2/8…           1   0.0%
  https://cdn.myanimelist.net/images/voiceactors/2/8…           1   0.0%
  https://cdn.myanimelist.net/images/voiceactors/3/8…           1   0.0%
  https://cdn.myanimelist.net/images/voiceactors/1/8…           1   0.0%
  https://cdn.myanimelist.net/images/voiceactors/2/8…           1   0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 76,594  (100.0%)
  Contiene maiuscole             0  (0.0%)
  Contiene minuscole             76,594  (100.0%)
  Contiene spazi                 0  (0.0%)
  Contiene caratteri speciali    76,594  (100.0%)
  Contiene URL                   76,594  (100.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

Immagini non conformi al formato atteso: 0

**Osservazioni:**  
- Non ci sono stringhe vuote o null. Tutta la colonna è popolata. 
- Ci sono 48.165 URL duplicati (62.88%). Tutti corrispondono a un link che porta a un'immagine placeholder. A ogni persona senza immagine reale viene assegnato il logo MAL. Non è un errore e non è necessaria nessuna pulizia. 
- Ci sono 28.429 URL unici (37.12%). Tutti le persone con immagine reale hanno un URL univoco.
- Tutte le URL seguono il formato corretto senza nessuna anomalia strutturale.
- Nella distribuzione delle lunghezze, le fasce 59–63 hanno 0 occorrenze, il che significa che le URL si dividono in due gruppi: percorso /images/characters/ (55–58 caratteri) e percorso placeholder /img/sp/icon/ (64 caratteri). 

**Nessuna pulizia necessaria**

### 2.5 `name`

Nome completo della persona. I duplicati sono possibili.

In [562]:
df_pd['name'] = df_pd['name'].str.strip()
analyze(df_pd['name'])

  Nome serie                     name
  dtype                          str
  Dimensione                     76,594
  Range indice                   0 … 76593
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   76,594
  Valori non nulli               76,592  (100.00%)
  Null / NaN                     2  (0.00%)
    di cui stringhe vuote        0  (convertite a NULL)
  Valori unici                   74,508  (97.28%)
  Valori duplicati               2,084  (2.72%)

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  1  caratteri
  Lunghezza max                  47  caratteri
  Lunghezza media                12.06  caratteri
  Lunghezza mediana              12.0000  caratteri
  Dev. standard lunghezza        3.65
  IQR lunghezza                  4.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #   Lunghezza   Valore
  ───   ─────────   ───────────────────────────────────────────────
   #1          47   ichigo from Kisida Kyodan & The Akebosi Rockets
   #2          41   Osaka Sumiyoshi Shounen Shoujo Gasshoudan
   #3          35   Kisida Kyodan & The Akebosi Rockets
   #4          34   Kamisama, Boku wa Kizuite Shimatta
   #5          34   Shintenchi Kaibyaku Shudan: Zigzag
   #6          33   Shounen Shoujo Gasshoudan Mizuumi
   #7          32   Domenico Gaetano Maria Donizetti
   #8          32   Claudia Patricia Chavarro Parada
   #9          32   Bookcube Networks Webtoon Studio
  #10          31   Fear, and Loathing in Las Vegas

  Le 10 stringhe più corte:
    #   Lunghezza   Valore
  ───   ─────────   ──────
   #1           1   Q
   #2           1   3
   #3           1   K
   #4           1   M
   #5           1   u
   #6           1   8
   #7           1   C
   #8           1   U
   #9           1   B
  #10           1   K

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  1 – 3                                 983     1.3%
  3 – 5                               3,961     5.2%
  5 – 7                               5,090     6.6%
  7 – 10                             11,328    14.8%
  10 – 12                            16,983    22.2%
  12 – 14                            19,307    25.2%
  14 – 17                            15,710    20.5%
  17 – 19                             2,284     3.0%
  19 – 21                               566     0.7%
  21 – 24                               201     0.3%
  24 – 26                               121     0.2%
  26 – 28                                29     0.0%
  28 – 30                                13     0.0%
  30 – 33                                11     0.0%
  33 – 35                                 3     0.0%
  35 – 37                                 0     0.0%
  37 – 40                                 0     0.0%
  40 – 42                                 1     0.0%
  42 – 44                                 0     0.0%
  44 – 47                                 1     0.0%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore              Conteggio      %
  ─────────────────   ─────────   ────
  Akira                       7   0.0%
  Yuu                         7   0.0%
  Yuuki Satou                 7   0.0%
  Jin                         6   0.0%
  Yuuki Hayashi               6   0.0%
  Hiroshi Takahashi           5   0.0%
  Mika                        5   0.0%
  Minami                      5   0.0%
  Nanao                       5   0.0%
  Keisuke Gotou               5   0.0%

  I 10 meno frequenti (più rari):
  Valore              Conteggio      %
  ─────────────────   ─────────   ────
  Daisuke Taniguchi           1   0.0%
  Hirari                      1   0.0%
  Tomoru Emoto                1   0.0%
  Pamon                       1   0.0%
  Nanako Kishimoto            1   0.0%
  Mizuha Akatsu               1   0.0%
  Akakage                     1   0.0%
  Oneuldoyo                   1   0.0%
  Bamhaneul                   1   0.0%
  Bokja                       1   0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 386  (0.5%)
  Contiene maiuscole             75,577  (98.7%)
  Contiene minuscole             75,312  (98.3%)
  Contiene spazi                 63,378  (82.7%)
  Contiene caratteri speciali    4,418  (5.8%)
  Contiene URL                   0  (0.0%)
  Contiene @                     16  (0.0%)
  Solo numerico                  56
  Solo alfabetico                12,122
  Solo alfanumerico              12,382

Analisi parole / token
────────────────────────────────────────────────────────────────────────────────

  Parole medie per valore        1.86
  Max parole                     8
  Min parole                     1

  Le 10 parole più comuni:
  Parola                  Conteggio
  ────────────────────   ──────────
  Kim                           456
  Lee                           390
  Satou                         380
  Yuuki                         379
  Akira                         367
  Suzuki                        364
  Yuu                           354
  Takahashi                     305
  Tanaka                        296
  Hiroshi                       284

**Osservazione:**  
- Ci sono 2 valori null. Li stampiamo per vedere se ci sono altri dati che possono essere utili. 
- Ci sono 2.084 duplicati. Stampiamo una parte per indagare meglio. 
- Ci sono nomi con un solo carattere, contenenti @ oppure interamente numerici. Stampiamo una parte per verificare se si tratta di errori.

In [563]:
# Null
null_name = df_pd[df_pd['name'].isna()]
print(f'Righe con name null: {len(null_name)}')
print(null_name.to_string(index=True))

# Duplicati
dup_name = df_pd[df_pd['name'].duplicated(keep=False)].sort_values('name')
print(f'\nRighe con name duplicato: {len(dup_name)}')
print(dup_name.head(20).to_string(index=True))

# Nomi da 1 carattere
singoli = df_pd[df_pd['name'].str.len() == 1]
print(f'\nNomi da 1 carattere: {len(singoli)}')
print(singoli.head(10).to_string(index=True))

# Nomi contenenti @
con_at = df_pd[df_pd['name'].str.contains('@|＠', regex=True, na=False)]
print(f"\nNomi contenenti '@': {len(con_at)}")
print(con_at.head(10).to_string(index=True))

# Nomi solo numerici
solo_num = df_pd[df_pd['name'].str.fullmatch(r'\d+', na=False)]
print(f'\nNomi solo numerici: {len(solo_num)}')
print(solo_num.head(10).to_string(index=True))

Righe con name null: 2
       person_mal_id                                        url website_url                                                         image_url name given_name family_name birthday  favorites
46633          59857  https://myanimelist.net/people/59857/None         NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png  NaN        NaN          のね      NaN          0
75815          89106  https://myanimelist.net/people/89106/NULL         NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png  NaN        NaN         NaN      NaN          0

Righe con name duplicato: 3805
       person_mal_id                                         url                         website_url                                                         image_url   name given_name family_name                   birthday  favorites
73307          86598     https://myanimelist.net/people/86598/Dd                                 NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png   .Dd.        NaN        .Dd.                        NaN          0
68770          82055     https://myanimelist.net/people/82055/Dd                                 NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png   .Dd.        NaN        .Dd.                        NaN          0
75037          88328     https://myanimelist.net/people/88328/23                                 NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png     23        NaN          23                        NaN          0
13992          17355     https://myanimelist.net/people/17355/23                                 NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png     23        NaN         NaN                        NaN          1
23850          36937     https://myanimelist.net/people/36937/23  http://candychapus.blog15.fc2.com/  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png     23        NaN         NaN                        NaN          1
57720          70990     https://myanimelist.net/people/70990/23                                 NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png     23        NaN          23                        NaN          0
52334          65589    https://myanimelist.net/people/65589/256                                 NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    256        NaN         256                        NaN          0
32156          45303    https://myanimelist.net/people/45303/256      https://256nigoroku.jimdo.com/        https://cdn.myanimelist.net/images/voiceactors/3/50468.jpg    256        NaN         NaN                        NaN          0
13502          16349    https://myanimelist.net/people/16349/310              http://nat.namaste.jp/        https://cdn.myanimelist.net/images/voiceactors/1/18809.jpg    310        NaN         310                        NaN          4
66763          80044    https://myanimelist.net/people/80044/310                                 NaN        https://cdn.myanimelist.net/images/voiceactors/1/82937.jpg    310        NaN         NaN                        NaN          0
47938          61170     https://myanimelist.net/people/61170/38                                 NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png     38        NaN          38                        NaN          1
71530          84818     https://myanimelist.net/people/84818/38                                 NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png     38        NaN          38                        NaN          0
19483          28433     https://myanimelist.net/people/28433/A1                http://initial-g.jp/  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png     A1        NaN         NaN                        NaN          1
58998          72269     https://myanimelist.net/people/72269/A1                                 NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png     A1        NaN          A1                        NaN          0
39928          53126     https://myanimelist.net/people/53126/A1                                 NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png     A1        NaN          A1                        NaN          4
15101          19613    https://myanimelist.net/people/19613/AAA                 http://avex.jp/aaa/        https://cdn.myanimelist.net/images/voiceactors/2/35411.jpg    AAA        NaN         AAA  2005-09-14T00:00:00+00:00         86
41348          54550    https://myanimelist.net/people/54550/AAA                                 NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    AAA        NaN         あああ                        NaN          0
31586          44728  https://myanimelist.net/people/44728/AKIRA                http://akira.pos.to/        https://cdn.myanimelist.net/images/voiceactors/1/50876.jpg  AKIRA        NaN       AKIRA                        NaN          2
55696          68962  https://myanimelist.net/people/68962/AKIRA                                 NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png  AKIRA        NaN         NaN                        NaN          0
25125          38215  https://myanimelist.net/people/38215/AKIRA            http://ameblo.jp/akiriot        https://cdn.myanimelist.net/images/voiceactors/3/41003.jpg  AKIRA        NaN       AKIRA  1987-03-15T00:00:00+00:00         18

Nomi da 1 carattere: 27
       person_mal_id                                     url                      website_url                                                         image_url name given_name family_name birthday  favorites
3839            4184   https://myanimelist.net/people/4184/Q    http://behindmoon.tripod.com/         https://cdn.myanimelist.net/images/voiceactors/2/6144.jpg    Q        NaN         NaN      NaN         12
16621          22689  https://myanimelist.net/people/22689/3                              NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    3        NaN         NaN      NaN          0
16917          23281  https://myanimelist.net/people/23281/K                              NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    K        NaN           K      NaN          1
23606          36692  https://myanimelist.net/people/36692/M                              NaN        https://cdn.myanimelist.net/images/voiceactors/2/56946.jpg    M        NaN         NaN      NaN          3
24689          37778  https://myanimelist.net/people/37778/u                              NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    u        NaN         NaN      NaN          0
32466          45616  https://myanimelist.net/people/45616/8                              NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    8        NaN         NaN      NaN          0
33378          46538  https://myanimelist.net/people/46538/C                              NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    C        NaN         NaN      NaN          1
36733          49924  https://myanimelist.net/people/49924/U  https://u-kumakichi.tumblr.com/  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    U        NaN           U      NaN          2
47020          60245  https://myanimelist.net/people/60245/B                              NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    B        NaN           B      NaN          0
47356          60588  https://myanimelist.net/people/60588/K                              NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    K        NaN          케이      NaN          0

Nomi contenenti '@': 18
       person_mal_id                                                      url                                    website_url                                                         image_url                 name given_name family_name                   birthday  favorites
11611          12596             https://myanimelist.net/people/12596/Tom-Hck                                            NaN        https://cdn.myanimelist.net/images/voiceactors/3/33089.jpg             Tom-H@ck        NaN         NaN  1985-05-13T00:00:00+00:00        144
17377          24203                https://myanimelist.net/people/24203/Maya                                            NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png                Ma@ya        NaN         ま@や                        NaN          0
18774          27009                 https://myanimelist.net/people/27009/CHR       http://char2v26shockingpink.web.fc2.com/  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png                 CH@R        NaN         NaN                        NaN          0
18836          27133   https://myanimelist.net/people/27133/NekorominShuujinP                         http://www.syujin.com/  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png   Nekoromin@ShuujinP    猫ロ眠@囚人P         NaN                        NaN          0
22709          34907               https://myanimelist.net/people/34907/Squat                                            NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png               Squat@        NaN      すくわっと＠                        NaN          0
23574          36641            https://myanimelist.net/people/36641/RyouRyou           http://facetoface765.blog23.fc2.com/  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png            Ryou@Ryou        NaN       りょう@涼                        NaN          0
23835          36922               https://myanimelist.net/people/36922/Akiha                                            NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png               Akiha@        NaN        あきは@                        NaN          0
24609          37698  https://myanimelist.net/people/37698/Philip_Ninj_Morzez                                            NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png  Philip Ninj@ Morzez      フィリップ   ニンジャ・モーゼズ                        NaN          1
28056          41157    https://myanimelist.net/people/41157/Maguro_NekoKaine                                            NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    Maguro Neko@Kaine        NaN     まぐろ猫＠恢猫                        NaN          0
36861          50053              https://myanimelist.net/people/50053/SUKE6＠  https://suke6a.wixsite.com/suke6a-information  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png               SUKE6＠        NaN      SUKE6＠                        NaN          1

Nomi solo numerici: 56
       person_mal_id                                         url             website_url                                                         image_url   name given_name family_name birthday  favorites
6690            7366     https://myanimelist.net/people/7366/888                     NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    888        NaN         888      NaN          1
11944          13143  https://myanimelist.net/people/13143/12012    http://www.12012.jp/        https://cdn.myanimelist.net/images/voiceactors/3/17595.jpg  12012        NaN       12012      NaN          7
13502          16349    https://myanimelist.net/people/16349/310  http://nat.namaste.jp/        https://cdn.myanimelist.net/images/voiceactors/1/18809.jpg    310        NaN         310      NaN          4
13689          16725    https://myanimelist.net/people/16725/029   http://029-oniku.com/  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    029        NaN         029      NaN          8
13992          17355     https://myanimelist.net/people/17355/23                     NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png     23        NaN         NaN      NaN          1
16621          22689      https://myanimelist.net/people/22689/3                     NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png      3        NaN         NaN      NaN          0
18942          27349    https://myanimelist.net/people/27349/144                     NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    144        NaN         NaN      NaN          1
18998          27461    https://myanimelist.net/people/27461/774                     NaN        https://cdn.myanimelist.net/images/voiceactors/2/59163.jpg    774        NaN         774      NaN        596
20436          30345    https://myanimelist.net/people/30345/566                     NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    566        NaN         NaN      NaN          0
21325          32127    https://myanimelist.net/people/32127/212                     NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    212        NaN         212      NaN          1

- I due valori nulli corrispondono a due profili vuoti che verranno rimossi. 
- Il resto dei valori corriponde a righe che contengono informazioni parzialmente mancanti. Prima di decidere se rimuoverli o meno, verifichiamo se compaiono in altri dataset come foreign keys. Le righe che non vengono mai referenziate, vengono rimosse.

In [564]:
# Rimozione righe con name null
print(f'Righe prima: {len(df_pd):,}')
df_pd.dropna(subset=['name'], inplace=True)
df_pd.reset_index(drop=True, inplace=True)
print(f'Righe dopo : {len(df_pd):,}')

# Verifica referenze degli ID anomali restanti negli altri dataset
from foreign_key_analyzer import check_pk_referenced

ids_anomali = pd.Series(
    list(
        set(singoli['person_mal_id'])
        | set(con_at['person_mal_id'])
        | set(solo_num['person_mal_id'])
        | set(dup_name['person_mal_id'])
    ),
    name='person_mal_id'
)

df_paw  = pd.read_csv('../datasets/person_anime_works.csv')
df_pvw  = pd.read_csv('../datasets/person_voice_works.csv')
df_pan  = pd.read_csv('../datasets/person_alternate_names.csv')
df_favs = pd.read_csv('../datasets/favs.csv')

mask_unreferenced = check_pk_referenced(
    parent   = ids_anomali,
    children = {
        'person_anime_works'     : df_paw['person_mal_id'],
        'person_voice_works'     : df_pvw['person_mal_id'],
        'person_alternate_names' : df_pan['person_mal_id'],
        'favs (people)'          : df_favs[df_favs['fav_type'] == 'people']['id'],
    },
    parent_df   = df_pd[df_pd['person_mal_id'].isin(ids_anomali)],
    sample_rows = 10
)
# Rimozione degli ID anomali non referenziati in nessuna tabella figlia
ids_da_rimuovere = ids_anomali[mask_unreferenced]
print(f'Righe prima della rimozione: {len(df_pd):,}')
df_pd = df_pd[~df_pd['person_mal_id'].isin(ids_da_rimuovere)]
df_pd.reset_index(drop=True, inplace=True)
print(f'Righe dopo la rimozione    : {len(df_pd):,}')
print(f'Righe rimosse              : {len(ids_da_rimuovere):,}')

Righe prima: 76,594
Righe dopo : 76,592

  Colonna PK  (tabella padre)         person_mal_id
  Tabelle figlie verificate           person_anime_works, person_voice_works, person_alternate_names, favs (people)
────────────────────────────────────────────────────────────────────────────────

Referenze per tabella figlia
────────────────────────────────────────────────────────────────────────────────

    person_anime_works                1,722 / 3,880 ID trovati  (44.4%)
    person_voice_works                557 / 3,880 ID trovati  (14.4%)
    person_alternate_names            545 / 3,880 ID trovati  (14.0%)
    favs (people)                     652 / 3,880 ID trovati  (16.8%)

Riepilogo globale
────────────────────────────────────────────────────────────────────────────────

  PK totali analizzati                3,880
  ✓  Referenziati in almeno 1 figlia  2,497  (64.4%)
  ✗  Non referenziati in nessuna      1,383  (35.6%)

ID non referenziati (rimovibili in sicurezza)
────────────────────────────────────────────────────────────────────────────────

  2015, 2145, 2180, 2230, 2254, 2330, 2389, 2678, 2687, 2766, 2773, 3090, 3101,
  3104, 3113, 3150, 3168, 3169, 3212, 3283
  … (+1363 altri)

Campione righe non referenziate (prime 10)
────────────────────────────────────────────────────────────────────────────────

      person_mal_id                                                   url                              website_url                                                         image_url              name given_name family_name                   birthday  favorites
1880           2015     https://myanimelist.net/people/2015/Yuu_Yamaguchi                                      NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png     Yuu Yamaguchi          優          山口                        NaN          0
1998           2145            https://myanimelist.net/people/2145/Mikasa                                      NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png            Mikasa        NaN          三笠                        NaN          0
2032           2180      https://myanimelist.net/people/2180/Ryou_Akizuki                                      NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png      Ryou Akizuki        りょう        あきづき                        NaN          7
2081           2230    https://myanimelist.net/people/2230/Kyouko_Negishi                                      NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    Kyouko Negishi       きょうこ         ねぎし                        NaN          3
2104           2254     https://myanimelist.net/people/2254/Shinya_Kaneko                                      NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png     Shinya Kaneko        しんや         かねこ                        NaN          2
2176           2330    https://myanimelist.net/people/2330/Tomohiro_Chiba                                      NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    Tomohiro Chiba         智宏          千葉                        NaN          0
2233           2389  https://myanimelist.net/people/2389/Miyuki_Kobayashi                                      NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png  Miyuki Kobayashi         深雪          小林  1964-03-10T00:00:00+00:00          4
2488           2678    https://myanimelist.net/people/2678/Chihiro_Tamaki  http://www.aa.alpha-net.ne.jp/nofuture/  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png    Chihiro Tamaki        ちひろ         たまき                        NaN          0
2497           2687       https://myanimelist.net/people/2687/Eiji_Kaneda                                      NaN  https://cdn.myanimelist.net/img/sp/icon/apple-touch-icon-256.png       Eiji Kaneda         榮路          金田                        NaN          0
2573           2766       https://myanimelist.net/people/2766/Yuri_Kimura                                      NaN        https://cdn.myanimelist.net/images/voiceactors/3/19635.jpg       Yuri Kimura         有里          木村                        NaN          0

Righe prima della rimozione: 76,592
Righe dopo la rimozione    : 75,211
Righe rimosse              : 1,383

### 2.6 `given_name`

Nome proprio in giapponese. I null sono strutturali: non disponibile per persone non giapponesi o quando non registrato su MAL.

In [565]:
df_pd['given_name'] = df_pd['given_name'].str.strip()
analyze(df_pd['given_name'])

  Nome serie                     given_name
  dtype                          str
  Dimensione                     75,211
  Range indice                   0 … 75210
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   75,211
  Valori non nulli               45,808  (60.91%)
  Null / NaN                     29,403  (39.09%)
    di cui stringhe vuote        0  (convertite a NULL)
  Valori unici                   22,014  (29.27%)
  Valori duplicati               23,794  (31.64%)

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  1  caratteri
  Lunghezza max                  28  caratteri
  Lunghezza media                2.18  caratteri
  Lunghezza mediana              2.0000  caratteri
  Dev. standard lunghezza        0.89
  IQR lunghezza                  1.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #   Lunghezza   Valore
  ───   ─────────   ────────────────────────────────────
   #1          28   ゴユナ (Japanese), 고윤하 (Korean)
   #2          24   Mayte Michelle Rodriguez
   #3          20   Coolest Guy on Earth
   #4          19   ナッシングス カーブド イン ストーン
   #5          18   Heidi Hynden Walch
   #6          18   アジアン・カンフー・ジェネレーション
   #7          18   ファルコム・サウンド・チーム・jdk
   #8          17   スクール フード パニッシュメント
   #9          17   Renato Rex Batera
  #10          16   Frank Andre Ware

  Le 10 stringhe più corte:
    #   Lunghezza   Valore
  ───   ─────────   ──────
   #1           1   綾
   #2           1   彰
   #3           1   藍
   #4           1   綾
   #5           1   愛
   #6           1   綾
   #7           1   潤
   #8           1   静
   #9           1   渉
  #10           1   剣

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  1 – 2                              34,297    74.9%
  2 – 3                               9,637    21.0%
  3 – 5                               1,564     3.4%
  5 – 6                                 120     0.3%
  6 – 7                                  66     0.1%
  7 – 9                                  65     0.1%
  9 – 10                                 15     0.0%
  10 – 11                                11     0.0%
  11 – 13                                13     0.0%
  13 – 14                                 5     0.0%
  14 – 15                                 3     0.0%
  15 – 17                                 5     0.0%
  17 – 18                                 3     0.0%
  18 – 19                                 1     0.0%
  19 – 21                                 1     0.0%
  21 – 22                                 0     0.0%
  22 – 23                                 0     0.0%
  23 – 25                                 1     0.0%
  25 – 26                                 0     0.0%
  26 – 28                                 1     0.0%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore   Conteggio      %
  ──────   ─────────   ────
  大輔            84   0.2%
  誠              78   0.2%
  愛              74   0.2%
  優              71   0.2%
  直樹            67   0.1%
  太郎            65   0.1%
  薫              63   0.1%
  ゆう            62   0.1%
  健              60   0.1%
  亮              58   0.1%

  I 10 meno frequenti (più rari):
  Valore         Conteggio      %
  ────────────   ─────────   ────
  ともる                 1   0.0%
  みづは                 1   0.0%
  홍태                   1   0.0%
  威戸れもね。           1   0.0%
  방랑                   1   0.0%
  聖也                   1   0.0%
  りぐ                   1   0.0%
  商鎬                   1   0.0%
  拓生                   1   0.0%
  羽也人                 1   0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 22  (0.0%)
  Contiene maiuscole             137  (0.3%)
  Contiene minuscole             76  (0.2%)
  Contiene spazi                 47  (0.1%)
  Contiene caratteri speciali    45,716  (99.8%)
  Contiene URL                   0  (0.0%)
  Contiene @                     1  (0.0%)
  Solo numerico                  1
  Solo alfabetico                78
  Solo alfanumerico              81

**Osservazioni:**  
- I null (~39%) sono strutturali e non richiedono intervento.  
- Dalla distribuzione delle lunghezze (min 1, max 28, media ~2.18) emergono valori anomali:  
  - stringhe con soli caratteri latini (il campo dovrebbe contenere kanji/kana);  
  - stringhe molto lunghe (> 15 car.) che non sembrano nomi propri;  
  - valori con parentesi che mescolano lingue o aggiungono annotazioni.  

Verifichiamo e puliamo.

In [566]:
# Stringhe con soli caratteri latini (attesi kanji/kana)
solo_latin_gn = df_pd[df_pd['given_name'].str.fullmatch(r'[A-Za-z\s\-\.]+', na=False)]
print(f'Solo caratteri latini: {len(solo_latin_gn)}')
print(solo_latin_gn[['person_mal_id', 'name', 'given_name']].head(15).to_string(index=True))

# Stringhe molto lunghe (> 15 caratteri)
lunghi_gn = df_pd[df_pd['given_name'].str.len() > 15]
print(f'Lunghezza > 15 caratteri: {len(lunghi_gn)}')
print(lunghi_gn[['person_mal_id', 'name', 'given_name']].head(15).to_string(index=True))

# Valori contenenti parentesi
con_par_gn = df_pd[df_pd['given_name'].str.contains(r'[\(\)\[\]]', na=False)]
print(f'Contenenti parentesi: {len(con_par_gn)}')
print(con_par_gn[['person_mal_id', 'name', 'given_name']].head(15).to_string(index=True))

Solo caratteri latini: 94
      person_mal_id                name                given_name
1273           1296           Joey Hood                      Joey
1342           1367     Peter Fernandez                     Peter
1711           1810        Hynden Walch        Heidi Hynden Walch
1717           1822  Michelle Rodriguez  Mayte Michelle Rodriguez
1720           1828         Dave Mallow           David J. Mallow
1726           1842          Andre Ware          Frank Andre Ware
2085           2238           Aoi Kujou                       AOI
4509           5048            Stan Lee            Stanley Martin
4776           5350  Phillip Wesolowski                   Phillip
5122           5739        Sunjun Hwang      Coolest Guy on Earth
5136           5754       Sound Horizon             Sound Horizon
5190           5816     Ilaria Graziano                         -
5653           6328    Thores Shibamoto                    Thores
6093           6806    Jonathan Diamani                  Jonathan
6675           7444        Izumi Oogami                     Izumi
Lunghezza > 15 caratteri: 12
       person_mal_id                       name                    given_name
1711            1810               Hynden Walch            Heidi Hynden Walch
1717            1822         Michelle Rodriguez      Mayte Michelle Rodriguez
1726            1842                 Andre Ware              Frank Andre Ware
4691            5251   Asian Kung-Fu Generation            アジアン・カンフー・ジェネレーション
5108            5725                  Younha Go  ゴユナ (Japanese), 고윤하 (Korean)
5122            5739               Sunjun Hwang          Coolest Guy on Earth
6735            7508     School Food Punishment             スクール フード パニッシュメント
11612          12738    Falcom Sound Team J.D.K            ファルコム・サウンド・チーム・jdk
15370          20572  Nothing's Carved in Stone           ナッシングス カーブド イン ストーン
16719          23343         GOING UNDER GROUND              ゴーイング・アンダー・グラウンド
29110          42741      9mm Parabellum Bullet              キューミリ パラベラム バレット
51309          65550                 Renato Rex             Renato Rex Batera
Contenenti parentesi: 3
       person_mal_id                 name                    given_name
5108            5725            Younha Go  ゴユナ (Japanese), 고윤하 (Korean)
12847          15327        Atsuro Watabe               渡部篤郎 (わたべ あつろう)
15114          20048  Team.Nekokan [Neko]                  Team.ねこかん[猫]

- Le stringhe con soli caratteri latini e quelle molto lunghe sono profili non giapponesi o voci di fantasia. Il campo `given_name` non è significativo per loro e quindi lo impostiamo a `null`.  
- I valori con parentesi rientrano nelle categorie precedenti (es. trascrizioni multi-lingua), trattati nello stesso modo.

In [567]:
# Maschera valori anomali in given_name
mask_anomali_gn = (
    df_pd['given_name'].str.fullmatch(r'[A-Za-z\s\-\.]+', na=False)   # solo Latin
    | (df_pd['given_name'].str.len() > 15)                                # troppo lunghi
    | df_pd['given_name'].str.contains(r'[\(\)\[\]]', na=False)       # parentesi
)

n_anomali = mask_anomali_gn.sum()
print(f'Valori anomali in given_name: {n_anomali}')

# Azzeriamo a NaN anziché rimuovere la riga: la persona può essere valida
df_pd.loc[mask_anomali_gn, 'given_name'] = np.nan
print(f'Null in given_name dopo pulizia: {df_pd["given_name"].isna().sum():,} ({df_pd["given_name"].isna().mean()*100:.1f}%)')

Valori anomali in given_name: 103
Null in given_name dopo pulizia: 29,506 (39.2%)

### 2.7 `family_name`

Cognome in giapponese (kanji/kana). Analogo a `given_name`, i null sono strutturali per le stesse ragioni.

In [568]:
df_pd['family_name'] = df_pd['family_name'].str.strip()
analyze(df_pd['family_name'])

  Nome serie                     family_name
  dtype                          str
  Dimensione                     75,211
  Range indice                   0 … 75210
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   75,211
  Valori non nulli               56,703  (75.39%)
  Null / NaN                     18,508  (24.61%)
    di cui stringhe vuote        0  (convertite a NULL)
  Valori unici                   27,273  (36.26%)
  Valori duplicati               29,430  (39.13%)

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  1  caratteri
  Lunghezza max                  31  caratteri
  Lunghezza media                2.37  caratteri
  Lunghezza mediana              2.0000  caratteri
  Dev. standard lunghezza        1.29
  IQR lunghezza                  0.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #   Lunghezza   Valore
  ───   ─────────   ────────────────────────────────────────────
   #1          31   Fear, and Loathing in Las Vegas
   #2          26   ichigo from 岸田教団&The明星ロケッツ
   #3          24   Survive Said The Prophet
   #4          23   テクノボーイズ パルクラフト グリーンファンド
   #5          22   STEREO DIVE FOUNDATION
   #6          21   Larval Stage Planning
   #7          21   ワグダグ フューチャリスティック ユニティ
   #8          21   Saulo Javan Lervolino
   #9          21   LonWatanuki&simejirow
  #10          20   UNISON SQUARE GARDEN

  Le 10 stringhe più corte:
    #   Lunghezza   Valore
  ───   ─────────   ──────
   #1           1   関
   #2           1   朴
   #3           1   岸
   #4           1   関
   #5           1   阪
   #6           1   泰
   #7           1   平
   #8           1   魚
   #9           1   南
  #10           1   堀

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  1 – 2                              43,849    77.3%
  2 – 4                               6,579    11.6%
  4 – 5                               4,627     8.2%
  5 – 7                                 657     1.2%
  7 – 8                                 606     1.1%
  8 – 10                                124     0.2%
  10 – 11                               143     0.3%
  11 – 13                                27     0.0%
  13 – 14                                39     0.1%
  14 – 16                                18     0.0%
  16 – 17                                16     0.0%
  17 – 19                                 6     0.0%
  19 – 20                                 3     0.0%
  20 – 22                                 4     0.0%
  22 – 23                                 2     0.0%
  23 – 25                                 1     0.0%
  25 – 26                                 1     0.0%
  26 – 28                                 0     0.0%
  28 – 29                                 0     0.0%
  29 – 31                                 1     0.0%

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore   Conteggio      %
  ──────   ─────────   ────
  佐藤           329   0.6%
  鈴木           315   0.6%
  김             311   0.5%
  이             253   0.4%
  田中           247   0.4%
  高橋           238   0.4%
  伊藤           234   0.4%
  山本           222   0.4%
  中村           219   0.4%
  小林           214   0.4%

  I 10 meno frequenti (più rari):
  Valore     Conteggio      %
  ────────   ─────────   ────
  ひらり             1   0.0%
  파몬               1   0.0%
  赤景               1   0.0%
  오늘도요           1   0.0%
  밤하늘             1   0.0%
  복자               1   0.0%
  그리다즈           1   0.0%
  구나               1   0.0%
  미르콘             1   0.0%
  월루눈             1   0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 228  (0.4%)
  Contiene maiuscole             1,269  (2.2%)
  Contiene minuscole             1,009  (1.8%)
  Contiene spazi                 251  (0.4%)
  Contiene caratteri speciali    55,337  (97.6%)
  Contiene URL                   0  (0.0%)
  Contiene @                     3  (0.0%)
  Solo numerico                  16
  Solo alfabetico                1,164
  Solo alfanumerico              1,262

**Osservazioni:**  
- I null (~24%) sono strutturali e non richiedono intervento.  
- Dalla distribuzione delle lunghezze (min 1, max 31, media ~2.37) emergono valori anomali:  
  - stringhe con soli caratteri latini (il campo dovrebbe contenere kanji/kana);  
  - stringhe molto lunghe (> 15 car.) con nomi di band o valori compositi;  
  - valori con parentesi che mescolano lingue o aggiungono annotazioni.  
Verifichiamo e puliamo.

In [569]:
# Stringhe con soli caratteri latini (attesi kanji/kana)
solo_latin_fn = df_pd[df_pd['family_name'].str.fullmatch(r'[A-Za-z\s\-\.]+', na=False)]
print(f'Solo caratteri latini: {len(solo_latin_fn)}')
print(solo_latin_fn[['person_mal_id', 'name', 'family_name']].head(15).to_string(index=True))

# Stringhe molto lunghe (> 15 caratteri)
lunghi_fn = df_pd[df_pd['family_name'].str.len() > 15]
print(f'Lunghezza > 15 caratteri: {len(lunghi_fn)}')
print(lunghi_fn[['person_mal_id', 'name', 'family_name']].head(15).to_string(index=True))

# Valori contenenti parentesi
con_par_fn = df_pd[df_pd['family_name'].str.contains(r'[\(\)\[\]]', na=False)]
print(f'Contenenti parentesi: {len(con_par_fn)}')
print(con_par_fn[['person_mal_id', 'name', 'family_name']].head(15).to_string(index=True))

Solo caratteri latini: 1342
      person_mal_id             name   family_name
219             223             Myco          myco
842             857             KENN          KENN
1273           1296        Joey Hood          Hood
1342           1367  Peter Fernandez     Fernandez
1747           1877            CLAMP         CLAMP
1869           2003              ZUN           ZUN
2190           2352              MEE           MEE
2348           2529     CJ Michalski  CJ Michalski
2509           2709            okama         okama
2674           2885              Key           Key
2752           2970        naked ape     naked ape
2811           3040            Meimu         MEIMU
2981           3246              Rem           Rem
3031           3303          Chi-Ran       CHI-RAN
3043           3316             RaTe          RaTe
Lunghezza > 15 caratteri: 34
       person_mal_id                             name                      family_name
7995            8878                  Dorian Harewood               W. Dorian Harewood
8747            9697            Plus-Tech Squeeze Box               プラスティック・スクイーズ・ボックス
11195          12304          Nikolai Rimsky-Korsakov                 Римский-Корсаков
11262          12373                 Little by Little                 little by little
11551          12674                 ANANT-GARDE EYES                 ANANT-GARDE EYES
12213          14001  Fear, and Loathing in Las Vegas  Fear, and Loathing in Las Vegas
12589          14783            Larval Stage Planning            Larval Stage Planning
16004          21883               Mix Speaker's,Inc.               Mix Speaker's,Inc.
16777          23461               fantasista utamaro               fantasista utamaro
17078          24075             UNISON SQUARE GARDEN             UNISON SQUARE GARDEN
18487          26977           STEREO DIVE FOUNDATION           STEREO DIVE FOUNDATION
19578          29237             Pay money To my Pain             Pay money To my Pain
21884          34003                People In The Box                People In The Box
22278          34811          Wagdug Futuristic Unity            ワグダグ フューチャリスティック ユニティ
22287          34829   Technoboys Pulcraft Green-Fund          テクノボーイズ パルクラフト グリーンファンド
Contenenti parentesi: 11
       person_mal_id          name       family_name
1821            1951    Bow Ditama            ぢたま(某)
3841            4232      LEN[A-7]          LEN[A-7]
20442          31001   Kyuubi(108)           九尾(108)
34335          48123      NormCore  NormCore (ノームコア)
35010          48803       LIPxLIP   LIP×LIP(リップリップ)
39195          53107      LEN[A-7]          LEN[A-7]
50196          64408       CodyLee       Cody・Lee(李)
55296          69620  Gas (Rokoru)          GAS(ろこる)
57201          71550    Arcana(mi)          あるかな(mi)
66373          80859      YASUHIRO      YASUHIRO(康寛)
73871          88510   Tan(bullet)         탄(bullet)

**Osservazioni:**  
- Le stringhe con soli caratteri latini e quelle oltre i 15 caratteri non sono cognomi giapponesi validi quindi li impostiamo a `null`.  
- I valori con parentesi rientrano nelle stesse categorie (valori compositi o multi-lingua), trattati nello stesso modo.

In [570]:
# Maschera valori anomali in family_name
mask_anomali_fn = (
    df_pd['family_name'].str.fullmatch(r'[A-Za-z\s\-\.]+', na=False)   # solo Latin
    | (df_pd['family_name'].str.len() > 15)                              # troppo lunghi
    | df_pd['family_name'].str.contains(r'[\(\)\[\]]', na=False)        # parentesi
)

n_anomali_fn = mask_anomali_fn.sum()
print(f'Valori anomali in family_name: {n_anomali_fn}')

df_pd.loc[mask_anomali_fn, 'family_name'] = np.nan
print(f'Null in family_name dopo pulizia: {df_pd["family_name"].isna().sum():,} ({df_pd["family_name"].isna().mean()*100:.1f}%)')

Valori anomali in family_name: 1366
Null in family_name dopo pulizia: 19,874 (26.4%)

### 2.8 `birthday`

Data di nascita come stringa ISO 8601 con timezone UTC, campo **opzionale**. I null sono strutturali: molte persone non rendono pubblica la data di nascita su MAL. Richiede conversione a `datetime64` e verifica di date implausibili.

In [571]:
df_pd['birthday'] = df_pd['birthday'].str.strip()
analyze(df_pd['birthday'])

  Nome serie                     birthday
  dtype                          str
  Dimensione                     75,211
  Range indice                   0 … 75210
  Tipo                           STRINGA / OGGETTO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   75,211
  Valori non nulli               17,154  (22.81%)
  Null / NaN                     58,057  (77.19%)
    di cui stringhe vuote        0  (convertite a NULL)
  Valori unici                   12,348  (16.42%)
  Valori duplicati               4,806  (6.39%)

Analisi lunghezza stringhe
────────────────────────────────────────────────────────────────────────────────

  Lunghezza min                  25  caratteri
  Lunghezza max                  25  caratteri
  Lunghezza media                25.00  caratteri
  Lunghezza mediana              25.0000  caratteri
  Dev. standard lunghezza        0.00
  IQR lunghezza                  0.0000

Valori di lunghezza estrema
────────────────────────────────────────────────────────────────────────────────

  Le 10 stringhe più lunghe:
    #   Lunghezza   Valore
  ───   ─────────   ─────────────────────────
   #1          25   1972-09-08T00:00:00+00:00
   #2          25   1980-10-11T00:00:00+00:00
   #3          25   1970-05-25T00:00:00+00:00
   #4          25   1987-10-08T00:00:00+00:00
   #5          25   1974-09-12T00:00:00+00:00
   #6          25   1967-01-26T00:00:00+00:00
   #7          25   1967-08-22T00:00:00+00:00
   #8          25   1979-05-30T00:00:00+00:00
   #9          25   1967-12-08T00:00:00+00:00
  #10          25   1976-01-06T00:00:00+00:00

  Le 10 stringhe più corte:
    #   Lunghezza   Valore
  ───   ─────────   ─────────────────────────
   #1          25   1972-09-08T00:00:00+00:00
   #2          25   1980-10-11T00:00:00+00:00
   #3          25   1970-05-25T00:00:00+00:00
   #4          25   1987-10-08T00:00:00+00:00
   #5          25   1974-09-12T00:00:00+00:00
   #6          25   1967-01-26T00:00:00+00:00
   #7          25   1967-08-22T00:00:00+00:00
   #8          25   1979-05-30T00:00:00+00:00
   #9          25   1967-12-08T00:00:00+00:00
  #10          25   1976-01-06T00:00:00+00:00

Distribuzione lunghezze
────────────────────────────────────────────────────────────────────────────────

  Tutte le stringhe hanno la stessa lunghezza. (25 caratteri)

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
  Valore                      Conteggio      %
  ─────────────────────────   ─────────   ────
  1987-03-17T00:00:00+00:00           7   0.0%
  1982-09-03T00:00:00+00:00           6   0.0%
  1968-07-13T00:00:00+00:00           6   0.0%
  1980-01-28T00:00:00+00:00           6   0.0%
  1981-01-28T00:00:00+00:00           6   0.0%
  1976-11-05T00:00:00+00:00           6   0.0%
  1990-08-20T00:00:00+00:00           6   0.0%
  1994-03-23T00:00:00+00:00           6   0.0%
  1977-08-05T00:00:00+00:00           5   0.0%
  1971-02-07T00:00:00+00:00           5   0.0%

  I 10 meno frequenti (più rari):
  Valore                      Conteggio      %
  ─────────────────────────   ─────────   ────
  1892-02-01T00:00:00+00:00           1   0.0%
  1979-12-30T00:00:00+00:00           1   0.0%
  1987-05-19T00:00:00+00:00           1   0.0%
  1962-08-06T00:00:00+00:00           1   0.0%
  1998-03-24T00:00:00+00:00           1   0.0%
  1995-04-12T00:00:00+00:00           1   0.0%
  2001-06-25T00:00:00+00:00           1   0.0%
  1996-08-25T00:00:00+00:00           1   0.0%
  1970-10-05T00:00:00+00:00           1   0.0%
  1993-02-03T00:00:00+00:00           1   0.0%

Analisi pattern / contenuto
────────────────────────────────────────────────────────────────────────────────

  Contiene cifre                 17,154  (100.0%)
  Contiene maiuscole             17,154  (100.0%)
  Contiene minuscole             0  (0.0%)
  Contiene spazi                 0  (0.0%)
  Contiene caratteri speciali    17,154  (100.0%)
  Contiene URL                   0  (0.0%)
  Contiene @                     0  (0.0%)
  Solo numerico                  0
  Solo alfabetico                0
  Solo alfanumerico              0

**Osservazioni:**  
- I valori sono stringhe che convertiamo a `datetime64`.
- I null (~78%) sono strutturali: date di nascita non pubbliche o non registrate su MAL.
- Controlliamo il range per verificare possibili date errate che verranno impostate a `null`.

In [572]:
df_pd['birthday'] = pd.to_datetime(df_pd['birthday'], errors='coerce', utc=True)
print(f'Range          : {df_pd["birthday"].min()} → {df_pd["birthday"].max()}')
print()

# Date implausibili: anno < 1800
mask_passato = df_pd['birthday'].dt.year < 1800
n_passato = mask_passato.sum()
print(f'Date con anno < 1800: {n_passato}')
print(df_pd.loc[mask_passato, ['person_mal_id', 'name', 'url', 'birthday']].head(30).to_string(index=True))

# Date recenti
mask_futuro = df_pd['birthday'].dt.year > 2020
n_futuro = mask_futuro.sum()
print(f'\nDate recenti: {n_futuro}')
print(df_pd.loc[mask_futuro, ['person_mal_id', 'name', 'url', 'birthday']].head(30).to_string(index=True))

# Rimozione di tutti i birthday il cui anno non inizia con 1 o 2 (fuori dal range 1000-2026)
mask_bad_date = df_pd['birthday'].notna() & ~df_pd['birthday'].dt.year.between(1000, 2026)
df_pd.loc[mask_bad_date, 'birthday'] = pd.NaT
print(f'\nDate anomale impostate a NaT : {mask_bad_date.sum()}')
print(f'birthday dtype : {df_pd["birthday"].dtype}')
print(f'Null residui   : {df_pd["birthday"].isna().sum():,}')

Range          : 0178-05-01 00:00:00+00:00 → 2023-06-15 00:00:00+00:00

Date con anno < 1800: 27
       person_mal_id                              name                                                                   url                  birthday
2888            3134               William Shakespeare               https://myanimelist.net/people/3134/William_Shakespeare 1564-04-26 00:00:00+00:00
4057            4482        Johann Wolfgang von Goethe        https://myanimelist.net/people/4482/Johann_Wolfgang_von_Goethe 1749-08-28 00:00:00+00:00
8145            9045                  Charles Perrault                  https://myanimelist.net/people/9045/Charles_Perrault 1628-01-12 00:00:00+00:00
8247            9159             Johann Sebastian Bach             https://myanimelist.net/people/9159/Johann_Sebastian_Bach 1685-03-31 00:00:00+00:00
8248            9160              Ludwig van Beethoven              https://myanimelist.net/people/9160/Ludwig_van_Beethoven 1770-12-16 00:00:00+00:00
8251            9163                 Giacomo Meyerbeer                 https://myanimelist.net/people/9163/Giacomo_Meyerbeer 1791-09-05 00:00:00+00:00
8267            9179  Domenico Gaetano Maria Donizetti  https://myanimelist.net/people/9179/Domenico_Gaetano_Maria_Donizetti 1797-11-29 00:00:00+00:00
10690          11768           Wolfgang Amadeus Mozart          https://myanimelist.net/people/11768/Wolfgang_Amadeus_Mozart 1756-01-27 00:00:00+00:00
13012          15677                    René Descartes                   https://myanimelist.net/people/15677/René_Descartes 1596-03-31 00:00:00+00:00
17383          24707                  Honoré De Balzac                 https://myanimelist.net/people/24707/Honoré_De_Balzac 1799-05-20 00:00:00+00:00
17388          24717      Miguel De Cervantes Saavedra     https://myanimelist.net/people/24717/Miguel_De_Cervantes_Saavedra 1547-09-29 00:00:00+00:00
17393          24727     Ernst Theodor Wilhelm Hoffman    https://myanimelist.net/people/24727/Ernst_Theodor_Wilhelm_Hoffman 1776-01-24 00:00:00+00:00
17498          24939             Antonio Lucio Vivaldi            https://myanimelist.net/people/24939/Antonio_Lucio_Vivaldi 1678-03-04 00:00:00+00:00
19975          30051              Franz Peter Schubert             https://myanimelist.net/people/30051/Franz_Peter_Schubert 1797-01-31 00:00:00+00:00
22466          35203                      Mary Shelley                     https://myanimelist.net/people/35203/Mary_Shelley 1797-08-30 00:00:00+00:00
24335          37864                Franz Xaver Gruber               https://myanimelist.net/people/37864/Franz_Xaver_Gruber 1787-11-25 00:00:00+00:00
24829          38374             Jean-Jacques Rousseau            https://myanimelist.net/people/38374/Jean-Jacques_Rousseau 1712-06-28 00:00:00+00:00
26183          39758                  Nanatsu Mukunoki                 https://myanimelist.net/people/39758/Nanatsu_Mukunoki 0800-11-01 00:00:00+00:00
48677          62858                            Karina                           https://myanimelist.net/people/62858/Karina 0984-02-21 00:00:00+00:00
48687          62868                  Toshiyuki Kimori                 https://myanimelist.net/people/62868/Toshiyuki_Kimori 0447-07-02 00:00:00+00:00
48885          63070                        Marco Eßer                       https://myanimelist.net/people/63070/Marco_Eßer 0296-12-01 00:00:00+00:00
48989          63178                   Kovács Patrícia                  https://myanimelist.net/people/63178/Kovács_Patrícia 0178-05-01 00:00:00+00:00
65318          79796                          Stendhal                         https://myanimelist.net/people/79796/Stendhal 1783-01-23 00:00:00+00:00
69820          84370                    Jonathan Swift                   https://myanimelist.net/people/84370/Jonathan_Swift 1667-11-30 00:00:00+00:00
69836          84386               Niccolò Machiavelli              https://myanimelist.net/people/84386/Niccolò_Machiavelli 1469-05-03 00:00:00+00:00
69837          84387                       Jane Austen                      https://myanimelist.net/people/84387/Jane_Austen 1775-12-16 00:00:00+00:00
71494          86083                      Fanny Dreiss                     https://myanimelist.net/people/86083/Fanny_Dreiss 1192-05-06 00:00:00+00:00

Date recenti: 14
       person_mal_id                      name                                                            url                  birthday
41193          55169                     V.W.P                       https://myanimelist.net/people/55169/VWP 2021-03-13 00:00:00+00:00
46051          60155                  NACHERRY                  https://myanimelist.net/people/60155/NACHERRY 2021-09-07 00:00:00+00:00
49035          63224                      KAFU                      https://myanimelist.net/people/63224/KAFU 2021-07-07 00:00:00+00:00
49585          63784                   amazuti                   https://myanimelist.net/people/63784/amazuti 2021-11-01 00:00:00+00:00
53953          68257               Le Sserafim               https://myanimelist.net/people/68257/Le_Sserafim 2022-05-02 00:00:00+00:00
60793          75202                       IVE                       https://myanimelist.net/people/75202/IVE 2021-12-01 00:00:00+00:00
60801          75210  Boku ga Mitakatta Aozora  https://myanimelist.net/people/75210/Boku_ga_Mitakatta_Aozora 2023-06-15 00:00:00+00:00
62980          77422           NOMELON NOLEMON           https://myanimelist.net/people/77422/NOMELON_NOLEMON 2021-08-11 00:00:00+00:00
63482          77932                     &TEAM                     https://myanimelist.net/people/77932/_TEAM 2022-12-07 00:00:00+00:00
64962          79436               Zerobaseone               https://myanimelist.net/people/79436/Zerobaseone 2023-06-10 00:00:00+00:00
65063          79539       Takane no Nadeshiko       https://myanimelist.net/people/79539/Takane_no_Nadeshiko 2022-07-10 00:00:00+00:00
65636          80116                       INI                       https://myanimelist.net/people/80116/INI 2021-11-03 00:00:00+00:00
70518          85083               Locker Room               https://myanimelist.net/people/85083/Locker_Room 2021-06-21 00:00:00+00:00
74272          88917                    UtaGe!                     https://myanimelist.net/people/88917/UtaGe 2022-04-15 00:00:00+00:00

Date anomale impostate a NaT : 5
birthday dtype : datetime64[us, UTC]
Null residui   : 58,062

Abbiamo effettuato un'analisi delle date estreme fuori dal range 1800 - 2020. Dalle date emerse prima del 1800, si nota che si tratta principalmente di autori o compositori classici mentre i valori dopo il 2020 corrispondono a AI oppure gruppi musicali formati recentemente. Abbiamo impostato a null solo gli anni che corrispondevano a valori evidentemente errati come `0800`, `0447`, `0296`, `0178`, etc.

### 2.9 `favorites`

Numero di utenti MAL che hanno aggiunto questa persona ai preferiti. Valore numerico non negativo, nessun null atteso.

In [573]:
analyze(df_pd['favorites'])

  Nome serie                     favorites
  dtype                          int64
  Dimensione                     75,211
  Range indice                   0 … 75210
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   75,211
  Valori non nulli               75,211  (100.00%)
  Null / NaN                     0  (0.00%)
  Zeri                           50,936  (67.72%)
  Positivi                       24,275   (32.28%)
  Negativi                       0   (0.00%)
  Valori unici                   1,168  (1.55%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            0
  Max                            108,157
  Range                          108,157
  Media                          54.5776
  Mediana                        0.0000
  Moda/e                         0
  Dev. standard                  1,146.10
  Varianza                       1,313,537
  Errore std (SEM)               4.1791
  IQR  (Q3 − Q1)                 1.0000
  Q1  (25° pct)                  0.0000
  Q3  (75° pct)                  1.0000
  P5  ( 5° pct)                  0.0000
  P95 (95° pct)                  40.0000
  Coefficiente di variazione     2099.94%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -1.5000
  Soglia alta   (Q3 + 1.5×IQR)   2.5000
  Outlier rilevati               13,613  (18.10%)

  Top 5 outlier estremi (per valore assoluto):
    [115]  108,157
    [181]  102,283
    [63]  92,366
    [661]  75,387
    [1741]  73,377

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  0 – 5,407                          75,075    99.8%
  5,407 – 10,815                         69     0.1%
  10,815 – 16,223                        20     0.0%
  16,223 – 21,631                        14     0.0%
  21,631 – 27,039                        10     0.0%
  27,039 – 32,447                         2     0.0%
  32,447 – 37,854                         5     0.0%
  37,854 – 43,262                         3     0.0%
  43,262 – 48,670                         3     0.0%
  48,670 – 54,078                         1     0.0%
  54,078 – 59,486                         2     0.0%
  59,486 – 64,894                         1     0.0%
  64,894 – 70,302                         1     0.0%
  70,302 – 75,709                         2     0.0%
  75,709 – 81,117                         0     0.0%
  81,117 – 86,525                         0     0.0%
  86,525 – 91,933                         0     0.0%
  91,933 – 97,341                         1     0.0%
  97,341 – 102,749                        1     0.0%
  102,749 – 108,157                       1     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   108,157
    #2   102,283
    #3   92,366
    #4   75,387
    #5   73,377
    #6   67,832
    #7   61,439
    #8   56,037
    #9   54,593
    #10  49,302

  I 10 più piccoli:
    #1   0
    #2   0
    #3   0
    #4   0
    #5   0
    #6   0
    #7   0
    #8   0
    #9   0
    #10  0

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                     0       50,936    67.7%
                     1        7,590    10.1%
                     2        3,072     4.1%
                     3        1,750     2.3%
                     4        1,218     1.6%
                     5          850     1.1%
                     6          687     0.9%
                     7          577     0.8%
                     8          477     0.6%
                     9          384     0.5%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                 1,830            1     0.0%
                   370            1     0.0%
                 5,882            1     0.0%
                   944            1     0.0%
                   406            1     0.0%
                 3,841            1     0.0%
                   730            1     0.0%
                   557            1     0.0%
                   999            1     0.0%
                 1,341            1     0.0%

Nessun null, dtype già `int64`. La distribuzione è fortemente asimmetrica (poche persone molto famose con molti preferiti).

**Nessuna pulizia necessaria.**

## 3. Riepilogo e Salvataggio
Le operazioni di pulizia sono state effettuate colonna per colonna nella sezione 2. In questa sezione riepiloghiamo il risultato ed effettuiamo il salvataggio del dataset finale.

In [580]:
print('Riepilogo Dataset Pulito')
print(f'Righe originali      : {n_originale:>10,}')
print(f'Righe dopo cleaning  : {len(df_pd):>10,}')
print(f'Righe rimosse totali : {n_originale - len(df_pd):>10,}')
print() 

df_pd.to_csv('../datasets_cleaned/person_details_clean.csv', index=False)
print('Salvato: datasets_cleaned/person_details_clean.csv')

Riepilogo Dataset Pulito
Righe originali      :     76,699
Righe dopo cleaning  :     75,211
Righe rimosse totali :      1,488

Salvato: datasets_cleaned/person_details_clean.csv