# 10 – Profiles

Esplorazione e data cleaning del dataset `profiles.csv`.

**Colonne:**
| Colonna | Descrizione |
|---|---|
| `username` | Nome utente MAL (chiave primaria) |
| `gender` | Genere dichiarato (`Male`, `Female`, `Non-Binary`) |
| `birthday` | Data di nascita (testo libero) |
| `location` | Paese dell'utente (22 valori categorici) |
| `joined` | Data di iscrizione a MAL |
| `watching` | Numero di anime attualmente in visione |
| `completed` | Numero di anime completati |
| `on_hold` | Numero di anime in pausa |
| `dropped` | Numero di anime abbandonati |
| `plan_to_watch` | Numero di anime in lista d'attesa |

## 1. Import e caricamento dati

In [1]:
import pandas as pd
import numpy as np
from dataset_analyzer import analyze

In [2]:
df_pr = pd.read_csv('../datasets/profiles.csv')
print(f'Shape: {df_pr.shape}')
df_pr.info()
df_pr.head()

Shape: (337155, 10)
<class 'pandas.DataFrame'>
RangeIndex: 337155 entries, 0 to 337154
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   username       337154 non-null  str
 1   gender         166279 non-null  str
 2   birthday       121329 non-null  str
 3   location       337155 non-null  str
 4   joined         335479 non-null  str
 5   watching       335477 non-null  str
 6   completed      335477 non-null  str
 7   on_hold        335477 non-null  str
 8   dropped        335477 non-null  str
 9   plan_to_watch  335477 non-null  str
dtypes: str(10)
memory usage: 25.7 MB

,username,gender,birthday,location,joined,watching,completed,on_hold,dropped,plan_to_watch
0,ishikawas,NaN,NaN,South Korea,NaN,NaN,NaN,NaN,NaN,NaN
1,CKK2,NaN,NaN,United States,"Dec 1, 2018",3,182,15,0,405
2,--------788,Female,NaN,Mexico,"Oct 4, 2022",1,64,0,0,1
3,potatoaris,NaN,NaN,Spain,"Oct 2, 2018",5,1,0,0,4
4,Rinrintan,NaN,NaN,Japan,"May 12, 2019",20,311,40,16,34

In [3]:
n_originale = len(df_pr)

## 1.1 Rimozione riga senza `username`

È presente 1 riga con `username` null. Senza identificatore il profilo è inutilizzabile → rimozione.

In [4]:
print('Riga con username null:')
print(df_pr[df_pr['username'].isna()])

df_pr.dropna(subset=['username'], inplace=True)
print(f'\nRighe dopo rimozione: {len(df_pr):,}')

Riga con username null:
       username gender birthday location        joined watching completed  \
271344      NaN    NaN      NaN   Mexico  Jul 28, 2007        2         2

       on_hold dropped plan_to_watch
271344       2       0             1

Righe dopo rimozione: 337,154

## 1.2 Rimozione profili senza dati statistici

1.678 righe hanno tutte le colonne statistiche (`watching`, `completed`, `on_hold`, `dropped`, `plan_to_watch`) e la data di iscrizione nulle: si tratta di profili vuoti senza alcun dato utile → rimozione.

In [5]:
stat_cols = ['watching', 'completed', 'on_hold', 'dropped', 'plan_to_watch']
mask_no_stats = df_pr[stat_cols].isna().all(axis=1)
print(f'Profili senza dati statistici : {mask_no_stats.sum():,}')
print(f'  di cui anche senza joined   : {(mask_no_stats & df_pr["joined"].isna()).sum():,}')
print()
print('Esempio profili vuoti:')
print(df_pr[mask_no_stats][['username', 'gender', 'location', 'joined'] + stat_cols].head())

df_pr = df_pr[~mask_no_stats].copy()
print(f'\nRighe prima della rimozione : {n_originale - 1:,}')
print(f'Righe dopo la rimozione     : {len(df_pr):,}')

Profili senza dati statistici : 1,678
  di cui anche senza joined   : 1,676

Esempio profili vuoti:
       username gender       location joined watching completed on_hold  \
0     ishikawas    NaN    South Korea    NaN      NaN       NaN     NaN
12  potatobeann    NaN         France    NaN      NaN       NaN     NaN
20   potatochib    NaN    South Korea    NaN      NaN       NaN     NaN
36     ishixawa    NaN          Japan    NaN      NaN       NaN     NaN
71   ---KING---    NaN  United States    NaN      NaN       NaN     NaN

   dropped plan_to_watch
0      NaN           NaN
12     NaN           NaN
20     NaN           NaN
36     NaN           NaN
71     NaN           NaN

Righe prima della rimozione : 337,154
Righe dopo la rimozione     : 335,476

## 2. Analisi colonna per colonna

### 2.1 `username`

In [6]:
analyze(df_pr['username'])

════════════════════════════════════════════════════════════════════════════════
═════════════════════  🔬  SERIES ANALYSIS  —  'username'  ══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    username
  dtype                          str
  Shape                          335,476
  Index range                    1 … 337154
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     335,476
  Non-null values                335,476  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  335,476  (100.00%)
  Duplicate values               0

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     1  chars
  Max length                     16  chars
  Mean length                    9.33  chars
  Median length                  9.0000  chars
  Std Dev length                 2.85
  IQR length                     4.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=16  Karinen-R-Andrew
    #2   len=16  potatochipmunk13
    #3   len=16  ThomasAndersonTR
    #4   len=16  KarlFellOffAnime
    #5   len=16  MoneyMakerMaster
    #6   len=16  --Hasuki_Komai--
    #7   len=16  ismailbarrrhouna
    #8   len=16  Karl_Marx_Sensei
    #9   len=16  --Mister_Mario--
    #10  len=16  Karl_von_Bahnhof

  10 Shortest strings:
    #1   len=1  K
    #2   len=2  CP
    #3   len=2  q2
    #4   len=2  qd
    #5   len=2  qh
    #6   len=2  -q
    #7   len=2  -s
    #8   len=2  02
    #9   len=2  0G
    #10  len=2  G9

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        1.00 – 1.94       │ 1
        1.94 – 2.88       │ 94
        2.88 – 3.81       │█ 959
        3.81 – 4.75       │█████ 5209
        4.75 – 5.69       │███████████████ 15989
        5.69 – 6.62       │████████████████████████████████ 33437
        6.62 – 7.56       │█████████████████████████████████████████ 43433
        7.56 – 8.50       │█████████████████████████████████████████████ 47428
        8.50 – 9.44       │█████████████████████████████████████████ 43353
        9.44 – 10.38      │████████████████████████████████████ 38016
       10.38 – 11.31      │█████████████████████████████ 30776
       11.31 – 12.25      │████████████████████████ 25211
       12.25 – 13.19      │██████████████████ 18742
       13.19 – 14.12      │█████████████ 14116
       14.12 – 15.06      │██████████ 10869
       15.06 – 16.00      │███████ 7843

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    CKK2                        [█████████████████████████] 100.0%  1
    --------788                 [█████████████████████████] 100.0%  1
    potatoaris                  [█████████████████████████] 100.0%  1
    Rinrintan                   [█████████████████████████] 100.0%  1
    Karincakes                  [█████████████████████████] 100.0%  1
    Folktal3wtb                 [█████████████████████████] 100.0%  1
    Monarchivist                [█████████████████████████] 100.0%  1
    Thom_dos                    [█████████████████████████] 100.0%  1
    arizkykun                   [█████████████████████████] 100.0%  1
    -----9-----                 [█████████████████████████] 100.0%  1

  Top 10 least frequent (rarest):
    arizkim                     [█████████████████████████] 100.0%  1
    arizima23                   [█████████████████████████] 100.0%  1
    ariyoskz                    [█████████████████████████] 100.0%  1
    ariyanvk18                  [█████████████████████████] 100.0%  1
    ariyanroy04                 [█████████████████████████] 100.0%  1
    ariwow                      [█████████████████████████] 100.0%  1
    ariwe                       [█████████████████████████] 100.0%  1
    ariu82                      [█████████████████████████] 100.0%  1
    aritzugazaga                [█████████████████████████] 100.0%  1
    aritza14                    [█████████████████████████] 100.0%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                92,100  (27.5%)
  Contains uppercase             231,229  (68.9%)
  Contains lowercase             326,443  (97.3%)
  Contains whitespace            0  (0.0%)
  Contains special chars         57,523  (17.1%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  250
  Fully alpha                    199,427
  Fully alphanumeric             277,953

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               3,129,122
  Unique characters              64
  Avg chars per value            9.33

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
Nessun null (rimosso al passo 1.1), nessun duplicato. È la chiave primaria del dataset.

In [7]:
print(f'Null in username      : {df_pr["username"].isna().sum()}')
print(f'Duplicati in username : {df_pr["username"].duplicated().sum()}')

Null in username      : 0
Duplicati in username : 0

### 2.2 `gender`

In [8]:
analyze(df_pr['gender'])

════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'gender'  ═══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    gender
  dtype                          str
  Shape                          335,476
  Index range                    1 … 337154
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     335,476
  Non-null values                166,277  [███████████████░░░░░░░░░░░░░░░]  49.6%
  Null / NaN                     169,199  (50.44%)
  Empty strings                  0
  Unique values                  3  (0.00%)
  Duplicate values               166,274

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     4  chars
  Max length                     10  chars
  Mean length                    4.65  chars
  Median length                  4.0000  chars
  Std Dev length                 1.22
  IQR length                     2.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=10  Non-Binary
    #2   len=10  Non-Binary
    #3   len=10  Non-Binary
    #4   len=10  Non-Binary
    #5   len=10  Non-Binary
    #6   len=10  Non-Binary
    #7   len=10  Non-Binary
    #8   len=10  Non-Binary
    #9   len=10  Non-Binary
    #10  len=10  Non-Binary

  10 Shortest strings:
    #1   len=4  Male
    #2   len=4  Male
    #3   len=4  Male
    #4   len=4  Male
    #5   len=4  Male
    #6   len=4  Male
    #7   len=4  Male
    #8   len=4  Male
    #9   len=4  Male
    #10  len=4  Male

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        4.00 – 4.86       │█████████████████████████████████████████████ 120747
        4.86 – 5.71       │ 0
        5.71 – 6.57       │███████████████ 41313
        6.57 – 7.43       │ 0
        7.43 – 8.29       │ 0
        8.29 – 9.14       │ 0
        9.14 – 10.00      │██ 4217

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    Male                        [█████████████████████████] 100.0%  120,747
    Female                      [█████████░░░░░░░░░░░░░░░░]  34.2%  41,313
    Non-Binary                  [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.5%  4,217

  Top 10 least frequent (rarest):
    Non-Binary                  [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.5%  4,217
    Female                      [█████████░░░░░░░░░░░░░░░░]  34.2%  41,313
    Male                        [█████████████████████████] 100.0%  120,747

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                0  (0.0%)
  Contains uppercase             166,277  (100.0%)
  Contains lowercase             166,277  (100.0%)
  Contains whitespace            0  (0.0%)
  Contains special chars         4,217  (2.5%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    162,060
  Fully alphanumeric             162,060

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               773,036
  Unique characters              14
  Avg chars per value            4.65

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
I null (~170.876, ~51%) sono strutturali: la maggior parte degli utenti MAL non dichiara il genere. I tre valori (`Male`, `Female`, `Non-Binary`) sono già consistenti.

In [9]:
print(f'Null in gender : {df_pr["gender"].isna().sum():,} ({df_pr["gender"].isna().mean()*100:.1f}%)')
print()
print('Distribuzione gender:')
print(df_pr['gender'].value_counts())

Null in gender : 169,199 (50.4%)

Distribuzione gender:
gender
Male          120747
Female         41313
Non-Binary      4217
Name: count, dtype: int64

### 2.3 `birthday`

In [10]:
analyze(df_pr['birthday'])

════════════════════════════════════════════════════════════════════════════════
═════════════════════  🔬  SERIES ANALYSIS  —  'birthday'  ══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    birthday
  dtype                          str
  Shape                          335,476
  Index range                    1 … 337154
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     335,476
  Non-null values                121,327  [███████████░░░░░░░░░░░░░░░░░░░]  36.2%
  Null / NaN                     214,149  (63.83%)
  Empty strings                  0
  Unique values                  11,344  (3.38%)
  Duplicate values               109,983

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     1  chars
  Max length                     12  chars
  Mean length                    9.90  chars
  Median length                  11.0000  chars
  Std Dev length                 2.88
  IQR length                     6.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=12  Apr 17, 2000
    #2   len=12  Feb 28, 2001
    #3   len=12  Jul 15, 1988
    #4   len=12  Jun 16, 2003
    #5   len=12  Dec 27, 2002
    #6   len=12  Jul 16, 1997
    #7   len=12  Nov 17, 2002
    #8   len=12  Aug 23, 2004
    #9   len=12  Apr 17, 2000
    #10  len=12  Dec 24, 1991

  10 Shortest strings:
    #1   len=1  1
    #2   len=1  8
    #3   len=1  6
    #4   len=1  9
    #5   len=1  1
    #6   len=1  7
    #7   len=1  5
    #8   len=1  6
    #9   len=1  4
    #10  len=1  8

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        1.00 – 1.92       │ 18
        1.92 – 2.83       │ 17
        2.83 – 3.75       │ 217
        3.75 – 4.67       │████ 5939
        4.67 – 5.58       │██████ 7873
        5.58 – 6.50       │██████████████ 19209
        6.50 – 7.42       │ 44
        7.42 – 8.33       │█ 1955
        8.33 – 9.25       │ 0
        9.25 – 10.17      │ 0
       10.17 – 11.08      │████████████████████ 26025
       11.08 – 12.00      │█████████████████████████████████████████████ 60030

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    2003                        [█████████████████████████] 100.0%  448
    1997                        [██████████████████████░░░]  89.1%  399
    2001                        [██████████████████████░░░]  89.1%  399
    2002                        [██████████████████████░░░]  87.1%  390
    1999                        [█████████████████████░░░░]  84.8%  380
    2000                        [█████████████████████░░░░]  83.7%  375
    2004                        [████████████████████░░░░░]  81.5%  365
    1998                        [███████████████████░░░░░░]  75.2%  337
    1996                        [██████████████████░░░░░░░]  71.7%  321
    1995                        [████████████████░░░░░░░░░]  65.6%  294

  Top 10 least frequent (rarest):
    14, 1998                    [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Sep 13, 1989                [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Sep 24, 1988                [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Jan 28, 2009                [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Mar 19, 1985                [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Feb 17, 2009                [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Dec 2, 1981                 [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Oct 14, 1980                [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    1, 1995                     [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Aug 14, 1968                [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                121,110  (99.8%)
  Contains uppercase             115,287  (95.0%)
  Contains lowercase             115,287  (95.0%)
  Contains whitespace            115,136  (94.9%)
  Contains special chars         86,121  (71.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  5,974
  Fully alpha                    217
  Fully alphanumeric             6,191

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               1,201,661
  Unique characters              34
  Avg chars per value            9.90

 💬 Word / Token Analysis
────────────────────────────────────────────────────────────────────────────────
  Avg words per value            2.66
  Max words                      3
  Min words                      1

  Top 10 most common words:
    Jan                   [█████████████████████████] 100.0%  10,152
    Oct                   [█████████████████████████]  98.5%  9,997
    Jul                   [████████████████████████░]  97.5%  9,903
    Sep                   [████████████████████████░]  96.8%  9,830
    Dec                   [████████████████████████░]  95.8%  9,726
    Aug                   [████████████████████████░]  95.3%  9,675
    May                   [████████████████████████░]  94.8%  9,624
    Nov                   [███████████████████████░░]  93.6%  9,506
    Apr                   [███████████████████████░░]  92.8%  9,417
    Jun                   [███████████████████████░░]  92.5%  9,392

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Pulizia necessaria:**  
- I valori sono stringhe in formato libero (es. `'Jul 7, 1989'`, `'2003'`, `'Jan 1'`) → conversione a `datetime64` con `errors='coerce'`
- Le date parziali (solo anno o solo giorno/mese) non sono parsabili come data completa → diventano `NaT`
- I ~215.826 null originali (~64%) sono strutturali: molti utenti non inseriscono la data di nascita su MAL

In [11]:
n_null_before = df_pr['birthday'].isna().sum()
n_nonnull_before = df_pr['birthday'].notna().sum()

df_pr['birthday'] = pd.to_datetime(df_pr['birthday'], errors='coerce')

n_null_after = df_pr['birthday'].isna().sum()
n_coerced = n_null_after - n_null_before

print(f'Valori non-null prima della conversione : {n_nonnull_before:,}')
print(f'  → convertiti correttamente            : {n_nonnull_before - n_coerced:,}')
print(f'  → coercizzati a NaT (date parziali)   : {n_coerced:,}')
print(f'Null totali dopo la conversione         : {n_null_after:,} ({n_null_after/len(df_pr)*100:.1f}%)')
print(f'birthday dtype : {df_pr["birthday"].dtype}')
print(f'Range          : {df_pr["birthday"].min()} → {df_pr["birthday"].max()}')

Valori non-null prima della conversione : 121,327
  → convertiti correttamente            : 86,055
  → coercizzati a NaT (date parziali)   : 35,272
Null totali dopo la conversione         : 249,421 (74.3%)
birthday dtype : datetime64[us]
Range          : 0001-01-01 00:00:00 → 9999-09-03 00:00:00

### 2.4 `location`

In [12]:
analyze(df_pr['location'])

════════════════════════════════════════════════════════════════════════════════
═════════════════════  🔬  SERIES ANALYSIS  —  'location'  ══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    location
  dtype                          str
  Shape                          335,476
  Index range                    1 … 337154
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     335,476
  Non-null values                335,476  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  22  (0.01%)
  Duplicate values               335,454

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     5  chars
  Max length                     14  chars
  Mean length                    8.03  chars
  Median length                  7.0000  chars
  Std Dev length                 3.39
  IQR length                     8.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=14  United Kingdom
    #2   len=14  United Kingdom
    #3   len=14  United Kingdom
    #4   len=14  United Kingdom
    #5   len=14  United Kingdom
    #6   len=14  United Kingdom
    #7   len=14  United Kingdom
    #8   len=14  United Kingdom
    #9   len=14  United Kingdom
    #10  len=14  United Kingdom

  10 Shortest strings:
    #1   len=5  Spain
    #2   len=5  Japan
    #3   len=5  Japan
    #4   len=5  Japan
    #5   len=5  Japan
    #6   len=5  Japan
    #7   len=5  Japan
    #8   len=5  Japan
    #9   len=5  Spain
    #10  len=5  China

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        5.00 – 5.90       │█████████████████████████████████████████████ 136654
        5.90 – 6.80       │██████████ 29531
        6.80 – 7.70       │██████████ 29483
        7.70 – 8.60       │█████ 16332
        8.60 – 9.50       │█████████ 26130
        9.50 – 10.40      │ 0
       10.40 – 11.30      │███ 9730
       11.30 – 12.20      │█ 3253
       12.20 – 13.10      │█████████████████████ 64930
       13.10 – 14.00      │██████ 19433

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    Japan                       [█████████████████████████] 100.0%  97,820
    United States               [█████████████████░░░░░░░░]  66.4%  64,930
    Germany                     [███████░░░░░░░░░░░░░░░░░░]  26.8%  26,226
    United Kingdom              [█████░░░░░░░░░░░░░░░░░░░░]  19.9%  19,433
    Thailand                    [████░░░░░░░░░░░░░░░░░░░░░]  16.7%  16,332
    Argentina                   [███░░░░░░░░░░░░░░░░░░░░░░]  13.5%  13,165
    China                       [███░░░░░░░░░░░░░░░░░░░░░░]  13.4%  13,128
    Spain                       [███░░░░░░░░░░░░░░░░░░░░░░]  13.1%  12,837
    France                      [███░░░░░░░░░░░░░░░░░░░░░░]  10.2%  9,983
    Australia                   [██░░░░░░░░░░░░░░░░░░░░░░░]   9.9%  9,651

  Top 10 least frequent (rarest):
    Canada                      [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.3%  3,187
    India                       [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.3%  3,207
    Egypt                       [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.3%  3,222
    Philippines                 [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.3%  3,240
    South Africa                [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.3%  3,253
    Vietnam                     [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.3%  3,257
    Brazil                      [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.4%  3,279
    Indonesia                   [█░░░░░░░░░░░░░░░░░░░░░░░░]   3.4%  3,314
    Italy                       [██░░░░░░░░░░░░░░░░░░░░░░░]   6.6%  6,440
    Turkey                      [██░░░░░░░░░░░░░░░░░░░░░░░]   6.6%  6,485

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                0  (0.0%)
  Contains uppercase             335,476  (100.0%)
  Contains lowercase             335,476  (100.0%)
  Contains whitespace            94,106  (28.1%)
  Contains special chars         0  (0.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    241,370
  Fully alphanumeric             241,370

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               2,694,881
  Unique characters              37
  Avg chars per value            8.03

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
Nessun null. La colonna presenta esattamente 22 valori distinti (paesi) uniformemente distribuiti, indice che si tratta di un campo categorico a selezione fissa (dropdown) anziché testo libero. Il Giappone è il paese più rappresentato, coerente con la base utenti di MAL.

In [13]:
print(f'Null in location  : {df_pr["location"].isna().sum()}')
print(f'Valori unici      : {df_pr["location"].nunique()}')
print()
print('Distribuzione location:')
print(df_pr['location'].value_counts())

Null in location  : 0
Valori unici      : 22

Distribuzione location:
location
Japan             97820
United States     64930
Germany           26226
United Kingdom    19433
Thailand          16332
Argentina         13165
China             13128
Spain             12837
France             9983
Australia          9651
Mexico             6597
South Korea        6490
Turkey             6485
Italy              6440
Indonesia          3314
Brazil             3279
Vietnam            3257
South Africa       3253
Philippines        3240
Egypt              3222
India              3207
Canada             3187
Name: count, dtype: int64

### 2.5 `joined`

In [14]:
analyze(df_pr['joined'])

════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'joined'  ═══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    joined
  dtype                          str
  Shape                          335,476
  Index range                    1 … 337154
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     335,476
  Non-null values                335,476  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  6,802  (2.03%)
  Duplicate values               328,674

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     11  chars
  Max length                     12  chars
  Mean length                    11.71  chars
  Median length                  12.0000  chars
  Std Dev length                 0.46
  IQR length                     1.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=12  May 12, 2019
    #2   len=12  Nov 16, 2024
    #3   len=12  Jan 16, 2016
    #4   len=12  Apr 15, 2020
    #5   len=12  Jan 23, 2018
    #6   len=12  Jul 25, 2021
    #7   len=12  May 15, 2024
    #8   len=12  Oct 19, 2009
    #9   len=12  Nov 12, 2021
    #10  len=12  Jan 21, 2024

  10 Shortest strings:
    #1   len=11  Dec 1, 2018
    #2   len=11  Oct 4, 2022
    #3   len=11  Oct 2, 2018
    #4   len=11  Jan 5, 2015
    #5   len=11  Jan 3, 2021
    #6   len=11  Sep 2, 2021
    #7   len=11  Apr 8, 2022
    #8   len=11  Sep 3, 2023
    #9   len=11  Dec 7, 2018
    #10  len=11  Aug 7, 2018

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
       11.00 – 11.50      │███████████████████ 98736
       11.50 – 12.00      │█████████████████████████████████████████████ 236740

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    Sep 30, 2025                [█████████████████████████] 100.0%  665
    Aug 27, 2024                [█████████████████████░░░░]  82.6%  549
    Dec 23, 2022                [██████████████████░░░░░░░]  74.0%  492
    Oct 1, 2023                 [█████████████░░░░░░░░░░░░]  53.7%  357
    Dec 9, 2020                 [█████████████░░░░░░░░░░░░]  52.8%  351
    Jul 23, 2023                [█████████████░░░░░░░░░░░░]  52.5%  349
    Jan 24, 2021                [█████████████░░░░░░░░░░░░]  50.5%  336
    Sep 29, 2023                [█████████████░░░░░░░░░░░░]  50.1%  333
    Jan 23, 2021                [████████████░░░░░░░░░░░░░]  49.5%  329
    Jul 31, 2023                [████████████░░░░░░░░░░░░░]  48.3%  321

  Top 10 least frequent (rarest):
    Aug 26, 2006                [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Oct 26, 2025                [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Aug 1, 2006                 [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Jan 17, 2007                [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Sep 22, 2006                [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    May 7, 2007                 [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Nov 2, 2025                 [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Sep 29, 2006                [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Mar 2, 2007                 [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1
    Oct 9, 2025                 [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.2%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                335,476  (100.0%)
  Contains uppercase             335,476  (100.0%)
  Contains lowercase             335,476  (100.0%)
  Contains whitespace            335,476  (100.0%)
  Contains special chars         335,476  (100.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  0
  Fully alpha                    0
  Fully alphanumeric             0

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               3,926,976
  Unique characters              34
  Avg chars per value            11.71

 💬 Word / Token Analysis
────────────────────────────────────────────────────────────────────────────────
  Avg words per value            3.00
  Max words                      3
  Min words                      3

  Top 10 most common words:
    2023                  [█████████████████████████] 100.0%  47,271
    2021                  [███████████████████████░░]  91.3%  43,170
    2020                  [██████████████████████░░░]  88.9%  42,019
    Aug                   [██████████████████░░░░░░░]  70.2%  33,193
    Jan                   [██████████████████░░░░░░░]  70.2%  33,181
    Sep                   [████████████████░░░░░░░░░]  64.9%  30,685
    Oct                   [████████████████░░░░░░░░░]  62.3%  29,468
    Jul                   [███████████████░░░░░░░░░░]  61.2%  28,950
    Dec                   [███████████████░░░░░░░░░░]  60.3%  28,515
    Apr                   [███████████████░░░░░░░░░░]  59.4%  28,073

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Pulizia necessaria:**  
I valori sono stringhe in formato `'Dec 1, 2018'` → conversione a `datetime64`.  
I null residui (~2, dopo la rimozione dei profili vuoti al passo 1.2) sono strutturali.

In [15]:
df_pr['joined'] = pd.to_datetime(df_pr['joined'], errors='coerce')
print(f'joined dtype  : {df_pr["joined"].dtype}')
print(f'Null residui  : {df_pr["joined"].isna().sum()}')
print(f'Range         : {df_pr["joined"].min()} → {df_pr["joined"].max()}')

joined dtype  : datetime64[us]
Null residui  : 0
Range         : 2004-11-05 00:00:00 → 2025-11-02 00:00:00

### 2.6 Colonne statistiche: `watching`, `completed`, `on_hold`, `dropped`, `plan_to_watch`

Le cinque colonne sono caricate come `str` e alcune contengono numeri con separatore delle migliaia (es. `'1,008'`). Pulizia uniforme: rimozione del separatore e conversione a `int64`.

In [16]:
stat_cols = ['watching', 'completed', 'on_hold', 'dropped', 'plan_to_watch']

for col in stat_cols:
    analyze(df_pr[col])

════════════════════════════════════════════════════════════════════════════════
═════════════════════  🔬  SERIES ANALYSIS  —  'watching'  ══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    watching
  dtype                          str
  Shape                          335,476
  Index range                    1 … 337154
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     335,476
  Non-null values                335,476  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  942  (0.28%)
  Duplicate values               334,534

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     1  chars
  Max length                     6  chars
  Mean length                    1.42  chars
  Median length                  1.0000  chars
  Std Dev length                 0.55
  IQR length                     1.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=6  27,020
    #2   len=6  16,422
    #3   len=5  2,617
    #4   len=5  2,055
    #5   len=5  1,930
    #6   len=5  2,216
    #7   len=5  1,041
    #8   len=5  1,023
    #9   len=5  1,332
    #10  len=5  2,772

  10 Shortest strings:
    #1   len=1  3
    #2   len=1  1
    #3   len=1  5
    #4   len=1  1
    #5   len=1  7
    #6   len=1  3
    #7   len=1  3
    #8   len=1  6
    #9   len=1  1
    #10  len=1  0

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        1.00 – 1.83       │█████████████████████████████████████████████ 204380
        1.83 – 2.67       │███████████████████████████ 121267
        2.67 – 3.50       │██ 9643
        3.50 – 4.33       │ 0
        4.33 – 5.17       │ 184
        5.17 – 6.00       │ 2

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    0                           [█████████████████████████] 100.0%  38,109
    1                           [███████████████████░░░░░░]  75.8%  28,898
    2                           [█████████████████░░░░░░░░]  67.0%  25,525
    3                           [███████████████░░░░░░░░░░]  59.1%  22,518
    4                           [█████████████░░░░░░░░░░░░]  52.8%  20,109
    5                           [████████████░░░░░░░░░░░░░]  46.6%  17,748
    6                           [██████████░░░░░░░░░░░░░░░]  40.6%  15,481
    7                           [█████████░░░░░░░░░░░░░░░░]  35.5%  13,516
    8                           [████████░░░░░░░░░░░░░░░░░]  31.3%  11,941
    9                           [███████░░░░░░░░░░░░░░░░░░]  27.6%  10,535

  Top 10 least frequent (rarest):
    872                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    1,289                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    853                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    1,216                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    466                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    940                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    750                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    8,365                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    756                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    670                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                335,476  (100.0%)
  Contains uppercase             0  (0.0%)
  Contains lowercase             0  (0.0%)
  Contains whitespace            0  (0.0%)
  Contains special chars         186  (0.1%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  335,290
  Fully alpha                    0
  Fully alphanumeric             335,290

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               476,775
  Unique characters              11
  Avg chars per value            1.42

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════


════════════════════════════════════════════════════════════════════════════════
═════════════════════  🔬  SERIES ANALYSIS  —  'completed'  ═════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    completed
  dtype                          str
  Shape                          335,476
  Index range                    1 … 337154
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     335,476
  Non-null values                335,476  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  3,380  (1.01%)
  Duplicate values               332,096

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     1  chars
  Max length                     6  chars
  Mean length                    2.64  chars
  Median length                  3.0000  chars
  Std Dev length                 0.79
  IQR length                     1.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=6  15,112
    #2   len=6  10,840
    #3   len=6  15,118
    #4   len=6  27,350
    #5   len=6  19,809
    #6   len=6  17,777
    #7   len=6  11,824
    #8   len=6  10,162
    #9   len=6  27,954
    #10  len=6  14,472

  10 Shortest strings:
    #1   len=1  1
    #2   len=1  0
    #3   len=1  3
    #4   len=1  0
    #5   len=1  0
    #6   len=1  0
    #7   len=1  1
    #8   len=1  0
    #9   len=1  4
    #10  len=1  8

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        1.00 – 1.83       │███████ 30170
        1.83 – 2.67       │██████████████████ 85280
        2.67 – 3.50       │█████████████████████████████████████████████ 207907
        3.50 – 4.33       │ 0
        4.33 – 5.17       │███ 12051
        5.17 – 6.00       │ 68

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    0                           [█████████████████████████] 100.0%  15,197
    1                           [█████░░░░░░░░░░░░░░░░░░░░]  20.8%  3,166
    2                           [███░░░░░░░░░░░░░░░░░░░░░░]  14.0%  2,123
    3                           [███░░░░░░░░░░░░░░░░░░░░░░]  10.7%  1,629
    4                           [██░░░░░░░░░░░░░░░░░░░░░░░]   9.9%  1,499
    5                           [██░░░░░░░░░░░░░░░░░░░░░░░]   9.4%  1,433
    6                           [██░░░░░░░░░░░░░░░░░░░░░░░]   8.8%  1,331
    7                           [██░░░░░░░░░░░░░░░░░░░░░░░]   8.6%  1,313
    8                           [██░░░░░░░░░░░░░░░░░░░░░░░]   8.2%  1,250
    9                           [██░░░░░░░░░░░░░░░░░░░░░░░]   8.1%  1,229

  Top 10 least frequent (rarest):
    3,240                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    2,537                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    3,768                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    1,824                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    2,599                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    8,366                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    5,549                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    5,299                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    3,392                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    3,481                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                335,476  (100.0%)
  Contains uppercase             0  (0.0%)
  Contains lowercase             0  (0.0%)
  Contains whitespace            0  (0.0%)
  Contains special chars         12,119  (3.6%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  323,357
  Fully alpha                    0
  Fully alphanumeric             323,357

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               885,114
  Unique characters              11
  Avg chars per value            2.64

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════


════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'on_hold'  ══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    on_hold
  dtype                          str
  Shape                          335,476
  Index range                    1 … 337154
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     335,476
  Non-null values                335,476  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  738  (0.22%)
  Duplicate values               334,738

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     1  chars
  Max length                     6  chars
  Mean length                    1.28  chars
  Median length                  1.0000  chars
  Std Dev length                 0.49
  IQR length                     1.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=6  18,403
    #2   len=5  1,492
    #3   len=5  1,660
    #4   len=5  1,044
    #5   len=5  1,014
    #6   len=5  2,097
    #7   len=5  1,151
    #8   len=5  1,619
    #9   len=5  1,261
    #10  len=5  1,517

  10 Shortest strings:
    #1   len=1  0
    #2   len=1  0
    #3   len=1  0
    #4   len=1  0
    #5   len=1  0
    #6   len=1  2
    #7   len=1  0
    #8   len=1  0
    #9   len=1  5
    #10  len=1  0

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        1.00 – 1.83       │█████████████████████████████████████████████ 247146
        1.83 – 2.67       │███████████████ 82737
        2.67 – 3.50       │█ 5499
        3.50 – 4.33       │ 0
        4.33 – 5.17       │ 93
        5.17 – 6.00       │ 1

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    0                           [█████████████████████████] 100.0%  122,275
    1                           [██████░░░░░░░░░░░░░░░░░░░]  25.0%  30,509
    2                           [████░░░░░░░░░░░░░░░░░░░░░]  17.1%  20,861
    3                           [███░░░░░░░░░░░░░░░░░░░░░░]  13.4%  16,328
    4                           [███░░░░░░░░░░░░░░░░░░░░░░]  11.0%  13,390
    5                           [██░░░░░░░░░░░░░░░░░░░░░░░]   9.3%  11,383
    6                           [██░░░░░░░░░░░░░░░░░░░░░░░]   8.0%  9,805
    7                           [██░░░░░░░░░░░░░░░░░░░░░░░]   7.0%  8,536
    8                           [██░░░░░░░░░░░░░░░░░░░░░░░]   6.1%  7,441
    9                           [█░░░░░░░░░░░░░░░░░░░░░░░░]   5.4%  6,618

  Top 10 least frequent (rarest):
    1,512                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    371                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    1,017                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    408                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    577                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    711                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    1,185                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    424                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    639                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    1,193                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                335,476  (100.0%)
  Contains uppercase             0  (0.0%)
  Contains lowercase             0  (0.0%)
  Contains whitespace            0  (0.0%)
  Contains special chars         94  (0.0%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  335,382
  Fully alpha                    0
  Fully alphanumeric             335,382

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               429,588
  Unique characters              11
  Avg chars per value            1.28

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════


════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'dropped'  ══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    dropped
  dtype                          str
  Shape                          335,476
  Index range                    1 … 337154
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     335,476
  Non-null values                335,476  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  900  (0.27%)
  Duplicate values               334,576

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     1  chars
  Max length                     6  chars
  Mean length                    1.34  chars
  Median length                  1.0000  chars
  Std Dev length                 0.53
  IQR length                     1.0000

 🏆 Extreme Length Values
────────────────────────────────────────────────────────────────────────────────
  10 Longest strings:
    #1   len=6  19,601
    #2   len=6  10,357
    #3   len=6  15,593
    #4   len=6  27,277
    #5   len=6  19,423
    #6   len=6  10,547
    #7   len=6  24,838
    #8   len=6  10,270
    #9   len=6  27,118
    #10  len=6  12,597

  10 Shortest strings:
    #1   len=1  0
    #2   len=1  0
    #3   len=1  0
    #4   len=1  8
    #5   len=1  2
    #6   len=1  2
    #7   len=1  1
    #8   len=1  3
    #9   len=1  0
    #10  len=1  0

 📉 Length Distribution (histogram)
────────────────────────────────────────────────────────────────────────────────
        1.00 – 1.83       │█████████████████████████████████████████████ 229694
        1.83 – 2.67       │███████████████████ 96886
        2.67 – 3.50       │██ 8712
        3.50 – 4.33       │ 0
        4.33 – 5.17       │ 168
        5.17 – 6.00       │ 16

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
    0                           [█████████████████████████] 100.0%  108,913
    1                           [███████░░░░░░░░░░░░░░░░░░]  26.7%  29,073
    2                           [█████░░░░░░░░░░░░░░░░░░░░]  18.6%  20,235
    3                           [████░░░░░░░░░░░░░░░░░░░░░]  14.5%  15,777
    4                           [███░░░░░░░░░░░░░░░░░░░░░░]  11.9%  12,990
    5                           [███░░░░░░░░░░░░░░░░░░░░░░]  10.0%  10,921
    6                           [██░░░░░░░░░░░░░░░░░░░░░░░]   8.8%  9,606
    7                           [██░░░░░░░░░░░░░░░░░░░░░░░]   7.7%  8,343
    8                           [██░░░░░░░░░░░░░░░░░░░░░░░]   6.7%  7,281
    9                           [██░░░░░░░░░░░░░░░░░░░░░░░]   6.0%  6,555

  Top 10 least frequent (rarest):
    653                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    22,907                      [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    616                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    886                         [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    1,721                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    1,880                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    1,055                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    6,705                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    2,966                       [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1
    11,416                      [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.0%  1

 🔍 Pattern / Content Analysis
────────────────────────────────────────────────────────────────────────────────
  Contains digits                335,476  (100.0%)
  Contains uppercase             0  (0.0%)
  Contains lowercase             0  (0.0%)
  Contains whitespace            0  (0.0%)
  Contains special chars         184  (0.1%)
  Contains URL                   0  (0.0%)
  Contains @                     0  (0.0%)
  Fully numeric                  335,292
  Fully alpha                    0
  Fully alphanumeric             335,292

 🔡 Character-Level Statistics
────────────────────────────────────────────────────────────────────────────────
  Total characters               450,538
  Unique characters              11
  Avg chars per value            1.34

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════


════════════════════════════════════════════════════════════════════════════════
═══════════════════  🔬  SERIES ANALYSIS  —  'plan_to_watch'  ═══════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    plan_to_watch
  dtype                          str
  Shape                          335,476
  Index range                    1 … 337154
  Kind                           STRING / OBJECT

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     335,476
  Non-null values                335,476  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Empty strings                  0
  Unique values                  2,538  (0.76%)
  Duplicate values               332,938

 📐 String Length Analysis
────────────────────────────────────────────────────────────────────────────────
  Min length                     1  chars

**Pulizia necessaria per tutte e cinque le colonne:**  
- Alcune celle contengono numeri con separatore migliaia (virgola), es. `'1,008'` → rimozione della virgola
- Dtype `str` → conversione a `int64`
- Dopo la rimozione dei profili vuoti (passo 1.2) non ci sono null residui

In [17]:
for col in stat_cols:
    # Rimuovi separatore delle migliaia
    df_pr[col] = df_pr[col].str.replace(',', '', regex=False)
    # Converti a int64
    df_pr[col] = pd.to_numeric(df_pr[col], errors='coerce').astype('Int64')

print('Dtypes colonne statistiche dopo la conversione:')
print(df_pr[stat_cols].dtypes)
print()
print('Null residui:')
print(df_pr[stat_cols].isnull().sum())
print()
print('Range valori:')
print(df_pr[stat_cols].agg(['min', 'max']))

Dtypes colonne statistiche dopo la conversione:
watching         Int64
completed        Int64
on_hold          Int64
dropped          Int64
plan_to_watch    Int64
dtype: object

Null residui:
watching         0
completed        0
on_hold          0
dropped          0
plan_to_watch    0
dtype: int64

Range valori:
     watching  completed  on_hold  dropped  plan_to_watch
min         0          0        0        0              0
max     27020      28313    18403    27277          27193

### 2.7 Chiave primaria `username`

Verifichiamo che `username` sia univoco dopo tutte le operazioni di pulizia.

In [18]:
n_pk_dup = df_pr.duplicated(subset=['username'], keep=False).sum()
print(f'Duplicati su username: {n_pk_dup}')

if n_pk_dup > 0:
    print('→ Rimozione duplicati sulla chiave primaria...')
    df_pr.drop_duplicates(subset=['username'], keep='first', inplace=True)
    print(f'Righe dopo la rimozione: {len(df_pr):,}')
else:
    print('→ Chiave primaria già univoca, nessuna operazione richiesta.')

Duplicati su username: 0
→ Chiave primaria già univoca, nessuna operazione richiesta.

## 3. Data Cleaning

In [19]:
print('=== Riepilogo Dataset Pulito ===')
print(f'Righe originali      : {n_originale:>10,}')
print(f'Righe dopo cleaning  : {len(df_pr):>10,}')
print(f'Righe rimosse totali : {n_originale - len(df_pr):>10,}')
print()
print('Dtypes finali:')
print(df_pr.dtypes)
print()
print('Valori mancanti residui:')
print(df_pr.isnull().sum())

=== Riepilogo Dataset Pulito ===
Righe originali      :    337,155
Righe dopo cleaning  :    335,476
Righe rimosse totali :      1,679

Dtypes finali:
username                    str
gender                      str
birthday         datetime64[us]
location                    str
joined           datetime64[us]
watching                  Int64
completed                 Int64
on_hold                   Int64
dropped                   Int64
plan_to_watch             Int64
dtype: object

Valori mancanti residui:
username              0
gender           169199
birthday         249421
location              0
joined                0
watching              0
completed             0
on_hold               0
dropped               0
plan_to_watch         0
dtype: int64

In [20]:
df_pr.head()

,username,gender,birthday,location,joined,watching,completed,on_hold,dropped,plan_to_watch
1,CKK2,NaN,NaT,United States,2018-12-01,3,182,15,0,405
2,--------788,Female,NaT,Mexico,2022-10-04,1,64,0,0,1
3,potatoaris,NaN,NaT,Spain,2018-10-02,5,1,0,0,4
4,Rinrintan,NaN,NaT,Japan,2019-05-12,20,311,40,16,34
5,Karincakes,NaN,NaT,Turkey,2015-01-05,79,2899,22,17,508

## 4. Salvataggio dataset pulito

In [21]:
df_pr.to_csv('../datasets_cleaned/profiles_clean.csv', index=False)
print('Salvato: datasets_cleaned/profiles_clean.csv')

Salvato: datasets_cleaned/profiles_clean.csv