# 12 – Recommendations

Esplorazione e data cleaning del dataset `recommendations.csv`.

**Colonne:**
| Colonna | Descrizione |
|---|---|
| `mal_id` | ID dell'anime su MAL (FK → `details.csv`) |
| `recommendation_mal_id` | ID dell'anime raccomandato su MAL (FK → `details.csv`) |

## 1. Import e caricamento dati

In [1]:
import pandas as pd
import numpy as np
from dataset_analyzer import analyze

In [2]:
df_rec = pd.read_csv('../datasets/recommendations.csv')
print(f'Shape: {df_rec.shape}')
df_rec.info()
df_rec.head()

Shape: (105249, 2)
<class 'pandas.DataFrame'>
RangeIndex: 105249 entries, 0 to 105248
Data columns (total 2 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   mal_id                 105249 non-null  int64
 1   recommendation_mal_id  105249 non-null  int64
dtypes: int64(2)
memory usage: 1.6 MB

   mal_id  recommendation_mal_id
0    3269                    317
1    3269                   6922
2    3269                    299
3    3269                   3446
4    3269                   5681

In [3]:
n_originale = len(df_rec)

## 1.1 Rimozione duplicati esatti

Prima dell'analisi per colonna, rimuoviamo le righe con valori identici in **tutte** le colonne, mantenendo solo la prima occorrenza.

In [4]:
mask_dup = df_rec.duplicated(keep=False)
n_righe_coinvolte = mask_dup.sum()
n_gruppi = df_rec[mask_dup].duplicated(keep='first').sum()
n_tenute = n_righe_coinvolte - n_gruppi

print(f'Righe totali coinvolte in duplicazioni : {n_righe_coinvolte:,}')
print(f'  → prime occorrenze mantenute         : {n_tenute:,}')
print(f'  → occorrenze extra rimosse           : {n_gruppi:,}')
print()

df_rec.drop_duplicates(keep='first', inplace=True)
print(f'Righe prima della rimozione : {n_originale:,}')
print(f'Righe dopo la rimozione     : {len(df_rec):,}')

Righe totali coinvolte in duplicazioni : 0
  → prime occorrenze mantenute         : 0
  → occorrenze extra rimosse           : 0

Righe prima della rimozione : 105,249
Righe dopo la rimozione     : 105,249

## 2. Analisi colonna per colonna

### 2.1 `mal_id`

In [5]:
analyze(df_rec['mal_id'])

════════════════════════════════════════════════════════════════════════════════
══════════════════════  🔬  SERIES ANALYSIS  —  'mal_id'  ═══════════════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    mal_id
  dtype                          int64
  Shape                          105,249
  Index range                    0 … 105248
  Kind                           NUMERIC

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     105,249
  Non-null values                105,249  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Zeros                          0  (0.00%)
  Positives                      105,249   (100.00%)
  Negatives                      0   (0.00%)
  Unique values                  9,033  (8.58%)

 📐 Descriptive Statistics
────────────────────────────────────────────────────────────────────────────────
  Min                            1
  Max                            62,417
  Range                          62,416
  Mean                           16,899.73
  Median                         10,408.00
  Mode(s)                        30
  Std Dev                        16,669.15
  Variance                       277,860,579
  Std Error (SEM)                51.3812
  IQR  (Q3 − Q1)                 30,337.00
  Q1  (25th pct)                 1,845.00
  Q3  (75th pct)                 32,182.00
  P5  ( 5th pct)                 152.0000
  P95 (95th pct)                 49,220.00
  Coefficient of Variation       98.64%

 📈 Distribution Shape
────────────────────────────────────────────────────────────────────────────────
  Skewness                       0.7282  → Mildly right-skewed

  Mean position within [min, max]:
  1  │────────────◆───────────────────────────────│  62,417

 ✨ Value Distribution (sorted sparkline)
────────────────────────────────────────────────────────────────────────────────
  ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂▂▂▂▂▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▅▅▅▅▆▆▆▇▇▇
  Each char ≈ 1754 value(s) | min=1 → max=62,417

 📉 Histogram
────────────────────────────────────────────────────────────────────────────────
        1.00 – 3121.80    │█████████████████████████████████████████████ 33321
     3121.80 – 6242.60    │█████████████ 9597
     6242.60 – 9363.40    │█████████ 6484
     9363.40 – 12484.20   │███████████ 8116
    12484.20 – 15605.00   │██████ 4093
    15605.00 – 18725.80   │█████ 3759
    18725.80 – 21846.60   │████ 3213
    21846.60 – 24967.40   │████ 3086
    24967.40 – 28088.20   │██ 1448
    28088.20 – 31209.00   │█████ 3599
    31209.00 – 34329.80   │████████ 6288
    34329.80 – 37450.60   │████████ 6109
    37450.60 – 40571.40   │███████ 5454
    40571.40 – 43692.20   │████ 3058
    43692.20 – 46813.00   │█ 958
    46813.00 – 49933.80   │███ 1906
    49933.80 – 53054.60   │███ 2214
    53054.60 – 56175.40   │██ 1284
    56175.40 – 59296.20   │█ 931
    59296.20 – 62417.00   │ 331

 🔍 Outlier Analysis
────────────────────────────────────────────────────────────────────────────────
  IQR  method  [lo, hi]          [-43,660.50,  77,687.50]
    → Outliers (IQR)             0 values  (0.00%)

 🏆 Extreme Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 largest:
    #1   62,417  [index 69829]
    #2   62,417  [index 69830]
    #3   61,984  [index 8935]
    #4   61,984  [index 8936]
    #5   61,984  [index 8937]
    #6   61,672  [index 84321]
    #7   61,672  [index 84322]
    #8   61,595  [index 39076]
    #9   61,595  [index 39077]
    #10  61,595  [index 39078]

  Top 10 smallest:
    #1   1  [index 17253]
    #2   1  [index 17254]
    #3   1  [index 17255]
    #4   1  [index 17256]
    #5   1  [index 17257]
    #6   1  [index 17258]
    #7   1  [index 17259]
    #8   1  [index 17260]
    #9   1  [index 17261]
    #10  1  [index 17262]

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
             30  [█████████████████████████] 100.0%  300
          9,756  [████████████████████████░]  98.0%  294
          1,575  [██████████████████████░░░]  86.3%  259
          2,001  [████████████████████░░░░░]  79.3%  238
            918  [████████████████████░░░░░]  79.0%  237
          1,535  [████████████████████░░░░░]  78.3%  235
          6,547  [█████████████████░░░░░░░░]  68.7%  206
         16,498  [█████████████████░░░░░░░░]  67.0%  201
          5,680  [████████████████░░░░░░░░░]  65.0%  195
            226  [████████████████░░░░░░░░░]  64.7%  194

  Top 10 least frequent:
         36,305  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         41,915  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         35,592  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         40,695  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         32,934  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
          2,442  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         37,395  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
          1,746  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         31,427  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         11,093  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
Nessun null, dtype già `int64`. I duplicati sono attesi: uno stesso anime può comparire più volte perché raccomandato insieme a diversi altri anime. Chiave esterna verso `details.csv`.

In [6]:
print(f'Null in mal_id      : {df_rec["mal_id"].isna().sum()}')
print(f'Anime distinti      : {df_rec["mal_id"].nunique():,}')

Null in mal_id      : 0
Anime distinti      : 9,033

### 2.2 `recommendation_mal_id`

In [7]:
analyze(df_rec['recommendation_mal_id'])

════════════════════════════════════════════════════════════════════════════════
═══════════════  🔬  SERIES ANALYSIS  —  'recommendation_mal_id'  ═══════════════
════════════════════════════════════════════════════════════════════════════════

  Series name                    recommendation_mal_id
  dtype                          int64
  Shape                          105,249
  Index range                    0 … 105248
  Kind                           NUMERIC

 📊 Basic Counts
────────────────────────────────────────────────────────────────────────────────
  Total rows                     105,249
  Non-null values                105,249  [██████████████████████████████] 100.0%
  Null / NaN                     0  (0.00%)
  Zeros                          0  (0.00%)
  Positives                      105,249   (100.00%)
  Negatives                      0   (0.00%)
  Unique values                  9,041  (8.59%)

 📐 Descriptive Statistics
────────────────────────────────────────────────────────────────────────────────
  Min                            1
  Max                            62,417
  Range                          62,416
  Mean                           16,911.97
  Median                         10,408.00
  Mode(s)                        30
  Std Dev                        16,680.26
  Variance                       278,231,145
  Std Error (SEM)                51.4155
  IQR  (Q3 − Q1)                 30,368.00
  Q1  (25th pct)                 1,846.00
  Q3  (75th pct)                 32,214.00
  P5  ( 5th pct)                 152.0000
  P95 (95th pct)                 49,310.00
  Coefficient of Variation       98.63%

 📈 Distribution Shape
────────────────────────────────────────────────────────────────────────────────
  Skewness                       0.7282  → Mildly right-skewed

  Mean position within [min, max]:
  1  │────────────◆───────────────────────────────│  62,417

 ✨ Value Distribution (sorted sparkline)
────────────────────────────────────────────────────────────────────────────────
  ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂▂▂▂▂▂▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▅▅▅▅▆▆▆▇▇▇
  Each char ≈ 1754 value(s) | min=1 → max=62,417

 📉 Histogram
────────────────────────────────────────────────────────────────────────────────
        1.00 – 3121.80    │█████████████████████████████████████████████ 33288
     3121.80 – 6242.60    │█████████████ 9595
     6242.60 – 9363.40    │█████████ 6519
     9363.40 – 12484.20   │███████████ 8108
    12484.20 – 15605.00   │██████ 4088
    15605.00 – 18725.80   │█████ 3757
    18725.80 – 21846.60   │████ 3209
    21846.60 – 24967.40   │████ 3085
    24967.40 – 28088.20   │██ 1447
    28088.20 – 31209.00   │█████ 3597
    31209.00 – 34329.80   │████████ 6280
    34329.80 – 37450.60   │████████ 6112
    37450.60 – 40571.40   │███████ 5447
    40571.40 – 43692.20   │████ 3051
    43692.20 – 46813.00   │█ 954
    46813.00 – 49933.80   │███ 1902
    49933.80 – 53054.60   │███ 2270
    53054.60 – 56175.40   │██ 1281
    56175.40 – 59296.20   │█ 929
    59296.20 – 62417.00   │ 330

 🔍 Outlier Analysis
────────────────────────────────────────────────────────────────────────────────
  IQR  method  [lo, hi]          [-43,706.00,  77,766.00]
    → Outliers (IQR)             0 values  (0.00%)

 🏆 Extreme Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 largest:
    #1   62,417  [index 9714]
    #2   62,417  [index 31533]
    #3   61,984  [index 18866]
    #4   61,984  [index 44336]
    #5   61,984  [index 49902]
    #6   61,672  [index 23233]
    #7   61,672  [index 97169]
    #8   61,595  [index 37901]
    #9   61,595  [index 53709]
    #10  61,595  [index 83178]

  Top 10 smallest:
    #1   1  [index 62]
    #2   1  [index 878]
    #3   1  [index 916]
    #4   1  [index 1180]
    #5   1  [index 1269]
    #6   1  [index 1554]
    #7   1  [index 3154]
    #8   1  [index 3302]
    #9   1  [index 5183]
    #10  1  [index 6465]

 🔢 Most & Least Frequent Values
────────────────────────────────────────────────────────────────────────────────
  Top 10 most frequent:
             30  [█████████████████████████] 100.0%  300
          9,756  [████████████████████████░]  97.7%  293
          1,575  [██████████████████████░░░]  86.0%  258
          2,001  [████████████████████░░░░░]  79.3%  238
            918  [████████████████████░░░░░]  79.0%  237
          1,535  [████████████████████░░░░░]  78.0%  234
          6,547  [█████████████████░░░░░░░░]  68.7%  206
         16,498  [█████████████████░░░░░░░░]  67.0%  201
          5,680  [████████████████░░░░░░░░░]  65.0%  195
            226  [████████████████░░░░░░░░░]  64.7%  194

  Top 10 least frequent:
         28,687  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         30,861  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         40,361  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         52,982  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         32,397  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         32,934  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         59,012  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         10,534  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         42,587  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1
         36,544  [░░░░░░░░░░░░░░░░░░░░░░░░░]   0.3%  1

════════════════════════════════════════════════════════════════════════════════
                                End of analysis
════════════════════════════════════════════════════════════════════════════════

**Nessuna pulizia necessaria.**  
Nessun null, dtype già `int64`. I duplicati sono attesi: lo stesso anime può essere raccomandato a partire da diversi anime. Chiave esterna verso `details.csv`.

In [8]:
print(f'Null in recommendation_mal_id : {df_rec["recommendation_mal_id"].isna().sum()}')
print(f'Anime distinti (raccomandati) : {df_rec["recommendation_mal_id"].nunique():,}')

Null in recommendation_mal_id : 0
Anime distinti (raccomandati) : 9,041

### 2.3 Chiave primaria `(mal_id, recommendation_mal_id)`

La coppia `(mal_id, recommendation_mal_id)` identifica univocamente una raccomandazione: lo stesso paio di anime non dovrebbe comparire più di una volta. Verifichiamo dopo la rimozione dei duplicati esatti.

In [9]:
n_pk_dup = df_rec.duplicated(subset=['mal_id', 'recommendation_mal_id'], keep=False).sum()
print(f'Duplicati su (mal_id, recommendation_mal_id): {n_pk_dup}')

if n_pk_dup > 0:
    print('→ Rimozione duplicati sulla chiave primaria...')
    df_rec.drop_duplicates(subset=['mal_id', 'recommendation_mal_id'], keep='first', inplace=True)
    print(f'Righe dopo la rimozione: {len(df_rec):,}')
else:
    print('→ Chiave primaria già univoca, nessuna operazione richiesta.')

Duplicati su (mal_id, recommendation_mal_id): 0
→ Chiave primaria già univoca, nessuna operazione richiesta.

## 3. Data Cleaning

In [10]:
print('=== Riepilogo Dataset Pulito ===')
print(f'Righe originali      : {n_originale:>12,}')
print(f'Righe dopo cleaning  : {len(df_rec):>12,}')
print(f'Righe rimosse totali : {n_originale - len(df_rec):>12,}')
print()
print('Dtypes finali:')
print(df_rec.dtypes)
print()
print('Valori mancanti residui:')
print(df_rec.isnull().sum())

=== Riepilogo Dataset Pulito ===
Righe originali      :      105,249
Righe dopo cleaning  :      105,249
Righe rimosse totali :            0

Dtypes finali:
mal_id                   int64
recommendation_mal_id    int64
dtype: object

Valori mancanti residui:
mal_id                   0
recommendation_mal_id    0
dtype: int64

In [11]:
df_rec.head()

   mal_id  recommendation_mal_id
0    3269                    317
1    3269                   6922
2    3269                    299
3    3269                   3446
4    3269                   5681

## 4. Salvataggio dataset pulito

In [12]:
df_rec.to_csv('../datasets_cleaned/recommendations_clean.csv', index=False)
print('Salvato: datasets_cleaned/recommendations_clean.csv')

Salvato: datasets_cleaned/recommendations_clean.csv