# 13 – Stats

Esplorazione e data cleaning del dataset `stats.csv`.

**Colonne:**
| Colonna | Descrizione |
|---|---|
| `mal_id` | ID dell'anime su MAL |
| `watching` | Numero di utenti che stanno guardando l'anime |
| `completed` | Numero di utenti che hanno completato l'anime |
| `on_hold` | Numero di utenti che hanno messo l'anime in pausa |
| `dropped` | Numero di utenti che hanno abbandonato l'anime |
| `plan_to_watch` | Numero di utenti che intendono guardare l'anime |
| `total` | Totale utenti che hanno l'anime in lista |
| `score_N_votes` | Numero di voti ricevuti per il punteggio N (1–10) |
| `score_N_percentage` | Percentuale di voti per il punteggio N rispetto al totale dei voti |

## 1. Import e caricamento dati

Importiamo le librerie necessarie e carichiamo il file csv. Facciamo una esplorazione generica per capire la struttura e le caratteristiche del dataset.

In [229]:
import pandas as pd
import numpy as np
from dataset_analyzer import analyze
from foreign_key_analyzer import check_fk

df_stats = pd.read_csv('../datasets/stats.csv')
print(f'Shape: {df_stats.shape}')
df_stats.info()
df_stats.head()

Shape: (28955, 27)
<class 'pandas.DataFrame'>
RangeIndex: 28955 entries, 0 to 28954
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   mal_id               28955 non-null  int64
 1   watching             28955 non-null  int64
 2   completed            28955 non-null  int64
 3   on_hold              28955 non-null  int64
 4   dropped              28955 non-null  int64
 5   plan_to_watch        28955 non-null  int64
 6   total                28955 non-null  int64
 7   score_1_votes        28525 non-null  float64
 8   score_1_percentage   28525 non-null  float64
 9   score_2_votes        28525 non-null  float64
 10  score_2_percentage   28525 non-null  float64
 11  score_3_votes        28525 non-null  float64
 12  score_3_percentage   28525 non-null  float64
 13  score_4_votes        28525 non-null  float64
 14  score_4_percentage   28525 non-null  float64
 15  score_5_votes        28525 non-null  float64
 16  score_5_percentage   28525 non-null  float64
 17  score_6_votes        28525 non-null  float64
 18  score_6_percentage   28525 non-null  float64
 19  score_7_votes        28525 non-null  float64
 20  score_7_percentage   28525 non-null  float64
 21  score_8_votes        28525 non-null  float64
 22  score_8_percentage   28525 non-null  float64
 23  score_9_votes        28525 non-null  float64
 24  score_9_percentage   28525 non-null  float64
 25  score_10_votes       28525 non-null  float64
 26  score_10_percentage  28525 non-null  float64
dtypes: float64(20), int64(7)
memory usage: 6.0 MB

,mal_id,watching,completed,on_hold,dropped,plan_to_watch,total,score_1_votes,score_1_percentage,score_2_votes,...,score_6_votes,score_6_percentage,score_7_votes,score_7_percentage,score_8_votes,score_8_percentage,score_9_votes,score_9_percentage,score_10_votes,score_10_percentage
0,59356,7,146,4,20,20,197,2.0,2.2,0.0,...,33.0,36.3,19.0,20.9,2.0,2.2,0.0,0.0,1.0,1.1
1,56036,21,770,8,29,113,941,5.0,1.0,6.0,...,138.0,27.4,144.0,28.6,81.0,16.1,17.0,3.4,40.0,8.0
2,2928,451,14953,302,349,6472,22527,101.0,1.0,93.0,...,2054.0,21.1,2709.0,27.8,1500.0,15.4,875.0,9.0,608.0,6.2
3,3269,726,22790,452,537,9762,34267,120.0,0.8,156.0,...,2457.0,16.0,4157.0,27.0,3075.0,20.0,1919.0,12.5,1400.0,9.1
4,4469,241,6918,182,266,3528,11135,83.0,1.9,104.0,...,888.0,20.6,871.0,20.2,592.0,13.7,308.0,7.1,315.0,7.3

**Osservazioni iniziali:**
- Il dataset contiene **28.955 righe** e **27 colonne**.
- Le prime 7 colonne (`mal_id` + conteggi utenti) sono complete senza null.
- Le 20 colonne `score_N_*` presentano 430 null, corrispondenti ad anime senza voti registrati su MAL (null strutturali).
- I tipi di dati saranno verificati nell'analisi per colonna.

## 1.1 Rimozione duplicati esatti

Prima dell'analisi per colonna, rimuoviamo le righe con valori identici in **tutte** le colonne, mantenendo solo la prima occorrenza.

In [230]:
n_originale = len(df_stats)

mask_dup = df_stats.duplicated(keep=False)
n_righe_coinvolte = mask_dup.sum()
n_gruppi = df_stats[mask_dup].duplicated(keep='first').sum()
n_tenute = n_righe_coinvolte - n_gruppi

print(f'Righe totali coinvolte in duplicazioni : {n_righe_coinvolte:,}')
print(f'  → prime occorrenze mantenute         : {n_tenute:,}')
print(f'  → occorrenze extra rimosse           : {n_gruppi:,}')
print()

df_stats.drop_duplicates(keep='first', inplace=True)
print(f'Righe prima della rimozione : {n_originale:,}')
print(f'Righe dopo la rimozione     : {len(df_stats):,}')

Righe totali coinvolte in duplicazioni : 0
  → prime occorrenze mantenute         : 0
  → occorrenze extra rimosse           : 0

Righe prima della rimozione : 28,955
Righe dopo la rimozione     : 28,955

Nessun duplicato esatto trovato. Tutte le 28.955 righe sono già uniche. Il dataset rimane invariato.

Adesso che siamo sicuri che tutte le righe sono uniche, iniziamo l'analisi per colonne utilizzando la nostra libreria `dataset_analyzer`.

## 2. Analisi colonna per colonna

### 2.1 `mal_id`

Questa colonna è la **chiave primaria** del dataset (ogni riga corrisponde a un anime distinto) ed è anche una **chiave esterna** che referenzia `mal_id` di `details.csv`.

I controlli rilevanti sono:
- **Valori nulli**: non ammessi su una chiave primaria.
- **Duplicati**: non ammessi su una chiave primaria.
- **Integrità referenziale**: ogni ID deve esistere in `details_clean.csv`.

Usiamo `check_fk` per verificare i controlli di integrità referenziale.

In [231]:
df_details = pd.read_csv('../datasets_cleaned/details_clean.csv')

mask_orphan_mal = check_fk(df_stats['mal_id'], df_details['mal_id'], child_df=df_stats)

print(f'Null in mal_id      : {df_stats["mal_id"].isna().sum()}')
print(f'Duplicati in mal_id : {df_stats["mal_id"].duplicated().sum()}')

  Colonna FK  (tabella figlia)        mal_id
  Colonna PK  (tabella padre)         mal_id
────────────────────────────────────────────────────────────────────────────────

Riepilogo conteggi
────────────────────────────────────────────────────────────────────────────────

  Righe totali (tabella figlia)       28,955
  Valori null nella FK                0  (0.00%)
  Valori non-null nella FK            28,955  (100.00%)
  Valori unici nella PK padre         28,955

  ✓  Righe con FK valida              28,955  (100.00%)
  ✗  Righe orfane (FK non in PK)      0  (0.00%)
     → ID orfani unici                0

Valutazione integrità referenziale
────────────────────────────────────────────────────────────────────────────────

Nessuna violazione. Tutti i valori FK esistono nella tabella padre.

Null in mal_id      : 0
Duplicati in mal_id : 0

**Osservazioni:**
- **Nessun valore nullo**: tutti i record hanno un ID anime valido.
- **Nessun duplicato**: la colonna è già una chiave primaria univoca.
- **Integrità referenziale**: non ci sono righe orfane.

Nessuna pulizia necessaria.

### 2.2 `watching`

Numero di utenti che stanno attualmente guardando l'anime.

Colonna numerica intera. I duplicati sono **attesi**: più anime possono avere lo stesso conteggio. Usiamo `analyze`.

In [232]:
analyze(df_stats['watching'])

  Nome serie                     watching
  dtype                          int64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Zeri                           321  (1.11%)
  Positivi                       28,634   (98.89%)
  Negativi                       0   (0.00%)
  Valori unici                   5,077  (17.53%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            0
  Max                            1,838,015
  Range                          1,838,015
  Media                          2,586.64
  Mediana                        57.0000
  Moda/e                         4
  Dev. standard                  16,545.37
  Varianza                       273,749,396
  Errore std (SEM)               97.2332
  IQR  (Q3 − Q1)                 478.5000
  Q1  (25° pct)                  11.0000
  Q3  (75° pct)                  489.5000
  P5  ( 5° pct)                  3.0000
  P95 (95° pct)                  11,582.90
  Coefficiente di variazione     639.65%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -706.7500
  Soglia alta   (Q3 + 1.5×IQR)   1,207.25
  Outlier rilevati               4,755  (16.42%)

  Top 5 outlier estremi (per valore assoluto):
    [17919]  1,838,015
    [2454]  507,711
    [16833]  449,814
    [2802]  376,388
    [9671]  375,910

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  0 – 91,900                         28,849    99.6%
  91,900 – 183,801                       85     0.3%
  183,801 – 275,702                      12     0.0%
  275,702 – 367,603                       4     0.0%
  367,603 – 459,503                       3     0.0%
  459,503 – 551,404                       1     0.0%
  551,404 – 643,305                       0     0.0%
  643,305 – 735,206                       0     0.0%
  735,206 – 827,106                       0     0.0%
  827,106 – 919,007                       0     0.0%
  919,007 – 1,010,908                     0     0.0%
  1,010,908 – 1,102,809                   0     0.0%
  1,102,809 – 1,194,709                   0     0.0%
  1,194,709 – 1,286,610                   0     0.0%
  1,286,610 – 1,378,511                   0     0.0%
  1,378,511 – 1,470,412                   0     0.0%
  1,470,412 – 1,562,312                   0     0.0%
  1,562,312 – 1,654,213                   0     0.0%
  1,654,213 – 1,746,114                   0     0.0%
  1,746,114 – 1,838,015                   1     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   1,838,015
    #2   507,711
    #3   449,814
    #4   376,388
    #5   375,910
    #6   366,847
    #7   358,442
    #8   293,191
    #9   278,645
    #10  239,111

  I 10 più piccoli:
    #1   0
    #2   0
    #3   0
    #4   0
    #5   0
    #6   0
    #7   0
    #8   0
    #9   0
    #10  0

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                     4        1,281     4.4%
                     3        1,214     4.2%
                     5          933     3.2%
                     2          910     3.1%
                     6          689     2.4%
                     7          501     1.7%
                     8          461     1.6%
                    14          384     1.3%
                    15          360     1.2%
                     9          358     1.2%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                10,332            1     0.0%
                11,349            1     0.0%
                 1,221            1     0.0%
                14,794            1     0.0%
                 1,284            1     0.0%
                19,069            1     0.0%
                41,047            1     0.0%
                 6,050            1     0.0%
               130,203            1     0.0%
                 7,022            1     0.0%

**Osservazioni:**
- Nessun valore null. Il dtype è già `int64` che è adeguato.
- I valori sono ≥ 0 come atteso per un conteggio. Stampiamo i valori estremi per verificare se si tratta di un'anomalia.

In [233]:
df_details_url = pd.read_csv('../datasets/details.csv', usecols=['mal_id', 'title', 'url'])
estremi_watching = (
    df_stats[df_stats["watching"] >= 275702][["mal_id", "watching", "completed", "total"]]
    .sort_values("watching", ascending=False)
    .merge(df_details_url, on="mal_id", how="left")
)
print(f"Righe con watching >= 275,702: {len(estremi_watching)}")
estremi_watching

Righe con watching >= 275,702: 9

,mal_id,watching,completed,total,title,url
0,21,1838015,14,2581610,One Piece,https://myanimelist.net/anime/21/One_Piece
1,34572,507711,737466,1832019,Black Clover,https://myanimelist.net/anime/34572/Black_Clover
2,1735,449814,1775074,2668197,Naruto: Shippuuden,https://myanimelist.net/anime/1735/Naruto__Shi...
3,34566,376388,87794,913313,Boruto: Naruto Next Generations,https://myanimelist.net/anime/34566/Boruto__Na...
4,11061,375910,2109985,3081045,Hunter x Hunter (2011),https://myanimelist.net/anime/11061/Hunter_x_H...
5,269,366847,1102401,2135419,Bleach,https://myanimelist.net/anime/269/Bleach
6,40748,358442,2234604,2880368,Jujutsu Kaisen,https://myanimelist.net/anime/40748/Jujutsu_Ka...
7,40028,293191,1697177,2202042,Shingeki no Kyojin: The Final Season,https://myanimelist.net/anime/40028/Shingeki_n...
8,5114,278645,2586001,3576614,Fullmetal Alchemist: Brotherhood,https://myanimelist.net/anime/5114/Fullmetal_A...

I valori estremi corrispondono ad anime molto famosi e qundi non si tratta di anomalie. 

Nessuna pulizia necessaria.

### 2.3 `completed`

Numero di utenti che hanno completato l'anime.

Colonna numerica intera. I duplicati sono **attesi**: più anime possono avere lo stesso conteggio. Usiamo `analyze`.

In [234]:
analyze(df_stats['completed'])

  Nome serie                     completed
  dtype                          int64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Zeri                           702  (2.42%)
  Positivi                       28,253   (97.58%)
  Negativi                       0   (0.00%)
  Valori unici                   10,080  (34.81%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            0
  Max                            3,716,436
  Range                          3,716,436
  Media                          24,838.18
  Mediana                        431.0000
  Moda/e                         0
  Dev. standard                  123,576.86
  Varianza                       15,271,241,056
  Errore std (SEM)               726.2320
  IQR  (Q3 − Q1)                 4,344.00
  Q1  (25° pct)                  86.0000
  Q3  (75° pct)                  4,430.00
  P5  ( 5° pct)                  26.0000
  P95 (95° pct)                  108,698.10
  Coefficiente di variazione     497.53%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -6,430.00
  Soglia alta   (Q3 + 1.5×IQR)   10,946.00
  Outlier rilevati               5,094  (17.59%)

  Top 5 outlier estremi (per valore assoluto):
    [22010]  3,716,436
    [4788]  3,474,406
    [17990]  2,998,253
    [2633]  2,812,949
    [12300]  2,806,977

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  0 – 185,821                        28,049    96.9%
  185,821 – 371,643                     487     1.7%
  371,643 – 557,465                     167     0.6%
  557,465 – 743,287                      82     0.3%
  743,287 – 929,109                      55     0.2%
  929,109 – 1,114,930                    26     0.1%
  1,114,930 – 1,300,752                  26     0.1%
  1,300,752 – 1,486,574                  18     0.1%
  1,486,574 – 1,672,396                  10     0.0%
  1,672,396 – 1,858,218                  16     0.1%
  1,858,218 – 2,044,039                   2     0.0%
  2,044,039 – 2,229,861                   2     0.0%
  2,229,861 – 2,415,683                   4     0.0%
  2,415,683 – 2,601,505                   4     0.0%
  2,601,505 – 2,787,327                   2     0.0%
  2,787,327 – 2,973,148                   2     0.0%
  2,973,148 – 3,158,970                   1     0.0%
  3,158,970 – 3,344,792                   0     0.0%
  3,344,792 – 3,530,614                   1     0.0%
  3,530,614 – 3,716,436                   1     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   3,716,436
    #2   3,474,406
    #3   2,998,253
    #4   2,812,949
    #5   2,806,977
    #6   2,766,326
    #7   2,633,970
    #8   2,586,001
    #9   2,550,243
    #10  2,525,762

  I 10 più piccoli:
    #1   0
    #2   0
    #3   0
    #4   0
    #5   0
    #6   0
    #7   0
    #8   0
    #9   0
    #10  0

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                     0          702     2.4%
                    28          345     1.2%
                    29          311     1.1%
                    27          277     1.0%
                    30          247     0.9%
                    31          236     0.8%
                    33          231     0.8%
                    32          217     0.7%
                    34          197     0.7%
                    35          174     0.6%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                 2,387            1     0.0%
                16,119            1     0.0%
               140,676            1     0.0%
                17,353            1     0.0%
                 3,793            1     0.0%
                20,487            1     0.0%
                 5,657            1     0.0%
                   950            1     0.0%
                 6,313            1     0.0%
               114,763            1     0.0%

**Osservazioni:**
- Nessun null. Il dtype già `int64` che è adeguato.
- I valori sono ≥ 0 come atteso per un conteggio.

**Nessuna pulizia necessaria.**

### 2.4 `on_hold`

Numero di utenti che hanno messo l'anime in pausa.

Colonna numerica intera. I duplicati sono **attesi**: più anime possono avere lo stesso conteggio. Usiamo `analyze`.

In [235]:
analyze(df_stats['on_hold'])

  Nome serie                     on_hold
  dtype                          int64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Zeri                           1,487  (5.14%)
  Positivi                       27,468   (94.86%)
  Negativi                       0   (0.00%)
  Valori unici                   3,764  (13.00%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            0
  Max                            308,583
  Range                          308,583
  Media                          974.9353
  Mediana                        22.0000
  Moda/e                         1
  Dev. standard                  5,151.36
  Varianza                       26,536,530
  Errore std (SEM)               30.2733
  IQR  (Q3 − Q1)                 226.0000
  Q1  (25° pct)                  4.0000
  Q3  (75° pct)                  230.0000
  P5  ( 5° pct)                  0.0000
  P95 (95° pct)                  4,506.60
  Coefficiente di variazione     528.38%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -335.0000
  Soglia alta   (Q3 + 1.5×IQR)   569.0000
  Outlier rilevati               4,592  (15.86%)

  Top 5 outlier estremi (per valore assoluto):
    [17919]  308,583
    [2502]  195,339
    [2454]  152,060
    [9671]  148,406
    [16833]  144,765

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  0 – 15,429                         28,578    98.7%
  15,429 – 30,858                       243     0.8%
  30,858 – 46,287                        76     0.3%
  46,287 – 61,716                        26     0.1%
  61,716 – 77,145                        14     0.0%
  77,145 – 92,574                         4     0.0%
  92,574 – 108,004                        3     0.0%
  108,004 – 123,433                       4     0.0%
  123,433 – 138,862                       1     0.0%
  138,862 – 154,291                       4     0.0%
  154,291 – 169,720                       0     0.0%
  169,720 – 185,149                       0     0.0%
  185,149 – 200,578                       1     0.0%
  200,578 – 216,008                       0     0.0%
  216,008 – 231,437                       0     0.0%
  231,437 – 246,866                       0     0.0%
  246,866 – 262,295                       0     0.0%
  262,295 – 277,724                       0     0.0%
  277,724 – 293,153                       0     0.0%
  293,153 – 308,583                       1     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   308,583
    #2   195,339
    #3   152,060
    #4   148,406
    #5   144,765
    #6   141,120
    #7   128,020
    #8   118,574
    #9   117,966
    #10  114,486

  I 10 più piccoli:
    #1   0
    #2   0
    #3   0
    #4   0
    #5   0
    #6   0
    #7   0
    #8   0
    #9   0
    #10  0

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                     1        1,932     6.7%
                     2        1,828     6.3%
                     3        1,516     5.2%
                     0        1,487     5.1%
                     4        1,220     4.2%
                     5          997     3.4%
                     6          771     2.7%
                     7          668     2.3%
                     8          524     1.8%
                     9          459     1.6%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                 3,025            1     0.0%
                 7,217            1     0.0%
                23,102            1     0.0%
                 5,403            1     0.0%
                31,524            1     0.0%
                 6,254            1     0.0%
                 2,893            1     0.0%
                 4,862            1     0.0%
                24,604            1     0.0%
                 4,064            1     0.0%

**Osservazioni:**
- Nessun null. Dtype già `int64`.
- I valori sono ≥ 0 come atteso per un conteggio.

**Nessuna pulizia necessaria.**

### 2.5 `dropped`

Numero di utenti che hanno abbandonato l'anime.

Colonna numerica intera. I duplicati sono **attesi**: più anime possono avere lo stesso conteggio. Usiamo `analyze`.

In [236]:
analyze(df_stats['dropped'])

  Nome serie                     dropped
  dtype                          int64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Zeri                           450  (1.55%)
  Positivi                       28,505   (98.45%)
  Negativi                       0   (0.00%)
  Valori unici                   4,070  (14.06%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            0
  Max                            237,819
  Range                          237,819
  Media                          1,301.31
  Mediana                        85.0000
  Moda/e                         0, 28
  Dev. standard                  5,930.20
  Varianza                       35,167,308
  Errore std (SEM)               34.8504
  IQR  (Q3 − Q1)                 225.0000
  Q1  (25° pct)                  33.0000
  Q3  (75° pct)                  258.0000
  P5  ( 5° pct)                  12.0000
  P95 (95° pct)                  6,941.60
  Coefficiente di variazione     455.71%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -304.5000
  Soglia alta   (Q3 + 1.5×IQR)   595.5000
  Outlier rilevati               4,588  (15.85%)

  Top 5 outlier estremi (per valore assoluto):
    [2802]  237,819
    [2502]  220,647
    [6099]  208,578
    [17919]  206,070
    [16833]  161,416

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  0 – 11,890                         28,110    97.1%
  11,890 – 23,781                       535     1.8%
  23,781 – 35,672                       154     0.5%
  35,672 – 47,563                        73     0.3%
  47,563 – 59,454                        40     0.1%
  59,454 – 71,345                        22     0.1%
  71,345 – 83,236                         6     0.0%
  83,236 – 95,127                         3     0.0%
  95,127 – 107,018                        2     0.0%
  107,018 – 118,909                       0     0.0%
  118,909 – 130,800                       1     0.0%
  130,800 – 142,691                       3     0.0%
  142,691 – 154,582                       0     0.0%
  154,582 – 166,473                       2     0.0%
  166,473 – 178,364                       0     0.0%
  178,364 – 190,255                       0     0.0%
  190,255 – 202,146                       0     0.0%
  202,146 – 214,037                       2     0.0%
  214,037 – 225,928                       1     0.0%
  225,928 – 237,819                       1     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   237,819
    #2   220,647
    #3   208,578
    #4   206,070
    #5   161,416
    #6   154,795
    #7   141,091
    #8   137,128
    #9   133,168
    #10  126,242

  I 10 più piccoli:
    #1   0
    #2   0
    #3   0
    #4   0
    #5   0
    #6   0
    #7   0
    #8   0
    #9   0
    #10  0

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                    28          450     1.6%
                     0          450     1.6%
                    30          446     1.5%
                    29          443     1.5%
                    31          414     1.4%
                    32          377     1.3%
                    27          355     1.2%
                    33          314     1.1%
                    26          301     1.0%
                    34          281     1.0%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                 1,440            1     0.0%
                37,884            1     0.0%
                 8,512            1     0.0%
                36,635            1     0.0%
                 3,515            1     0.0%
                 1,176            1     0.0%
                 2,370            1     0.0%
                 1,043            1     0.0%
                 1,084            1     0.0%
                 4,812            1     0.0%

**Osservazioni:**
- Nessun null. Dtype già `int64`.
- I valori sono ≥ 0 come atteso per un conteggio.

**Nessuna pulizia necessaria.**

### 2.6 `plan_to_watch`

Numero di utenti che intendono guardare l'anime.

Colonna numerica intera. I duplicati sono **attesi**: più anime possono avere lo stesso conteggio. Usiamo `analyze`.

In [237]:
analyze(df_stats['plan_to_watch'])

  Nome serie                     plan_to_watch
  dtype                          int64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Zeri                           0  (0.00%)
  Positivi                       28,955   (100.00%)
  Negativi                       0   (0.00%)
  Valori unici                   9,120  (31.50%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            2
  Max                            687,110
  Range                          687,108
  Media                          9,058.57
  Mediana                        335.0000
  Moda/e                         18
  Dev. standard                  30,335.00
  Varianza                       920,212,256
  Errore std (SEM)               178.2716
  IQR  (Q3 − Q1)                 3,005.50
  Q1  (25° pct)                  52.0000
  Q3  (75° pct)                  3,057.50
  P5  ( 5° pct)                  17.0000
  P95 (95° pct)                  49,714.50
  Coefficiente di variazione     334.88%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -4,456.25
  Soglia alta   (Q3 + 1.5×IQR)   7,565.75
  Outlier rilevati               4,937  (17.05%)

  Top 5 outlier estremi (per valore assoluto):
    [23288]  687,110
    [6593]  529,859
    [4253]  493,291
    [19488]  484,134
    [16162]  483,053

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  2 – 34,357                         26,939    93.0%
  34,357 – 68,712                       963     3.3%
  68,712 – 103,068                      447     1.5%
  103,068 – 137,423                     234     0.8%
  137,423 – 171,779                     134     0.5%
  171,779 – 206,134                      89     0.3%
  206,134 – 240,489                      48     0.2%
  240,489 – 274,845                      38     0.1%
  274,845 – 309,200                      19     0.1%
  309,200 – 343,556                      20     0.1%
  343,556 – 377,911                      12     0.0%
  377,911 – 412,266                       6     0.0%
  412,266 – 446,622                       1     0.0%
  446,622 – 480,977                       0     0.0%
  480,977 – 515,333                       3     0.0%
  515,333 – 549,688                       1     0.0%
  549,688 – 584,043                       0     0.0%
  584,043 – 618,399                       0     0.0%
  618,399 – 652,754                       0     0.0%
  652,754 – 687,110                       1     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   687,110
    #2   529,859
    #3   493,291
    #4   484,134
    #5   483,053
    #6   432,621
    #7   406,676
    #8   404,281
    #9   403,435
    #10  390,957

  I 10 più piccoli:
    #1   2
    #2   2
    #3   2
    #4   2
    #5   2
    #6   2
    #7   3
    #8   3
    #9   3
    #10  3

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                    18          329     1.1%
                    19          315     1.1%
                    20          294     1.0%
                    17          279     1.0%
                    22          275     0.9%
                    16          274     0.9%
                    21          257     0.9%
                    23          245     0.8%
                    24          223     0.8%
                    26          215     0.7%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                94,249            1     0.0%
                15,729            1     0.0%
                 7,839            1     0.0%
                31,967            1     0.0%
                85,284            1     0.0%
                33,878            1     0.0%
               131,969            1     0.0%
               117,358            1     0.0%
                15,228            1     0.0%
                43,561            1     0.0%

**Osservazioni:**
- Nessun null. Dtype già `int64`.
- I valori sono ≥ 0 come atteso per un conteggio.

**Nessuna pulizia necessaria.**

### 2.7 `total`

Totale utenti che hanno l'anime in lista. Deve corrispondere alla somma delle cinque categorie precedenti.

Colonna numerica intera. I duplicati sono **attesi**: più anime possono avere lo stesso conteggio. Usiamo `analyze`.

In [238]:
analyze(df_stats['total'])

  Nome serie                     total
  dtype                          int64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,955  (100.00%)
  Null / NaN                     0  (0.00%)
  Zeri                           0  (0.00%)
  Positivi                       28,955   (100.00%)
  Negativi                       0   (0.00%)
  Valori unici                   12,265  (42.36%)

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            23
  Max                            4,230,824
  Range                          4,230,801
  Media                          38,759.63
  Mediana                        1,077.00
  Moda/e                         80
  Dev. standard                  167,392.08
  Varianza                       28,020,108,973
  Errore std (SEM)               983.7237
  IQR  (Q3 − Q1)                 8,966.00
  Q1  (25° pct)                  233.0000
  Q3  (75° pct)                  9,199.00
  P5  ( 5° pct)                  83.0000
  P95 (95° pct)                  182,322.00
  Coefficiente di variazione     431.87%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -13,216.00
  Soglia alta   (Q3 + 1.5×IQR)   22,648.00
  Outlier rilevati               5,044  (17.42%)

  Top 5 outlier estremi (per valore assoluto):
    [22010]  4,230,824
    [4788]  4,171,073
    [6593]  3,576,614
    [17990]  3,431,091
    [12300]  3,323,322

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  23 – 211,563                       27,690    95.6%
  211,563 – 423,103                     663     2.3%
  423,103 – 634,643                     227     0.8%
  634,643 – 846,183                     131     0.5%
  846,183 – 1,057,723                    78     0.3%
  1,057,723 – 1,269,263                  48     0.2%
  1,269,263 – 1,480,803                  24     0.1%
  1,480,803 – 1,692,343                  23     0.1%
  1,692,343 – 1,903,883                  25     0.1%
  1,903,883 – 2,115,423                  10     0.0%
  2,115,423 – 2,326,963                  12     0.0%
  2,326,963 – 2,538,503                   6     0.0%
  2,538,503 – 2,750,043                   5     0.0%
  2,750,043 – 2,961,583                   3     0.0%
  2,961,583 – 3,173,123                   3     0.0%
  3,173,123 – 3,384,663                   3     0.0%
  3,384,663 – 3,596,203                   2     0.0%
  3,596,203 – 3,807,743                   0     0.0%
  3,807,743 – 4,019,283                   0     0.0%
  4,019,283 – 4,230,824                   2     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   4,230,824
    #2   4,171,073
    #3   3,576,614
    #4   3,431,091
    #5   3,323,322
    #6   3,232,570
    #7   3,212,928
    #8   3,081,045
    #9   3,035,526
    #10  2,984,930

  I 10 più piccoli:
    #1   23
    #2   24
    #3   25
    #4   25
    #5   26
    #6   26
    #7   27
    #8   27
    #9   27
    #10  27

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                    80          127     0.4%
                    83          120     0.4%
                    79          119     0.4%
                    82          116     0.4%
                    81          111     0.4%
                    78          111     0.4%
                    84          110     0.4%
                    86          107     0.4%
                    77           97     0.3%
                    75           93     0.3%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                 5,526            1     0.0%
                27,334            1     0.0%
               249,662            1     0.0%
                46,445            1     0.0%
                 2,397            1     0.0%
                11,536            1     0.0%
                75,100            1     0.0%
                 9,645            1     0.0%
                 2,588            1     0.0%
                13,758            1     0.0%

**Osservazioni:**
- Nessun null. Dtype già `int64`.
- I valori sono ≥ 0 come atteso per un conteggio.
- Verifichiamo che `total` sia uguale alla somma delle cinque categorie utente.

In [239]:
count_cols = ['watching', 'completed', 'on_hold', 'dropped', 'plan_to_watch', 'total']
somma_categorie = df_stats[['watching', 'completed', 'on_hold', 'dropped', 'plan_to_watch']].sum(axis=1)
discrepanze = (somma_categorie != df_stats['total']).sum()
print(f'Righe dove total ≠ somma categorie: {discrepanze:,}')

Righe dove total ≠ somma categorie: 0

Non ci sono righe dove `total` non corrisponde alla somma delle categorie. 

Nessuna pulizia necessaria.

### 2.8 Colonne `score_N_votes` e `score_N_percentage` (N = 1–10)

Tutte e 20 le colonne presentano lo stesso numero di null (430). Verifichiamo se si tratta delle stesse righe, ovvero anime che non hanno ancora ricevuto voti su MAL.

In [240]:
score_votes_cols = [
    "score_1_votes", "score_2_votes", "score_3_votes", "score_4_votes", "score_5_votes",
    "score_6_votes", "score_7_votes", "score_8_votes", "score_9_votes", "score_10_votes"
]
score_pct_cols = [
    "score_1_percentage", "score_2_percentage", "score_3_percentage", "score_4_percentage", "score_5_percentage",
    "score_6_percentage", "score_7_percentage", "score_8_percentage", "score_9_percentage", "score_10_percentage"
]
score_cols = score_votes_cols + score_pct_cols

# Verifica che i null siano nelle stesse righe per tutti i campi score
mask_no_score = df_stats["score_1_votes"].isna()
tutti_stessi = df_stats[score_cols].isna().eq(mask_no_score, axis=0).all(axis=None)
print(f"Righe senza dati di voto                          : {mask_no_score.sum():,}")
print(f"Null nelle stesse righe per tutti i campi score   : {tutti_stessi}")
print()
print("Campione di 10 righe con score nulli:")
df_stats[mask_no_score][["mal_id", "watching", "completed", "on_hold", "dropped", "plan_to_watch", "total"]].sample(10, random_state=42)

Righe senza dati di voto                          : 430
Null nelle stesse righe per tutti i campi score   : True

Caratteristiche anime senza score (colonne di conteggio):

Campione di 10 righe con score nulli:

       mal_id  watching  completed  on_hold  dropped  plan_to_watch  total
28620   35854         0          0        0        0           1920   1920
5005    61269         4          0        0        0          10128  10132
11463   62050         1          0        0        0           1322   1323
1983    62430         0          0        0        0           1721   1721
24779   61014         0          0        0        0           2966   2966
26039   61073         0          0        0        0            333    333
10296   56906         1          1        1        0          29085  29088
9920    60831         0          0        0        0           1488   1488
10828   61567         0          0        0        0            101    101
11253   62507         0          0        0        0            394    394

Le 430 righe con valutazione nullo sono le stesse in tutte le colonne. Questo è strutturale e si riferisce ad anime che non hanno ancora ricevuto nessun voto. Vanno mantenute perchè le righe forniscono dati sulle altre colonne non nulle.  

Usiamo `analyze` per continuare la verifica sul resto delle righe. I duplicati sono **attesi**: diversi anime possono ricevere lo stesso numero di voti o la stessa percentuale.

In [241]:
_ = df_stats[score_cols].apply(analyze)

  Nome serie                     score_1_votes
  dtype                          float64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,525  (98.51%)
  Null / NaN                     430  (1.49%)
  Zeri                           1,214  (4.19%)
  Positivi                       27,311   (94.32%)
  Negativi                       0   (0.00%)
  Valori unici                   1,486  (5.13%)
  Valori float                   0

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            0.0000
  Max                            50,279.00
  Range                          50,279.00
  Media                          143.4331
  Mediana                        17.0000
  Moda/e                         1.0000
  Dev. standard                  930.8225
  Varianza                       866,430.44
  Errore std (SEM)               5.5113
  IQR  (Q3 − Q1)                 53.0000
  Q1  (25° pct)                  4.0000
  Q3  (75° pct)                  57.0000
  P5  ( 5° pct)                  1.0000
  P95 (95° pct)                  484.0000
  Coefficiente di variazione     648.96%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -75.5000
  Soglia alta   (Q3 + 1.5×IQR)   136.5000
  Outlier rilevati               3,937  (13.60%)

  Top 5 outlier estremi (per valore assoluto):
    [6593]  50,279.00
    [2673]  47,845.00
    [27608]  38,954.00
    [20998]  37,624.00
    [19534]  33,153.00

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  0 – 2,513                          28,272    99.1%
  2,513 – 5,027                         160     0.6%
  5,027 – 7,541                          43     0.2%
  7,541 – 10,055                         14     0.0%
  10,055 – 12,569                        10     0.0%
  12,569 – 15,083                         6     0.0%
  15,083 – 17,597                         6     0.0%
  17,597 – 20,111                         2     0.0%
  20,111 – 22,625                         2     0.0%
  22,625 – 25,139                         0     0.0%
  25,139 – 27,653                         1     0.0%
  27,653 – 30,167                         3     0.0%
  30,167 – 32,681                         1     0.0%
  32,681 – 35,195                         1     0.0%
  35,195 – 37,709                         1     0.0%
  37,709 – 40,223                         1     0.0%
  40,223 – 42,737                         0     0.0%
  42,737 – 45,251                         0     0.0%
  45,251 – 47,765                         0     0.0%
  47,765 – 50,279                         2     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   50,279.00
    #2   47,845.00
    #3   38,954.00
    #4   37,624.00
    #5   33,153.00
    #6   31,294.00
    #7   30,154.00
    #8   29,470.00
    #9   29,341.00
    #10  25,980.00

  I 10 più piccoli:
    #1   0.0000
    #2   0.0000
    #3   0.0000
    #4   0.0000
    #5   0.0000
    #6   0.0000
    #7   0.0000
    #8   0.0000
    #9   0.0000
    #10  0.0000

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                1.0000        2,508     8.7%
                2.0000        1,876     6.5%
                0.0000        1,214     4.2%
                3.0000        1,022     3.5%
                4.0000          917     3.2%
                5.0000          845     2.9%
                6.0000          667     2.3%
                7.0000          630     2.2%
                8.0000          608     2.1%
                9.0000          540     1.9%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
              868.0000            1     0.0%
              1,136.00            1     0.0%
              569.0000            1     0.0%
              1,404.00            1     0.0%
              1,347.00            1     0.0%

              1,317.00            1     0.0%
              2,979.00            1     0.0%
              745.0000            1     0.0%
              4,021.00            1     0.0%
              353.0000            1     0.0%


  Nome serie                     score_2_votes
  dtype                          float64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,525  (98.51%)
  Null / NaN                     430  (1.49%)
  Zeri                           5,240  (18.10%)
  Positivi                       23,285   (80.42%)
  Negativi                       0   (0.00%)
  Valori unici                   1,464  (5.06%)
  Valori float                   0

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            0.0000
  Max                            36,397.00
  Range                          36,397.00
  Media                          126.2279
  Mediana                        9.0000
  Moda/e                         0.0000
  Dev. standard                  711.5652
  Varianza                       506,325.05
  Errore std (SEM)               4.2131
  IQR  (Q3 − Q1)                 45.0000
  Q1  (25° pct)                  1.0000
  Q3  (75° pct)                  46.0000
  P5  ( 5° pct)                  0.0000
  P95 (95° pct)                  490.0000
  Coefficiente di variazione     563.71%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -66.5000
  Soglia alta   (Q3 + 1.5×IQR)   113.5000
  Outlier rilevati               4,160  (14.37%)

  Top 5 outlier estremi (per valore assoluto):
    [27608]  36,397.00
    [23654]  33,480.00
    [20998]  30,833.00
    [23662]  29,093.00
    [24922]  20,344.00

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  0 – 1,819                          28,177    98.8%
  1,819 – 3,639                         204     0.7%
  3,639 – 5,459                          79     0.3%
  5,459 – 7,279                          27     0.1%
  7,279 – 9,099                           5     0.0%
  9,099 – 10,919                         11     0.0%
  10,919 – 12,738                         7     0.0%
  12,738 – 14,558                         2     0.0%
  14,558 – 16,378                         4     0.0%
  16,378 – 18,198                         2     0.0%
  18,198 – 20,018                         2     0.0%
  20,018 – 21,838                         1     0.0%
  21,838 – 23,658                         0     0.0%
  23,658 – 25,477                         0     0.0%
  25,477 – 27,297                         0     0.0%
  27,297 – 29,117                         1     0.0%
  29,117 – 30,937                         1     0.0%
  30,937 – 32,757                         0     0.0%
  32,757 – 34,577                         1     0.0%
  34,577 – 36,397                         1     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   36,397.00
    #2   33,480.00
    #3   30,833.00
    #4   29,093.00
    #5   20,344.00
    #6   19,640.00
    #7   19,569.00
    #8   18,077.00
    #9   17,500.00
    #10  16,221.00

  I 10 più piccoli:
    #1   0.0000
    #2   0.0000
    #3   0.0000
    #4   0.0000
    #5   0.0000
    #6   0.0000
    #7   0.0000
    #8   0.0000
    #9   0.0000
    #10  0.0000

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                0.0000        5,240    18.1%
                1.0000        2,204     7.6%
                2.0000        1,535     5.3%
                3.0000        1,185     4.1%
                4.0000        1,016     3.5%
                5.0000          889     3.1%
                6.0000          697     2.4%
                7.0000          629     2.2%
                8.0000          551     1.9%
                9.0000          545     1.9%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
              940.0000            1     0.0%
              675.0000            1     0.0%
              802.0000            1     0.0%
              437.0000            1     0.0%
              1,789.00            1     0.0%
              1,776.00            1     0.0%
              1,264.00            1     0.0%
              689.0000            1     0.0%
              676.0000            1     0.0%
              1,147.00            1     0.0%


  Nome serie                     score_3_votes
  dtype                          float64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,525  (98.51%)
  Null / NaN                     430  (1.49%)
  Zeri                           4,064  (14.04%)
  Positivi                       24,461   (84.48%)
  Negativi                       0   (0.00%)
  Valori unici                   1,949  (6.73%)
  Valori float                   0

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            0.0000
  Max                            59,478.00
  Range                          59,478.00
  Media                          215.1770
  Mediana                        14.0000
  Moda/e                         0.0000
  Dev. standard                  1,102.87
  Varianza                       1,216,326
  Errore std (SEM)               6.5300
  IQR  (Q3 − Q1)                 75.0000
  Q1  (25° pct)                  2.0000
  Q3  (75° pct)                  77.0000
  P5  ( 5° pct)                  0.0000
  P95 (95° pct)                  886.6000
  Coefficiente di variazione     512.54%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -110.5000
  Soglia alta   (Q3 + 1.5×IQR)   189.5000
  Outlier rilevati               4,295  (14.83%)

  Top 5 outlier estremi (per valore assoluto):
    [23654]  59,478.00
    [27608]  48,953.00
    [23662]  48,227.00
    [24922]  35,511.00
    [24925]  31,892.00

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  0 – 2,973                          28,133    98.6%
  2,973 – 5,947                         243     0.9%
  5,947 – 8,921                          84     0.3%
  8,921 – 11,895                         30     0.1%
  11,895 – 14,869                        10     0.0%
  14,869 – 17,843                         8     0.0%
  17,843 – 20,817                         7     0.0%
  20,817 – 23,791                         0     0.0%
  23,791 – 26,765                         3     0.0%
  26,765 – 29,739                         1     0.0%
  29,739 – 32,712                         2     0.0%
  32,712 – 35,686                         1     0.0%
  35,686 – 38,660                         0     0.0%
  38,660 – 41,634                         0     0.0%
  41,634 – 44,608                         0     0.0%
  44,608 – 47,582                         0     0.0%
  47,582 – 50,556                         2     0.0%
  50,556 – 53,530                         0     0.0%
  53,530 – 56,504                         0     0.0%
  56,504 – 59,478                         1     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   59,478.00
    #2   48,953.00
    #3   48,227.00
    #4   35,511.00
    #5   31,892.00
    #6   30,265.00
    #7   28,702.00
    #8   25,700.00
    #9   25,238.00
    #10  24,782.00

  I 10 più piccoli:
    #1   0.0000
    #2   0.0000
    #3   0.0000
    #4   0.0000
    #5   0.0000
    #6   0.0000
    #7   0.0000
    #8   0.0000
    #9   0.0000
    #10  0.0000

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                0.0000        4,064    14.0%
                1.0000        1,973     6.8%
                2.0000        1,375     4.7%
                3.0000        1,060     3.7%
                4.0000          871     3.0%
                5.0000          792     2.7%
                6.0000          695     2.4%
                7.0000          601     2.1%
                8.0000          565     2.0%
                9.0000          446     1.5%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
              1,011.00            1     0.0%
              2,005.00            1     0.0%
              1,377.00            1     0.0%
              3,432.00            1     0.0%
              3,423.00            1     0.0%
              2,914.00            1     0.0%
              1,418.00            1     0.0%
              3,048.00            1     0.0%
              2,481.00            1     0.0%
              4,134.00            1     0.0%


  Nome serie                     score_4_votes
  dtype                          float64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,525  (98.51%)
  Null / NaN                     430  (1.49%)
  Zeri                           322  (1.11%)
  Positivi                       28,203   (97.40%)
  Negativi                       0   (0.00%)
  Valori unici                   2,902  (10.02%)
  Valori float                   0

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            0.0000
  Max                            112,961.00
  Range                          112,961.00
  Media                          469.8474
  Mediana                        26.0000
  Moda/e                         2.0000
  Dev. standard                  2,219.09
  Varianza                       4,924,357
  Errore std (SEM)               13.1390
  IQR  (Q3 − Q1)                 151.0000
  Q1  (25° pct)                  6.0000
  Q3  (75° pct)                  157.0000
  P5  ( 5° pct)                  2.0000
  P95 (95° pct)                  2,048.00
  Coefficiente di variazione     472.30%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -220.5000
  Soglia alta   (Q3 + 1.5×IQR)   383.5000
  Outlier rilevati               4,436  (15.32%)

  Top 5 outlier estremi (per valore assoluto):
    [23654]  112,961.00
    [23662]  90,975.00
    [27608]  75,781.00
    [24922]  72,568.00
    [24925]  67,255.00

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  0 – 5,648                          28,035    98.3%
  5,648 – 11,296                        306     1.1%
  11,296 – 16,944                       103     0.4%
  16,944 – 22,592                        41     0.1%
  22,592 – 28,240                        16     0.1%
  28,240 – 33,888                         7     0.0%
  33,888 – 39,536                         5     0.0%
  39,536 – 45,184                         3     0.0%
  45,184 – 50,832                         2     0.0%
  50,832 – 56,480                         2     0.0%
  56,480 – 62,128                         0     0.0%
  62,128 – 67,776                         1     0.0%
  67,776 – 73,424                         1     0.0%
  73,424 – 79,072                         1     0.0%
  79,072 – 84,720                         0     0.0%
  84,720 – 90,368                         0     0.0%
  90,368 – 96,016                         1     0.0%
  96,016 – 101,664                        0     0.0%
  101,664 – 107,312                       0     0.0%
  107,312 – 112,961                       1     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   112,961.00
    #2   90,975.00
    #3   75,781.00
    #4   72,568.00
    #5   67,255.00
    #6   52,041.00
    #7   51,577.00
    #8   49,627.00
    #9   45,607.00
    #10  45,042.00

  I 10 più piccoli:
    #1   0.0000
    #2   0.0000
    #3   0.0000
    #4   0.0000
    #5   0.0000
    #6   0.0000
    #7   0.0000
    #8   0.0000
    #9   0.0000
    #10  0.0000

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                2.0000        2,742     9.5%
                3.0000        1,321     4.6%
                4.0000          952     3.3%
                1.0000          916     3.2%
                5.0000          753     2.6%
                6.0000          675     2.3%
                7.0000          569     2.0%
                8.0000          558     1.9%
               10.0000          491     1.7%
                9.0000          467     1.6%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
              2,269.00            1     0.0%
              984.0000            1     0.0%
              815.0000            1     0.0%
              4,920.00            1     0.0%
              3,280.00            1     0.0%
              3,530.00            1     0.0%
              3,924.00            1     0.0%
              3,078.00            1     0.0%
              1,620.00            1     0.0%
              7,995.00            1     0.0%


  Nome serie                     score_5_votes
  dtype                          float64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,525  (98.51%)
  Null / NaN                     430  (1.49%)
  Zeri                           1,639  (5.66%)
  Positivi                       26,886   (92.85%)
  Negativi                       0   (0.00%)
  Valori unici                   4,282  (14.79%)
  Valori float                   0

Statistiche descrittive
────────────────────────────────────────────────────────────────────────────────

  Min                            0.0000
  Max                            179,632.00
  Range                          179,632.00
  Media                          1,048.81
  Mediana                        57.0000
  Moda/e                         0.0000
  Dev. standard                  4,177.93
  Varianza                       17,455,089
  Errore std (SEM)               24.7371
  IQR  (Q3 − Q1)                 368.0000
  Q1  (25° pct)                  12.0000
  Q3  (75° pct)                  380.0000
  P5  ( 5° pct)                  0.0000
  P95 (95° pct)                  5,023.80
  Coefficiente di variazione     398.35%

Analisi outlier
────────────────────────────────────────────────────────────────────────────────

  Soglia bassa  (Q1 − 1.5×IQR)   -540.0000
  Soglia alta   (Q3 + 1.5×IQR)   932.0000
  Outlier rilevati               4,569  (15.78%)

  Top 5 outlier estremi (per valore assoluto):
    [23654]  179,632.00
    [23662]  145,199.00
    [24922]  101,075.00
    [24925]  95,003.00
    [4696]  80,184.00

Distribuzione
────────────────────────────────────────────────────────────────────────────────

  Intervallo                      Conteggio        %
  ────────────────────────────── ──────────   ──────
  0 – 8,981                          27,741    97.3%
  8,981 – 17,963                        480     1.7%
  17,963 – 26,944                       162     0.6%
  26,944 – 35,926                        66     0.2%
  35,926 – 44,908                        34     0.1%
  44,908 – 53,889                        20     0.1%
  53,889 – 62,871                         4     0.0%
  62,871 – 71,852                         7     0.0%
  71,852 – 80,834                         7     0.0%
  80,834 – 89,816                         0     0.0%
  89,816 – 98,797                         1     0.0%
  98,797 – 107,779                        1     0.0%
  107,779 – 116,760                       0     0.0%
  116,760 – 125,742                       0     0.0%
  125,742 – 134,724                       0     0.0%
  134,724 – 143,705                       0     0.0%
  143,705 – 152,687                       1     0.0%
  152,687 – 161,668                       0     0.0%
  161,668 – 170,650                       0     0.0%
  170,650 – 179,632                       1     0.0%

Valori estremi
────────────────────────────────────────────────────────────────────────────────

  I 10 più grandi:
    #1   179,632.00
    #2   145,199.00
    #3   101,075.00
    #4   95,003.00
    #5   80,184.00
    #6   79,537.00
    #7   79,042.00
    #8   78,318.00
    #9   76,825.00
    #10  75,239.00

  I 10 più piccoli:
    #1   0.0000
    #2   0.0000
    #3   0.0000
    #4   0.0000
    #5   0.0000
    #6   0.0000
    #7   0.0000
    #8   0.0000
    #9   0.0000
    #10  0.0000

Valori più e meno frequenti
────────────────────────────────────────────────────────────────────────────────

  I 10 più frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
                0.0000        1,639     5.7%
                1.0000        1,312     4.5%
                2.0000          794     2.7%
                3.0000          546     1.9%
                4.0000          438     1.5%
                5.0000          389     1.3%
                8.0000          339     1.2%
                6.0000          333     1.2%
               10.0000          318     1.1%
                7.0000          309     1.1%

  I 10 meno frequenti:
                Valore    Conteggio        %
  ────────────────────   ──────────   ──────
              7,199.00            1     0.0%
             12,495.00            1     0.0%
              7,300.00            1     0.0%
              9,696.00            1     0.0%
              2,000.00            1     0.0%
             10,167.00            1     0.0%
              6,286.00            1     0.0%
              2,407.00            1     0.0%
              3,969.00            1     0.0%
             18,141.00            1     0.0%


  Nome serie                     score_6_votes
  dtype                          float64
  Dimensione                     28,955
  Range indice                   0 … 28954
  Tipo                           NUMERICO

Conteggi di base
────────────────────────────────────────────────────────────────────────────────

  Righe totali                   28,955
  Valori non nulli               28,525  (98.51%)
  Null / NaN                     430  (1.49%)
  Zeri                           325  (1.12%)
  Positivi                       28,200   (97.39%)
  Negativi                       0   (0.00%)

**Pulizia necessaria:**  
- Le colonne `score_N_votes` hanno dtype `float64` a causa dei 430 null. Poiché rappresentano conteggi interi, li convertiamo in `Int64`.
- Le colonne `score_N_percentage` rimangono `float64` in quanto solo valori percentuali.

In [242]:
# Conversione score_N_votes da float64 a Int64 (nullable integer)
df_stats[score_votes_cols] = df_stats[score_votes_cols].astype('Int64')

print('Dtype score_N_votes dopo la conversione:')
print(df_stats[score_votes_cols].dtypes)

Dtype score_N_votes dopo la conversione:
score_1_votes     Int64
score_2_votes     Int64
score_3_votes     Int64
score_4_votes     Int64
score_5_votes     Int64
score_6_votes     Int64
score_7_votes     Int64
score_8_votes     Int64
score_9_votes     Int64
score_10_votes    Int64
dtype: object

## 3. Riepilogo e Salvataggio
Le operazioni di pulizia sono state effettuate colonna per colonna nella sezione 2. In questa sezione riepiloghiamo il risultato ed effettuiamo il salvataggio del dataset finale.

In [243]:
print('=== Riepilogo Dataset Pulito ===')
print(f'Righe originali      : {n_originale:>10,}')
print(f'Righe dopo cleaning  : {len(df_stats):>10,}')
print(f'Righe rimosse totali : {n_originale - len(df_stats):>10,}')
print()
df_stats.to_csv('../datasets_cleaned/stats_clean.csv', index=False)
print('Salvato: datasets_cleaned/stats_clean.csv')

=== Riepilogo Dataset Pulito ===
Righe originali      :     28,955
Righe dopo cleaning  :     28,955
Righe rimosse totali :          0

Salvato: datasets_cleaned/stats_clean.csv